#!/bin/bash

echo -n "please provide github username: "
read user
echo -n "please provide github password: "
read -s passwd
echo ""
echo -n "please provide a build message(if none is provided will not commit): "
read message

if [[ $message = *[!\ ]* ]] && [[ $user = *[!\ ]* ]] && [[ $passwd = *[!\ ]* ]]; then

	echo "building documentation"
	doxygen docs/TomoBay.doxyfile

	echo "building TomoBay"
	ant && 

	echo "Assembling .exe"
	/opt/launch4j/launch4j exeConf.xml  && 

	echo "commit and push TomoBay"
	git add . && 
	git commit -m "$message" && 
	git push https://$user:$passwd@github.com/jpchanson/TomoBay.git stopgap &&

	cd ../../Docs/TomoBay

	echo "commit and push docs" 
	git add . &&
	git commit -m "$message" &&
	git push https://$user:$passwd@github.com/jpchanson/TomoBay.git gh-pages

else
        echo "you did not enter a user/password/build message"
fi

