TomoBay: tomoBay.model.sql.queries.QueryInvoker Class Reference
tomoBay.model.sql.queries.QueryInvoker Class Reference
Classes
enum QueryType
Static Public Member Functions
static AbstractDBQuery make (QueryType query)
static List< String[]> execute (QueryType query, String[] parameters)
Static Private Attributes
static final Map< QueryType, AbstractQueryFactory > factoryMap_M
Detailed Description
This object is responsible for providing the user with Query objects as specified by the internal enum, which defines all possible queries that can be executed on the database.
These queries objects can either be created using the make() method or directly executed using the execute() method.
acceptable input values for those methods is defined in QueryType.
Author
Jan P.C. Hanson
Definition at line 61 of file QueryInvoker.java.
Member Function Documentation
static List<String[]> tomoBay.model.sql.queries.QueryInvoker.execute (QueryType query, String[] parameters) static
execute a requested query
Parameters
query one of the enum values provided by QueryType enum.
parameters String[] of parameters specific to the query you are using, see individual query docs.
Returns
List<String[]>
Exceptions
SQLException
Definition at line 181 of file QueryInvoker.java.
References tomoBay.model.sql.queries.AbstractDBQuery.execute(), and tomoBay.model.sql.queries.QueryInvoker.make().
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.assembleItemsList(), tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.calculate(), tomoBay.model.services.stockUpdate.StockRequired.clearTables(), tomoBay.model.services.stockUpdate.StockRequired.getItemList(), tomoBay.model.services.stockUpdate.StockRequired.insertORUpdate(), tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.insertOrUpdate(), tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.insertStockIntoDB(), tomoBay.model.services.stockUpdate.StockUpdateService.insertStockIntoDB(), tomoBay.model.services.basicEbayUpdate.BuyersTable.populate(), tomoBay.model.services.basicEbayUpdate.TransactionsTable.populate(), tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.populate(), tomoBay.model.services.basicEbayUpdate.ItemsTable.populate(), tomoBay.model.services.basicEbayUpdate.OrdersTable.populate(), tomoBay.presenters.sales.SalesOrderPresenter.present(), tomoBay.model.services.basicEbayUpdate.ItemsTable.requiredQty(), tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.resetBrandTable(), tomoBay.model.services.invoiceOrderService.InvoiceService.run(), tomoBay.model.services.stockUpdate.StockUpdateService.run(), and tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
static AbstractDBQuery tomoBay.model.sql.queries.QueryInvoker.make (QueryType query) static
make the requested data base query.
Parameters
query
Returns
Definition at line 170 of file QueryInvoker.java.
References tomoBay.model.sql.queries.QueryInvoker.factoryMap_M.
Referenced by tomoBay.model.sql.queries.QueryInvoker.execute().
Member Data Documentation
final Map<QueryType, AbstractQueryFactory> tomoBay.model.sql.queries.QueryInvoker.factoryMap_M static private
internal map holds factory objects created static final to make threadsafe
Definition at line 129 of file QueryInvoker.java.
Referenced by tomoBay.model.sql.queries.QueryInvoker.make().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/QueryInvoker.java