TomoBay: tomoBay.model.services.individualItemRefresh.RePopulateEbayItem Class Reference
tomoBay.model.services.individualItemRefresh.RePopulateEbayItem Class Reference
Public Member Functions
RePopulateEbayItem ()
void populate (String partNo, String brand, long itemID)
void resetBrandTable (PartList parts, String partNoDB, String brand, long itemID)
Detailed Description
This class takes data provided to it and uses this to re populate the database so that the changes can be picked up by the system.
Author
Jan P.C. Hanson
Definition at line 31 of file RePopulateEbayItem.java.
Constructor & Destructor Documentation
tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.RePopulateEbayItem ()
default ctor
Definition at line 36 of file RePopulateEbayItem.java.
Member Function Documentation
void tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.populate (String partNo, String brand, long itemID)
update the database with the new brand and part number information gleaned from an ItemCall
Parameters
partNo the composite part number associated with this eBay Item
brand the brand string associated with this eBay Item
itemID the eBay ItemID.
Definition at line 45 of file RePopulateEbayItem.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), and tomoBay.model.sql.queries.QueryInvoker.QueryType.UPDATE_ITEM_BRAND_AND_PARTNO.
Referenced by tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.run().
void tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.resetBrandTable (PartList parts, String partNoDB, String brand, long itemID)
This method resets the databases brand specific parts table.
Parameters
parts the partlist to use
partNoDB String representing the database table associated with this part number
brand the brand of the part number
itemID the itemID of the listing as a whole.
select specific ebay item use partlist to parse partNo use required value and partlist to calculate decomposed stock level for this item remove above stock level from brand tables
Definition at line 59 of file RePopulateEbayItem.java.
References tomoBay.helpers.BrandToCode.convert(), tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.services.helpers.PartList.getPartNumber(), tomoBay.model.services.helpers.PartList.getPartQty(), tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.make(), tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.SELECT, tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ITEM_SPECIFIC, tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.setBrand(), tomoBay.model.services.helpers.PartList.size(), and tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.UPDATE.
Referenced by tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.run().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/individualItemRefresh/RePopulateEbayItem.java