TomoBay: tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired Class Reference
tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired Class Reference
Public Member Functions
UpdateTotalItemsRequired ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
this class represents a query that updates the total number of items needed in the items table with data taken from the transactions transactions table. given a specific item id.
Author
Jan P.C. Hanson
Definition at line 31 of file UpdateTotalItemsRequired.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.UpdateTotalItemsRequired ()
default constructor
Definition at line 46 of file UpdateTotalItemsRequired.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 92 of file UpdateTotalItemsRequired.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. This query only needs 1 input so any element above the 0th element will be ignored.
col1 = required:int(6)
Returns
List<String[]> representing the results of the query. The list contains only 1 column the itemID, so each list element contains a String[1] which contains
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 59 of file UpdateTotalItemsRequired.java.
References tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.cleanup(), and tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.initQuery().
void tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 81 of file UpdateTotalItemsRequired.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.connection_M = null private
reference to the JDBC Database connection
Definition at line 36 of file UpdateTotalItemsRequired.java.
String tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.query private
Initial value:
="UPDATE ebay.ebay_items "
                    + "SET noRequired=(SELECT SUM(ebay_transactions.quantity) AS required "
                    + "FROM ebay.ebay_transactions WHERE ebay_transactions.itemID=?) "
                    + "WHERE ebay_items.itemID=?;"
SQL query string
Definition at line 38 of file UpdateTotalItemsRequired.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.statement_M = null private
reference to the JDBC Statement
Definition at line 34 of file UpdateTotalItemsRequired.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/UpdateTotalItemsRequired.java