TomoBay: tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions Class Reference
tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions Class Reference
Public Member Functions
SelectEbayItemsNotInTransactions ()
List< String[]> execute (String[] NotUsed) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement selectStatement_M = null
Connection connection_M = null
String query
Detailed Description
This class represents a query that selects all items (from the transactions table) that do not currently exist in the items table.
Author
Jan P.C. Hanson
Definition at line 32 of file SelectEbayItemsNotInTransactions.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.SelectEbayItemsNotInTransactions ()
default constructor
Definition at line 48 of file SelectEbayItemsNotInTransactions.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 106 of file SelectEbayItemsNotInTransactions.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.execute (String[] NotUsed) throws SQLException
execute the query
Parameters
NotUsed NOT USED
Returns
List<String[]> representing the results of the query. The list contains only 1 column the itemID, so each list element contains a String[1] which contains an itemID.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 58 of file SelectEbayItemsNotInTransactions.java.
References tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.cleanup(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.formatResults(), and tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.initQuery().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 79 of file SelectEbayItemsNotInTransactions.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.execute().
void tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 95 of file SelectEbayItemsNotInTransactions.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.connection_M = null private
reference to the JDBC Database connection
Definition at line 37 of file SelectEbayItemsNotInTransactions.java.
String tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.query private
Initial value:
="SELECT DISTINCT ebay_transactions.itemID "
            + "FROM ebay_transactions "
            + "WHERE ebay_transactions.itemID "
            + "NOT IN (SELECT DISTINCT ebay_items.itemID FROM ebay_items);"
SQL query string
Definition at line 39 of file SelectEbayItemsNotInTransactions.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.selectStatement_M = null private
reference to the JDBC Statement
Definition at line 35 of file SelectEbayItemsNotInTransactions.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/SelectEbayItemsNotInTransactions.java