TomoBay: tomoBay.model.sql.queries.concreteQueries.SelectEbayItems Class Reference
tomoBay.model.sql.queries.concreteQueries.SelectEbayItems Class Reference
Public Member Functions
SelectEbayItems ()
List< String[]> execute (String[] NotUsed) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement selectStatement_M = null
Connection connection_M = null
String query ="SELECT * FROM ebay_items;"
Detailed Description
This class represents a query that selects all the fields in the items table of the database.
Author
Jan P.C. Hanson
Definition at line 32 of file SelectEbayItems.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.SelectEbayItems ()
default constructor
Definition at line 44 of file SelectEbayItems.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 119 of file SelectEbayItems.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.execute (String[] NotUsed) throws SQLException
execute the query
Parameters
NotUsed NOT USED
Returns
List<String[]> representing the results of the query. Each element in the list represents a row of the database and each element of the String[] represents a field.
The available fields for each element of the string[] are:
String[0] = itemID
String[1] = title
String[2] = sellCondition
String[3] = brand
String[4] = partNo
String[5] = noRequired
String[6] = cost
String[7] = notes
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 65 of file SelectEbayItems.java.
References tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.cleanup(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.formatResults(), and tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.initQuery().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 85 of file SelectEbayItems.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.execute().
void tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 108 of file SelectEbayItems.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.connection_M = null private
reference to the JDBC Database connection
Definition at line 37 of file SelectEbayItems.java.
String tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.query ="SELECT * FROM ebay_items;" private
SQL query string
Definition at line 39 of file SelectEbayItems.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.selectStatement_M = null private
reference to the JDBC Statement
Definition at line 35 of file SelectEbayItems.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/SelectEbayItems.java