TomoBay: tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige Class Reference
tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige Class Reference
Public Member Functions
ClearPartsPrestige ()
List< String[]> execute (String[] NotUsed) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
This class represents a query that clears the required field of the Prestige specific parts table in the database.
Author
Jan P.C. Hanson
Definition at line 32 of file ClearPartsPrestige.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.ClearPartsPrestige ()
default constructor
Definition at line 46 of file ClearPartsPrestige.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 85 of file ClearPartsPrestige.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.execute (String[] NotUsed) throws SQLException
execute the query
Parameters
NotUsed NOT USED
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 56 of file ClearPartsPrestige.java.
References tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.cleanup(), and tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.initQuery().
void tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 74 of file ClearPartsPrestige.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.connection_M = null private
reference to the JDBC Database connection
Definition at line 37 of file ClearPartsPrestige.java.
String tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.query private
Initial value:
="UPDATE ebay.parts_prestige "
                        + "SET parts_prestige.required=0 "
                        + "WHERE parts_prestige.required!=0;"
SQL query string
Definition at line 39 of file ClearPartsPrestige.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.statement_M = null private
reference to the JDBC Statement
Definition at line 35 of file ClearPartsPrestige.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/ClearPartsPrestige.java