TomoBay: tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart Class Reference
tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart Class Reference
Public Member Functions
SelectPrestigeStockReqByPart ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement selectStatement_M = null
Connection connection_M = null
String query ="SELECT partNo, required FROM parts_prestige WHERE partNo=?;"
Detailed Description
This class represents a query that selects the part number and required stock level from the Prestige specific parts table of the database, given a particular part number.
Author
Jan P.C. Hanson
Definition at line 34 of file SelectPrestigeStockReqByPart.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.SelectPrestigeStockReqByPart ()
default constructor
Definition at line 46 of file SelectPrestigeStockReqByPart.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 112 of file SelectPrestigeStockReqByPart.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter the partNumber that you wish to query the required stock levels of encoded as a 1 element String array i.e. String[0]=partNumber String.length=1.
Returns
List<String[]> representing the results of the query. Each element in the list represents a row of the database and each element of the String[] represents a field.
The available fields for each element of the string[] are:
String[0] = partNo
String[1] = required
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 62 of file SelectPrestigeStockReqByPart.java.
References tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.cleanup(), tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.formatResults(), and tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.initQuery().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 84 of file SelectPrestigeStockReqByPart.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.execute().
void tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 101 of file SelectPrestigeStockReqByPart.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.connection_M = null private
reference to the JDBC Database connection
Definition at line 39 of file SelectPrestigeStockReqByPart.java.
String tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.query ="SELECT partNo, required FROM parts_prestige WHERE partNo=?;" private
SQL query string
Definition at line 41 of file SelectPrestigeStockReqByPart.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.selectStatement_M = null private
reference to the JDBC Statement
Definition at line 37 of file SelectPrestigeStockReqByPart.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/SelectPrestigeStockReqByPart.java