TomoBay: tomoBay.model.sql.ConnectionManager Class Reference
tomoBay.model.sql.ConnectionManager Class Reference
Public Member Functions
Connection getConnection () throws SQLException
Static Public Member Functions
static ConnectionManager instance ()
Private Member Functions
ConnectionManager ()
Private Attributes
ComboPooledDataSource cpds
Static Private Attributes
static ConnectionManager test = new ConnectionManager()
Detailed Description
This class provides access to a pool of database connections. It is a threadsafe singleton so always use the instance method to get an instance of this class, NEVER STORE THE INSTANCE.
Author
Jan P.C. Hanson
Definition at line 30 of file ConnectionManager.java.
Constructor & Destructor Documentation
tomoBay.model.sql.ConnectionManager.ConnectionManager () private
singleton contstructor, initialises the connection pool
Definition at line 40 of file ConnectionManager.java.
References tomoBay.helpers.ConfigReader.read().
Member Function Documentation
Connection tomoBay.model.sql.ConnectionManager.getConnection () throws SQLException
retrieves a database connection from the pool of available connections. When Connection.close is called the connection is returned to the pool.
Returns
Exceptions
SQLException
Definition at line 71 of file ConnectionManager.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.ClearPartsFord.initQuery(), tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.initQuery(), tomoBay.model.sql.queries.concreteQueries.ClearPartsPSA.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateFordStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertFordStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdatePrestigeStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayBuyers.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertPSAStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateItemBrandAndPartNo.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayTransactions.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockPSA.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockPrestige.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectPSAStockReqByPart.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectFordStockReqByPart.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayOrders.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.initQuery(), and tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.initQuery().
static ConnectionManager tomoBay.model.sql.ConnectionManager.instance () static
instance method returns an instance of the ConnectionManager class
Returns
ConnectionManager instance
Definition at line 62 of file ConnectionManager.java.
References tomoBay.model.sql.ConnectionManager.test.
Referenced by tomoBay.model.sql.queries.concreteQueries.ClearPartsFord.initQuery(), tomoBay.model.sql.queries.concreteQueries.ClearPartsPrestige.initQuery(), tomoBay.model.sql.queries.concreteQueries.ClearPartsPSA.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateFordStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertFordStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdatePrestigeStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayBuyers.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertPSAStockReq.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateItemBrandAndPartNo.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateTotalItemsRequired.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayTransactions.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockPSA.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.initQuery(), tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockPrestige.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItemsNotInTransactions.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectPSAStockReqByPart.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectPrestigeStockReqByPart.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectFordStockReqByPart.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItems.initQuery(), tomoBay.model.sql.queries.concreteQueries.InsertEbayOrders.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery(), tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.initQuery(), and tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.initQuery().
Member Data Documentation
ComboPooledDataSource tomoBay.model.sql.ConnectionManager.cpds private
C3P0 Data pool
Definition at line 35 of file ConnectionManager.java.
ConnectionManager tomoBay.model.sql.ConnectionManager.test = new ConnectionManager() static private
Singleton instance with eager instanciation
Definition at line 33 of file ConnectionManager.java.
Referenced by tomoBay.model.sql.ConnectionManager.instance().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/ConnectionManager.java