TomoBay: tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq Class Reference
tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq Class Reference
Public Member Functions
UpdatePSAStockReq ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query ="UPDATE parts_psa SET required=? WHERE partNo=?"
Detailed Description
This class represents a query that updates the PSA specific parts table of the database with data representing the amount of required stock, given a particular part number.
Author
Jan P.C. Hanson
Definition at line 33 of file UpdatePSAStockReq.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.UpdatePSAStockReq ()
default constructor
Definition at line 45 of file UpdatePSAStockReq.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 89 of file UpdatePSAStockReq.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. This query only needs 2 inputs columns so any element above the 1st element will be ignored.
col1 = required:int(6)
col2 = partNo:varchar(50)
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 59 of file UpdatePSAStockReq.java.
References tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.cleanup(), and tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.initQuery().
void tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 78 of file UpdatePSAStockReq.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.connection_M = null private
reference to the JDBC Database connection
Definition at line 38 of file UpdatePSAStockReq.java.
String tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.query ="UPDATE parts_psa SET required=? WHERE partNo=?" private
SQL query string
Definition at line 40 of file UpdatePSAStockReq.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.UpdatePSAStockReq.statement_M = null private
reference to the JDBC Statement
Definition at line 36 of file UpdatePSAStockReq.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/UpdatePSAStockReq.java