TomoBay: tomoBay.model.sql.queries.concreteQueries.InsertEbayItems Class Reference
tomoBay.model.sql.queries.concreteQueries.InsertEbayItems Class Reference
Public Member Functions
InsertEbayItems ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
This class represents a query that inserts item details into the items table of the database.
Author
Jan P.C. Hanson
Definition at line 47 of file InsertEbayItems.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.InsertEbayItems ()
default constructor
Definition at line 61 of file InsertEbayItems.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 111 of file InsertEbayItems.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. The Ebay Orders Table only has 5 columns so any element above the 5th element will be ignored.
col1 =itemID:varchar(11)
col2=title:varchar(83)
col3=sellCondition:varchar(15)
col4=brand:varchar(45)
col5=partNo:varchar(100)
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 78 of file InsertEbayItems.java.
References tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.cleanup(), and tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.initQuery().
void tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 100 of file InsertEbayItems.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.connection_M = null private
reference to the JDBC Database connection
Definition at line 52 of file InsertEbayItems.java.
String tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.query private
Initial value:
="INSERT IGNORE INTO ebay.ebay_items "
            + "(itemID, title, sellCondition, brand, partNo)"
            + "VALUES (?,?,?,?,?);"
SQL query string
Definition at line 54 of file InsertEbayItems.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.InsertEbayItems.statement_M = null private
reference to the JDBC Statement
Definition at line 50 of file InsertEbayItems.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/InsertEbayItems.java