TomoBay: tomoBay.model.services.helpers.PartList Class Reference
tomoBay.model.services.helpers.PartList Class Reference
Public Member Functions
PartList (String partNoString)
String getPartNumber (int i)
String[] getPartNumbers ()
int getPartQty (int i)
int[] getPartQtys ()
int size ()
void destroy ()
Private Member Functions
void convert (String partNoString)
void bracketsNSpaces (String input)
void bracketsNSpacesTrunc (String input)
void spacesNoBrackets (String input)
void noBracketsNoSpaces (String input)
void error (String input)
Private Attributes
String[] partNos_M
int[] partQty_M
Detailed Description
converts a list of parts in the form of a string containing part numbers and quantities into a unordered 2-tuple list of part numbers and their associated quantities.
Author
Jan P.C. Hanson
Definition at line 24 of file PartList.java.
Constructor & Destructor Documentation
tomoBay.model.services.helpers.PartList.PartList (String partNoString)
creates a part list with the partNoString provided.
Parameters
partNoString a list of part numbers and quantities. acceptable formats are: 1234 or 1234(1)567(2)8910(3) or 1234(1)567(2)8910 [if 8910 has qty 1] or 1234 567 [if both 1234 AND 567 have qty 1
Definition at line 37 of file PartList.java.
References tomoBay.model.services.helpers.PartList.convert().
Member Function Documentation
void tomoBay.model.services.helpers.PartList.bracketsNSpaces (String input) private
convert a composite part number containing brackets and spaces i.e. there is more than one part number or a quantity larger than 1. uses regex W00t :)
Parameters
input the composite part number
Definition at line 121 of file PartList.java.
Referenced by tomoBay.model.services.helpers.PartList.bracketsNSpacesTrunc(), and tomoBay.model.services.helpers.PartList.convert().
void tomoBay.model.services.helpers.PartList.bracketsNSpacesTrunc (String input) private
does the conversion for an input string that contains brackets and spaces but where the last part number has no brackets i.e. quantity of 1 on last entry.
Parameters
input the composite part number
Definition at line 150 of file PartList.java.
References tomoBay.model.services.helpers.PartList.bracketsNSpaces().
Referenced by tomoBay.model.services.helpers.PartList.convert().
void tomoBay.model.services.helpers.PartList.convert (String partNoString) private
orchestrates the conversion of the composite part number as provided in the constructor to individual part numbers. depending on the format of the composite part number i.e. does it contain brackets and/or spaces etc.
Parameters
partNoString
Definition at line 99 of file PartList.java.
References tomoBay.model.services.helpers.PartList.bracketsNSpaces(), tomoBay.model.services.helpers.PartList.bracketsNSpacesTrunc(), tomoBay.model.services.helpers.PartList.error(), tomoBay.model.services.helpers.PartList.noBracketsNoSpaces(), and tomoBay.model.services.helpers.PartList.spacesNoBrackets().
Referenced by tomoBay.model.services.helpers.PartList.PartList().
void tomoBay.model.services.helpers.PartList.destroy ()
de- allocate internal data.
Definition at line 84 of file PartList.java.
Referenced by tomoBay.model.services.stockUpdate.StockRequired.calculate(), and tomoBay.model.services.stockUpdate.StockUpdateService.run().
void tomoBay.model.services.helpers.PartList.error (String input) private
if the part number is not convertible as defined by the rules of the convert method this method is triggered. It provides an easily recognisable error code.
Parameters
input the composite part number.
Definition at line 184 of file PartList.java.
Referenced by tomoBay.model.services.helpers.PartList.convert().
String tomoBay.model.services.helpers.PartList.getPartNumber (int i)
get the part number at position i in the list
Parameters
i the index of the partNumber you wish to get
Returns
String part number stored at index i
Definition at line 48 of file PartList.java.
Referenced by tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.calculate(), tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.checkStockLevelOfItems(), tomoBay.model.services.stockUpdate.StockRequired.insertORUpdate(), tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.insertOrUpdate(), tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.resetBrandTable(), and tomoBay.model.services.stockUpdate.StockUpdateService.run().
String [] tomoBay.model.services.helpers.PartList.getPartNumbers ()
get the part numbers as a whole
Returns
String[] where the elements correspond to the part numbers as ordered in the argument passed to the constructor.
Definition at line 56 of file PartList.java.
References tomoBay.model.services.helpers.PartList.partNos_M.
int tomoBay.model.services.helpers.PartList.getPartQty (int i)
get the quantity of the part number at position i in the list
Parameters
i the index of the part number you wish to query the quantity of.
Returns
int the quantity of the part number at index i
Definition at line 63 of file PartList.java.
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.checkStockLevelOfItems(), tomoBay.model.services.stockUpdate.StockRequired.insertORUpdate(), tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.insertOrUpdate(), and tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.resetBrandTable().
int [] tomoBay.model.services.helpers.PartList.getPartQtys ()
get the par quantities as a whole.
Returns
int[] with each element containing the quantity of the part associated with the same index.
Definition at line 71 of file PartList.java.
References tomoBay.model.services.helpers.PartList.partQty_M.
void tomoBay.model.services.helpers.PartList.noBracketsNoSpaces (String input) private
does the conversion for a composite part number where the input contains no brackets or spaces i.e. the composite part number contains only one part number and it has a quantity of 1.
Parameters
input the composite part number
Definition at line 173 of file PartList.java.
Referenced by tomoBay.model.services.helpers.PartList.convert().
int tomoBay.model.services.helpers.PartList.size ()
the size of the part list.
Returns
the size of the part list.
Definition at line 78 of file PartList.java.
Referenced by tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.calculate(), tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.checkStockLevelOfItems(), tomoBay.model.services.stockUpdate.StockRequired.iterateThroughPartsList(), tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.resetBrandTable(), tomoBay.model.services.stockUpdate.StockUpdateService.run(), and tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.updateDB().
void tomoBay.model.services.helpers.PartList.spacesNoBrackets (String input) private
does the conversion for a composite part number where the composite contains spaces but no brackets i.e. all part numbers have quantity 1.
Parameters
input the composite part number
Definition at line 160 of file PartList.java.
Referenced by tomoBay.model.services.helpers.PartList.convert().
Member Data Documentation
String [] tomoBay.model.services.helpers.PartList.partNos_M private
internal holder for part numbers
Definition at line 27 of file PartList.java.
Referenced by tomoBay.model.services.helpers.PartList.getPartNumbers().
int [] tomoBay.model.services.helpers.PartList.partQty_M private
internal holder for part quantities
Definition at line 29 of file PartList.java.
Referenced by tomoBay.model.services.helpers.PartList.getPartQtys().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/helpers/PartList.java