TomoBay: tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders Class Reference
tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders Class Reference
Public Member Functions
SelectEbayOrders ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
Static Private Attributes
static final String query = "SELECT * FROM ebay.ebay_orders ORDER BY createdTime ASC;"
Detailed Description
This class represents a query that selects all data contained in the orders table of the database sorted by the time it was created (in ascending order)
Author
Jan P.C. Hanson
Definition at line 32 of file SelectEbayOrders.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.SelectEbayOrders ()
default constructor
Definition at line 44 of file SelectEbayOrders.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 120 of file SelectEbayOrders.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter NotUsed NOT USED
Returns
List<String[]> representing the results of the query. Each element in the list represents a row of the database and each element of the String[] represents a field.
The available fields for each element of the string[] are:
String[0] = orderID
String[1] = buyerID
String[2] = salesRecNo
String[3] = shippingType
String[4] = createdTime
String[5] = picked
String[6] = packed
String[7] = shipped
String[8] = invoiced
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 66 of file SelectEbayOrders.java.
References tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.cleanup(), tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.formatResults(), and tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 85 of file SelectEbayOrders.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.execute().
void tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 109 of file SelectEbayOrders.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.connection_M = null private
reference to the JDBC Database connection
Definition at line 37 of file SelectEbayOrders.java.
final String tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.query = "SELECT * FROM ebay.ebay_orders ORDER BY createdTime ASC;" static private
SQL query string
Definition at line 39 of file SelectEbayOrders.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.SelectEbayOrders.statement_M = null private
reference to the JDBC Statement
Definition at line 35 of file SelectEbayOrders.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/SelectEbayOrders.java