TomoBay: tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus Class Reference
tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus Class Reference
Public Member Functions
UpdateInvoiceStatus ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query ="UPDATE ebay_orders SET invoiced=? WHERE orderID=?"
Detailed Description
This class represents a query that updates the 'invoiced' field of particular order on the orders table of the database with appropriate data:
0 = not invoiceable
1 = partially invoiceable
2 = order has been invoiced
Author
Jan P.C. Hanson
Definition at line 34 of file UpdateInvoiceStatus.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.UpdateInvoiceStatus ()
default constructor
Definition at line 46 of file UpdateInvoiceStatus.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 88 of file UpdateInvoiceStatus.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter The list contains only 2 elements 1st element is invoiced status (0=not invoiceable, 1=partially invoiceable, 3=invoiced), the second element is the orderID
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 58 of file UpdateInvoiceStatus.java.
References tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.cleanup(), and tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.initQuery().
void tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 77 of file UpdateInvoiceStatus.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.connection_M = null private
reference to the JDBC Database connection
Definition at line 39 of file UpdateInvoiceStatus.java.
String tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.query ="UPDATE ebay_orders SET invoiced=? WHERE orderID=?" private
SQL query string
Definition at line 41 of file UpdateInvoiceStatus.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.UpdateInvoiceStatus.statement_M = null private
reference to the JDBC Statement
Definition at line 37 of file UpdateInvoiceStatus.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/UpdateInvoiceStatus.java