TomoBay: tomoBay.presenters.sales.SalesOrderPresenter Class Reference
tomoBay.presenters.sales.SalesOrderPresenter Class Reference
Public Member Functions
SalesOrderPresenter ()
String present ()
Private Member Functions
String doStuff (List< String[]> input)
String pickeability (String invoiced)
Detailed Description
This class is responsible for providing the dynamic data to the orders section of the sales area.
Author
Jan P.C. Hanson
Definition at line 28 of file SalesOrderPresenter.java.
Constructor & Destructor Documentation
tomoBay.presenters.sales.SalesOrderPresenter.SalesOrderPresenter ()
default constructor
Definition at line 33 of file SalesOrderPresenter.java.
Member Function Documentation
String tomoBay.presenters.sales.SalesOrderPresenter.doStuff (List< String[]> input) private
Parameters
input
Returns
Definition at line 58 of file SalesOrderPresenter.java.
References tomoBay.presenters.sales.SalesOrderPresenter.pickeability().
Referenced by tomoBay.presenters.sales.SalesOrderPresenter.present().
String tomoBay.presenters.sales.SalesOrderPresenter.pickeability (String invoiced) private
Parameters
invoiced
Returns
Definition at line 83 of file SalesOrderPresenter.java.
Referenced by tomoBay.presenters.sales.SalesOrderPresenter.doStuff().
String tomoBay.presenters.sales.SalesOrderPresenter.present ()
this method is called when you actually want to present the information contained in the view/presenter to the servlet
Returns
String representing the html contained in the view/presenter
Implements tomoBay.presenters.AbstractPresenter.
Definition at line 40 of file SalesOrderPresenter.java.
References tomoBay.presenters.sales.SalesOrderPresenter.doStuff(), tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ORDERS, and tomoBay.presenters.helpers.SortOrders.sortDefault().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/presenters/sales/SalesOrderPresenter.java