TomoBay: tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus Class Reference
tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus Class Reference
Public Member Functions
CalculateInvoiceStatus ()
InvoiceableStatus status (String orderNo)
Private Member Functions
void assembleItemsList (List< String[]> transactionVar, List< String[]> itemsVar)
Set< Boolean > checkStockLevelOfItems (List< String[]> itemsVar)
Detailed Description
This class calculates the invoicability of all orders currently on the system. (yes i know invoicability isnt a word)
Author
Jan P.C. Hanson
Definition at line 34 of file CalculateInvoiceStatus.java.
Constructor & Destructor Documentation
tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.CalculateInvoiceStatus ()
default ctor
Definition at line 39 of file CalculateInvoiceStatus.java.
Member Function Documentation
void tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.assembleItemsList (List< String[]> transactionVar, List< String[]> itemsVar) private
modifies the transactionVar list passed in as an argument so that it contains the list of transactions associated with this order.
Parameters
transactionVar
itemsVar
Definition at line 74 of file CalculateInvoiceStatus.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), and tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ITEM_SPECIFIC.
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
Set<Boolean> tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.checkStockLevelOfItems (List< String[]> itemsVar) private
Takes the list of items generated in this.assembleItemsList and checks a PartList associated with each item against Stock held in winstock. For every item with enough stock level it adds a true value to a Set<Boolean> i.e. if everything is in stock the set will only contain 1 element = true, if everything is out of stock the set will contain only 1 element = false, but if some items are in stock and others arnt it will contain 2 elements true and false.
Parameters
itemsVar the list of items to check off against Stock levels
Returns
Set<Boolean> in stock - size=1 value={true}; out of stock - size=1 values={false}; partial stock - size = 2 values = {true,false}
Definition at line 98 of file CalculateInvoiceStatus.java.
References tomoBay.helpers.BrandToCode.convert(), tomoBay.model.services.helpers.PartList.getPartNumber(), tomoBay.model.services.helpers.PartList.getPartQty(), tomoBay.model.winstock.Stock.requestStockLevel(), tomoBay.model.services.helpers.PartList.size(), and tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
InvoiceableStatus tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status (String orderNo)
calculates the InvoiceableStatus for a particular order, Invoiceable/UnInvoiceable/Partial
Parameters
orderNo the order number to check
Returns
InvoiceableStatus Invoiceable/UnInvoiceable/Partial/ERROR
Definition at line 47 of file CalculateInvoiceStatus.java.
References tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.assembleItemsList(), tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.checkStockLevelOfItems(), tomoBay.model.services.helpers.InvoiceableStatus.ERROR, tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.services.helpers.InvoiceableStatus.Invoiceable, tomoBay.model.services.helpers.InvoiceableStatus.Partial, tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_TRANSACTION_BY_ORDERID, and tomoBay.model.services.helpers.InvoiceableStatus.UnInvoiceable.
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.checkStockLevelOfItems(), and tomoBay.model.services.invoiceOrderService.InvoiceService.run().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/invoiceOrderService/CalculateInvoiceStatus.java