TomoBay: tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock Class Reference
tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock Class Reference
Public Member Functions
ReCalculateRequiredStock ()
void calculate (PartList partList, String brand, String partNo, ItemType item)
Private Member Functions
void updateDB (PartList partList, String partNo, String brand, int qty)
void insertOrUpdate (StockRequiredQueryFactory enumFactory, PartList parts, int qty, int count)
Detailed Description
This class re calculates the ammount of stock currently required to fulfill all orders on the system. it does this by querying the MySQL database used to store all app specific information.
Author
Jan P.C. Hanson
Definition at line 34 of file ReCalculateRequiredStock.java.
Constructor & Destructor Documentation
tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.ReCalculateRequiredStock ()
default ctor
Definition at line 39 of file ReCalculateRequiredStock.java.
Member Function Documentation
void tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.calculate (PartList partList, String brand, String partNo, ItemType item)
calculate the amount of stock required to fulfil an order for a particular ebay item, update the database with the calculated values.
Parameters
item The item to update.
partList the partlist created by the composite part list retrieved from an ItemCall
brand the brand string associaiated with this eBay Item.
partNo the composite part number taken from the ItemCall
Definition at line 50 of file ReCalculateRequiredStock.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ITEM_SPECIFIC, and tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.updateDB().
Referenced by tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.run().
void tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.insertOrUpdate (StockRequiredQueryFactory enumFactory, PartList parts, int qty, int count) private
This method either inserts data into the database iff the part number doesnt already exist on the system. If the part number does exist on the system then it updates the part number already in existance with new data.
Parameters
enumFactory the StockUpdateQueryFactory that allows the selection of appropriate queries through the returned enum constants(based on brand code)
parts the PartList associated with this eBay Item
qty the quantity of a particular eBay item that is on order at this point in time.
count integer generated by for loop, allows indexing of the appropriate part in the PartList.
Definition at line 90 of file ReCalculateRequiredStock.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.services.helpers.PartList.getPartNumber(), tomoBay.model.services.helpers.PartList.getPartQty(), tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.INSERT, tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.make(), tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.SELECT, and tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.UPDATE.
Referenced by tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.updateDB().
void tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.updateDB (PartList partList, String partNo, String brand, int qty) private
updates the database with the required stock level
Parameters
partList the partlist constructed using the composite part number retrieved from the ItemCall.
partNo the composite part number retrieved from the the ItemCall
brand the brand retrieved from the item specifics (stored in ItemCall)
qty the quantity as taken from the ebay_items table of the database.
Definition at line 69 of file ReCalculateRequiredStock.java.
References tomoBay.helpers.BrandToCode.convert(), tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.insertOrUpdate(), tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.setBrand(), and tomoBay.model.services.helpers.PartList.size().
Referenced by tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.calculate().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/individualItemRefresh/ReCalculateRequiredStock.java