TomoBay: tomoBay.model.services.helpers.InvoiceableStatus Enum Reference
tomoBay.model.services.helpers.InvoiceableStatus Enum Reference
Public Member Functions
int getStatusCode ()
Static Public Member Functions
static InvoiceableStatus fromInt (int statusCode)
static int size ()
Public Attributes
Invoiceable =(0)
Partial =(1)
UnInvoiceable =(2)
ERROR =(3)
Private Member Functions
InvoiceableStatus (int status)
Private Attributes
int status_M
Static Private Attributes
static final Map< Integer, InvoiceableStatus > fromInt_M
static final int size = InvoiceableStatus.values().length
Detailed Description
this enum defines the different status's and status codes for the state of an order with respect to invoiceability.
Author
Jan P.C. Hanson
Definition at line 25 of file InvoiceableStatus.java.
Constructor & Destructor Documentation
tomoBay.model.services.helpers.InvoiceableStatus.InvoiceableStatus (int status) private
private ctor so enum can hold int values
Definition at line 55 of file InvoiceableStatus.java.
Member Function Documentation
static InvoiceableStatus tomoBay.model.services.helpers.InvoiceableStatus.fromInt (int statusCode) static
Parameters
statusCode
Returns
Definition at line 70 of file InvoiceableStatus.java.
References tomoBay.model.services.helpers.InvoiceableStatus.fromInt_M.
int tomoBay.model.services.helpers.InvoiceableStatus.getStatusCode ()
retrieve the status code for a particular constant
Returns
integer status code
Definition at line 62 of file InvoiceableStatus.java.
Referenced by tomoBay.model.services.invoiceOrderService.InvoiceService.run().
static int tomoBay.model.services.helpers.InvoiceableStatus.size () static
gets the number of constants held in this enum
Returns
integer denoting the size of the enum
Definition at line 77 of file InvoiceableStatus.java.
References tomoBay.model.services.helpers.InvoiceableStatus.size.
Member Data Documentation
tomoBay.model.services.helpers.InvoiceableStatus.ERROR =(3)
there has been an error somewhere along the line.....dufus
Definition at line 34 of file InvoiceableStatus.java.
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
static final Map<Integer, InvoiceableStatus> tomoBay.model.services.helpers.InvoiceableStatus.fromInt_M static private
Initial value:
= new HashMap<Integer,InvoiceableStatus>()
    {{
        put(3, InvoiceableStatus.ERROR);
        put(2 , InvoiceableStatus.UnInvoiceable);
        put(1 , InvoiceableStatus.Partial);
        put(0 , InvoiceableStatus.Invoiceable);
    }}
map for converting ints back to enum constants
Definition at line 38 of file InvoiceableStatus.java.
Referenced by tomoBay.model.services.helpers.InvoiceableStatus.fromInt().
tomoBay.model.services.helpers.InvoiceableStatus.Invoiceable =(0)
an invoice is fully invoiceable or already invoiced
Definition at line 28 of file InvoiceableStatus.java.
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
tomoBay.model.services.helpers.InvoiceableStatus.Partial =(1)
this order is partially invoiceable, probably due to some parts being out of stock
Definition at line 30 of file InvoiceableStatus.java.
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
static final int tomoBay.model.services.helpers.InvoiceableStatus.size = InvoiceableStatus.values().length static private
size of the enum
Definition at line 50 of file InvoiceableStatus.java.
Referenced by tomoBay.model.services.helpers.InvoiceableStatus.size(), and tomoBay.presenters.helpers.SortOrders.sortByPickeability().
int tomoBay.model.services.helpers.InvoiceableStatus.status_M private
holder for the status code
Definition at line 47 of file InvoiceableStatus.java.
tomoBay.model.services.helpers.InvoiceableStatus.UnInvoiceable =(2)
it is not possible to invoice this order at the present time
Definition at line 32 of file InvoiceableStatus.java.
Referenced by tomoBay.model.services.invoiceOrderService.CalculateInvoiceStatus.status().
The documentation for this enum was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/helpers/InvoiceableStatus.java