TomoBay: tomoBay.model.services.stockUpdate.StockRequired Class Reference
tomoBay.model.services.stockUpdate.StockRequired Class Reference
Public Member Functions
StockRequired ()
void calculate ()
Private Member Functions
List< String[]> getItemList ()
void iterateThroughPartsList (PartList parts, String[] item, StockRequiredQueryFactory enumFactory)
void insertORUpdate (StockRequiredQueryFactory enumFactory, PartList parts, String[] item, int count)
void clearTables ()
Detailed Description
This class calculates the stock required for all orders on the system at the point in time at which the service is run.
Author
Jan P.C. Hanson
Definition at line 31 of file StockRequired.java.
Constructor & Destructor Documentation
tomoBay.model.services.stockUpdate.StockRequired.StockRequired ()
default ctor
Definition at line 36 of file StockRequired.java.
Member Function Documentation
void tomoBay.model.services.stockUpdate.StockRequired.calculate ()
calculate the amount of required stock for each part number.
Definition at line 42 of file StockRequired.java.
References tomoBay.model.services.stockUpdate.StockRequired.clearTables(), tomoBay.helpers.BrandToCode.convert(), tomoBay.model.services.helpers.PartList.destroy(), tomoBay.model.services.stockUpdate.StockRequired.getItemList(), tomoBay.model.services.stockUpdate.StockRequired.iterateThroughPartsList(), and tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.setBrand().
Referenced by tomoBay.model.services.stockUpdate.StockUpdateService.run().
void tomoBay.model.services.stockUpdate.StockRequired.clearTables () private
clears the tables of any required qty information. Allowing the part numbers to remain is just less data that needs inserting.
Exceptions
SQLException
Definition at line 113 of file StockRequired.java.
References tomoBay.model.sql.queries.QueryInvoker.QueryType.CLEAR_PARTS_FORD, tomoBay.model.sql.queries.QueryInvoker.QueryType.CLEAR_PARTS_PRESTIGE, tomoBay.model.sql.queries.QueryInvoker.QueryType.CLEAR_PARTS_PSA, and tomoBay.model.sql.queries.QueryInvoker.execute().
Referenced by tomoBay.model.services.stockUpdate.StockRequired.calculate().
List<String[]> tomoBay.model.services.stockUpdate.StockRequired.getItemList () private
gets a list of items from the items table of the database
Returns
Exceptions
SQLException
Definition at line 61 of file StockRequired.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), and tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ITEMS.
Referenced by tomoBay.model.services.stockUpdate.StockRequired.calculate().
void tomoBay.model.services.stockUpdate.StockRequired.insertORUpdate (StockRequiredQueryFactory enumFactory, PartList parts, String[] item, int count) private
depending on whether the Select query returns results or not decides whether an IndexOutOfBoundsException is thrown, which in turn decides whether the system will insert or update a particular record.
Parameters
parts
item list of items
enumFactory the StockRequiredQueryFactory
count the loop count variable
Definition at line 88 of file StockRequired.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.services.helpers.PartList.getPartNumber(), tomoBay.model.services.helpers.PartList.getPartQty(), tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.INSERT, tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.make(), tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.SELECT, and tomoBay.model.services.stockUpdate.StockRequiredQueryFactory.StockQueryType.UPDATE.
Referenced by tomoBay.model.services.stockUpdate.StockRequired.iterateThroughPartsList().
void tomoBay.model.services.stockUpdate.StockRequired.iterateThroughPartsList (PartList parts, String[] item, StockRequiredQueryFactory enumFactory) private
iterates through the parts list for a particular listing and adds the quantity of each part number to the specific brands parts db.
Parameters
parts
item list of items
enumFactory the StockRequiredQueryFactory
Exceptions
SQLException
Definition at line 72 of file StockRequired.java.
References tomoBay.model.services.stockUpdate.StockRequired.insertORUpdate(), and tomoBay.model.services.helpers.PartList.size().
Referenced by tomoBay.model.services.stockUpdate.StockRequired.calculate().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/stockUpdate/StockRequired.java