TomoBay: tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService Class Reference
tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService Class Reference
Public Member Functions
void run ()
Private Member Functions
ItemType getItemData (String itemID)
Map< String, String > getSpecifics (ItemType item)
Private Attributes
long listingID_M
Detailed Description
This service updates an individual item by re querying the eBay API for item information. It requires information provided by an IndividualItemRefreshConfiguration object passed to its setConfig method in order to function properly.
Author
Jan P.C. Hanson
Definition at line 42 of file IndividualItemRefreshService.java.
Member Function Documentation
ItemType tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.getItemData (String itemID) private
use the itemID passed in to find out information about a specific eBay item.
Parameters
itemID the ID of a particular eBay Item (listing)
Returns
ItemType eBay API datatype containing the details of a particular item.
Definition at line 80 of file IndividualItemRefreshService.java.
References tomoBay.model.eBayAPI.ItemCall.call(), and tomoBay.helpers.ConfigReader.read().
Referenced by tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.run().
Map<String, String> tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.getSpecifics (ItemType item) private
Read the Brand and the manufacturer part number into a map for convenience
Parameters
item the item to store the brand and manufacturer part number of.
Returns
Map<String,String> containing the above data.
Definition at line 100 of file IndividualItemRefreshService.java.
Referenced by tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.run().
void tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.run ()
The individual services equivalent of main
Implements tomoBay.model.services.AbstractService.
Definition at line 51 of file IndividualItemRefreshService.java.
References tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.calculate(), tomoBay.model.services.individualItemRefresh.ReCalculateRequiredStock.calculate(), tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.getItemData(), tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.getSpecifics(), tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.populate(), and tomoBay.model.services.individualItemRefresh.RePopulateEbayItem.resetBrandTable().
Member Data Documentation
long tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.listingID_M private
Definition at line 45 of file IndividualItemRefreshService.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/individualItemRefresh/IndividualItemRefreshService.java