TomoBay: Listing Class Reference
Listing Class Reference
This class represents an eBay Listing and once instantiated, contains all the information pertinent to a listing.
Public Member Functions
Listing (long listingID)
constructor, instantiates this listing based on the listingID provided (aka in the database as itemID)
long listingID ()
retrieve the listingID associated with this listing
String title ()
retreive the title of the listing as it appears on ebay
String brand ()
retrieve the brand that is associated with this listing(as it appears on eBay)
int noOfParts ()
retreive the number of parts that exist in this listing.
String partNos ()
retrieve the composite part no for this listing
Part part (int index)
retrieve the part specified in the parameter
int qty (int index)
retrieve the qty of the part at this index.
double listingCost ()
retrieve the accumulated base cost of all parts associated with this listing.
Static Private Member Functions
static final HeteroFieldContainer getListingInfo (long listingID)
internal method, gets the data for a listing from the database
Private Attributes
final Part[] parts_M
the parts associated with this listing
final int[] partQtys_M
the quantities fo the parts stored in parts_M
final HeteroFieldContainer ListingInfo_M
the container for the listing information from the database
Detailed Description
This class represents an eBay Listing and once instantiated, contains all the information pertinent to a listing.
The key part of the listing is the fact that it is a container for the parts associated with this particular eBay listing. This class provides the functionality to retrieve these parts and various bits of information about them.
Author
Jan P.C. Hanson
Definition at line 32 of file Listing.java.
Constructor & Destructor Documentation
Listing (long listingID)
constructor, instantiates this listing based on the listingID provided (aka in the database as itemID)
Parameters
listingID the itemID that uniquely identifies a particular listing
Definition at line 46 of file Listing.java.
References Listing.brand(), HeteroFieldContainer.get(), Listing.getListingInfo(), PartList.getPartNumber(), PartList.getPartQty(), ItemsTable.PART_NO, PartList.size(), and ClassRef.STRING.
Member Function Documentation
long listingID ()
retrieve the listingID associated with this listing
Returns
long representing the listingID
Definition at line 68 of file Listing.java.
References HeteroFieldContainer.get(), ItemsTable.ITEM_ID, and ClassRef.LONG.
Referenced by OrderInfo.transactionInfo().
String title ()
retreive the title of the listing as it appears on ebay
Returns
String containing the listing title.
Definition at line 75 of file Listing.java.
References HeteroFieldContainer.get(), ClassRef.STRING, and ItemsTable.TITLE.
Referenced by OrderInfo.transactionInfo().
String brand ()
retrieve the brand that is associated with this listing(as it appears on eBay)
Returns
String containing the brand
Definition at line 82 of file Listing.java.
References ItemsTable.BRAND, HeteroFieldContainer.get(), and ClassRef.STRING.
Referenced by Listing.Listing().
int noOfParts ()
retreive the number of parts that exist in this listing.
Returns
int representing the number of parts associated with this listing.
Definition at line 89 of file Listing.java.
Referenced by OrderInfo.transactionInfo().
String partNos ()
retrieve the composite part no for this listing
Returns
Part representing the specified part.
Definition at line 95 of file Listing.java.
References HeteroFieldContainer.get(), ItemsTable.PART_NO, and ClassRef.STRING.
Referenced by OrderInfo.transactionInfo().
Part part (int index)
retrieve the part specified in the parameter
Parameters
index the index of the part to retrieve, you can check how many parts exist in this listing by calling noOfParts();
Returns
Part representing the specified part.
Definition at line 104 of file Listing.java.
Referenced by AbstractLineItem.description(), PrintInvoices.execute(), WinstockFormat.format(), AbstractLineItem.partNo(), OrderInfo.transactionInfo(), GSPInvoiceLine.unitPrice(), and StandardInvoiceLine.unitPrice().
int qty (int index)
retrieve the qty of the part at this index.
Parameters
index the index of the part who's qty you wish to know, you can check how many parts exist in this listing by calling noOfParts().
Returns
Definition at line 112 of file Listing.java.
Referenced by AbstractLineItem.quantity(), GSPInvoiceLine.unitPrice(), and StandardInvoiceLine.unitPrice().
double listingCost ()
retrieve the accumulated base cost of all parts associated with this listing.
Returns
double representing the cumulative price of all items associated with the listing.
Definition at line 118 of file Listing.java.
References Part.cost().
Referenced by GSPInvoiceLine.unitPrice(), and StandardInvoiceLine.unitPrice().
static final HeteroFieldContainer getListingInfo (long listingID) static private
internal method, gets the data for a listing from the database
Parameters
listingID long containing the listingID
Returns
String[] containing the results of the query.
Definition at line 132 of file Listing.java.
References HeteroFieldContainer.add(), SelectQueryInvoker.execute(), ItemsTable.ITEM_ID, and SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_ITEM_SPECIFIC.
Referenced by Listing.Listing().
Member Data Documentation
final Part [] parts_M private
the parts associated with this listing
Definition at line 35 of file Listing.java.
final int [] partQtys_M private
the quantities fo the parts stored in parts_M
Definition at line 37 of file Listing.java.
final HeteroFieldContainer ListingInfo_M private
the container for the listing information from the database
Definition at line 39 of file Listing.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/StopGap/src/tomoBay/model/dataTypes/order/Listing.java