TomoBay: tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder Class Reference
tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder Class Reference
Public Member Functions
SelectTransactionByOrder ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
Static Private Attributes
static final String query = "SELECT * FROM ebay_transactions WHERE orderID=?;"
Detailed Description
This class represents a query that selects all data from the transactions table of the database given a particular orderID.
Author
Jan P.C. Hanson
Definition at line 33 of file SelectTransactionByOrder.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.SelectTransactionByOrder ()
default constructor
Definition at line 45 of file SelectTransactionByOrder.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 122 of file SelectTransactionByOrder.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter single element String array with that element being the order number to look up.
Returns
List<String[]> representing the results of the query. Each element in the list represents a row of the database and each element of the String[] represents a field.
The available fields for each element of the string[] are:
String[0] = transactionID
String[1] = orderID
String[2] = itemID
String[3] = quantity
String[4] = price
String[5] = picked
String[6] = packed
String[7] = shipped
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 67 of file SelectTransactionByOrder.java.
References tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.cleanup(), tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.formatResults(), and tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.initQuery().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 88 of file SelectTransactionByOrder.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.execute().
void tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 111 of file SelectTransactionByOrder.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.connection_M = null private
reference to the JDBC Database connection
Definition at line 38 of file SelectTransactionByOrder.java.
final String tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.query = "SELECT * FROM ebay_transactions WHERE orderID=?;" static private
SQL query string
Definition at line 40 of file SelectTransactionByOrder.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.SelectTransactionByOrder.statement_M = null private
reference to the JDBC Statement
Definition at line 36 of file SelectTransactionByOrder.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/SelectTransactionByOrder.java