TomoBay: tomoBay.model.services.basicEbayUpdate.ItemsTable Class Reference
tomoBay.model.services.basicEbayUpdate.ItemsTable Class Reference
Public Member Functions
ItemsTable ()
Static Public Member Functions
static void populate (String[] credentials, OrderType[] orders) throws ApiException, SdkException, Exception
Static Private Member Functions
static Map< String, String > getSpecifics (ItemType item)
static void requiredQty () throws SQLException
Detailed Description
updates the items table with the information gleaned from a specific ebay item call.
Author
Jan P.C. Hanson
Definition at line 36 of file ItemsTable.java.
Constructor & Destructor Documentation
tomoBay.model.services.basicEbayUpdate.ItemsTable.ItemsTable ()
default ctor
Definition at line 41 of file ItemsTable.java.
Member Function Documentation
static Map<String, String> tomoBay.model.services.basicEbayUpdate.ItemsTable.getSpecifics (ItemType item) static private
Parameters
item
Returns
Definition at line 81 of file ItemsTable.java.
Referenced by tomoBay.model.services.basicEbayUpdate.ItemsTable.populate().
static void tomoBay.model.services.basicEbayUpdate.ItemsTable.populate (String[] credentials, OrderType[] orders) throws ApiException, SdkException, Exception static
populates the Orders Table in the database with data grabbed from the ebay API
Parameters
credentials API credentials.
orders list of orders.
Exceptions
Exception
SdkException
ApiException
Definition at line 52 of file ItemsTable.java.
References tomoBay.model.eBayAPI.ItemCall.call(), tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.services.basicEbayUpdate.ItemsTable.getSpecifics(), tomoBay.model.sql.queries.QueryInvoker.QueryType.INSERT_EBAY_ITEMS, tomoBay.model.services.basicEbayUpdate.ItemsTable.requiredQty(), and tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ITEMS_NOT_IN_TRANSACTIONS.
Referenced by tomoBay.model.services.basicEbayUpdate.BasicEbayUpdateService.run().
static void tomoBay.model.services.basicEbayUpdate.ItemsTable.requiredQty () throws SQLException static private
add up all the distinct items and update with the total number of those items on order taken from the transactions table.
Exceptions
SQLException
Definition at line 110 of file ItemsTable.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ITEMS, and tomoBay.model.sql.queries.QueryInvoker.QueryType.UPDATE_TOTAL_ITEMS_REQUIRED.
Referenced by tomoBay.model.services.basicEbayUpdate.ItemsTable.populate().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/basicEbayUpdate/ItemsTable.java