TomoBay: tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq Class Reference
tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq Class Reference
Public Member Functions
InsertPrestigeStockReq ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
This class represents a query that inserts required stock level data into the Prestige specific parts table of the database.
Author
Jan P.C. Hanson
Definition at line 32 of file InsertPrestigeStockReq.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.InsertPrestigeStockReq ()
default constructor
Definition at line 45 of file InsertPrestigeStockReq.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 89 of file InsertPrestigeStockReq.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. The Ebay Orders Table only has 4 columns so any element above the 3rd element will be ignored.
col1 = partNo:VARCHAR(20)
col2 = required:INT(6)
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 59 of file InsertPrestigeStockReq.java.
References tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.cleanup(), and tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.initQuery().
void tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 78 of file InsertPrestigeStockReq.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.connection_M = null private
reference to the JDBC Database connection
Definition at line 37 of file InsertPrestigeStockReq.java.
String tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.query private
Initial value:
="INSERT IGNORE INTO ebay.parts_prestige (parts_prestige.partNo, parts_prestige.required)"
            + " VALUES(?, ?) ;"
SQL query string
Definition at line 39 of file InsertPrestigeStockReq.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.InsertPrestigeStockReq.statement_M = null private
reference to the JDBC Statement
Definition at line 35 of file InsertPrestigeStockReq.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/InsertPrestigeStockReq.java