TomoBay: HttpServer Class Reference
HttpServer Class Reference
This class defines the setup of the Jetty embedded http server, servlets, resources, security and many other features can be introduced from here.
Public Member Functions
HttpServer ()
default ctor
void start (int port) throws MalformedURLException
This starts the http servlet with 2 context handler: 1 is a resource handler that is responsible for providing access to the static html and the other is the DataServlet which is what can be queried by the WebApp for specific presenters.
Static Private Member Functions
static ServerConnector sslConnector (Server server, int port)
set up the ssl server connector
static ContextHandler setUpDataServletHandler ()
do setup for the servlet handler
static ContextHandler setUpGuiHandler () throws MalformedURLException
do setup for the static resource handler
Detailed Description
This class defines the setup of the Jetty embedded http server, servlets, resources, security and many other features can be introduced from here.
the server operates on a port specified as a command line argument.
Author
Jan P.C. Hanson
Definition at line 41 of file HttpServer.java.
Constructor & Destructor Documentation
HttpServer ()
default ctor
Definition at line 46 of file HttpServer.java.
Member Function Documentation
void start (int port) throws MalformedURLException
This starts the http servlet with 2 context handler: 1 is a resource handler that is responsible for providing access to the static html and the other is the DataServlet which is what can be queried by the WebApp for specific presenters.
Parameters
port the port to run the server on
Exceptions
MalformedURLException
server.join();
Definition at line 56 of file HttpServer.java.
References HttpServer.setUpDataServletHandler(), HttpServer.setUpGuiHandler(), and HttpServer.sslConnector().
Referenced by MAIN.main().
static ServerConnector sslConnector (Server server, int port) static private
set up the ssl server connector
Parameters
server the server that this connector should connect to
port the port that this connector should listen on
Returns
ServerConnector the server connector
Definition at line 82 of file HttpServer.java.
Referenced by HttpServer.start().
static ContextHandler setUpDataServletHandler () static private
do setup for the servlet handler
Returns
ContextHandler for the servlet
Definition at line 103 of file HttpServer.java.
Referenced by HttpServer.start().
static ContextHandler setUpGuiHandler () throws MalformedURLException static private
do setup for the static resource handler
Returns
ContextHandler for the static resource handler
Definition at line 117 of file HttpServer.java.
Referenced by HttpServer.start().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/StopGap/src/tomoBay/view/HttpServer.java