TomoBay: tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific Class Reference
tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific Class Reference
Public Member Functions
SelectEbayItemSpecific ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement selectStatement_M = null
Connection connection_M = null
String query ="SELECT * FROM ebay_items WHERE itemID=?;"
Detailed Description
This class represents a query that selects a specific item from the items table of the database, based on the itemID.
Author
Jan P.C. Hanson
Definition at line 33 of file SelectEbayItemSpecific.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.SelectEbayItemSpecific ()
default constructor
Definition at line 45 of file SelectEbayItemSpecific.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 111 of file SelectEbayItemSpecific.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter single element array where that single element corresponds to the itemID you wish to query. (all further elements will be ignored)
Returns
List<String[]> representing the results of the query. The list contains only 1 column the itemID, so each list element contains a String[1] which contains an itemID.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 56 of file SelectEbayItemSpecific.java.
References tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.cleanup(), tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.formatResults(), and tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.initQuery().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 77 of file SelectEbayItemSpecific.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.execute().
void tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 100 of file SelectEbayItemSpecific.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.connection_M = null private
reference to the JDBC Database connection
Definition at line 38 of file SelectEbayItemSpecific.java.
String tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.query ="SELECT * FROM ebay_items WHERE itemID=?;" private
SQL query string
Definition at line 40 of file SelectEbayItemSpecific.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.SelectEbayItemSpecific.selectStatement_M = null private
reference to the JDBC Statement
Definition at line 36 of file SelectEbayItemSpecific.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/SelectEbayItemSpecific.java