TomoBay: tomoBay.presenters.helpers.SortOrders Class Reference
tomoBay.presenters.helpers.SortOrders Class Reference
Public Member Functions
SortOrders ()
List< String[]> sortDefault (List< String[]> input)
Private Member Functions
List< String[]> sortByPickeability (List< String[]> input)
List< String[]> sortByShipping (List< String[]> input)
List< String[]> reAssembleCategories (List< List< String[]>> input, int size)
Detailed Description
This class contains functionality for performing a category based sorting algorithm first ordering the data passed in by shipping type and the now sorted data by Pickeability. this leads to data that is first displayed by pickeability then within each pickability type it is then sorted by shipping type.
See also
tomoBay.presenters.helpers.ShippingPriority
Author
Jan P.C. Hanson
Definition at line 31 of file SortOrders.java.
Constructor & Destructor Documentation
tomoBay.presenters.helpers.SortOrders.SortOrders ()
default ctor
Definition at line 36 of file SortOrders.java.
Member Function Documentation
List<String[]> tomoBay.presenters.helpers.SortOrders.reAssembleCategories (List< List< String[]>> input, int size) private
reassemble the categories into one list
Parameters
input List<List<String[]>> the list of catagories
size the size of the shipping priority enum
Returns
category sorted list of strings with previous sort order preserved
Definition at line 92 of file SortOrders.java.
Referenced by tomoBay.presenters.helpers.SortOrders.sortByPickeability(), and tomoBay.presenters.helpers.SortOrders.sortByShipping().
List<String[]> tomoBay.presenters.helpers.SortOrders.sortByPickeability (List< String[]> input) private
sort the list<String> by Invoice status descending (see InvoiceableStatus enum)
Parameters
input list of strings unordered
Returns
List<String> sorted by date descending
Definition at line 53 of file SortOrders.java.
References tomoBay.presenters.helpers.SortOrders.reAssembleCategories(), and tomoBay.model.services.helpers.InvoiceableStatus.size.
Referenced by tomoBay.presenters.helpers.SortOrders.sortDefault().
List<String[]> tomoBay.presenters.helpers.SortOrders.sortByShipping (List< String[]> input) private
sort the List<String> by shipping type descending (see ShippingPriority enum)
Parameters
input list of strings sorted by date descending.
Returns
List<String> sorted by ShippingPriority then date
Definition at line 72 of file SortOrders.java.
References tomoBay.presenters.helpers.SortOrders.reAssembleCategories(), and tomoBay.presenters.helpers.ShippingPriority.size.
Referenced by tomoBay.presenters.helpers.SortOrders.sortDefault().
List<String[]> tomoBay.presenters.helpers.SortOrders.sortDefault (List< String[]> input)
sort an input list of Strings i.e. the results of an eBay orders query, by shipping type and then by date.
Parameters
input
Returns
sorted list of strings.
Definition at line 45 of file SortOrders.java.
References tomoBay.presenters.helpers.SortOrders.sortByPickeability(), and tomoBay.presenters.helpers.SortOrders.sortByShipping().
Referenced by tomoBay.presenters.sales.SalesOrderPresenter.present().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/presenters/helpers/SortOrders.java