TomoBay: Buyer Class Reference
Buyer Class Reference
This class represents an eBay buyer and once instantiated contains all the pertinent information on the particular buyer instance.
Public Member Functions
Buyer (String buyerID)
CONSTRUCTOR, initialises object by grabbing the relevant information from the database, requires a valid buyerID in order to function properly.
Buyer (HeteroFieldContainer buyerInfo)
String buyerID ()
retrieve the BuyerID for this buyer
String name ()
retrieve the name of this buyer
String street1 ()
retrieve the first street line of the address of this buyer
String street2 ()
retrieve the second street line of the address of this buyer
String county ()
retrieve the county that this buyers address is associated with
String city ()
retrieve the city for this buyers listed address
String postcode ()
retreive the postcode for this buyers address
String email ()
retrieve the email address associated with this buyer
String phoneNo ()
retrieve the phone number of this buyer
Private Attributes
final HeteroFieldContainer buyerInfo_M
Static Private Attributes
static final String ERRORMSG
the error message that will be displayed should the incorrect no of arguments be used to create the Buyer
Detailed Description
This class represents an eBay buyer and once instantiated contains all the pertinent information on the particular buyer instance.
Author
Jan P.C. Hanson
Definition at line 31 of file Buyer.java.
Constructor & Destructor Documentation
Buyer (String buyerID)
CONSTRUCTOR, initialises object by grabbing the relevant information from the database, requires a valid buyerID in order to function properly.
Parameters
buyerID
Definition at line 45 of file Buyer.java.
References HeteroFieldContainer.add(), BuyerTable.BUYERID, SelectQueryInvoker.execute(), and SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_BUYER.
Buyer (HeteroFieldContainer buyerInfo)
Parameters
buyerInfo
Definition at line 56 of file Buyer.java.
References HeteroFieldContainer.size().
Member Function Documentation
String buyerID ()
retrieve the BuyerID for this buyer
Returns
String containing the BuyerID
Definition at line 66 of file Buyer.java.
References BuyerTable.BUYERID, HeteroFieldContainer.get(), and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo().
String name ()
retrieve the name of this buyer
Returns
String containing the name of this buyer
Definition at line 73 of file Buyer.java.
References HeteroFieldContainer.get(), BuyerTable.NAME, and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo(), and WinstockFormat.format().
String street1 ()
retrieve the first street line of the address of this buyer
Returns
String containing the first street line
Definition at line 80 of file Buyer.java.
References HeteroFieldContainer.get(), BuyerTable.STREET1, and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo(), and WinstockFormat.format().
String street2 ()
retrieve the second street line of the address of this buyer
Returns
String containing the second street line
Definition at line 87 of file Buyer.java.
References HeteroFieldContainer.get(), BuyerTable.STREET2, and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo(), WinstockFormat.format(), SalesDayBookLineFactory.make(), and OrderInfo.shippingInfo().
String county ()
retrieve the county that this buyers address is associated with
Returns
String containing the county
Definition at line 94 of file Buyer.java.
References BuyerTable.COUNTY, HeteroFieldContainer.get(), and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo(), and WinstockFormat.format().
String city ()
retrieve the city for this buyers listed address
Returns
String containing the city for this buyer
Definition at line 101 of file Buyer.java.
References BuyerTable.CITY, HeteroFieldContainer.get(), and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo(), and WinstockFormat.format().
String postcode ()
retreive the postcode for this buyers address
Returns
String containing the postcode of this buyer
Definition at line 108 of file Buyer.java.
References HeteroFieldContainer.get(), BuyerTable.POSTCODE, and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo(), and WinstockFormat.format().
String email ()
retrieve the email address associated with this buyer
Returns
String containing the email address of this buyer
Definition at line 115 of file Buyer.java.
References BuyerTable.EMAIL, HeteroFieldContainer.get(), and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo().
String phoneNo ()
retrieve the phone number of this buyer
Returns
long representing the phone number of this buyer
Definition at line 122 of file Buyer.java.
References HeteroFieldContainer.get(), BuyerTable.PHONE, and ClassRef.STRING.
Referenced by OrderInfo.buyerInfo().
Member Data Documentation
final String ERRORMSG static private
Initial value:
="a Buyer must be created with 8 elements: "
                                            + "ID, NAME, STREET1, STREE2, CITY, COUNTY, "
                                            + "POSTCODE, EMAIL and a PHONE"
the error message that will be displayed should the incorrect no of arguments be used to create the Buyer
Definition at line 34 of file Buyer.java.
final HeteroFieldContainer buyerInfo_M private
Definition at line 38 of file Buyer.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/StopGap/src/tomoBay/model/dataTypes/order/Buyer.java