TomoBay: DualList< V1, V2 > Class Template Reference
DualList< V1, V2 > Class Template Reference
Classes
class childIterator
Public Member Functions
DualList ()
create an empty PairList
void put (V1 value1, V2 value2)
add a value pair to the DualList
void put (V1 value1, V2 value2, int index)
add a value pair to this DualList at the index specified
DualList< V1, V2 > append (DualList< V1, V2 > dualList)
grows the list by the size of the DualList to append, and adds its contents after the end of the current contents.
V1 getValue1 (int index)
Returns the value1 at the specified position in the DualList.
V2 getValue2 (int index)
returns the value2 at the specified position in the DualList
void remove ()
removes the last value pair in the list.
void remove (int index)
Removes the element at the specified position in this list (optional operation).
void clear ()
clears the dualList, when this method returns the DualList will be of size 0.
int size ()
retrieve the size of the DualList
String toString ()
meaningful toString() method.
String toString (String separator)
provides a meaningful toString() method with the addition of being able to specify a user defined seperator for the list pairs.
void finalize () throws Throwable
finalizer.
Iterator< Integer > iterator ()
provides an iterator over the DualList.
Private Attributes
V1[] value1_M
the array holding the value1 values
V2[] value2_M
the array holding the value2 values
int size
the size of this pairList i.e.
Detailed Description
Definition at line 29 of file DualList.java.
Constructor & Destructor Documentation
DualList ()
create an empty PairList
Definition at line 42 of file DualList.java.
Member Function Documentation
void put (V1 value1, V2 value2)
add a value pair to the DualList
Parameters
value1
value2
Definition at line 54 of file DualList.java.
Referenced by JSONentity.addBranch(), JSONentity.addLeaf(), JSONentity.addPreFormatted(), WinstockFormat.format(), PrintInvoices.formatAsDualList(), and ClientSocketTest.main().
void put (V1 value1, V2 value2, int index)
add a value pair to this DualList at the index specified
Parameters
value1 the first value in the value pair
value2 the second value in the value pair
index the index at which to add the value pair
Definition at line 69 of file DualList.java.
DualList<V1,V2> append (DualList< V1, V2 > dualList)
grows the list by the size of the DualList to append, and adds its contents after the end of the current contents.
Parameters
dualList the DualList whose values should be appended to this one
Returns
DualList
Definition at line 88 of file DualList.java.
V1 getValue1 (int index)
Returns the value1 at the specified position in the DualList.
Parameters
index specifies the position in the DualList
Returns
K the key at the specified position
Definition at line 108 of file DualList.java.
V2 getValue2 (int index)
returns the value2 at the specified position in the DualList
Parameters
index Specifies the position in the DualList
Returns
V the value at the specified position.
Definition at line 116 of file DualList.java.
void remove ()
removes the last value pair in the list.
Definition at line 122 of file DualList.java.
void remove (int index)
Removes the element at the specified position in this list (optional operation).
Shifts any subsequent elements to the left (subtracts one from their indices).
Parameters
index the index at which to remove a value pair
Definition at line 134 of file DualList.java.
void clear ()
clears the dualList, when this method returns the DualList will be of size 0.
Definition at line 150 of file DualList.java.
Referenced by JSONentity.clear(), and JSONentity.finalize().
int size ()
retrieve the size of the DualList
Returns
int the size of the DualList
Definition at line 161 of file DualList.java.
Referenced by DualList< String, String >.put(), DualList< String, String >.remove(), and DualList< String, String >.size().
String toString ()
meaningful toString() method.
Returns
String comprised of comma separated value pairs
Definition at line 167 of file DualList.java.
String toString (String separator)
provides a meaningful toString() method with the addition of being able to specify a user defined seperator for the list pairs.
Parameters
separator user defined string to be inserted between value pairs.
Returns
String pairs of values seperated by the separator specified
Definition at line 181 of file DualList.java.
void finalize () throws Throwable
finalizer.
Definition at line 192 of file DualList.java.
Iterator<Integer> iterator ()
provides an iterator over the DualList.
Unusually, however, the iterator is of type Integer. this was done as there is the priority of the values is up to the user, there is no key/value relationship, and as such making this class iterable over one type of value doesnt make sense. This iterator provides syntactic suger allowing the use of the enhanced for loop as a shorthand for a standard loop.
Returns
Iterator of type Integer
Definition at line 207 of file DualList.java.
Member Data Documentation
V1 [] value1_M private
the array holding the value1 values
Definition at line 32 of file DualList.java.
Referenced by DualList< String, String >.append().
V2 [] value2_M private
the array holding the value2 values
Definition at line 34 of file DualList.java.
Referenced by DualList< String, String >.append().
int size private
the size of this pairList i.e.
how many elements independently stored in the arrays
Definition at line 36 of file DualList.java.
Referenced by DualList< String, String >.append().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/StopGap/src/tomoBay/model/dataTypes/DualList.java