TomoBay: tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders Class Reference
tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders Class Reference
Public Member Functions
SelectUninvoicedOrders ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
Static Private Attributes
static final String query = "SELECT * FROM ebay.ebay_orders WHERE invoiced <> 2;"
Detailed Description
This class represents a query that selects all data from the orders table that is not currently invoiced as determined by the value of the 'invoiced' field where a value of 0 indicates that the order is not invoicable, a value of 1 indicates that the order is partially invoicable and a value of 2 indicates that the order has been invoiced.
Author
Jan P.C. Hanson
Definition at line 34 of file SelectUninvoicedOrders.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.SelectUninvoicedOrders ()
default constructor
Definition at line 46 of file SelectUninvoicedOrders.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 122 of file SelectUninvoicedOrders.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter NOT USED for this query.
Returns
List<String[]> representing the results of the query. Each element in the list represents a row of the database and each element of the String[] represents a field.
The available fields for each element of the string[] are:
String[0] = orderID
String[1] = buyerID
String[2] = salesRecNo
String[3] = shippingType
String[4] = createdTime
String[5] = picked
String[6] = packed
String[7] = shipped
String[8] = invoiced
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 68 of file SelectUninvoicedOrders.java.
References tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.cleanup(), tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.formatResults(), and tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.initQuery().
List<String[]> tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 87 of file SelectUninvoicedOrders.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.execute().
void tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 111 of file SelectUninvoicedOrders.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.connection_M = null private
reference to the JDBC Database connection
Definition at line 39 of file SelectUninvoicedOrders.java.
final String tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.query = "SELECT * FROM ebay.ebay_orders WHERE invoiced <> 2;" static private
SQL query string
Definition at line 41 of file SelectUninvoicedOrders.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.SelectUninvoicedOrders.statement_M = null private
reference to the JDBC Statement
Definition at line 37 of file SelectUninvoicedOrders.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/SelectUninvoicedOrders.java