TomoBay: tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord Class Reference
tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord Class Reference
Public Member Functions
UpdateAvailableStockFord ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement1_M = null
PreparedStatement statement2_M = null
Connection connection_M = null
String query ="UPDATE parts_ford SET available=? WHERE partNo=?;"
String query2 = "UPDATE ebay_items SET notes=? WHERE itemID=?;"
Detailed Description
this class defines a database transaction comprised of two queries: the first updates the ford specific parts table with available stock data based on partNo. The second query updates the items table with a note (assuming there is an error) given a particular item id.
Author
Jan P.C. Hanson
Definition at line 33 of file UpdateAvailableStockFord.java.
Constructor & Destructor Documentation
tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.UpdateAvailableStockFord ()
default constructor
Definition at line 49 of file UpdateAvailableStockFord.java.
Member Function Documentation
void tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 103 of file UpdateAvailableStockFord.java.
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.execute().
List<String[]> tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. The Ebay Orders Table only has 4 columns so any element above the 3rd element will be ignored.
col1 = parts_ford.available:int(6)
col2 = parts_ford.partNo:varchar(50)
col3 = ebay_items.notes:varchar(60)
col4 = ebay_items.itemID:bigint(11)
Returns
List<String[]> representing the results of the query. The list contains only 2 columns the first is a resultcode for the first query, the second is the resultcode for the second query.
Exceptions
SQLException
Implements tomoBay.model.sql.queries.AbstractDBQuery.
Definition at line 66 of file UpdateAvailableStockFord.java.
References tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.cleanup(), and tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.initQuery().
void tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 91 of file UpdateAvailableStockFord.java.
References tomoBay.model.sql.ConnectionManager.getConnection(), and tomoBay.model.sql.ConnectionManager.instance().
Referenced by tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.execute().
Member Data Documentation
Connection tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.connection_M = null private
reference to the JDBC Database connection
Definition at line 40 of file UpdateAvailableStockFord.java.
String tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.query ="UPDATE parts_ford SET available=? WHERE partNo=?;" private
SQL query string
Definition at line 42 of file UpdateAvailableStockFord.java.
String tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.query2 = "UPDATE ebay_items SET notes=? WHERE itemID=?;" private
Definition at line 44 of file UpdateAvailableStockFord.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.statement1_M = null private
reference to the JDBC Statement
Definition at line 36 of file UpdateAvailableStockFord.java.
PreparedStatement tomoBay.model.sql.queries.concreteQueries.UpdateAvailableStockFord.statement2_M = null private
reference to the JDBC Statement
Definition at line 38 of file UpdateAvailableStockFord.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/sql/queries/concreteQueries/UpdateAvailableStockFord.java