TomoBay: CheckTime Class Reference
CheckTime Class Reference
This class provides static access to functions relating time, primarily to see if the current time is within the range set in the config file.
Static Public Member Functions
static boolean isInRange ()
tells you whether the current time is within the range specified in the config file.
static Date OutOfHoursDate ()
if before the start time for today returns yesterdays date otherwise returns todays date.
static String currentTimeStamp ()
does what it says on the tin.
Private Member Functions
CheckTime ()
default ctor
Static Private Member Functions
static int currentTime ()
queries the current time
static int currentDay ()
queries the current day
Static Private Attributes
static Map< Integer, Day > today_M
static map which equates Calendar enum constants to Day objects
Detailed Description
This class provides static access to functions relating time, primarily to see if the current time is within the range set in the config file.
Author
Jan P.C. Hanson
Definition at line 30 of file CheckTime.java.
Constructor & Destructor Documentation
CheckTime () private
default ctor
Definition at line 47 of file CheckTime.java.
Member Function Documentation
static boolean isInRange () static
tells you whether the current time is within the range specified in the config file.
Returns
true iff time is within range(inclusive), false otherwise.
Definition at line 54 of file CheckTime.java.
References CheckTime.currentDay(), CheckTime.currentTime(), and CheckTime.today_M.
Referenced by OutOfHoursService.onRunning().
static Date OutOfHoursDate () static
if before the start time for today returns yesterdays date otherwise returns todays date.
Returns
Calendar object returning the date that any out of hours should be registerd under
Definition at line 67 of file CheckTime.java.
References CheckTime.currentDay(), CheckTime.currentTime(), and CheckTime.today_M.
Referenced by OnRunning.getDate().
static String currentTimeStamp () static
does what it says on the tin.
Returns
String containing the current timestamp in the yyyy-mm-dd hh:mm:ss format
Definition at line 80 of file CheckTime.java.
static int currentTime () static private
queries the current time
Returns
int containing the current time
Definition at line 91 of file CheckTime.java.
Referenced by CheckTime.isInRange(), and CheckTime.OutOfHoursDate().
static int currentDay () static private
queries the current day
Returns
integer representation of the current day, with 1 = Sunday, 7 = saturday.
Definition at line 102 of file CheckTime.java.
Referenced by CheckTime.isInRange(), and CheckTime.OutOfHoursDate().
Member Data Documentation
Map<Integer, Day> today_M static private
Initial value:
= new THashMap<Integer, Day>()
            {{
                put(Calendar.MONDAY, new Monday());
                put(Calendar.TUESDAY, new Tuesday());
                put(Calendar.WEDNESDAY, new Wednesday());
                put(Calendar.THURSDAY, new Thursday());
                put(Calendar.FRIDAY, new Friday());
                put(Calendar.SATURDAY, new Saturday());
                put(Calendar.SUNDAY, new Sunday());
            }}
static map which equates Calendar enum constants to Day objects
Definition at line 33 of file CheckTime.java.
Referenced by CheckTime.isInRange(), and CheckTime.OutOfHoursDate().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/StopGap/src/tomoBay/helpers/checkTime/CheckTime.java