TomoBay: tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock Class Reference
tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock Class Reference
Public Member Functions
ReCalculateAvailableStock ()
void calculate (PartList parts, String brand, String partNo, String itemID)
Private Member Functions
int getStockLevel (String partNo, String brandCode)
void insertStockIntoDB (String brandCode, String partNo, int available, String notes, String itemID)
Detailed Description
This class recalculates the available stock of a particular listing, by querying Winstock for the appropriate information.
Author
Jan P.C. Hanson
Definition at line 28 of file ReCalculateAvailableStock.java.
Constructor & Destructor Documentation
tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.ReCalculateAvailableStock ()
default ctor
Definition at line 33 of file ReCalculateAvailableStock.java.
Member Function Documentation
void tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.calculate (PartList parts, String brand, String partNo, String itemID)
calculates the amount of available stock for a PartList.
Parameters
parts the PartsList for this particular eBay Item
brand the brand associated with this eBay Item
partNo the composite partNumber for this eBay item
itemID the eBay Item ID.
Definition at line 43 of file ReCalculateAvailableStock.java.
References tomoBay.helpers.BrandToCode.convert(), tomoBay.model.services.helpers.PartList.getPartNumber(), tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.getStockLevel(), tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.insertStockIntoDB(), and tomoBay.model.services.helpers.PartList.size().
Referenced by tomoBay.model.services.individualItemRefresh.IndividualItemRefreshService.run().
int tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.getStockLevel (String partNo, String brandCode) private
This method talks to winstock and returns an available stock level for a particular part number, given that it has an associated brand.
Parameters
partNo the part number to find the available stock level of.
brandCode a code representing the brand associated with the item.
Returns
an integer representing the amount of available stock.
Definition at line 70 of file ReCalculateAvailableStock.java.
References tomoBay.model.winstock.Stock.requestStockLevel().
Referenced by tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.calculate().
void tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.insertStockIntoDB (String brandCode, String partNo, int available, String notes, String itemID) private
This method inserts the available stock information into the appropriate tables of the database, which in this case is the brand specific tables.
Parameters
brandCode a code representing the brand associated with the eBay item.
partNo the individual part number to be updated
available the amount of available stock for this item
notes error messages ad notes that should be associated with a particular eBay item.
itemID the item ID that uniquely identifies a particular eBay item.
Definition at line 83 of file ReCalculateAvailableStock.java.
References tomoBay.model.sql.queries.QueryInvoker.execute(), tomoBay.model.sql.queries.QueryInvoker.QueryType.UPDATE_AVAILABLE_STOCK_FORD, tomoBay.model.sql.queries.QueryInvoker.QueryType.UPDATE_AVAILABLE_STOCK_PRESTIGE, and tomoBay.model.sql.queries.QueryInvoker.QueryType.UPDATE_AVAILABLE_STOCK_PSA.
Referenced by tomoBay.model.services.individualItemRefresh.ReCalculateAvailableStock.calculate().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/src/tomoBay/model/services/individualItemRefresh/ReCalculateAvailableStock.java