TomoBay: PresenterActionFactory Class Reference
PresenterActionFactory Class Reference
This class provides static functionality for creating AbstractPresenterActions.
Classes
enum PresenterActions
Public Member Functions
PresenterActionFactory ()
default ctor
Static Public Member Functions
static final AbstractPresenterAction make (PresenterActionFactory.PresenterActions action)
this method will provide you with the specific AbstractPresenterAction that you request using the PresenterAction provided as the argument to this method.
Static Private Attributes
static final Map< PresenterActions, AbstractPresenterActionFactory > actionMap_M
maps the type string to an action
Detailed Description
This class provides static functionality for creating AbstractPresenterActions.
Author
Jan P.C. Hanson
Definition at line 39 of file PresenterActionFactory.java.
Constructor & Destructor Documentation
PresenterActionFactory ()
default ctor
Definition at line 86 of file PresenterActionFactory.java.
Member Function Documentation
static final AbstractPresenterAction make (PresenterActionFactory.PresenterActions action) static
this method will provide you with the specific AbstractPresenterAction that you request using the PresenterAction provided as the argument to this method.
Parameters
action PresenterAction enum const specifying the AbstractPresenterAction to provide.
Returns
AbstractPresenterAction requested.
Definition at line 95 of file PresenterActionFactory.java.
References PresenterActionFactory.actionMap_M.
Referenced by OrderDetailsPresenter.present(), AdminPresenter.present(), RootPresenter.present(), CRMOverviewPresenter.present(), and CRMDetailPresenter.present().
Member Data Documentation
final Map<PresenterActions, AbstractPresenterActionFactory> actionMap_M static private
Initial value:
= new THashMap<PresenterActions, AbstractPresenterActionFactory>()
                {{
                    put(PresenterActions.LOG_FILE_VIEWER, new LogFileViewerFactory());
                    put(PresenterActions.MARK_AS_INVOICED, new MarkAsInvoicedFactory());
                    put(PresenterActions.MARK_AS_UNINVOICED, new MarkAsUninvoicedFactory());
                    put(PresenterActions.ORDER_INFO, new OrderInfoFactory());
                    put(PresenterActions.PERIODIC_SERVICES_CONTROLLER, new PeriodicServicesControllerFactory());
                    put(PresenterActions.RE_SCAN_LISTING, new ReScanListingFactory());
                    put(PresenterActions.BUYER_DETAILS, new BuyerDetailsFactory());
                    put(PresenterActions.BUYER_LIST, new BuyerListFactory());
                    put(PresenterActions.RE_SCAN_BUYER, new ReScanBuyerFactory());
                    put(PresenterActions.INVOICE_ORDERS, new InvoiceOrdersFactory());
                    put(PresenterActions.PRINT_INVOICES, new PrintInvoicesFactory());
                }}
maps the type string to an action
Definition at line 68 of file PresenterActionFactory.java.
Referenced by PresenterActionFactory.make().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/StopGap/src/tomoBay/presenters/presenterActions/PresenterActionFactory.java