
package com.royalmailgroup.api.ship.v2;

import javax.xml.ws.WebFault;
import com.royalmailgroup.soap.extensions.v1.ExceptionDetails;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "exceptionDetails", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2")
public class FaultResponse
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionDetails faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultResponse(String message, ExceptionDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FaultResponse(String message, ExceptionDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.royalmailgroup.soap.extensions.v1.ExceptionDetails
     */
    public ExceptionDetails getFaultInfo() {
        return faultInfo;
    }

}
