
package com.royalmailgroup.api.ship.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "shippingAPI", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", wsdlLocation = "file:/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/config/ShippingAPIV2(SOAP)/ShippingAPI_V2_0_9.wsdl")
public class ShippingAPI
    extends Service
{

    private final static URL SHIPPINGAPI_WSDL_LOCATION;
    private final static WebServiceException SHIPPINGAPI_EXCEPTION;
    private final static QName SHIPPINGAPI_QNAME = new QName("http://www.royalmailgroup.com/api/ship/V2", "shippingAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/config/ShippingAPIV2(SOAP)/ShippingAPI_V2_0_9.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHIPPINGAPI_WSDL_LOCATION = url;
        SHIPPINGAPI_EXCEPTION = e;
    }

    public ShippingAPI() {
        super(__getWsdlLocation(), SHIPPINGAPI_QNAME);
    }

    public ShippingAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIPPINGAPI_QNAME, features);
    }

    public ShippingAPI(URL wsdlLocation) {
        super(wsdlLocation, SHIPPINGAPI_QNAME);
    }

    public ShippingAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIPPINGAPI_QNAME, features);
    }

    public ShippingAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShippingAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShippingAPIPortType
     */
    @WebEndpoint(name = "shippingAPIPort")
    public ShippingAPIPortType getShippingAPIPort() {
        return super.getPort(new QName("http://www.royalmailgroup.com/api/ship/V2", "shippingAPIPort"), ShippingAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShippingAPIPortType
     */
    @WebEndpoint(name = "shippingAPIPort")
    public ShippingAPIPortType getShippingAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.royalmailgroup.com/api/ship/V2", "shippingAPIPort"), ShippingAPIPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIPPINGAPI_EXCEPTION!= null) {
            throw SHIPPINGAPI_EXCEPTION;
        }
        return SHIPPINGAPI_WSDL_LOCATION;
    }

}
