
package com.royalmailgroup.api.ship.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "shippingAPIPortType", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.royalmailgroup.api.ship.v2.ObjectFactory.class,
    com.royalmailgroup.cm.common.v4.ObjectFactory.class,
    com.royalmailgroup.cm.referencedata.v3.ObjectFactory.class,
    com.royalmailgroup.integration.core.v1.ObjectFactory.class,
    com.royalmailgroup.soap.extensions.v1.ObjectFactory.class,
    org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
    org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface ShippingAPIPortType {


    /**
     * 
     * @param createShipmentRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.CreateShipmentResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "createShipment")
    @WebResult(name = "createShipmentResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "createShipmentResponse")
    public CreateShipmentResponse createShipment(
        @WebParam(name = "createShipmentRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "createShipmentRequest")
        CreateShipmentRequest createShipmentRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param printLabelRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.PrintLabelResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "printLabel")
    @WebResult(name = "printLabelResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "printLabelResponse")
    public PrintLabelResponse printLabel(
        @WebParam(name = "printLabelRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "printLabelRequest")
        PrintLabelRequest printLabelRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param createManifestRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.CreateManifestResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "createManifest")
    @WebResult(name = "createManifestResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "createManifestResponse")
    public CreateManifestResponse createManifest(
        @WebParam(name = "createManifestRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "createManifestRequest")
        CreateManifestRequest createManifestRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param printManifestRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.PrintManifestResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "printManifest")
    @WebResult(name = "printManifestResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "printManifestResponse")
    public PrintManifestResponse printManifest(
        @WebParam(name = "printManifestRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "printManifestRequest")
        PrintManifestRequest printManifestRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param updateShipmentRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.UpdateShipmentResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "updateShipment")
    @WebResult(name = "updateShipmentResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "updateShipmentResponse")
    public UpdateShipmentResponse updateShipment(
        @WebParam(name = "updateShipmentRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "updateShipmentRequest")
        UpdateShipmentRequest updateShipmentRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param cancelShipmentRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.CancelShipmentResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "cancelShipment")
    @WebResult(name = "cancelShipmentResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "cancelShipmentResponse")
    public CancelShipmentResponse cancelShipment(
        @WebParam(name = "cancelShipmentRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "cancelShipmentRequest")
        CancelShipmentRequest cancelShipmentRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param printDocumentRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.PrintDocumentResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "printDocument")
    @WebResult(name = "printDocumentResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "printDocumentResponse")
    public PrintDocumentResponse printDocument(
        @WebParam(name = "printDocumentRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "printDocumentRequest")
        PrintDocumentRequest printDocumentRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param request1DRangesRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.Request1DRangesResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "request1DRanges")
    @WebResult(name = "request1DRangesResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "request1DRangesResponse")
    public Request1DRangesResponse request1DRanges(
        @WebParam(name = "request1DRangesRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "request1DRangesRequest")
        Request1DRangesRequest request1DRangesRequest)
        throws FaultResponse
    ;

    /**
     * 
     * @param request2DItemIDRangeRequest
     * @return
     *     returns com.royalmailgroup.api.ship.v2.Request2DItemIDRangeResponse
     * @throws FaultResponse
     */
    @WebMethod(action = "request2DItemIDRange")
    @WebResult(name = "request2DItemIDRangeResponse", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "request2DItemIDRangeResponse")
    public Request2DItemIDRangeResponse request2DItemIDRange(
        @WebParam(name = "request2DItemIDRangeRequest", targetNamespace = "http://www.royalmailgroup.com/api/ship/V2", partName = "request2DItemIDRangeRequest")
        Request2DItemIDRangeRequest request2DItemIDRangeRequest)
        throws FaultResponse
    ;

}
