TomoBay: AbstractModifyQueryParams Class Reference
AbstractModifyQueryParams Class Reference abstract
This is the Abstract Base class for all queries that modify the database in some way (INSERT/UPDATE/DELETE) and require some parameter(s) in order to function properly.
Public Member Functions
AbstractModifyQueryParams ()
default CTOR
HeteroFieldContainer execute (HeteroFieldContainer parameters) throws SQLException
Executes the query using the provided parameters and returns a HeteroFieldContainer containing the result fields (refer to the specific derived class docs for individual info)
Public Member Functions inherited from AbstractModifyQuery
AbstractModifyQuery ()
default ctor
Public Member Functions inherited from AbstractDBQuery
PreparedStatement statement ()
get the statement object associated with this query
Protected Member Functions
abstract String queryString ()
Used by derived classes to define the Query string to be used in the query.
abstract void setParameters (HeteroFieldContainer parameter) throws ClassCastException, SQLException
Used by derived classes to set the parameters for this particular query.
Protected Member Functions inherited from AbstractDBQuery
abstract String queryString ()
Used by derived classes to define the Query string to be used in the query.
void cleanup () throws SQLException
commits the transaction and does cleanup after the query has been executed
Private Member Functions
void initQuery (String query) throws SQLException
initialise the connection and statement and set transaction variables.
Additional Inherited Members
Protected Attributes inherited from AbstractDBQuery
PreparedStatement statement_M = null
reference to the JDBC Statement
Connection connection_M = null
reference to the JDBC Database connection
Detailed Description
This is the Abstract Base class for all queries that modify the database in some way (INSERT/UPDATE/DELETE) and require some parameter(s) in order to function properly.
Author
Jan P.C. Hanson
Definition at line 28 of file AbstractModifyQueryParams.java.
Constructor & Destructor Documentation
AbstractModifyQueryParams ()
default CTOR
Definition at line 34 of file AbstractModifyQueryParams.java.
Member Function Documentation
HeteroFieldContainer execute (HeteroFieldContainer parameters) throws SQLException
Executes the query using the provided parameters and returns a HeteroFieldContainer containing the result fields (refer to the specific derived class docs for individual info)
Parameters
parameters HeteroFieldContainer containing the parameters that this query needs.
Returns
HeteroFieldContainer containing a NonDBFields.RESULT_CODE field only.
Exceptions
SQLException
Definition at line 46 of file AbstractModifyQueryParams.java.
References AbstractModifyQueryParams.initQuery(), AbstractModifyQueryParams.queryString(), NonDBFields.RESULT_CODE, and AbstractModifyQueryParams.setParameters().
abstract String queryString () abstract protected
Used by derived classes to define the Query string to be used in the query.
Returns
String containing the JDBC query string
Referenced by AbstractModifyQueryParams.execute().
abstract void setParameters (HeteroFieldContainer parameter) throws ClassCastException, SQLException abstract protected
Used by derived classes to set the parameters for this particular query.
Exceptions
SQLException
ClassCastException
Referenced by AbstractModifyQueryParams.execute().
void initQuery (String query) throws SQLException private
initialise the connection and statement and set transaction variables.
Parameters
query String containing the sql query
Exceptions
SQLException
Definition at line 74 of file AbstractModifyQueryParams.java.
References AbstractDBQuery.connection_M, ConnectionManager.getConnection(), ConnectionManager.instance(), and AbstractDBQuery.statement_M.
Referenced by AbstractModifyQueryParams.execute().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/framework/queryTypes/modify/AbstractModifyQueryParams.java