TomoBay: RoyalMailCSVGenerator Class Reference
RoyalMailCSVGenerator Class Reference
This class represents an object that generates CSV files in a format that the Royal Mail Dispatch Manager Online can accept.
Public Member Functions
RoyalMailCSVGenerator ()
ctor, creates an empty CSV of the format: "Service Reference","Service","Recipient","Address Line 1","Address Line 2","PostCode","Post Town", "Country Code","Reference","Items","Weight","Service Enhancement","Service Format",
void setseparators (char separator, char entryIndicator)
This method allows you to set different separators than the default values, it is recommended to leave the defaults active unless you have a good reason not to.
void addRow (String[] row) throws ArrayIndexOutOfBoundsException, ArrayStoreException
Adds a row of data to the CSV and checks the validity of the data against the specification defined in the config file (tomoBay.conf)
void addBatch (List< String[]> batch) throws ArrayIndexOutOfBoundsException
adds a whole batch of data to the end of the CSV
void generate (String fileName, String filePath, String encoding) throws IOException
Generated the actual CSV file, it will overwrite any file already at that path with the name specified.
int size ()
indicates how many columns are required for each row of this CSV.
String toString ()
informative String representation of the CSV file at the point in time where this method is called.
Static Private Member Functions
static void checkSize (String[] row, String[] columnNames) throws ArrayIndexOutOfBoundsException
make sure that the two arrays are the same length
static void validate (String[] row, String[] columnValidations) throws ArrayStoreException
Use the validation data pulled from the config file at construction time and make sure that the data entries are valid.
Private Attributes
final String[] columnNames_M
final String[] columnValidations_M
char separator_M = ','
char entryIndicator_M ='"'
List< String[]> result_M
Detailed Description
This class represents an object that generates CSV files in a format that the Royal Mail Dispatch Manager Online can accept.
The Columns in this CSV are laid out as follows:
Field Name Order Format Notes
Service Reference 0 n/a SR1
Service 1 n/a available options: 24/48/SD500/SD1000/SD2500
Recipient 2 n/a recipients name
Address Line 1 3 n/a first address line
Address Line 2 4 ` n/a second address line
PostCode 5 n/a recipients post code (must match with post town)
Post Town 6 n/a recipients town must match with postcode
Country Code 7 n/a GB
Reference 8 n/a (C or F or P) followed by invoice#
Items 9 ` n/a always 1
Weight 10 12000 the weight in grams of the invoice
Service Enhancement 11 n/a SF (if signed for) OR leave blank
Service Format 12 n/a L (for letter) or P(for parcel)
Author
Jan P.C. Hanson
Definition at line 53 of file RoyalMailCSVGenerator.java.
Constructor & Destructor Documentation
RoyalMailCSVGenerator ()
ctor, creates an empty CSV of the format: "Service Reference","Service","Recipient","Address Line 1","Address Line 2","PostCode","Post Town", "Country Code","Reference","Items","Weight","Service Enhancement","Service Format",
Definition at line 66 of file RoyalMailCSVGenerator.java.
References Config.CSV_FIELD_NAME, Config.CSV_FIELD_VALID, and ConfigReader.getConfs().
Member Function Documentation
void setseparators (char separator, char entryIndicator)
This method allows you to set different separators than the default values, it is recommended to leave the defaults active unless you have a good reason not to.
Parameters
separator defaults to a comma ,
entryIndicator defaults to double quotes ""
Implements CSVGenerator.
Definition at line 81 of file RoyalMailCSVGenerator.java.
Referenced by RoyalMailCSVGeneratorTest.testSetseparators().
void addRow (String[] row) throws ArrayIndexOutOfBoundsException, ArrayStoreException
Adds a row of data to the CSV and checks the validity of the data against the specification defined in the config file (tomoBay.conf)
Parameters
row String[] of data to be inserted into the CSV
Exceptions
ArrayIndexOutOfBoundsException if the data array is longer than is specified by this CSV (see tomoBay.conf)
ArrayStoreException if the data is not valid data for a particular column (see tomobay.conf)
Implements CSVGenerator.
Definition at line 96 of file RoyalMailCSVGenerator.java.
References RoyalMailCSVGenerator.checkSize(), and RoyalMailCSVGenerator.validate().
Referenced by RoyalMailCSVGeneratorTest.testAddRow(), RoyalMailCSVGeneratorTest.testGenerate(), RoyalMailCSVGeneratorTest.testSetseparators(), RoyalMailCSVGeneratorTest.testToStringBadInput(), and RoyalMailCSVGeneratorTest.testToStringGoodInput().
void addBatch (List< String[]> batch) throws ArrayIndexOutOfBoundsException
adds a whole batch of data to the end of the CSV
Parameters
batch List<String[]> containing the batch information
Exceptions
ArrayIndexOutOfBoundsException if the data array is longer than is specified by this CSV (see tomoBay.conf)
ArrayStoreException if the data is not valid data for a particular column (see tomobay.conf)
Definition at line 110 of file RoyalMailCSVGenerator.java.
Referenced by GenerateRoyalMailCSV.createCSV(), and RoyalMailCSVGeneratorTest.testAddBatch().
void generate (String fileName, String filePath, String encoding) throws IOException
Generated the actual CSV file, it will overwrite any file already at that path with the name specified.
Parameters
fileName the name of the file to create
filePath the path of the file to create
encoding the encoding to use on creation of the file
Exceptions
IOException
Implements CSVGenerator.
Definition at line 122 of file RoyalMailCSVGenerator.java.
References RoyalMailCSVGenerator.separator_M.
Referenced by GenerateRoyalMailCSV.createCSV(), and RoyalMailCSVGeneratorTest.testGenerate().
int size ()
indicates how many columns are required for each row of this CSV.
Returns
int representing the number of columns.
Implements CSVGenerator.
Definition at line 145 of file RoyalMailCSVGenerator.java.
Referenced by GenerateRoyalMailCSV.formatInitialData(), and RoyalMailCSVGeneratorTest.testSize().
String toString ()
informative String representation of the CSV file at the point in time where this method is called.
This method should print out the names of the columns as the first line, followed by the values of each of those columns in a given row.
Returns
String representation of the CSV File in its current state.
Implements CSVGenerator.
Definition at line 153 of file RoyalMailCSVGenerator.java.
References RoyalMailCSVGenerator.separator_M.
Referenced by GenerateRoyalMailCSV.createCSV(), RoyalMailCSVGeneratorTest.testSetseparators(), RoyalMailCSVGeneratorTest.testToStringBadInput(), and RoyalMailCSVGeneratorTest.testToStringGoodInput().
static void checkSize (String[] row, String[] columnNames) throws ArrayIndexOutOfBoundsException static private
make sure that the two arrays are the same length
Parameters
row the String[] containing the data
columnNames String[] containing the column names
Exceptions
ArrayIndexOutOfBoundsException
Definition at line 173 of file RoyalMailCSVGenerator.java.
Referenced by RoyalMailCSVGenerator.addRow().
static void validate (String[] row, String[] columnValidations) throws ArrayStoreException static private
Use the validation data pulled from the config file at construction time and make sure that the data entries are valid.
Parameters
row Data to be validated
columnValidations the regular expressions used to validate the data
Exceptions
ArrayStoreException thrown if any of the expressions do not find matches.
Definition at line 187 of file RoyalMailCSVGenerator.java.
Referenced by RoyalMailCSVGenerator.addRow().
Member Data Documentation
final String [] columnNames_M private
Definition at line 55 of file RoyalMailCSVGenerator.java.
final String [] columnValidations_M private
Definition at line 56 of file RoyalMailCSVGenerator.java.
char separator_M = ',' private
Definition at line 57 of file RoyalMailCSVGenerator.java.
Referenced by RoyalMailCSVGenerator.generate(), and RoyalMailCSVGenerator.toString().
char entryIndicator_M ='"' private
Definition at line 58 of file RoyalMailCSVGenerator.java.
List<String[]> result_M private
Definition at line 59 of file RoyalMailCSVGenerator.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/royalMail/RoyalMailCSVGenerator.java