My Project: openDMS.presenters.ebay.EbayPresenter Class Reference
openDMS.presenters.ebay.EbayPresenter Class Reference
Public Member Functions
EbayPresenter ()
String present (AbstractView view)
Private Member Functions
String doStuff ()
Detailed Description
Author
Jan P.C. Hanson
Definition at line 25 of file EbayPresenter.java.
Constructor & Destructor Documentation
openDMS.presenters.ebay.EbayPresenter.EbayPresenter ()
default constructor
Definition at line 30 of file EbayPresenter.java.
Member Function Documentation
String openDMS.presenters.ebay.EbayPresenter.doStuff () private
Definition at line 48 of file EbayPresenter.java.
Referenced by openDMS.presenters.ebay.EbayPresenter.present().
String openDMS.presenters.ebay.EbayPresenter.present (AbstractView view)
this method is called when you actually want to present the information contained in the view/presenter to the servlet
Parameters
view the view to be rpesented
Returns
String representing the html contained in the view/presenter
Implements openDMS.presenters.AbstractPresenter.
Definition at line 37 of file EbayPresenter.java.
References openDMS.presenters.ebay.EbayPresenter.doStuff(), openDMS.view.views.EbayView.Part.FOOTER, openDMS.view.views.EbayView.Part.HEADER, and openDMS.view.views.AbstractView.make().
The documentation for this class was generated from the following file:
src/openDMS/presenters/ebay/EbayPresenter.java