TomoBay: OnRunning Class Reference
OnRunning Class Reference
Public Member Functions
OnRunning (String buyerID)
default ctor
String execute ()
this method defines what to do in the given derived state
Static Private Member Functions
static void getAddress (OrderType order, HeteroFieldContainer container)
retrieves the personal address associated with the order passed in as an argument.
static void getGSPaddress (OrderType order, HeteroFieldContainer container)
retrieves the global shipping program address associated with the order passed in as an argument.
Private Attributes
String buyerID_M
the ebay buyerID
Detailed Description
Author
Jan P.C. Hanson
Definition at line 37 of file OnRunning.java.
Constructor & Destructor Documentation
OnRunning (String buyerID)
default ctor
Definition at line 45 of file OnRunning.java.
Member Function Documentation
String execute ()
this method defines what to do in the given derived state
Returns
String representing the end product of the state.
Implements AbstractServiceState.
Definition at line 55 of file OnRunning.java.
References OrdersTable.ACCOUNT, EbayAccounts.apiKey(), OrdersCall.call(), HeteroFieldContainer.get(), OnRunning.getAddress(), OnRunning.getGSPaddress(), DBActions.getLatestOrderID(), ClassRef.INTEGER, EbayAccounts.name(), OrdersTable.ORDER_ID, NonDBFields.RESULT_CODE, EbayAccounts.serverAddress(), ClassRef.STRING, and DBActions.updateBuyerTable().
Referenced by ReScanBuyerService.onRunning().
static void getAddress (OrderType order, HeteroFieldContainer container) static private
retrieves the personal address associated with the order passed in as an argument.
Parameters
order the OrderType representing a particular order (from ebay API)
container the HeterpFieldContainer to add the address fields to.
Returns
HeteroFieldContainer containing the address fields for this buyer
Definition at line 89 of file OnRunning.java.
References HeteroFieldContainer.add(), BuyerTable.BUYERID, BuyerTable.CITY, BuyerTable.COUNTY, BuyerTable.EMAIL, BuyerTable.NAME, BuyerTable.PHONE, BuyerTable.POSTCODE, BuyerTable.STREET1, and BuyerTable.STREET2.
Referenced by OnRunning.execute().
static void getGSPaddress (OrderType order, HeteroFieldContainer container) static private
retrieves the global shipping program address associated with the order passed in as an argument.
This method will return a null pointer if the order is not applicable to the global shipping program
Parameters
order the OrderType representing a particular order (from ebay API)
container the HeterpFieldContainer to add the address fields to.
Returns
HeteroFieldContainer containing the address fields for this buyer
Definition at line 110 of file OnRunning.java.
References HeteroFieldContainer.add(), BuyerTable.BUYERID, BuyerTable.CITY, BuyerTable.COUNTY, BuyerTable.EMAIL, BuyerTable.NAME, BuyerTable.PHONE, BuyerTable.POSTCODE, BuyerTable.STREET1, and BuyerTable.STREET2.
Referenced by OnRunning.execute().
Member Data Documentation
String buyerID_M private
the ebay buyerID
Definition at line 40 of file OnRunning.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/services/reScanBuyerService/OnRunning.java