TomoBay: Pair< X, Y > Class Template Reference
Pair< X, Y > Class Template Reference
Copyright(C) 2015 Jan P.C.
Public Member Functions
Pair (X xVal, Y yVal)
Instantiates the pair with the x and y values provided, where x is of type X and y is of type Y.
final X xVal ()
retrieve the x-value
final Y yVal ()
retrieve the y-value
Private Attributes
final X xValue_M
the x-value of this pair
final Y yValue_M
the y-value of this pair
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/. This class represents a pair of values of type <X,Y>
Author
Jan P.C. Hanson
Definition at line 23 of file Pair.java.
Constructor & Destructor Documentation
Pair (X xVal, Y yVal)
Instantiates the pair with the x and y values provided, where x is of type X and y is of type Y.
Parameters
xVal X the x-value of this pair
yVal Y the y-value of this pair
Definition at line 36 of file Pair.java.
References Pair< X, Y >.xVal(), and Pair< X, Y >.yVal().
Member Function Documentation
final X xVal ()
retrieve the x-value
Returns
X the value of x
Definition at line 47 of file Pair.java.
References Pair< X, Y >.xValue_M.
Referenced by Pair< X, Y >.Pair().
final Y yVal ()
retrieve the y-value
Returns
Y the value of y
Definition at line 53 of file Pair.java.
References Pair< X, Y >.yValue_M.
Referenced by Pair< X, Y >.Pair().
Member Data Documentation
final X xValue_M private
the x-value of this pair
Definition at line 26 of file Pair.java.
Referenced by Pair< X, Y >.xVal().
final Y yValue_M private
the y-value of this pair
Definition at line 28 of file Pair.java.
Referenced by Pair< X, Y >.yVal().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/Pair.java