TomoBay: OnRunning Class Reference
OnRunning Class Reference
Public Member Functions
OnRunning (Long listingID)
String execute ()
this method defines what to do in the given derived state
Private Member Functions
ItemType getItemData (Long itemID, int account)
use the itemID passed in to find out information about a specific eBay item.
Map< String, String > getSpecifics (ItemType item)
Read the Brand and the manufacturer part number into a map for convenience.
Private Attributes
Long listingID_M
Static Private Attributes
static Logger log = Logger.getLogger(OnRunning.class.getName())
Detailed Description
Author
Jan P.C. Hanson
Definition at line 41 of file OnRunning.java.
Constructor & Destructor Documentation
OnRunning (Long listingID)
Definition at line 49 of file OnRunning.java.
Member Function Documentation
String execute ()
this method defines what to do in the given derived state
Returns
String representing the end product of the state.
Implements AbstractServiceState.
Definition at line 59 of file OnRunning.java.
References ItemsTable.ACCOUNT, HeteroFieldContainer.add(), SelectQueryInvoker.execute(), OnRunning.getItemData(), OnRunning.getSpecifics(), ClassRef.INTEGER, ItemsTable.ITEM_ID, RePopulateEbayItem.populate(), SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_ITEM_SPECIFIC, and StackTraceToString.toString().
Referenced by IndividualItemRefreshService.onRunning().
ItemType getItemData (Long itemID, int account) private
use the itemID passed in to find out information about a specific eBay item.
Parameters
itemID the ID of a particular eBay Item (listing)
account integer representing the account that is requesting the item data (as defined in the ebay_accounts table of the database)
Returns
ItemType eBay API datatype containing the details of a particular item.
Definition at line 92 of file OnRunning.java.
References EbayAccounts.apiKey(), ItemCall.call(), EbayAccounts.name(), EbayAccounts.serverAddress(), and StackTraceToString.toString().
Referenced by OnRunning.execute().
Map<String, String> getSpecifics (ItemType item) private
Read the Brand and the manufacturer part number into a map for convenience.
Parameters
item the item to store the brand and manufacturer part number of.
Returns
Map<String,String> containing the above data.
Definition at line 113 of file OnRunning.java.
Referenced by OnRunning.execute().
Member Data Documentation
Logger log = Logger.getLogger(OnRunning.class.getName()) static private
Definition at line 43 of file OnRunning.java.
Long listingID_M private
Definition at line 44 of file OnRunning.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/services/individualItemRefreshService/OnRunning.java