TomoBay: Buyers_Table Class Reference
Buyers_Table Class Reference
updates the buyers table of the database with the information gleaned from an ebay api call
Public Member Functions
Buyers_Table ()
default ctor
Static Public Member Functions
static void populate (OrderType[] orders) throws SQLException
populates the Orders Table in the database with data grabbed from the ebay API
Static Private Member Functions
static void getAddress (OrderType order, HeteroFieldContainer container)
retrieves the personal address associated with the order passed in as an argument.
static void getGSPaddress (OrderType order, HeteroFieldContainer container)
retrieves the global shipping program address associated with the order passed in as an argument.
Detailed Description
updates the buyers table of the database with the information gleaned from an ebay api call
Author
Jan P.C. Hanson
Definition at line 30 of file Buyers_Table.java.
Constructor & Destructor Documentation
Buyers_Table ()
default ctor
Definition at line 35 of file Buyers_Table.java.
Member Function Documentation
static void populate (OrderType[] orders) throws SQLException static
populates the Orders Table in the database with data grabbed from the ebay API
Parameters
orders list of orders.
Exceptions
SQLException
Definition at line 43 of file Buyers_Table.java.
References ModifyQueryInvoker.execute(), Buyers_Table.getAddress(), Buyers_Table.getGSPaddress(), and ModifyQueryInvoker.ModifyQueryTypeParams.INSERT_EBAY_BUYERS.
Referenced by OnRunning.execute().
static void getAddress (OrderType order, HeteroFieldContainer container) static private
retrieves the personal address associated with the order passed in as an argument.
Parameters
order the OrderType representing a particular order (from ebay API)
container the HeterpFieldContainer to add the address fields to.
Returns
container containing the address fields for this buyer
Definition at line 68 of file Buyers_Table.java.
References HeteroFieldContainer.add(), BuyerTable.BUYERID, BuyerTable.CITY, BuyerTable.COUNTY, BuyerTable.EMAIL, BuyerTable.NAME, BuyerTable.PHONE, BuyerTable.POSTCODE, BuyerTable.STREET1, and BuyerTable.STREET2.
Referenced by Buyers_Table.populate().
static void getGSPaddress (OrderType order, HeteroFieldContainer container) static private
retrieves the global shipping program address associated with the order passed in as an argument.
This method will return a null pointer if the order is not applicable to the global shipping program
Parameters
order the OrderType representing a particular order (from ebay API)
container the HeterpFieldContainer to add the address fields to.
Returns
container containing the address fields for this buyer
Definition at line 89 of file Buyers_Table.java.
References HeteroFieldContainer.add(), BuyerTable.BUYERID, BuyerTable.CITY, BuyerTable.COUNTY, BuyerTable.EMAIL, BuyerTable.NAME, BuyerTable.PHONE, BuyerTable.POSTCODE, BuyerTable.STREET1, and BuyerTable.STREET2.
Referenced by Buyers_Table.populate().
The documentation for this class was generated from the following file:
src/tomoBay/model/services/basicEbayUpdateService/Buyers_Table.java