TomoBay: HttpGET Class Reference
HttpGET Class Reference
provides functionality to perform a HTTP GET request and recieve a HttpResponse object in response.
Public Member Functions
HttpGET ()
default constructor
HttpResponse request (String targetURL)
perform an HTTP GET request for the specified url, returns the contents of the response as a string.
Private Member Functions
HttpURLConnection setUpConnection (URL url) throws IOException
do setup for the HttpURLConnection object
String readConnection (int responseCode, HttpURLConnection connection) throws IOException
reads from the HttpURLConnection and passes back a string containing the contents of the response.
String stackTraceToString (Exception e)
converts a stacktrace to a string that can be printed to the screen
Detailed Description
provides functionality to perform a HTTP GET request and recieve a HttpResponse object in response.
Author
Jan P.C. Hanson
Definition at line 30 of file HttpGET.java.
Constructor & Destructor Documentation
HttpGET ()
default constructor
Definition at line 35 of file HttpGET.java.
Member Function Documentation
HttpResponse request (String targetURL)
perform an HTTP GET request for the specified url, returns the contents of the response as a string.
Parameters
targetURL
Returns
String containing the value of the HTTP response
Exceptions
IOException
Definition at line 45 of file HttpGET.java.
References HttpGET.readConnection(), HttpGET.setUpConnection(), and HttpGET.stackTraceToString().
HttpURLConnection setUpConnection (URL url) throws IOException private
do setup for the HttpURLConnection object
Parameters
url URL representing the address you wish to visit
Returns
HttpURLConnection to the specified URL
Exceptions
IOException
Definition at line 67 of file HttpGET.java.
Referenced by HttpGET.request().
String readConnection (int responseCode, HttpURLConnection connection) throws IOException private
reads from the HttpURLConnection and passes back a string containing the contents of the response.
Parameters
responseCode
connection
Returns
Exceptions
IOException
Definition at line 83 of file HttpGET.java.
Referenced by HttpGET.request().
String stackTraceToString (Exception e) private
converts a stacktrace to a string that can be printed to the screen
Parameters
e the exception to convert the stack trace of
Returns
String containing the stack trace of the Exception specified.
Definition at line 105 of file HttpGET.java.
Referenced by HttpGET.request().
The documentation for this class was generated from the following file:
src/tomoBay/model/net/HttpGET.java