TomoBay: TransactionsTable Class Reference
TransactionsTable Class Reference
This represents the ebay_transactions table in the database, An order usually consists of one transaction but there are occaisions where a customer will order multiple listings in one order when this is the case there will be multiple transactions associated with a particular order.
Static Public Attributes
static final TransactionID TRANSACTION_ID = new TransactionID()
The transactionID column of the ebay_transactions table.
static final AbstractField ORDER_ID = OrdersTable.ORDER_ID
The orderID column of the ebay_transactions table.
static final AbstractField ITEM_ID = ItemsTable.ITEM_ID
The itemID column of the ebay_transactions table.
static final Quantity QUANTITY = new Quantity()
the quantity column of the ebay_transactions table
static final Price PRICE = new Price()
The price column of the ebay_transactions table.
static final ShippingCost SHIPPING_COST = new ShippingCost()
The shippingCost column of the ebay_transactions table.
Private Member Functions
TransactionsTable ()
private ctor ensures this class is never instantiated
Detailed Description
This represents the ebay_transactions table in the database, An order usually consists of one transaction but there are occaisions where a customer will order multiple listings in one order when this is the case there will be multiple transactions associated with a particular order.
It is worth noting that in this scenario there will also be multiple sales record numbers for the order (hence why the sales record numbers may have breaks between orders). It is also worth noting that in the case where there are multiple transactions on an order; there orderID will be a single (large number) rather than a combination of the transactionID and the itemID with a hyphen between them.
Author
Jan P.C. Hanson
Definition at line 34 of file TransactionsTable.java.
Constructor & Destructor Documentation
TransactionsTable () private
private ctor ensures this class is never instantiated
Definition at line 91 of file TransactionsTable.java.
Member Data Documentation
final TransactionID TRANSACTION_ID = new TransactionID() static
The transactionID column of the ebay_transactions table.
BIGINT(20)
Primary Key
See also
tomoBay.model.sql.schema.transactionsTable.TransactionID
Definition at line 42 of file TransactionsTable.java.
Referenced by SelectUncalculatedInvoices.format(), SelectTransactionByOrder.format(), Transaction.getTransactionInfo(), Order.getTransactionList(), Transactions_Table.populate(), InsertEbayTransactions.setParameters(), and SelectEbayTransactionByID.setParameters().
final AbstractField ORDER_ID = OrdersTable.ORDER_ID static
The orderID column of the ebay_transactions table.
VARCHAR(30)
Foreign Key ebay_orders table
See also
tomoBay.model.sql.schema.ordersTable.OrderID
tomoBay.model.sql.schema.ordersTable.OrdersTable
Definition at line 52 of file TransactionsTable.java.
Referenced by SelectUncalculatedInvoices.format(), Transactions_Table.populate(), InsertEbayTransactions.setParameters(), and SelectTransactionByOrder.setParameters().
final AbstractField ITEM_ID = ItemsTable.ITEM_ID static
The itemID column of the ebay_transactions table.
BIGINT(20)
Foreign Key ebay_items table
See also
tomoBay.model.sql.schema.itemsTable.ItemID
tomoBay.model.sql.schema.itemsTable.ItemsTable
Definition at line 62 of file TransactionsTable.java.
Referenced by SelectTransactionByOrder.format(), SelectEbayTransactionByID.format(), Transactions_Table.populate(), InsertEbayTransactions.setParameters(), and Transaction.Transaction().
final Quantity QUANTITY = new Quantity() static
the quantity column of the ebay_transactions table
INT(7)
See also
tomoBay.model.sql.schema.transactionsTable.Quantity
Definition at line 70 of file TransactionsTable.java.
Referenced by SelectUncalculatedInvoices.format(), SelectEbayTransactionByID.format(), SelectFullOrderLine.format(), Transactions_Table.populate(), Transaction.qtyPurchased(), and InsertEbayTransactions.setParameters().
final Price PRICE = new Price() static
The price column of the ebay_transactions table.
FLOAT()
See also
tomoBay.model.sql.schema.transactionsTable.Price
Definition at line 78 of file TransactionsTable.java.
Referenced by SelectUncalculatedInvoices.format(), SelectEbayTransactionByID.format(), SelectFullOrderLine.format(), Transactions_Table.populate(), InsertEbayTransactions.setParameters(), and Transaction.transactionPrice().
final ShippingCost SHIPPING_COST = new ShippingCost() static
The shippingCost column of the ebay_transactions table.
FLOAT()
See also
tomoBay.model.sql.schema.transactionsTable.ShippingCost
Definition at line 86 of file TransactionsTable.java.
Referenced by SelectUncalculatedInvoices.format(), SelectEbayTransactionByID.format(), SelectFullOrderLine.format(), Transactions_Table.populate(), InsertEbayTransactions.setParameters(), and Transaction.shippingCost().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/schema/transactionsTable/TransactionsTable.java