My Project: openDMS.ebay.query.recievers.ItemCall Class Reference
openDMS.ebay.query.recievers.ItemCall Class Reference
Public Member Functions
ItemCall (String usrToken, String server)
ApiItemData call (ApiItemData data, String itemId)
Additional Inherited Members
Protected Member Functions inherited from openDMS.ebay.query.recievers.AbstractAPIcall
AbstractAPIcall (String usrToken, String server)
Protected Attributes inherited from openDMS.ebay.query.recievers.AbstractAPIcall
String usrToken_M
String server_M
Detailed Description
Copyright(C) 2015 Jan P.C. Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jan P.C. Hanson
Definition at line 30 of file ItemCall.java.
Constructor & Destructor Documentation
openDMS.ebay.query.recievers.ItemCall.ItemCall (String usrToken, String server)
constructor, calls superconstructor and
Parameters
usrToken
server
Definition at line 42 of file ItemCall.java.
References openDMS.ebay.query.data.APIcontext.apiContext(), and openDMS.ebay.query.data.APIcontext.instance().
Member Function Documentation
ApiItemData openDMS.ebay.query.recievers.ItemCall.call (ApiItemData data, String itemId)
This method performs a call to the API grabbing a list of orders for the specified number of days.
Parameters
data an ApiOrderData object to populate with the orders
numOfDays
Returns
ApiOrderData, populated with the orders retrieved from the API call.
Definition at line 57 of file ItemCall.java.
References openDMS.ebay.query.data.ApiItemData.addData().
Referenced by openDMS.ebay.query.commands.GetItemCommand.execute().
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/recievers/ItemCall.java