TomoBay: StockReOrderAnalysis Class Reference
StockReOrderAnalysis Class Reference
This class represents functionality to.
Public Member Functions
StockReOrderAnalysis ()
default ctor
String execute (String data)
performs the action specified
Private Member Functions
JsonObject convertToJSon (String data)
convert a JSON formatted string to a JsonObject
List< HeteroFieldContainer > grabDBdata (int lookback)
grab the history of the last 'lookback' days worth of listings part numbers and the number of those listings sold
List< String[]> processDBdata (List< HeteroFieldContainer > dbData)
Takes the database data and processes it so that the composite part number provided by the database is converted to individual parts, the quantities of these parts(within the listing) are then multiplied by the quantity of the listing ordered over the number of days to provide the total list of parts sold over the time period specified.
List< String[]> createSuggestedOrders (List< String[]> processedDBData, int threshold)
String formatResultAsJSON (List< String[]> processedResults)
formats the processed data
Static Private Attributes
static final String LOOKBACK_PROPERTY = "lookback"
name of the JSON object property containing the lookback value
static final String THRESHOLD_PROPERTY = "threshold"
name of the JSON object property containing the threshold reorder value
Detailed Description
This class represents functionality to.
Author
Jan P.C. Hanson
Definition at line 34 of file StockReOrderAnalysis.java.
Constructor & Destructor Documentation
StockReOrderAnalysis ()
default ctor
Definition at line 44 of file StockReOrderAnalysis.java.
Member Function Documentation
String execute (String data)
performs the action specified
Returns
String representing the results of the performed action.
Implements AbstractPresenterAction.
Definition at line 51 of file StockReOrderAnalysis.java.
References StockReOrderAnalysis.convertToJSon(), StockReOrderAnalysis.createSuggestedOrders(), StockReOrderAnalysis.formatResultAsJSON(), StockReOrderAnalysis.grabDBdata(), and StockReOrderAnalysis.processDBdata().
JsonObject convertToJSon (String data) private
convert a JSON formatted string to a JsonObject
Parameters
data the JSON formatted string
Returns
JsonObject
Definition at line 65 of file StockReOrderAnalysis.java.
Referenced by StockReOrderAnalysis.execute().
List<HeteroFieldContainer> grabDBdata (int lookback) private
grab the history of the last 'lookback' days worth of listings part numbers and the number of those listings sold
Parameters
lookback the number of days worth of history to retrieve
Returns
Definition at line 79 of file StockReOrderAnalysis.java.
References HeteroFieldContainer.add(), NonDBFields.Custom_INT_FIELD, SelectQueryInvoker.execute(), and SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_ORDER_HISTORY_LAST_N_DAYS.
Referenced by StockReOrderAnalysis.execute().
List<String[]> processDBdata (List< HeteroFieldContainer > dbData) private
Takes the database data and processes it so that the composite part number provided by the database is converted to individual parts, the quantities of these parts(within the listing) are then multiplied by the quantity of the listing ordered over the number of days to provide the total list of parts sold over the time period specified.
Parameters
dbData the data
Returns
Definition at line 97 of file StockReOrderAnalysis.java.
Referenced by StockReOrderAnalysis.execute().
List<String[]> createSuggestedOrders (List< String[]> processedDBData, int threshold) private
Parameters
processedDBData
threshold
Returns
Definition at line 107 of file StockReOrderAnalysis.java.
Referenced by StockReOrderAnalysis.execute().
String formatResultAsJSON (List< String[]> processedResults) private
formats the processed data
Parameters
processedResults
Returns
Definition at line 117 of file StockReOrderAnalysis.java.
Referenced by StockReOrderAnalysis.execute().
Member Data Documentation
final String LOOKBACK_PROPERTY = "lookback" static private
name of the JSON object property containing the lookback value
Definition at line 37 of file StockReOrderAnalysis.java.
final String THRESHOLD_PROPERTY = "threshold" static private
name of the JSON object property containing the threshold reorder value
Definition at line 39 of file StockReOrderAnalysis.java.
The documentation for this class was generated from the following file:
src/tomoBay/presenters/presenterActions/concreteActions/StockReOrderAnalysis.java