My Project: openDMS.model.sql.queries.concreteQueries.SelectEbayOrders Class Reference
openDMS.model.sql.queries.concreteQueries.SelectEbayOrders Class Reference
Public Member Functions
SelectEbayOrders ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
Static Private Attributes
static final String query = "SELECT * FROM ebay.ebay_buyers;"
Detailed Description
Author
Jan P.C. Hanson
Definition at line 31 of file SelectEbayOrders.java.
Constructor & Destructor Documentation
openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.SelectEbayOrders ()
default constructor
Definition at line 43 of file SelectEbayOrders.java.
Member Function Documentation
void openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 102 of file SelectEbayOrders.java.
Referenced by openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.execute().
List<String[]> openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter NOT USED for this query.
Returns
String representing the results of the query. each item of the list is a seperate row, each element of the String[] represents a column. String[0]=buyerID, String[1]=name, String[2]=shippingAddress.
Exceptions
SQLException
Implements openDMS.model.sql.queries.AbstractDBQuery.
Definition at line 54 of file SelectEbayOrders.java.
References openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.cleanup(), openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.formatResults(), and openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery().
List<String[]> openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 73 of file SelectEbayOrders.java.
Referenced by openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.execute().
void openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 91 of file SelectEbayOrders.java.
References openDMS.model.sql.ConnectionManager.getConnection(), and openDMS.model.sql.ConnectionManager.instance().
Referenced by openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.execute().
Member Data Documentation
Connection openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.connection_M = null private
reference to the JDBC Database connection
Definition at line 36 of file SelectEbayOrders.java.
final String openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.query = "SELECT * FROM ebay.ebay_buyers;" static private
SQL query string
Definition at line 38 of file SelectEbayOrders.java.
PreparedStatement openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.statement_M = null private
reference to the JDBC Statement
Definition at line 34 of file SelectEbayOrders.java.
The documentation for this class was generated from the following file:
src/openDMS/model/sql/queries/concreteQueries/SelectEbayOrders.java