TomoBay: OrdersTable Class Reference
OrdersTable Class Reference
This class represents the ebay_orders table in the database.
Static Public Attributes
static final OrderID ORDER_ID = new OrderID()
this is the orderID field of the ebay_orders table in the database, and is the primary key for this table.
static final AbstractField BUYERID = BuyerTable.BUYERID
this is the buyerId field of the ebay_orders table, it is a foreign key for the ebay_buyers table
static final SalesRecNo SALES_REC_NO = new SalesRecNo()
this is the salesRecNo field of the ebay_orders table in the database, it is a number generated by ebay chronologically i.e.
static final ShippingType SHIPPING_TYPE = new ShippingType()
this is the shippingType field of the ebay_orders table of the database and is a textual representation of the shipping service used to dispatch this order.
static final CreatedTime CREATED_TIME = new CreatedTime()
this is the createdTime field of the ebay_orders table in the database.
static final Invoiced INVOICED = new Invoiced()
this is the invoiced field of the ebay_orders table in the database.
static final OrderTotal ORDER_TOTAL = new OrderTotal()
this is the orderTotal field of the ebay_orders table in the database, it represents the total price for the order.
static final AbstractField ACCOUNT = AccountsTable.ID
this is the account field of the ebay_orders table in the database.
Private Member Functions
OrdersTable ()
private ctor ensures this class is NEVER INSTANTIATED
Detailed Description
This class represents the ebay_orders table in the database.
Author
Jan P.C. Hanson
Definition at line 26 of file OrdersTable.java.
Constructor & Destructor Documentation
OrdersTable () private
private ctor ensures this class is NEVER INSTANTIATED
Definition at line 102 of file OrdersTable.java.
Member Data Documentation
final OrderID ORDER_ID = new OrderID() static
this is the orderID field of the ebay_orders table in the database, and is the primary key for this table.
VARCHAR(30)
Primary Key
See also
tomoBay.model.sql.schema.ordersTable.OrderID
Definition at line 36 of file OrdersTable.java.
Referenced by ItemStockLevel.check(), SalesOrderPresenter.checkPickability(), OnRunning.execute(), SalesHistoryView.format(), SalesOrderView.format(), SelectUncalculatedOrders.format(), SelectEbayOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByBuyer.format(), SelectEbayOrderByID.format(), SelectFullOrderLine.format(), Order.getOrderInfo(), Order.getTransactionList(), Order.orderID(), Orders_Table.populate(), Orders_Table.populateGSP(), UpdateInvoiceStatus.setParameters(), InsertEbayOrders.setParameters(), SelectBrandAndPartNoByOrderID.setParameters(), SelectEbayOrderByID.setParameters(), SelectFullOrderLine.setParameters(), and InvoiceOrders.updateDB().
final AbstractField BUYERID = BuyerTable.BUYERID static
this is the buyerId field of the ebay_orders table, it is a foreign key for the ebay_buyers table
VARCHAR(40)
Foreign Key ebay_buyers
See also
tomoBay.model.sql.schema.ordersTable.OrderID
tomoBay.model.sql.schema.buyerTable.BuyerTable
Definition at line 45 of file OrdersTable.java.
Referenced by SalesHistoryView.format(), SalesOrderView.format(), SelectEbayOrders.format(), SelectUninvoicedOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByID.format(), DBActions.getLatestOrderID(), Order.Order(), Orders_Table.populate(), Orders_Table.populateGSP(), InsertEbayOrders.setParameters(), SelectEbayOrderByBuyer.setParameters(), and SelectEbayBuyer.setParameters().
final SalesRecNo SALES_REC_NO = new SalesRecNo() static
this is the salesRecNo field of the ebay_orders table in the database, it is a number generated by ebay chronologically i.e.
the first sale would be 1 the second 2 and so on.
INT(10)
See also
tomoBay.model.sql.schema.buyerTable.SalesRecNo
Definition at line 53 of file OrdersTable.java.
Referenced by MarkAsInvoiced.execute(), MarkAsUninvoiced.execute(), OnRunning.execute(), SalesHistoryView.format(), OutOfHoursView.format(), SalesOrderView.format(), SelectEbayOrders.format(), SelectUninvoicedOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByID.format(), SelectOutOfHoursOrders.format(), SelectFullOrderLine.format(), GenerateRoyalMailCSV.grabAndProcessDBData(), Orders_Table.populate(), Orders_Table.populateGSP(), Order.salesRecNo(), UpdateInvoiceStatusSRN.setParameters(), InsertEbayOrders.setParameters(), and SelectBuyerByAccAndSRN.setParameters().
final ShippingType SHIPPING_TYPE = new ShippingType() static
this is the shippingType field of the ebay_orders table of the database and is a textual representation of the shipping service used to dispatch this order.
VARCHAR(200)
See also
tomoBay.model.sql.schema.ordersTable.ShippingType
Definition at line 61 of file OrdersTable.java.
Referenced by SalesOrderView.format(), SelectEbayOrders.format(), SelectUninvoicedOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByID.format(), SelectFullOrderLine.format(), Orders_Table.populate(), Orders_Table.populateGSP(), InsertEbayOrders.setParameters(), Order.shippingType(), and SortOrders.sortByShipping().
final CreatedTime CREATED_TIME = new CreatedTime() static
this is the createdTime field of the ebay_orders table in the database.
The value of this field is grabbed using the ebayAPI and is the time and date at which this order was created.
TIMESTAMP()
See also
tomoBay.model.sql.schema.ordersTable.CreatedTime
Definition at line 69 of file OrdersTable.java.
Referenced by Order.createdTime(), SalesHistoryView.format(), OutOfHoursView.format(), SalesOrderView.format(), SelectEbayOrders.format(), SelectUninvoicedOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByID.format(), SelectOutOfHoursOrders.format(), SelectFullOrderLine.format(), Orders_Table.populate(), Orders_Table.populateGSP(), and InsertEbayOrders.setParameters().
final Invoiced INVOICED = new Invoiced() static
this is the invoiced field of the ebay_orders table in the database.
it is a numerical value that defines whether this order has been invoiced or not. If the order has not been invoiced then it will have a value of 0, if it has been invoiced then the value contained will be the invoice number.
INT(11)
See also
tomoBay.model.sql.schema.ordersTable.Invoiced
Definition at line 79 of file OrdersTable.java.
Referenced by SalesOrderPresenter.checkPickability(), MarkAsInvoiced.execute(), MarkAsUninvoiced.execute(), SalesOrderView.format(), SelectEbayOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByID.format(), SelectBuyerByAccAndSRN.format(), SelectFullOrderLine.format(), GenerateRoyalMailCSV.grabAndProcessDBData(), Order.invoiceNo(), UpdateInvoiceStatusSRN.setParameters(), UpdateInvoiceStatus.setParameters(), SelectBrandByInv.setParameters(), SortOrders.sortByPickeability(), and InvoiceOrders.updateDB().
final OrderTotal ORDER_TOTAL = new OrderTotal() static
this is the orderTotal field of the ebay_orders table in the database, it represents the total price for the order.
FLOAT()
See also
tomoBay.model.sql.schema.ordersTable.OrderTotal
Definition at line 87 of file OrdersTable.java.
Referenced by OutOfHoursView.format(), SelectEbayOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByID.format(), SelectOutOfHoursOrders.format(), SelectFullOrderLine.format(), Orders_Table.populate(), Orders_Table.populateGSP(), InsertEbayOrders.setParameters(), and Order.totalPrice().
final AbstractField ACCOUNT = AccountsTable.ID static
this is the account field of the ebay_orders table in the database.
it is a foreign key to the ebay_accounts table and represents the account that this order is associated with.
INT(3)
Foreign Key ebay_accounts
See also
tomoBay.model.sql.schema.accountsTable.AccountsTable
tomoBay.model.sql.schema.accountsTable.Id
Definition at line 97 of file OrdersTable.java.
Referenced by Order.account(), MarkAsInvoiced.execute(), MarkAsUninvoiced.execute(), OnRunning.execute(), SalesOrderView.format(), SelectEbayOrders.format(), SelectUninvoicedOrders.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByBuyer.format(), SelectEbayOrderByID.format(), Orders_Table.populate(), Orders_Table.populateGSP(), UpdateInvoiceStatusSRN.setParameters(), and InsertEbayOrders.setParameters().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/schema/ordersTable/OrdersTable.java