TomoBay: ItemCall Class Reference
ItemCall Class Reference
This class represents an eBay API call requesting Item Data.
Public Member Functions
ItemCall (String usrToken, String server)
constructor, calls superconstructor and initialises with api key and server string
ItemType call (long itemId) throws ApiException, SdkException, Exception
This method performs a call to the API grabbing a item data for the specified itemID.
Package Attributes
GetItemCall item_M
holder for the call object
GetItemRequestType itemreq_M
holder for request object
Additional Inherited Members
Protected Member Functions inherited from AbstractAPIcall
AbstractAPIcall (String usrToken, String server)
this constructor initialises the Abstract query with a usr token and server string, these are needed so that it can properly assign an ApiContext to the call.
Protected Attributes inherited from AbstractAPIcall
String usrToken_M
holder for the user token string provided in the construction of this object
String server_M
holder for the server string provided in the construction of this object
Detailed Description
This class represents an eBay API call requesting Item Data.
Author
Jan P.C. Hanson
Definition at line 28 of file ItemCall.java.
Constructor & Destructor Documentation
ItemCall (String usrToken, String server)
constructor, calls superconstructor and initialises with api key and server string
Parameters
usrToken your api key
server either the url string of the production or sandbox server
Definition at line 40 of file ItemCall.java.
References APIcontext.apiContext(), and APIcontext.instance().
Member Function Documentation
ItemType call (long itemId) throws ApiException, SdkException, Exception
This method performs a call to the API grabbing a item data for the specified itemID.
Parameters
itemId the itemID found from the order data
Returns
ItemType containing all item specific data
Exceptions
Exception
SdkException
ApiException
Definition at line 57 of file ItemCall.java.
Referenced by OnRunning.getItemData(), ItemSpecifics.performAPIcall(), and ItemsAndPartsTable.populate().
Member Data Documentation
GetItemCall item_M package
holder for the call object
Definition at line 31 of file ItemCall.java.
GetItemRequestType itemreq_M package
holder for request object
Definition at line 33 of file ItemCall.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/eBayAPI/ItemCall.java