TomoBay: StandardInvoiceLine Class Reference
StandardInvoiceLine Class Reference
Public Member Functions
StandardInvoiceLine (AbstractSalesDayBookLine invoice, int transactionNo, int partIndex)
creates an invoiceLine using the transactionNo and partIndex provided
Public Member Functions inherited from AbstractLineItem
AbstractLineItem (AbstractSalesDayBookLine line, int transactionNo, int partIndex)
create an AbstractLineItem using the parameters provided
void adjustPrice (AbstractSalesDayBookLine invoice, int pennyAdjustment)
add or subtract the given amount of pennies from this line item
int quantity (AbstractSalesDayBookLine invoice)
retrieve the invoiced quantity of the part to be invoiced in this line item
String description (AbstractSalesDayBookLine invoice)
retrieve the description of the invoiced part
String partNo (AbstractSalesDayBookLine invoice)
retrieve the part number associated with the part that has been invoiced
int price ()
retrieve the price of the quantity of parts invoiced (EX VAT)
Protected Member Functions
int unitPrice (AbstractSalesDayBookLine invoice)
Protected Member Functions inherited from AbstractLineItem
abstract int unitPrice (AbstractSalesDayBookLine line)
implementation specific code used to work out the unit price for a specific line item
Additional Inherited Members
Protected Attributes inherited from AbstractLineItem
final int partIndex
the index of the part(within a transaction) that this lineItem corresponds to
final int transactionIndex_M
this index represents the transaction number that this lineItem corresponds to
Detailed Description
Author
Jan P.C. Hanson
Definition at line 26 of file StandardInvoiceLine.java.
Constructor & Destructor Documentation
StandardInvoiceLine (AbstractSalesDayBookLine invoice, int transactionNo, int partIndex)
creates an invoiceLine using the transactionNo and partIndex provided
Parameters
invoice the invoice AbstractSalesDayBookLine that this StandardInvoiceLine is contained in.
transactionNo the index of the transaction to use.
partIndex the partIndex within the specified Transaction.
Definition at line 34 of file StandardInvoiceLine.java.
Member Function Documentation
int unitPrice (AbstractSalesDayBookLine invoice) protected
Definition at line 41 of file StandardInvoiceLine.java.
References Part.cost(), Transaction.listing(), Listing.listingCost(), AbstractSalesDayBookLine.orderInfo(), Listing.part(), Listing.qty(), VAT.subtract(), GBP.toPennies(), Order.transaction(), and Transaction.transactionPrice().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/financial/SalesOrderDayBook/concreteLineTypes/StandardInvoiceLine.java