TomoBay: AbstractPayload Class Reference
AbstractPayload Class Reference
This is the abstract base class for all Payload sub types.
Public Member Functions
AbstractPayload ()
default ctor
byte[] getPayload (DualList< String, PayloadType > input) throws PayloadException
This method contains the implementiation for the specific command that this payload is applicable to.
Protected Attributes
List< Byte > result_M = new ArrayList<Byte>()
the resulting list.
Map< PayloadType, AbstractComponentFactory > payloadBuilder_M
Static Protected Attributes
static final String HEADER_M = "WSC0"
the header bytes as a string (add these to the start of the byte[])
static final byte FOOTER_M = (byte) 0xAA
the header byte (add to end of byte[])
Private Member Functions
byte[] getResult ()
reassembles the internal list as a byte[] that can be passed straight to the ClientSockets object.
Detailed Description
This is the abstract base class for all Payload sub types.
This allows a different payload to be created for each type of Winstock command that exists.
Author
Jan P.C. Hanson
Definition at line 31 of file AbstractPayload.java.
Constructor & Destructor Documentation
AbstractPayload ()
default ctor
Definition at line 45 of file AbstractPayload.java.
Member Function Documentation
byte [] getPayload (DualList< String, PayloadType > input) throws PayloadException
This method contains the implementiation for the specific command that this payload is applicable to.
Definition at line 52 of file AbstractPayload.java.
References AbstractPayload.FOOTER_M, AbstractPayload.getResult(), and AbstractPayload.HEADER_M.
Referenced by PrintInvoiceCommand.execute(), and PutInvoiceCommand.execute().
byte [] getResult () private
reassembles the internal list as a byte[] that can be passed straight to the ClientSockets object.
Returns
byte[] that can be passed to the client socket
Definition at line 72 of file AbstractPayload.java.
Referenced by AbstractPayload.getPayload().
Member Data Documentation
final String HEADER_M = "WSC0" static protected
the header bytes as a string (add these to the start of the byte[])
Definition at line 33 of file AbstractPayload.java.
Referenced by AbstractPayload.getPayload().
final byte FOOTER_M = (byte) 0xAA static protected
the header byte (add to end of byte[])
Definition at line 35 of file AbstractPayload.java.
Referenced by AbstractPayload.getPayload().
List<Byte> result_M = new ArrayList<Byte>() protected
the resulting list.
Definition at line 37 of file AbstractPayload.java.
Referenced by PutInvoicePayload.PutInvoicePayload().
Map<PayloadType, AbstractComponentFactory> payloadBuilder_M protected
Initial value:
=
            new HashMap<PayloadType, AbstractComponentFactory>()
Definition at line 39 of file AbstractPayload.java.
Referenced by PutInvoicePayload.PutInvoicePayload().
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/payloads/AbstractPayload.java