TomoBay: ViewFactoryTest Class Reference
ViewFactoryTest Class Reference
Tests the ViewFactory class.
Public Member Functions
void testVisitErrorPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.error.ErrorPresenter).
void testVisitRootPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.root.RootPresenter).
void testVisitSalesHistoryPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.sales.SalesHistoryPresenter).
void testVisitSalesOrderPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.sales.SalesOrderPresenter).
void testVisitWarehouseOrderPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.warehouse.WarehouseOrderPresenter).
Package Attributes
ViewFactory viewFactory = new ViewFactory()
test copy of ViewFactory
ErrorPresenter errorPresenter = new ErrorPresenter()
RootPresenter rootPresenter = new RootPresenter()
SalesHistoryPresenter sHpresenter = new SalesHistoryPresenter()
SalesOrderPresenter sOpresenter = new SalesOrderPresenter()
WarehouseOrderPresenter wOpresenter = new WarehouseOrderPresenter()
Detailed Description
Tests the ViewFactory class.
Author
Jan P.C. Hanson
Definition at line 38 of file ViewFactoryTest.java.
Member Function Documentation
void testVisitErrorPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.error.ErrorPresenter).
Definition at line 52 of file ViewFactoryTest.java.
References ViewFactory.visit().
void testVisitRootPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.root.RootPresenter).
Definition at line 65 of file ViewFactoryTest.java.
References ViewFactory.visit().
void testVisitSalesHistoryPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.sales.SalesHistoryPresenter).
Definition at line 78 of file ViewFactoryTest.java.
References ViewFactory.visit().
void testVisitSalesOrderPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.sales.SalesOrderPresenter).
Definition at line 91 of file ViewFactoryTest.java.
References ViewFactory.visit().
void testVisitWarehouseOrderPresenter ()
Test method for tomoBay.view.ViewFactory#visit(tomoBay.presenters.warehouse.WarehouseOrderPresenter).
Definition at line 104 of file ViewFactoryTest.java.
References ViewFactory.visit().
Member Data Documentation
ViewFactory viewFactory = new ViewFactory() package
test copy of ViewFactory
Definition at line 41 of file ViewFactoryTest.java.
ErrorPresenter errorPresenter = new ErrorPresenter() package
Definition at line 42 of file ViewFactoryTest.java.
RootPresenter rootPresenter = new RootPresenter() package
Definition at line 43 of file ViewFactoryTest.java.
SalesHistoryPresenter sHpresenter = new SalesHistoryPresenter() package
Definition at line 44 of file ViewFactoryTest.java.
SalesOrderPresenter sOpresenter = new SalesOrderPresenter() package
Definition at line 45 of file ViewFactoryTest.java.
WarehouseOrderPresenter wOpresenter = new WarehouseOrderPresenter() package
Definition at line 46 of file ViewFactoryTest.java.
The documentation for this class was generated from the following file:
src/tomoBayTests/view/ViewFactoryTest.java