TomoBay: MailClient Class Reference
MailClient Class Reference
Public Member Functions
MailClient ()
Static Public Member Functions
static String send (String message, String subject, String[] to, String[] cc, String[] bcc, AbstractEmailBuilder builder)
Static Private Member Functions
static Email setUpEmail (String message, String subject, String[] to, String[] cc, String[] bcc, EmailDirector mailmanager) throws AddressException, MessagingException, NullEmailObjectException
set up the email ready to use in the rest of the mail client
Detailed Description
Author
Jan P.C. Hanson
Definition at line 33 of file MailClient.java.
Constructor & Destructor Documentation
MailClient ()
Definition at line 35 of file MailClient.java.
References MailClient.send().
Member Function Documentation
static String send (String message, String subject, String[] to, String[] cc, String[] bcc, AbstractEmailBuilder builder) static
Parameters
message
subject
to
cc
bcc
builder
Returns
Definition at line 49 of file MailClient.java.
References EmailDirector.constructEmailAndServer(), ConfigReader.getConf(), EmailDirector.getMailSendServer(), Config.MAIL_ADDR, Config.MAIL_PWD, MailServerSend.send(), and MailClient.setUpEmail().
Referenced by InvoiceOrders.emailResults(), and MailClient.MailClient().
static Email setUpEmail (String message, String subject, String[] to, String[] cc, String[] bcc, EmailDirector mailmanager) throws AddressException, MessagingException, NullEmailObjectException static private
set up the email ready to use in the rest of the mail client
Parameters
message The message that is the main body of the email
subject the subject line of the email
to array of email addresses that this email should be sent to
cc array of email addresses that should be CC'd in this email
bcc array of email addresses that should be BCC'd in this email
mailmanager The EmailDirector that is responsible for this email
Returns
Email completely se up email object that is ready to send
Exceptions
AddressException
MessagingException
NullEmailObjectException
Definition at line 83 of file MailClient.java.
References Email.setMessage(), Email.setRecipient(), and Email.setSubject().
Referenced by MailClient.send().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/net/email/MailClient.java