TomoBay: RoyalMailCSVGeneratorTest Class Reference
RoyalMailCSVGeneratorTest Class Reference
Unit test case for tomoBay.model.royalMail.RoyalMailCSVGenerator.
Public Member Functions
final void testRoyalMailCSVGenerator ()
final void testSetseparators ()
final void testAddRow ()
final void testAddBatch ()
final void testGenerate ()
final void testSize ()
final void testToStringGoodInput ()
final void testToStringBadInput ()
Static Private Attributes
static final String[] goodTestData1 = {"SR1","24"," jan bob hanson-baloon","2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"}
good test data set 1
static final String[] goodTestData2 = {"SR1","24"," jan bob hanson-baloon","2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"}
good test data set 2
static final String[] goodTestData3 = {"SR1","24"," jan bob hanson-baloon","2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"}
good test data set 3
static final String[] badTestData1 = {"SR1\"","24"," jan bob hanson-baloon","2 lexington apartements\"","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"}
bad data set 1: extra quote in first column
static final String[] badTestData2 = {"SR1","24"," jan bob hanson-baloon","<>2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"}
bad data set 2: non allowed char in column 4
static final String[] badTestData3 = {"SR1","24"," jan bob hanson-baloon","<>2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456^","1","300","ABC","L"}
bad data set 3: invalid option in column 12
Detailed Description
Unit test case for tomoBay.model.royalMail.RoyalMailCSVGenerator.
Test:
all functionality contained within the RoyalMailCSVGenerator class
Precondition
none
Postcondition
a RoyalMailCSVGenerator object should behave reasonable as defined by the tests carried out.
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator
Author
Jan P.C. Hanson
Definition at line 51 of file RoyalMailCSVGeneratorTest.java.
Member Function Documentation
final void testRoyalMailCSVGenerator ()
Test:
instantiation test of the RoyalMailCSVGenerator class, guaruntees that object can be initialised without issue (default constructor).
Precondition
none
Postcondition
fully initialised instance of the RoyalMailCSVGenerator available for use.
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::RoyalMailCSVGenerator().
Definition at line 83 of file RoyalMailCSVGeneratorTest.java.
final void testSetseparators ()
Test:
guaruntees that the setSeparators method behaves as expected the default quotes and commas are replaced with the chars presented.
Precondition
requires that the toString method works as expected.
Postcondition
separators will remain set until this method is called again.
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::setseparators(char, char).
Definition at line 108 of file RoyalMailCSVGeneratorTest.java.
References RoyalMailCSVGenerator.addRow(), RoyalMailCSVGeneratorTest.goodTestData1, RoyalMailCSVGenerator.setseparators(), and RoyalMailCSVGenerator.toString().
final void testAddRow ()
Test:
makes sure that the addRow method will correctly add a row to the csv
Precondition
the toString method works as expected.
the array provided is the same size as the number of CSV_FIELD's in config/tomoBay.conf
the input for each column matches its corresponding regex validation string found in the CSV_FIELD_VALIDATION tags in config/tomoBay.conf.
Postcondition
Data can be added to the csv file as stated in the pre-condition.
an ArrayStoreException will be thrown if the data provided fails validataion
an ArrayIndexOutOfBoundsException will be thrown if the size of the String[] provided is different from the number of fields available in the config file. The error message in the exception will reflect whether the array provided is too large or too small.
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::addRow(java.lang.String[]).
Definition at line 137 of file RoyalMailCSVGeneratorTest.java.
References RoyalMailCSVGenerator.addRow(), RoyalMailCSVGeneratorTest.badTestData1, RoyalMailCSVGeneratorTest.badTestData2, RoyalMailCSVGeneratorTest.badTestData3, RoyalMailCSVGeneratorTest.goodTestData1, RoyalMailCSVGeneratorTest.goodTestData2, and RoyalMailCSVGeneratorTest.goodTestData3.
final void testAddBatch ()
Test:
makes sure that the addBatch method allows you to add batches of data in the form of a List<String[]>
Precondition
the toString method works as expected:
the arrays provided in the List<String[]> are the same size as the number of CSV_FIELD's in config/tomoBay.conf
the input for each column in an individual array of the List<String[]> matches its corresponding regex validation string found in the CSV_FIELD_VALIDATION tags in config/tomoBay.conf.
Postcondition
Data can be added to the csv file as stated in the pre-condition.
an ArrayStoreException will be thrown if the data provided fails validataion
an ArrayIndexOutOfBoundsException will be thrown if the size of the String[] provided is different from the number of fields available in the config file. The error message in the exception will reflect whether the array provided is too large or too small.
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::addBatch(java.util.List).
Definition at line 186 of file RoyalMailCSVGeneratorTest.java.
References RoyalMailCSVGenerator.addBatch(), RoyalMailCSVGeneratorTest.badTestData1, RoyalMailCSVGeneratorTest.badTestData2, RoyalMailCSVGeneratorTest.badTestData3, RoyalMailCSVGeneratorTest.goodTestData1, RoyalMailCSVGeneratorTest.goodTestData2, and RoyalMailCSVGeneratorTest.goodTestData3.
final void testGenerate ()
Test:
makes sure that the generate method produces a file, and that it is in the format required.
Precondition
the addRow method behaves as expected
valid data is passed into the addRow method
Postcondition
A file is produced that corresponds to the path and filename provided
this file is a properly formatted csv file
if invalid data is passed in then an excetion should be thrown see tomoBayTests.model.royalMail.RoyalMailCSVGeneratorTest#testAddRow()
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::generate(java.lang.String, java.lang.String, java.lang.String).
Definition at line 235 of file RoyalMailCSVGeneratorTest.java.
References RoyalMailCSVGenerator.addRow(), RoyalMailCSVGenerator.generate(), RoyalMailCSVGeneratorTest.goodTestData1, RoyalMailCSVGeneratorTest.goodTestData2, and RoyalMailCSVGeneratorTest.goodTestData3.
final void testSize ()
Test:
makes sure that the size method returns an integer equal to the number of columns specified in the config file (tomoBay.conf)
Precondition
tomoBay.helpers.ConfigReader behaves as expected
Postcondition
testSize returns an integer equal to the number of CSV_FIELD_NAME tag pairs in the config file
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::size()
Definition at line 272 of file RoyalMailCSVGeneratorTest.java.
References Config.CSV_FIELD_NAME, ConfigReader.size(), and RoyalMailCSVGenerator.size().
final void testToStringGoodInput ()
Test:
makes sure that the toString method behaves appropriately given valid inputs
Precondition
the data provided to the toString method is valid and of the correct size.
the addRow method behaves as expected.
Postcondition
the method will produce a well formatted csv string
linebreaks are placed at the end of eachline
only the special chars -_:;'@()\/,# are allowed within the csv
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::toString().
Definition at line 295 of file RoyalMailCSVGeneratorTest.java.
References RoyalMailCSVGenerator.addRow(), RoyalMailCSVGeneratorTest.goodTestData1, RoyalMailCSVGeneratorTest.goodTestData2, RoyalMailCSVGeneratorTest.goodTestData3, and RoyalMailCSVGenerator.toString().
final void testToStringBadInput ()
Test:
makes sure that the toString method behaves appropriately given bad inputs.
Precondition
input contains:
quotes inside csv entry
special chars in places where they are not allowed
values other than those specified in option lists e.g. if valid options are AB or BC then try AA or CC etc
Postcondition
the testString method will produce an ArrayStoreException indicating that the data provided is not acceptable.
no other exception will be thrown.
See also
tomoBay.model.royalMail.RoyalMailCSVGenerator::toString().
Definition at line 329 of file RoyalMailCSVGeneratorTest.java.
References RoyalMailCSVGenerator.addRow(), RoyalMailCSVGeneratorTest.badTestData1, RoyalMailCSVGeneratorTest.badTestData2, RoyalMailCSVGeneratorTest.badTestData3, and RoyalMailCSVGenerator.toString().
Member Data Documentation
final String [] goodTestData1 = {"SR1","24"," jan bob hanson-baloon","2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"} static private
good test data set 1
Definition at line 55 of file RoyalMailCSVGeneratorTest.java.
Referenced by RoyalMailCSVGeneratorTest.testAddBatch(), RoyalMailCSVGeneratorTest.testAddRow(), RoyalMailCSVGeneratorTest.testGenerate(), RoyalMailCSVGeneratorTest.testSetseparators(), and RoyalMailCSVGeneratorTest.testToStringGoodInput().
final String [] goodTestData2 = {"SR1","24"," jan bob hanson-baloon","2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"} static private
good test data set 2
Definition at line 58 of file RoyalMailCSVGeneratorTest.java.
Referenced by RoyalMailCSVGeneratorTest.testAddBatch(), RoyalMailCSVGeneratorTest.testAddRow(), RoyalMailCSVGeneratorTest.testGenerate(), and RoyalMailCSVGeneratorTest.testToStringGoodInput().
final String [] goodTestData3 = {"SR1","24"," jan bob hanson-baloon","2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"} static private
good test data set 3
Definition at line 61 of file RoyalMailCSVGeneratorTest.java.
Referenced by RoyalMailCSVGeneratorTest.testAddBatch(), RoyalMailCSVGeneratorTest.testAddRow(), RoyalMailCSVGeneratorTest.testGenerate(), and RoyalMailCSVGeneratorTest.testToStringGoodInput().
final String [] badTestData1 = {"SR1\"","24"," jan bob hanson-baloon","2 lexington apartements\"","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"} static private
bad data set 1: extra quote in first column
Definition at line 64 of file RoyalMailCSVGeneratorTest.java.
Referenced by RoyalMailCSVGeneratorTest.testAddBatch(), RoyalMailCSVGeneratorTest.testAddRow(), and RoyalMailCSVGeneratorTest.testToStringBadInput().
final String [] badTestData2 = {"SR1","24"," jan bob hanson-baloon","<>2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456","1","300","SF","L"} static private
bad data set 2: non allowed char in column 4
Definition at line 67 of file RoyalMailCSVGeneratorTest.java.
Referenced by RoyalMailCSVGeneratorTest.testAddBatch(), RoyalMailCSVGeneratorTest.testAddRow(), and RoyalMailCSVGeneratorTest.testToStringBadInput().
final String [] badTestData3 = {"SR1","24"," jan bob hanson-baloon","<>2 lexington apartements","Railway terrace","sl2 5gq","Slough","GB","C123456^","1","300","ABC","L"} static private
bad data set 3: invalid option in column 12
Definition at line 70 of file RoyalMailCSVGeneratorTest.java.
Referenced by RoyalMailCSVGeneratorTest.testAddBatch(), RoyalMailCSVGeneratorTest.testAddRow(), and RoyalMailCSVGeneratorTest.testToStringBadInput().
The documentation for this class was generated from the following file:
src/tomoBayTests/model/royalMail/RoyalMailCSVGeneratorTest.java