TomoBay: EmailErrorsMailActions Class Reference
EmailErrorsMailActions Class Reference
This class encapsulates all the interactions this service has with the model.net.email system.
Public Member Functions
EmailErrorsMailActions () throws ServiceException
default ctor
void loadData (Map< String, emailDataType > mailData) throws ServiceException
handle the creation of the Email by passing in a map with the appropriate data inside it.
void send ()
send the email
void addMessage (String message)
add a message to the email
Private Member Functions
void addRecipient (EmailErrorsService.emailDataType type, String address) throws AddressException, MessagingException
add a recipient to the email
void addSubject (String subject) throws MessagingException
add a subject line to the email
Private Attributes
EmailDirector mailManager_M
the email Director
MailServerSend sendConnection
the MailServer for sending the email
Email email
the email itself
Static Private Attributes
static Map< EmailErrorsService.emailDataType, Message.RecipientType > recipients_M
map of Strings to RecipientType so the service can convert easily.
Detailed Description
This class encapsulates all the interactions this service has with the model.net.email system.
Author
Jan P.C. Hanson
Definition at line 37 of file EmailErrorsMailActions.java.
Constructor & Destructor Documentation
EmailErrorsMailActions () throws ServiceException
default ctor
Exceptions
ServiceException
Definition at line 59 of file EmailErrorsMailActions.java.
References EmailDirector.constructEmailAndServer(), EmailDirector.getEmail(), and EmailDirector.getMailSendServer().
Member Function Documentation
void loadData (Map< String, emailDataType > mailData) throws ServiceException
handle the creation of the Email by passing in a map with the appropriate data inside it.
Parameters
mailData
Exceptions
ServiceException
Definition at line 78 of file EmailErrorsMailActions.java.
References EmailErrorsMailActions.addMessage(), EmailErrorsMailActions.addRecipient(), and EmailErrorsMailActions.addSubject().
Referenced by OnRunning.execute().
void send ()
send the email
Definition at line 107 of file EmailErrorsMailActions.java.
References ConfigReader.getConf(), Config.MAIL_ADDR, Config.MAIL_PWD, and MailServerSend.send().
Referenced by OnRunning.execute().
void addMessage (String message)
add a message to the email
Parameters
message the message to add
Exceptions
MessagingException
Definition at line 121 of file EmailErrorsMailActions.java.
References Email.setMessage().
Referenced by OnRunning.execute(), and EmailErrorsMailActions.loadData().
void addRecipient (EmailErrorsService.emailDataType type, String address) throws AddressException, MessagingException private
add a recipient to the email
Parameters
type the type of recipient: 'TO'/'CC'/'BCC'
address the email address of the recipient
Exceptions
MessagingException
AddressException
Definition at line 134 of file EmailErrorsMailActions.java.
References EmailErrorsMailActions.recipients_M, and Email.setRecipient().
Referenced by EmailErrorsMailActions.loadData().
void addSubject (String subject) throws MessagingException private
add a subject line to the email
Parameters
subject the subject line to add
Exceptions
MessagingException
Definition at line 142 of file EmailErrorsMailActions.java.
References Email.setSubject().
Referenced by EmailErrorsMailActions.loadData().
Member Data Documentation
EmailDirector mailManager_M private
the email Director
Definition at line 40 of file EmailErrorsMailActions.java.
MailServerSend sendConnection private
the MailServer for sending the email
Definition at line 42 of file EmailErrorsMailActions.java.
Email email private
the email itself
Definition at line 44 of file EmailErrorsMailActions.java.
Map<EmailErrorsService.emailDataType,Message.RecipientType> recipients_M static private
Initial value:
= new HashMap<EmailErrorsService.emailDataType,Message.RecipientType>()
            {{
                put(EmailErrorsService.emailDataType.TO, Message.RecipientType.TO);
                put(EmailErrorsService.emailDataType.CC, Message.RecipientType.CC);
                put(EmailErrorsService.emailDataType.BCC, Message.RecipientType.BCC);
            }}
map of Strings to RecipientType so the service can convert easily.
Definition at line 48 of file EmailErrorsMailActions.java.
Referenced by EmailErrorsMailActions.addRecipient().
The documentation for this class was generated from the following file:
src/tomoBay/model/services/emailErrorsService/EmailErrorsMailActions.java