TomoBay: GenerateRoyalMailCSV Class Reference
GenerateRoyalMailCSV Class Reference
This class represents a presenter action that will generate a CSV file in a format compatible with the Royal Mail DMO, and will generate it in a place that is accessibe to the frontend.
Public Member Functions
GenerateRoyalMailCSV ()
default ctor
String execute (String data)
performs the action specified
Private Member Functions
String[][] processInput (String input)
takes the input string and makes it accessible as an array, the public static finals define the indices that the data is stored at.
String[][] formatInitialData (String[][] initialData)
formats the initial data passed in to the execute method by the frontend and puts data into the relevant columns for the CSV.
String[][] grabAndProcessDBData (String[][] inputData, String[][] initialData)
grabs the rest of the data necessary for the RoyalMailCSVGenerator to create a CSV file
String[][] getInvoiceWeight (String[][] inputData, String[][] initialData)
queries winstock for the weight associated with the invoice number provided as an argument.
String[][] formatReferenceFields (String[][] inputData, String[][] initialData)
adds the account letter to the front of the invoice number in the reference field of the CSV
String createCSV (String[][] csvData)
use the information provided to create a CSV file that the frontend can access.
Private Attributes
final RoyalMailCSVGenerator csvGen_M
holder for the model object RoyalMailCSVGenerator
Static Private Attributes
static final int ACCOUNT = 0
defines where the Account info is within the input data
static final int SALES_REC_NO = 1
defines where the sales record number is within the input data
static final int SERVICE = 2
defines where the Service info is within the input data
static final int SERVICE_ENHANCEMENT = 3
defines where the service enhancement info is within the input data
static final int FORMAT = 4
defines where the format info is within the input data
Detailed Description
This class represents a presenter action that will generate a CSV file in a format compatible with the Royal Mail DMO, and will generate it in a place that is accessibe to the frontend.
The format of the input to this PresenterAction is: "Account-SalesRecNo-Service-Service Enhancement-format|Account-SalesRecNo-Service-Service Enhancement-format|....."
Author
Jan P.C. Hanson
Definition at line 44 of file GenerateRoyalMailCSV.java.
Constructor & Destructor Documentation
GenerateRoyalMailCSV ()
default ctor
Definition at line 62 of file GenerateRoyalMailCSV.java.
Member Function Documentation
String execute (String data)
performs the action specified
Returns
String representing the results of the performed action.
Implements AbstractPresenterAction.
Definition at line 72 of file GenerateRoyalMailCSV.java.
References GenerateRoyalMailCSV.createCSV(), GenerateRoyalMailCSV.formatInitialData(), GenerateRoyalMailCSV.formatReferenceFields(), GenerateRoyalMailCSV.getInvoiceWeight(), GenerateRoyalMailCSV.grabAndProcessDBData(), and GenerateRoyalMailCSV.processInput().
Referenced by GenerateRoyalMailCSVTest.testExecute().
String [][] processInput (String input) private
takes the input string and makes it accessible as an array, the public static finals define the indices that the data is stored at.
Parameters
input String of the form "Account-SalesRecNo-Service-Service Enhancement-format|Account-SalesRecNo-Service-Service Enhancement-format|....."
Returns
String[][] containing the intial data
Definition at line 102 of file GenerateRoyalMailCSV.java.
Referenced by GenerateRoyalMailCSV.execute().
String [][] formatInitialData (String initialData[][]) private
formats the initial data passed in to the execute method by the frontend and puts data into the relevant columns for the CSV.
Parameters
initialData the String containing the input data
Returns
String[][] containing as many elements as there are entries inputted into the frontend each of these elements is an array containing 13 data points with the data taken from the input put in the right places.
Definition at line 124 of file GenerateRoyalMailCSV.java.
References RoyalMailCSVType.COUNTRY_CODE, GenerateRoyalMailCSV.FORMAT, RoyalMailCSVType.ITEMS, RoyalMailCSVType.SERVICE, GenerateRoyalMailCSV.SERVICE, RoyalMailCSVType.SERVICE_ENHANCEMENT, GenerateRoyalMailCSV.SERVICE_ENHANCEMENT, RoyalMailCSVType.SERVICE_FORMAT, RoyalMailCSVType.SERVICE_REF, and RoyalMailCSVGenerator.size().
Referenced by GenerateRoyalMailCSV.execute().
String [][] grabAndProcessDBData (String inputData[][], String initialData[][]) private
grabs the rest of the data necessary for the RoyalMailCSVGenerator to create a CSV file
Parameters
inputData the processed input data that acts as a key to grab the rest of the data from the database.
initialData String[][] containing the intial data passed in from the frontend
Returns
String[][] containing the data passed in with DB data inserted into relevant columns
Definition at line 147 of file GenerateRoyalMailCSV.java.
References GenerateRoyalMailCSV.ACCOUNT, AccountsTable.ACCOUNT_NAME, HeteroFieldContainer.add(), RoyalMailCSVType.ADDRESS_LINE_1, RoyalMailCSVType.ADDRESS_LINE_2, BuyerTable.CITY, HeteroFieldContainer.clear(), SelectQueryInvoker.execute(), ClassRef.INTEGER, OrdersTable.INVOICED, BuyerTable.NAME, RoyalMailCSVType.POST_TOWN, RoyalMailCSVType.POSTCODE, BuyerTable.POSTCODE, RoyalMailCSVType.RECIPIENT, RoyalMailCSVType.REFERENCE, GenerateRoyalMailCSV.SALES_REC_NO, OrdersTable.SALES_REC_NO, SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_BUYER_BY_ACCOUNT_AND_SRN, BuyerTable.STREET1, BuyerTable.STREET2, and ClassRef.STRING.
Referenced by GenerateRoyalMailCSV.execute().
String [][] getInvoiceWeight (String inputData[][], String initialData[][]) private
queries winstock for the weight associated with the invoice number provided as an argument.
Parameters
inputData the String[][] to insert the weight into.
initialData String[][] containing the initial data passed in from the frontend
Returns
String[][] containing the data passed in with the weight inserted into the appropriate column.
Definition at line 191 of file GenerateRoyalMailCSV.java.
References GenerateRoyalMailCSV.ACCOUNT, BrandToCode.convertToWinstockInt(), RoyalMailCSVType.REFERENCE, Stock.requestInvoiceWeight(), and RoyalMailCSVType.WEIGHT.
Referenced by GenerateRoyalMailCSV.execute().
String [][] formatReferenceFields (String inputData[][], String initialData[][]) private
adds the account letter to the front of the invoice number in the reference field of the CSV
Parameters
inputData the data after all extra information has been inserted
initialData the initial data taken from the frontend
Returns
String[][] completely formatted data ready to pass to the createCSV method.
Definition at line 211 of file GenerateRoyalMailCSV.java.
References GenerateRoyalMailCSV.ACCOUNT, BrandToCode.convert(), and RoyalMailCSVType.REFERENCE.
Referenced by GenerateRoyalMailCSV.execute().
String createCSV (String csvData[][]) private
use the information provided to create a CSV file that the frontend can access.
Parameters
csvData the data to include in the CSV file
Returns
String containing the CSV formatted data
Definition at line 226 of file GenerateRoyalMailCSV.java.
References RoyalMailCSVGenerator.addBatch(), RoyalMailCSVGenerator.generate(), and RoyalMailCSVGenerator.toString().
Referenced by GenerateRoyalMailCSV.execute().
Member Data Documentation
final int ACCOUNT = 0 static private
defines where the Account info is within the input data
Definition at line 47 of file GenerateRoyalMailCSV.java.
Referenced by GenerateRoyalMailCSV.formatReferenceFields(), GenerateRoyalMailCSV.getInvoiceWeight(), and GenerateRoyalMailCSV.grabAndProcessDBData().
final int SALES_REC_NO = 1 static private
defines where the sales record number is within the input data
Definition at line 49 of file GenerateRoyalMailCSV.java.
Referenced by GenerateRoyalMailCSV.grabAndProcessDBData().
final int SERVICE = 2 static private
defines where the Service info is within the input data
Definition at line 51 of file GenerateRoyalMailCSV.java.
Referenced by GenerateRoyalMailCSV.formatInitialData().
final int SERVICE_ENHANCEMENT = 3 static private
defines where the service enhancement info is within the input data
Definition at line 53 of file GenerateRoyalMailCSV.java.
Referenced by GenerateRoyalMailCSV.formatInitialData().
final int FORMAT = 4 static private
defines where the format info is within the input data
Definition at line 55 of file GenerateRoyalMailCSV.java.
Referenced by GenerateRoyalMailCSV.formatInitialData().
final RoyalMailCSVGenerator csvGen_M private
holder for the model object RoyalMailCSVGenerator
Definition at line 57 of file GenerateRoyalMailCSV.java.
The documentation for this class was generated from the following file:
src/tomoBay/presenters/presenterActions/concreteActions/GenerateRoyalMailCSV.java