TomoBay: BasicEbayUpdateService Class Reference
BasicEbayUpdateService Class Reference
This class represents the start of the execution flow for the eBay Service, The service quereies the eBay API for Order and Item information and.
Protected Member Functions
String onRunning () throws ServiceException
String onPaused () throws ServiceException
String onStopped () throws ServiceException
String onError () throws ServiceException
Protected Member Functions inherited from AbstractService
abstract String onRunning () throws ServiceException
abstract String onPaused () throws ServiceException
abstract String onStopped () throws ServiceException
abstract String onError () throws ServiceException
Package Functions
public< E > void setConfig (AbstractConfiguration< E > config)
Additional Inherited Members
Public Member Functions inherited from AbstractService
String call () throws ServiceException
The individual services equivalent of main.
abstract< E > void setConfig (AbstractConfiguration< E > config)
sets the configuration for this service.
Detailed Description
This class represents the start of the execution flow for the eBay Service, The service quereies the eBay API for Order and Item information and.
Author
Jan P.C. Hanson
Definition at line 26 of file BasicEbayUpdateService.java.
Member Function Documentation
public<E> void setConfig (AbstractConfiguration< E > config) package
Definition at line 32 of file BasicEbayUpdateService.java.
String onRunning () throws ServiceException protected
Definition at line 39 of file BasicEbayUpdateService.java.
References OnRunning.execute().
Referenced by BasicEbayUpdateService.onPaused().
String onPaused () throws ServiceException protected
Definition at line 46 of file BasicEbayUpdateService.java.
References BasicEbayUpdateService.onRunning().
String onStopped () throws ServiceException protected
Definition at line 53 of file BasicEbayUpdateService.java.
String onError () throws ServiceException protected
Definition at line 60 of file BasicEbayUpdateService.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/services/basicEbayUpdateService/BasicEbayUpdateService.java