My Project: openDMS.model.services.basicEbayUpdate.ItemsTable Class Reference
openDMS.model.services.basicEbayUpdate.ItemsTable Class Reference
Public Member Functions
ItemsTable ()
Static Public Member Functions
static void populate (String[] credentials, OrderType[] orders) throws ApiException, SdkException, Exception
Static Private Member Functions
static Map< String, String > getSpecifics (ItemType item)
Detailed Description
Copyright(C) 2015 Jan P.C. Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jan P.C. Hanson
Definition at line 39 of file ItemsTable.java.
Constructor & Destructor Documentation
openDMS.model.services.basicEbayUpdate.ItemsTable.ItemsTable ()
default ctor
Definition at line 44 of file ItemsTable.java.
Member Function Documentation
static Map<String, String> openDMS.model.services.basicEbayUpdate.ItemsTable.getSpecifics (ItemType item) static private
Parameters
item
Returns
Definition at line 83 of file ItemsTable.java.
Referenced by openDMS.model.services.basicEbayUpdate.ItemsTable.populate().
static void openDMS.model.services.basicEbayUpdate.ItemsTable.populate (String[] credentials, OrderType[] orders) throws ApiException, SdkException, Exception static
populates the Orders Table in the database with data grabbed from the ebay API
Parameters
credentials API credentials.
orders list of orders.
Exceptions
Exception
SdkException
ApiException
Definition at line 55 of file ItemsTable.java.
References openDMS.model.eBayAPI.ItemCall.call(), openDMS.model.sql.queries.QueryInvoker.execute(), openDMS.model.services.basicEbayUpdate.ItemsTable.getSpecifics(), openDMS.model.sql.queries.QueryInvoker.QueryType.INSERT_EBAY_ITEMS, and openDMS.model.sql.queries.QueryInvoker.QueryType.SELECT_EBAY_ITEMS.
Referenced by openDMS.model.services.basicEbayUpdate.BasicEbayUpdateService.run().
The documentation for this class was generated from the following file:
src/openDMS/model/services/basicEbayUpdate/ItemsTable.java