TomoBay: OnRunning Class Reference
OnRunning Class Reference
Public Member Functions
OnRunning (Map< String, emailDataType > mailData)
String execute ()
this method defines what to do in the given derived state
Static Package Attributes
static Logger log = Logger.getLogger(EmailErrorsService.class.getName())
Private Attributes
Map< String, emailDataType > mailData_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 31 of file OnRunning.java.
Constructor & Destructor Documentation
OnRunning (Map< String, emailDataType > mailData)
Definition at line 40 of file OnRunning.java.
Member Function Documentation
String execute ()
this method defines what to do in the given derived state
Returns
String representing the end product of the state.
Implements AbstractServiceState.
Definition at line 50 of file OnRunning.java.
References EmailErrorsMailActions.addMessage(), EmailErrorsDataFormat.asHTML(), ErrorsList.exist(), ErrorsList.get(), EmailErrorsMailActions.loadData(), and EmailErrorsMailActions.send().
Referenced by EmailErrorsService.onRunning().
Member Data Documentation
Logger log = Logger.getLogger(EmailErrorsService.class.getName()) static package
Definition at line 33 of file OnRunning.java.
Map<String, emailDataType> mailData_M private
Definition at line 35 of file OnRunning.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/services/emailErrorsService/OnRunning.java