TomoBay: AccountsTable Class Reference
AccountsTable Class Reference
This represents the structure of the ebay_accounts table in the database.
Public Member Functions
AccountsTable ()
private Ctor ensures this class is NEVER INSTANTIATED
Static Public Attributes
static final AbstractField ID = new Id()
The id field of the ebay_accounts table.
static final AbstractField API_KEY = new ApiKey()
the accountName field of the ebay_accounts table
static final AbstractField SERVER_ADDR = new ServerAddr()
the apiKey field of the ebay_accounts table
static final AbstractField ACCOUNT_NAME = new AccountName()
the serverAddr field of the ebay_accounts table
static final AbstractField LOOKBACK_DAYS = new LookbackDays()
the accountName field of the ebay_accounts table
Detailed Description
This represents the structure of the ebay_accounts table in the database.
The static values contained inside this class are for use with the tomoBay.model.dataTypes.dbSchema.HeteroFieldContainer
Author
Jan P.C. Hanson
Definition at line 25 of file AccountsTable.java.
Constructor & Destructor Documentation
AccountsTable ()
private Ctor ensures this class is NEVER INSTANTIATED
Definition at line 62 of file AccountsTable.java.
Member Data Documentation
final AbstractField ID = new Id() static
The id field of the ebay_accounts table.
INT(3)
[PK]
See also
tomoBay.model.sql.schema.accountsTable.Id
Definition at line 33 of file AccountsTable.java.
Referenced by SelectAccounts.format(), EbayAccounts.id(), and EbayAccounts.name().
final AbstractField API_KEY = new ApiKey() static
the accountName field of the ebay_accounts table
VARCHAR(20)
See also
tomoBay.model.sql.schema.accountsTable.ApiKey
Definition at line 39 of file AccountsTable.java.
Referenced by EbayAccounts.apiKey(), and SelectAccounts.format().
final AbstractField SERVER_ADDR = new ServerAddr() static
the apiKey field of the ebay_accounts table
VARCHAR(900)
See also
tomoBay.model.sql.schema.accountsTable.ServerAddr
Definition at line 45 of file AccountsTable.java.
Referenced by SelectAccounts.format(), and EbayAccounts.serverAddress().
final AbstractField ACCOUNT_NAME = new AccountName() static
the serverAddr field of the ebay_accounts table
VARCHAR(45)
See also
tomoBay.model.sql.schema.accountsTable.AccountName
Definition at line 51 of file AccountsTable.java.
Referenced by EbayAccounts.accounts(), EbayAccounts.apiKey(), SelectAccounts.format(), GenerateRoyalMailCSV.grabAndProcessDBData(), EbayAccounts.id(), EbayAccounts.lookbackDays(), EbayAccounts.name(), EbayAccounts.serverAddress(), and SelectBuyerByAccAndSRN.setParameters().
final AbstractField LOOKBACK_DAYS = new LookbackDays() static
the accountName field of the ebay_accounts table
VARCHAR(20)
See also
tomoBay.model.sql.schema.accountsTable.LookbackDays
Definition at line 57 of file AccountsTable.java.
Referenced by SelectAccounts.format(), and EbayAccounts.lookbackDays().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/schema/accountsTable/AccountsTable.java