My Project: openDMS.model.eBayAPI.APIcontext Class Reference
openDMS.model.eBayAPI.APIcontext Class Reference
Public Member Functions
ApiContext apiContext (String usrToken, String server)
Static Public Member Functions
static APIcontext instance ()
Private Member Functions
APIcontext ()
Static Private Attributes
static final APIcontext instance_M = new APIcontext()
Detailed Description
This class contains functionality to provide an APIContext object which is used by API calls in order to authorise an API call. It is a Singleton
Author
Jan P.C. Hanson
Definition at line 29 of file APIcontext.java.
Constructor & Destructor Documentation
openDMS.model.eBayAPI.APIcontext.APIcontext () private
private constructor, Singleton
Definition at line 37 of file APIcontext.java.
Member Function Documentation
ApiContext openDMS.model.eBayAPI.APIcontext.apiContext (String usrToken, String server)
used for getting an ApiContext object that can then be passed to individual API calls.
Parameters
usrToken an eBay API user token
server the server to use for api calls (https://api.sandbox.ebay.com/wsapi for testing and XXXXXXXXXXXXX for production)
Returns
ApiContext object.
Definition at line 55 of file APIcontext.java.
Referenced by openDMS.model.eBayAPI.ItemCall.ItemCall(), and openDMS.model.eBayAPI.OrdersCall.OrdersCall().
static APIcontext openDMS.model.eBayAPI.APIcontext.instance () static
Used instead of constructor for getting an APIcontext instance
Returns
the singleton instance
Definition at line 44 of file APIcontext.java.
References openDMS.model.eBayAPI.APIcontext.instance_M.
Referenced by openDMS.model.eBayAPI.ItemCall.ItemCall(), and openDMS.model.eBayAPI.OrdersCall.OrdersCall().
Member Data Documentation
final APIcontext openDMS.model.eBayAPI.APIcontext.instance_M = new APIcontext() static private
instance variable holds singleton instance
Definition at line 32 of file APIcontext.java.
Referenced by openDMS.model.eBayAPI.APIcontext.instance().
The documentation for this class was generated from the following file:
src/openDMS/model/eBayAPI/APIcontext.java