My Project: openDMS.view.views.RootView Class Reference
openDMS.view.views.RootView Class Reference
Classes
enum Part
Public Member Functions
RootView ()
String make (AbstractViewPart part)
Private Member Functions
void populateMap ()
Private Attributes
Map< Part, String > viewPart_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 26 of file RootView.java.
Constructor & Destructor Documentation
openDMS.view.views.RootView.RootView ()
Definition at line 33 of file RootView.java.
References openDMS.view.views.RootView.populateMap().
Member Function Documentation
String openDMS.view.views.RootView.make (AbstractViewPart part)
This method constructs the part of the view that is requested in the parameters.
Parameters
part should be taken from the internal Enum defined within this class. Each enum constant refers to a specific part of the view.
Returns
String containing the HTML for the part of the view that has been requested.
Implements openDMS.view.views.AbstractView.
Definition at line 44 of file RootView.java.
void openDMS.view.views.RootView.populateMap () private
Definition at line 47 of file RootView.java.
References openDMS.helpers.FileToString.convert(), and openDMS.view.views.RootView.Part.INDEX.
Referenced by openDMS.view.views.RootView.RootView().
Member Data Documentation
Map<Part, String> openDMS.view.views.RootView.viewPart_M private
mapping of enum constant keys to html strings
Definition at line 29 of file RootView.java.
The documentation for this class was generated from the following file:
src/openDMS/view/views/RootView.java