TomoBay: Stock Class Reference
Stock Class Reference
This class is responsible for querying winstock for information.
Public Member Functions
Stock ()
default ctor
final int requestStockLevel (String partNo, String brandCode)
query winstock for the stock level of a particular part.
final String requestDescription (String partNo, String brandCode)
query winstock for the description of a particular part.
final double requestLastCost (String partNo, String brandCode)
query winstock for the last cost price of a particular part.
final int requestInvoiceWeight (int invoiceNo, int brandCode)
query winstock for the weight of a particular invoice
Static Public Attributes
static final int ERROR = -8008135
Private Member Functions
void queryWinstockURL (String partNo, String brandCode)
String postFormatXMLString (HttpResponse xmlResponse)
remove the header bumpf from the bottom of the response
Private Attributes
HttpResponse response_M
the response from winstock for the last part number queried
Static Private Attributes
static final String HTTP_HEADER = "HTTP/1.1 "
static final String URL_PT1_M =ConfigReader.getConf(Config.WIN_URL1)
the first part of the winstock url up to the first variable
static final String URL_PT2_M = ConfigReader.getConf(Config.WIN_URL2)
the second part of the winstock url up to the second variable
Detailed Description
This class is responsible for querying winstock for information.
Author
Jan P.C. Hanson
Definition at line 27 of file Stock.java.
Constructor & Destructor Documentation
Stock ()
default ctor
Definition at line 42 of file Stock.java.
Member Function Documentation
final int requestStockLevel (String partNo, String brandCode)
query winstock for the stock level of a particular part.
Parameters
partNo the manufacturer part number
brandCode 'C'=citroen/peugeot/psa, 'F'=ford, 'P'=everything else
Returns
int the number of the requested part in stock
Definition at line 51 of file Stock.java.
References Stock.ERROR, XMLParser.parse(), Stock.postFormatXMLString(), and Stock.queryWinstockURL().
Referenced by ItemStockLevel.checkStockLevelOfItems(), and OnRunning.execute().
final String requestDescription (String partNo, String brandCode)
query winstock for the description of a particular part.
Parameters
partNo the manufacturer part number
brandCode 'C'=citroen/peugeot/psa, 'F'=ford, 'P'=everything else
Returns
int the number of the requested part in stock
Definition at line 67 of file Stock.java.
References XMLParser.parse(), Stock.postFormatXMLString(), and Stock.queryWinstockURL().
Referenced by Part.getDescription().
final double requestLastCost (String partNo, String brandCode)
query winstock for the last cost price of a particular part.
Parameters
partNo the manufacturer part number
brandCode 'C'=citroen/peugeot/psa, 'F'=ford, 'P'=everything else
Returns
int the number of the requested part in stock
Definition at line 83 of file Stock.java.
References Stock.ERROR, XMLParser.parse(), Stock.postFormatXMLString(), and Stock.queryWinstockURL().
Referenced by Part.getCost().
final int requestInvoiceWeight (int invoiceNo, int brandCode)
query winstock for the weight of a particular invoice
Parameters
invoiceNo the number of the invoice
brandCode brandCode '3'=citroen/peugeot/psa, '0'=ford, '8'=prestige
Returns
int representing the invoice weight.
Definition at line 100 of file Stock.java.
References Stock.ERROR, ConfigReader.getConf(), XMLParser.parse(), Stock.postFormatXMLString(), Config.WIN_WEIGHT_CALL1, and Config.WIN_WEIGHT_CALL2.
Referenced by GenerateRoyalMailCSV.getInvoiceWeight().
void queryWinstockURL (String partNo, String brandCode) private
Parameters
partNo
brandCode
Definition at line 117 of file Stock.java.
References Stock.URL_PT1_M, and Stock.URL_PT2_M.
Referenced by Stock.requestDescription(), Stock.requestLastCost(), and Stock.requestStockLevel().
String postFormatXMLString (HttpResponse xmlResponse) private
remove the header bumpf from the bottom of the response
Parameters
xmlResponse the response returned by the HttpGET.request()
Returns
String containing just the XML
Definition at line 129 of file Stock.java.
References HttpResponse.getResponseMessage(), and Stock.HTTP_HEADER.
Referenced by Stock.requestDescription(), Stock.requestInvoiceWeight(), Stock.requestLastCost(), and Stock.requestStockLevel().
Member Data Documentation
final int ERROR = -8008135 static
Definition at line 29 of file Stock.java.
Referenced by ItemStockLevel.checkStockLevelOfItems(), Stock.requestInvoiceWeight(), Stock.requestLastCost(), and Stock.requestStockLevel().
final String HTTP_HEADER = "HTTP/1.1 " static private
Definition at line 31 of file Stock.java.
Referenced by Stock.postFormatXMLString().
final String URL_PT1_M =ConfigReader.getConf(Config.WIN_URL1) static private
the first part of the winstock url up to the first variable
Definition at line 33 of file Stock.java.
Referenced by Stock.queryWinstockURL().
final String URL_PT2_M = ConfigReader.getConf(Config.WIN_URL2) static private
the second part of the winstock url up to the second variable
Definition at line 35 of file Stock.java.
Referenced by Stock.queryWinstockURL().
HttpResponse response_M private
the response from winstock for the last part number queried
Definition at line 37 of file Stock.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/Stock.java