TomoBay: EmailDirector Class Reference
EmailDirector Class Reference
This class is responsible for sending creating email and mail server objects.
Public Member Functions
EmailDirector () throws NoSuchProviderException
default ctor
void constructEmailAndServer (AbstractEmailBuilder builder)
initialises the email and server objects ready to be retrieved by the get methods.
Email getEmail () throws NullEmailObjectException
MailServerSend getMailSendServer () throws NullEmailServerObjectException
Package Attributes
AbstractEmailBuilder builder_M
holder for the builder that determines the specific email server to connect to
Detailed Description
This class is responsible for sending creating email and mail server objects.
At the moment there is only a MailServerSend class but at some point it may be worth implementing a recieving interface as well.
In order to create email and server objects an AbstractEmailBuilder must be passed in. This builder determines the specifics of the email server that the system is to connect to.
Author
Jan P.C. Hanson
Definition at line 32 of file EmailDirector.java.
Constructor & Destructor Documentation
EmailDirector () throws NoSuchProviderException
default ctor
Exceptions
NoSuchProviderException
Definition at line 41 of file EmailDirector.java.
Member Function Documentation
void constructEmailAndServer (AbstractEmailBuilder builder)
initialises the email and server objects ready to be retrieved by the get methods.
Definition at line 47 of file EmailDirector.java.
References AbstractEmailBuilder.buildEmail(), and AbstractEmailBuilder.buildMailServerSendConnection().
Referenced by EmailErrorsMailActions.EmailErrorsMailActions(), EmailTest.main(), and MailClient.send().
Email getEmail () throws NullEmailObjectException
Returns
Exceptions
MessagingException
NullEmailObjectException
Definition at line 60 of file EmailDirector.java.
References AbstractEmailBuilder.email_M.
Referenced by EmailErrorsMailActions.EmailErrorsMailActions(), and EmailTest.main().
MailServerSend getMailSendServer () throws NullEmailServerObjectException
Returns
Exceptions
MessagingException
Definition at line 73 of file EmailDirector.java.
References AbstractEmailBuilder.mailServer_M.
Referenced by EmailErrorsMailActions.EmailErrorsMailActions(), EmailTest.main(), and MailClient.send().
Member Data Documentation
AbstractEmailBuilder builder_M package
holder for the builder that determines the specific email server to connect to
Definition at line 35 of file EmailDirector.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/net/email/EmailDirector.java