TomoBay: EmailErrorsService Class Reference
EmailErrorsService Class Reference
This service is responsible for generating a list of erroneous items that exist within the database and emailing it to appropriate parties.
Classes
enum emailDataType
Public Member Functions
EmailErrorsService ()
Public Member Functions inherited from AbstractService
String call () throws ServiceException
The individual services equivalent of main.
abstract< E > void setConfig (AbstractConfiguration< E > config)
sets the configuration for this service.
Protected Member Functions
String onRunning () throws ServiceException
String onPaused () throws ServiceException
String onStopped () throws ServiceException
String onError () throws ServiceException
Protected Member Functions inherited from AbstractService
abstract String onRunning () throws ServiceException
abstract String onPaused () throws ServiceException
abstract String onStopped () throws ServiceException
abstract String onError () throws ServiceException
Package Functions
public< E > void setConfig (AbstractConfiguration< E > config)
Private Attributes
Map< String, emailDataType > mailData_M
Detailed Description
This service is responsible for generating a list of erroneous items that exist within the database and emailing it to appropriate parties.
Author
Jan P.C. Hanson
Definition at line 32 of file EmailErrorsService.java.
Constructor & Destructor Documentation
EmailErrorsService ()
Definition at line 46 of file EmailErrorsService.java.
Member Function Documentation
public<E> void setConfig (AbstractConfiguration< E > config) package
Definition at line 53 of file EmailErrorsService.java.
References AbstractConfiguration< T >.configure(), and XMLParser.parseAll().
String onRunning () throws ServiceException protected
Definition at line 73 of file EmailErrorsService.java.
References OnRunning.execute().
String onPaused () throws ServiceException protected
Definition at line 80 of file EmailErrorsService.java.
String onStopped () throws ServiceException protected
Definition at line 87 of file EmailErrorsService.java.
String onError () throws ServiceException protected
Definition at line 94 of file EmailErrorsService.java.
Member Data Documentation
Map<String, emailDataType> mailData_M private
Definition at line 35 of file EmailErrorsService.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/services/emailErrorsService/EmailErrorsService.java