TomoBay: PrintInvoiceCommand Class Reference
PrintInvoiceCommand Class Reference
This class represents a command to winstock to print an invoice.
Public Member Functions
PrintInvoiceCommand () throws UnknownHostException, IOException
default ctor
PrintInvoiceResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException
Public Member Functions inherited from AbstractWinstockCommand
abstract AbstractWinstockCommandResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException
this method executes the AbstractWinstockCommand specific to the derived type.
Private Attributes
PrintInvoiceResponse response_M
the response object
PrintInvoicePayload payload_M
the payload object
Static Private Attributes
static final int RESPONSE_LENGTH = 7
constant holding the the length of the response in bytes
Additional Inherited Members
Protected Member Functions inherited from AbstractWinstockCommand
AbstractWinstockCommand () throws UnknownHostException, IOException
default ctor, does preliminary initailisation of the config object and socket connection to Winstock.
Protected Attributes inherited from AbstractWinstockCommand
WinstockConfig config_M
client socket connection
ClientSocket winstockConnection_M
the configuration details
Detailed Description
This class represents a command to winstock to print an invoice.
Author
Jan P.C. Hanson
Definition at line 30 of file PrintInvoiceCommand.java.
Constructor & Destructor Documentation
PrintInvoiceCommand () throws UnknownHostException, IOException
default ctor
Exceptions
UnknownHostException
IOException
Definition at line 44 of file PrintInvoiceCommand.java.
Member Function Documentation
PrintInvoiceResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException
Definition at line 55 of file PrintInvoiceCommand.java.
References AbstractPayload.getPayload(), PrintInvoiceCommand.response_M, PrintInvoiceResponse.setResponseBytes(), and PrintInvoiceResponse.setSentBytes().
Member Data Documentation
final int RESPONSE_LENGTH = 7 static private
constant holding the the length of the response in bytes
Definition at line 33 of file PrintInvoiceCommand.java.
PrintInvoiceResponse response_M private
the response object
Definition at line 35 of file PrintInvoiceCommand.java.
Referenced by PrintInvoiceCommand.execute().
PrintInvoicePayload payload_M private
the payload object
Definition at line 37 of file PrintInvoiceCommand.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/commands/PrintInvoiceCommand.java