TomoBay: XMLParser Class Reference
XMLParser Class Reference
This class parses an XML file and returns a string specific to the tag requested.
Static Public Member Functions
static String parse (String tag, String stringToParse)
parses an XML formatted string looking for the first tag specified in the parameters.
static NodeList parseAll (String tag, String stringToParse)
returns a NodeList containing all the nodes that have the specified tag name
Detailed Description
This class parses an XML file and returns a string specific to the tag requested.
Author
Jan P.C. Hanson
Definition at line 33 of file XMLParser.java.
Member Function Documentation
static String parse (String tag, String stringToParse) static
parses an XML formatted string looking for the first tag specified in the parameters.
Parameters
tag the name of the tag (not including angle brackets)
stringToParse the XML formatted string to parse for the tag specified
Returns
String containing the text inside the XML tag specified
Exceptions
SAXException
IOException
ParserConfigurationException
Definition at line 44 of file XMLParser.java.
Referenced by ConfigReader.getConf(), Stock.requestDescription(), Stock.requestLastCost(), and Stock.requestStockLevel().
static NodeList parseAll (String tag, String stringToParse) static
returns a NodeList containing all the nodes that have the specified tag name
Parameters
tag the tag to search for within the string provided
stringToParse The string to search for specific tags in.
Returns
NodeList containing all the tags that match the search term.
Definition at line 71 of file XMLParser.java.
Referenced by ConfigReader.getConf(), ConfigReader.getConfs(), EmailErrorsService.setConfig(), and ConfigReader.size().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/helpers/XMLParser.java