TomoBay: StockReOrderAnalysisTest Class Reference
StockReOrderAnalysisTest Class Reference
Public Member Functions
final void testStockReOrderAnalysis ()
final void testExecuteGoodData ()
final void testExecuteBadData1 ()
final void testExecuteBadData2 ()
final void testExecuteBadData3 ()
Private Attributes
final String goodData = "{lookback:28,threshold:2}"
final String badData1 = "{lookback:'28' threshold:'2'}"
final String badData2 = "{lookback:'28 ,threshold:'2'}"
final String badData3 = "{lookback:'28',threshold:'29'}"
final String validResult =""
Detailed Description
Precondition
database containing the tables referenced in tomoBay.model.sql.queries.concreteQueries.select.params.SelectEbayOrderHistoryLastNDays exists.
tomoBay.model.sql.queries.concreteQueries.select.params.SelectEbayOrderHistoryLastNDays works as expected.
input to the execute method is a well formed JSON string containing the 'lookback' and 'threshold' properties.
Postcondition
A well formatted JSON string result
result contains array of objects of the form [{partNo:"abc123", quantity:123},....]
See also
tomoBay.presenters.presenterActions.concreteActions.StockReOrderAnalysis
Author
Jan P.C. Hanson
Definition at line 43 of file StockReOrderAnalysisTest.java.
Member Function Documentation
final void testStockReOrderAnalysis ()
Precondition
none
Postcondition
fully initialised StockReOrderAnalaysis object
Test method for tomoBay.presenters.presenterActions.concreteActions.StockReOrderAnalysis::StockReOrderAnalysis()
Definition at line 68 of file StockReOrderAnalysisTest.java.
final void testExecuteGoodData ()
Precondition
correctly formatted JSON string, containing the 'lookback' and 'threshold' properties.
- database containing the tables referenced in tomoBay.model.sql.queries.concreteQueries.select.params.SelectEbayOrderHistoryLastNDays exists.
tomoBay.model.sql.queries.concreteQueries.select.params.SelectEbayOrderHistoryLastNDays works as expected.
input to the execute method is a well formed JSON string containing the 'lookback' and 'threshold' properties.
Postcondition
A well formatted JSON string result
result contains array of objects of the form [{partNo:"abc123", quantity:123},....] Test method for tomoBay.presenters.presenterActions.concreteActions.StockReOrderAnalysis::execute(java.lang.String)
Definition at line 91 of file StockReOrderAnalysisTest.java.
References StockReOrderAnalysis.execute().
final void testExecuteBadData1 ()
Precondition
correctly formatted JSON string, containing the 'lookback' and 'threshold' properties.
- database containing the tables referenced in tomoBay.model.sql.queries.concreteQueries.select.params.SelectEbayOrderHistoryLastNDays exists.
tomoBay.model.sql.queries.concreteQueries.select.params.SelectEbayOrderHistoryLastNDays works as expected.
input to the execute method is a well formed JSON string containing the 'lookback' and 'threshold' properties.
Postcondition
A well formatted JSON string result
result contains array of objects of the form [{partNo:"abc123", quantity:123},....] Test method for tomoBay.presenters.presenterActions.concreteActions.StockReOrderAnalysis::execute(java.lang.String)
Definition at line 117 of file StockReOrderAnalysisTest.java.
References StockReOrderAnalysis.execute().
final void testExecuteBadData2 ()
Definition at line 126 of file StockReOrderAnalysisTest.java.
References StockReOrderAnalysis.execute().
final void testExecuteBadData3 ()
Definition at line 135 of file StockReOrderAnalysisTest.java.
References StockReOrderAnalysis.execute().
Member Data Documentation
final String goodData = "{lookback:28,threshold:2}" private
Definition at line 46 of file StockReOrderAnalysisTest.java.
final String badData1 = "{lookback:'28' threshold:'2'}" private
Definition at line 48 of file StockReOrderAnalysisTest.java.
final String badData2 = "{lookback:'28 ,threshold:'2'}" private
Definition at line 50 of file StockReOrderAnalysisTest.java.
final String badData3 = "{lookback:'28',threshold:'29'}" private
Definition at line 52 of file StockReOrderAnalysisTest.java.
final String validResult ="" private
Definition at line 54 of file StockReOrderAnalysisTest.java.
The documentation for this class was generated from the following file:
src/tomoBayTests/presenters/presenterActions/concreteActions/StockReOrderAnalysisTest.java