TomoBay: PriceAdjustment Class Reference
PriceAdjustment Class Reference
This class represents an algorithm for adjusting the prices of an AbstractSalesDayBookLine so that the calculated total (i.e.
Protected Member Functions
PriceAdjustment ()
Default ctor.
void adjust (AbstractSalesDayBookLine line)
calculate the adjustments necessary and apply them to the AbstractSalesDayBookLine provided as an argument
Private Member Functions
void performAdjustement (AbstractSalesDayBookLine line, int[] newPrices)
actually performs the adjustement
int[] convertListToArray (int noOfItems, AbstractSalesDayBookLine line)
convert the internal list of AbstractLineItem withing the AbstractSalesDayBookLine to an array.
int calculateTotal (int[] testPrices, AbstractSalesDayBookLine line)
calculate the total cost (EX VAT) of the testPrices array.
int noOfItems (AbstractSalesDayBookLine line)
returns the number of AbstractLineItems (minus postage line items) contained within this AbstractSalesDayBookLine.
int fitness (AbstractSalesDayBookLine line, int calculatedTotal)
this method represents a fitness function to be used when calculating the adjustments to the AbstractSalesDayBookLine.
int smallestQty (AbstractSalesDayBookLine line)
The smallest quantity of the parts on this AbstractSalesDayBookLine.
int adjustmentAmt (int discrepancy)
the incremental amount to adjust the price by.
Static Private Attributes
static final int PLACEHOLDER = 99999999
Detailed Description
This class represents an algorithm for adjusting the prices of an AbstractSalesDayBookLine so that the calculated total (i.e.
the amount that is actually invoiced) is as close as physically possible to the listing price on ebay. This is necessary as the ebay based order price is inclusive of VAT however the number that I need to provide the winstock invoiceing system is inclusive of VAT. This is coupled with the fact that when listing items, the humans responsible do not always figure VAT in when deciding on a price.
This class is final and ALL methods in this class are either protected or private so that this class cannot be subclassed and the methods in this class cannot be accessed outside of this package....(package scope is silly)
Author
Jan P.C. Hanson
Definition at line 32 of file PriceAdjustment.java.
Constructor & Destructor Documentation
PriceAdjustment () protected
Default ctor.
Definition at line 39 of file PriceAdjustment.java.
Member Function Documentation
void adjust (AbstractSalesDayBookLine line) protected
calculate the adjustments necessary and apply them to the AbstractSalesDayBookLine provided as an argument
Parameters
line AbstractSalesDayBookLine to adjust
Definition at line 47 of file PriceAdjustment.java.
References PriceAdjustment.adjustmentAmt(), PriceAdjustment.calculateTotal(), PriceAdjustment.convertListToArray(), PriceAdjustment.fitness(), PriceAdjustment.noOfItems(), PriceAdjustment.performAdjustement(), PriceAdjustment.PLACEHOLDER, and PriceAdjustment.smallestQty().
Referenced by AbstractSalesDayBookLine.adjustPrices().
void performAdjustement (AbstractSalesDayBookLine line, int[] newPrices) private
actually performs the adjustement
Parameters
line AbstractSalesDayBookLine to adjust
newPrices the new prices that the AbstractSalesDayBookLine should be adjusted to
Definition at line 76 of file PriceAdjustment.java.
References AbstractLineItem.adjustPrice(), AbstractSalesDayBookLine.getLineItem(), and AbstractLineItem.price().
Referenced by PriceAdjustment.adjust().
int [] convertListToArray (int noOfItems, AbstractSalesDayBookLine line) private
convert the internal list of AbstractLineItem withing the AbstractSalesDayBookLine to an array.
Parameters
noOfItems the number of items excluding the postage item
line AbstractSalesDayBookLine in question
Definition at line 91 of file PriceAdjustment.java.
References AbstractSalesDayBookLine.getLineItem(), PriceAdjustment.noOfItems(), and AbstractLineItem.price().
Referenced by PriceAdjustment.adjust().
int calculateTotal (int[] testPrices, AbstractSalesDayBookLine line) private
calculate the total cost (EX VAT) of the testPrices array.
The AbstractSalesDayBookLine is necessary in case this AbstractSalesDayBookLine contains a POST part
Parameters
testPrices the array of prices to calculate the total (ex vat) from
line AbstractSalesDayBookLine in question
Returns
int representing the total price in pennies (ex VAT)
Definition at line 106 of file PriceAdjustment.java.
References AbstractSalesDayBookLine.getLineItem(), AbstractLineItem.partNo(), AbstractLineItem.price(), AbstractLineItem.quantity(), and AbstractSalesDayBookLine.size().
Referenced by PriceAdjustment.adjust().
int noOfItems (AbstractSalesDayBookLine line) private
returns the number of AbstractLineItems (minus postage line items) contained within this AbstractSalesDayBookLine.
Parameters
line AbstractSalesDayBookLine to analyse
Returns
int representing the number of line items (minus postage lineItems)
Definition at line 124 of file PriceAdjustment.java.
References AbstractSalesDayBookLine.getLineItem(), and AbstractSalesDayBookLine.size().
Referenced by PriceAdjustment.adjust(), and PriceAdjustment.convertListToArray().
int fitness (AbstractSalesDayBookLine line, int calculatedTotal) private
this method represents a fitness function to be used when calculating the adjustments to the AbstractSalesDayBookLine.
it is based around the difference between the actual total (as taken from eBay), and the calculated total, as worked out by the AbstractSalesDayBookLine object and this price adjustment class.
Parameters
line the AbstractSalesDayBookLine that this method applies to.
calculatedTotal the total as calculated by the AbstractSalesDayBookLine object and this price Adjustment class
Returns
int the number of pennies difference between the actualTotal and the calculatedTotal
Definition at line 143 of file PriceAdjustment.java.
References VAT.add(), and AbstractSalesDayBookLine.totalIncVat().
Referenced by PriceAdjustment.adjust().
int smallestQty (AbstractSalesDayBookLine line) private
The smallest quantity of the parts on this AbstractSalesDayBookLine.
i.e. the smallest adjustement that can be made by the system e.g. a quantity of 1 would mean the smallest adjustment possible to make is 1 penny. for a quantity of 11 the smallest possible adjustment is 11 pennies.
Parameters
line the AbstractSalesDayBookLine to analyse for the smallest part qwuantity.
Returns
int representing the smallest quantity found in this AbstractSalesDayBookLine
Definition at line 154 of file PriceAdjustment.java.
References PriceAdjustment.PLACEHOLDER.
Referenced by PriceAdjustment.adjust().
int adjustmentAmt (int discrepancy) private
the incremental amount to adjust the price by.
this will always be either +1 or -1 depending on whether the initial discrepancy is positive or negative. This is so that it will adjust in the right direction.
Parameters
discrepancy the intitial difference between actual and calculated price
Returns
int either +1 or -1
Definition at line 169 of file PriceAdjustment.java.
Referenced by PriceAdjustment.adjust().
Member Data Documentation
final int PLACEHOLDER = 99999999 static private
Definition at line 34 of file PriceAdjustment.java.
Referenced by PriceAdjustment.adjust(), and PriceAdjustment.smallestQty().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/financial/SalesOrderDayBook/PriceAdjustment.java