TomoBay: BuyerTable Class Reference
BuyerTable Class Reference
This represents the structure of the ebay_buyers table in the database.
Static Public Attributes
static final BuyerID BUYERID = new BuyerID()
The buyerID column of the ebay_buyers table.
static final Name NAME = new Name()
The name column of the ebay_buyers table.
static final Street STREET1 = new Street()
The street1 column of the ebay_buyers table.
static final Street STREET2 = new Street()
The street2 column of the ebay_buyers table.
static final City CITY = new City()
The city column of the ebay_buyers table.
static final County COUNTY = new County()
The county column of the ebay_buyers table.
static final Postcode POSTCODE = new Postcode()
The postcode column of the ebay_buyers table.
static final Email EMAIL = new Email()
The email column of the ebay_buyers table.
static final Phone PHONE = new Phone()
The phoneNo column of the ebay_buyers table.
Private Member Functions
BuyerTable ()
private ctor ensures this class is NEVER INSTANTIATED
Detailed Description
This represents the structure of the ebay_buyers table in the database.
The static values contained inside this class are for use with the tomoBay.model.dataTypes.dbSchema.HeteroFieldContainer
Author
Jan P.C. Hanson
Definition at line 24 of file BuyerTable.java.
Constructor & Destructor Documentation
BuyerTable () private
private ctor ensures this class is NEVER INSTANTIATED
Definition at line 94 of file BuyerTable.java.
Member Data Documentation
final BuyerID BUYERID = new BuyerID() static
The buyerID column of the ebay_buyers table.
VARCHAR(40)
Primary Key
See also
tomoBay.model.sql.schema.buyerTable.BuyerID
Definition at line 33 of file BuyerTable.java.
Referenced by Buyer.Buyer(), Buyer.buyerID(), BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), SelectFullOrderLine.format(), BuyerList.formatResults(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), BuyerDetails.getRawData(), UpdateEbayBuyer.setParameters(), and InsertEbayBuyers.setParameters().
final Name NAME = new Name() static
The name column of the ebay_buyers table.
VARCHAR(45)
See also
tomoBay.model.sql.schema.buyerTable.Name
Definition at line 40 of file BuyerTable.java.
Referenced by BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), SelectFullOrderLine.format(), BuyerList.formatResults(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), Buyer.name(), UpdateEbayBuyer.setParameters(), and InsertEbayBuyers.setParameters().
final Street STREET1 = new Street() static
The street1 column of the ebay_buyers table.
VARCHAR(80)
See also
tomoBay.model.sql.schema.buyerTable.Street
Definition at line 47 of file BuyerTable.java.
Referenced by BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), SelectFullOrderLine.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), UpdateEbayBuyer.setParameters(), InsertEbayBuyers.setParameters(), and Buyer.street1().
final Street STREET2 = new Street() static
The street2 column of the ebay_buyers table.
VARCHAR(80)
See also
tomoBay.model.sql.schema.buyerTable.Street
Definition at line 54 of file BuyerTable.java.
Referenced by BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), SelectFullOrderLine.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), UpdateEbayBuyer.setParameters(), InsertEbayBuyers.setParameters(), and Buyer.street2().
final City CITY = new City() static
The city column of the ebay_buyers table.
VARCHAR(80)
See also
tomoBay.model.sql.schema.buyerTable.City
Definition at line 61 of file BuyerTable.java.
Referenced by Buyer.city(), BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), SelectFullOrderLine.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), UpdateEbayBuyer.setParameters(), and InsertEbayBuyers.setParameters().
final County COUNTY = new County() static
The county column of the ebay_buyers table.
VARCHAR(80)
See also
tomoBay.model.sql.schema.buyerTable.County
Definition at line 68 of file BuyerTable.java.
Referenced by Buyer.county(), BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), SelectFullOrderLine.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), UpdateEbayBuyer.setParameters(), and InsertEbayBuyers.setParameters().
final Postcode POSTCODE = new Postcode() static
The postcode column of the ebay_buyers table.
VARCHAR(15)
See also
tomoBay.model.sql.schema.buyerTable.Postcode
Definition at line 75 of file BuyerTable.java.
Referenced by BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), SelectFullOrderLine.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), Buyer.postcode(), UpdateEbayBuyer.setParameters(), and InsertEbayBuyers.setParameters().
final Email EMAIL = new Email() static
The email column of the ebay_buyers table.
VARCHAR(100)
See also
tomoBay.model.sql.schema.buyerTable.Email
Definition at line 82 of file BuyerTable.java.
Referenced by Buyer.email(), BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), UpdateEbayBuyer.setParameters(), and InsertEbayBuyers.setParameters().
final Phone PHONE = new Phone() static
The phoneNo column of the ebay_buyers table.
VARCHAR(16)
See also
tomoBay.model.sql.schema.buyerTable.Phone
Definition at line 89 of file BuyerTable.java.
Referenced by BuyerDetails.execute(), SelectEbayBuyers.format(), SelectEbayBuyer.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), Buyer.phoneNo(), UpdateEbayBuyer.setParameters(), and InsertEbayBuyers.setParameters().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/sql/schema/buyerTable/BuyerTable.java