My Project: openDMS.ebay.query.commands.GetOrderListCommand Class Reference
openDMS.ebay.query.commands.GetOrderListCommand Class Reference
Public Member Functions
String execute (ApiCallData callData, int NOTUSED, String NOTUSEDEITHER)
ApiCallData getCallData ()
Public Member Functions inherited from openDMS.ebay.query.commands.AbstractEbayQuery
abstract String execute (ApiCallData callData, int index, String string)
abstract ApiCallData getCallData ()
Additional Inherited Members
Protected Attributes inherited from openDMS.ebay.query.commands.AbstractEbayQuery
ApiCallData callData_M
Detailed Description
This is a concrete command that returns a list of orders from the last day.
Author
Jan P.C. Hanson
Definition at line 24 of file GetOrderListCommand.java.
Member Function Documentation
String openDMS.ebay.query.commands.GetOrderListCommand.execute (ApiCallData callData, int NOTUSED, String NOTUSEDEITHER)
Definition at line 30 of file GetOrderListCommand.java.
References openDMS.ebay.query.data.ApiOrderData.accessData(), openDMS.ebay.query.data.ApiCallData.accessOrderData(), openDMS.ebay.query.recievers.OrdersCall.call(), and openDMS.ebay.query.data.ApiOrderData.clearData().
ApiCallData openDMS.ebay.query.commands.GetOrderListCommand.getCallData ()
Definition at line 51 of file GetOrderListCommand.java.
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/commands/GetOrderListCommand.java