TomoBay: ItemStockLevel Class Reference
ItemStockLevel Class Reference
Public Member Functions
ItemStockLevel ()
Static Package Functions
static final Set< Boolean > check (String orderId)
Static Private Member Functions
static Set< Boolean > checkStockLevelOfItems (List< HeteroFieldContainer > itemsVar)
Takes the list of items generated in this.assembleItemsList and checks a PartList associated with each item against Stock held in winstock.
Detailed Description
Author
Jan P.C. Hanson
Definition at line 36 of file ItemStockLevel.java.
Constructor & Destructor Documentation
ItemStockLevel ()
Definition at line 42 of file ItemStockLevel.java.
Member Function Documentation
static final Set<Boolean> check (String orderId) static package
Parameters
orderId
Returns
Definition at line 49 of file ItemStockLevel.java.
References HeteroFieldContainer.add(), ItemStockLevel.checkStockLevelOfItems(), SelectQueryInvoker.execute(), OrdersTable.ORDER_ID, and SelectQueryInvoker.SelectQueryTypeParams.SELECT_BRAND_AND_PARTNO_BY_ORDERID.
Referenced by Pickeablity.Pickeablity().
static Set<Boolean> checkStockLevelOfItems (List< HeteroFieldContainer > itemsVar) static private
Takes the list of items generated in this.assembleItemsList and checks a PartList associated with each item against Stock held in winstock.
For every item with enough stock level it adds a true value to a Set<Boolean> i.e. if everything is in stock the set will only contain 1 element = true, if everything is out of stock the set will contain only 1 element = false, but if some items are in stock and others arn't it will contain 2 elements true and false.
Parameters
itemsVar the list of items to check off against Stock levels
Returns
Set<Boolean> in stock - size=1 value={true}; out of stock - size=1 values={false}; partial stock - size = 2 values = {true,false}
Definition at line 73 of file ItemStockLevel.java.
References ItemsTable.BRAND, BrandToCode.convertToWinstockInt(), Stock.ERROR, PartList.getPartNumber(), PartList.getPartQty(), ItemsTable.PART_NO, Stock.requestStockLevel(), PartList.size(), and ClassRef.STRING.
Referenced by ItemStockLevel.check().
The documentation for this class was generated from the following file:
src/tomoBay/presenters/helpers/pickeability/ItemStockLevel.java