TomoBay: ClientSocketTest Class Reference
ClientSocketTest Class Reference
Static Public Member Functions
static void main (String[] args)
Static Private Member Functions
static void test (DualList< String, PayloadType > data, WinstockCommandInvoker.WinstockCommandTypes command) throws UnknownHostException, IOException, PayloadException, NotAValidResultCodeException
Detailed Description
Author
Jan P.C. Hanson
Definition at line 31 of file ClientSocketTest.java.
Member Function Documentation
static void main (String[] args) static
Parameters
args
Definition at line 37 of file ClientSocketTest.java.
References PayloadType.ADDRESS1, PayloadType.ADDRESS2, PayloadType.CITY, PayloadType.COMPANY, PayloadType.COUNTY, PayloadType.DESCRIPTION, PayloadType.INSTOCK, PayloadType.INV_LINES, PayloadType.INVOICE_ACCOUNT, PayloadType.INVOICE_NO, PayloadType.NAME, PayloadType.ORDER_NO, PayloadType.PACKING_LISTS, PayloadType.PART_NO, PayloadType.POSTCODE, PayloadType.PRICE, PayloadType.PRINT_COPIES, WinstockCommandInvoker.WinstockCommandTypes.PrintInvoice, DualList< V1, V2 >.put(), PayloadType.QUANTITY, ClientSocketTest.test(), and PayloadType.TYPE.
static void test (DualList< String, PayloadType > data, WinstockCommandInvoker.WinstockCommandTypes command) throws UnknownHostException, IOException, PayloadException, NotAValidResultCodeException static private
Definition at line 81 of file ClientSocketTest.java.
References WinstockCommandInvoker.execute(), AbstractWinstockCommandResponse.getRecieved(), AbstractWinstockCommandResponse.getSent(), and AbstractWinstockCommandResponse.isSuccess().
Referenced by ClientSocketTest.main().
The documentation for this class was generated from the following file:
src/tomoBayTests/model/net/ClientSocketTest.java