TomoBay: BrandToCode Class Reference
BrandToCode Class Reference
This helper class converts a generic brand string into a brand code specific to the winstock http api.
Public Member Functions
BrandToCode ()
defualt ctor
Static Public Member Functions
static String convert (String brand)
converts a string like "citroen" or "fOrd" to a brandcode specific to winstock.
static int convertToWinstockInt (String brand)
converts converts a string like "citroen" or "fOrd" to a brandcode integer specific to winstock.
Static Private Attributes
static final String PSA = "C"
definition of the Citroes brandCode
static final String FORD = "F"
definition of the Ford brandCode
static final String PRESTIGE = "P"
definition of the prestige brandCode
static final Map< String, Integer > intMap_M
mapping of string brandcode to integer brandcode
Detailed Description
This helper class converts a generic brand string into a brand code specific to the winstock http api.
Author
Jan P.C. Hanson
Definition at line 29 of file BrandToCode.java.
Constructor & Destructor Documentation
BrandToCode ()
defualt ctor
Definition at line 52 of file BrandToCode.java.
Member Function Documentation
static String convert (String brand) static
converts a string like "citroen" or "fOrd" to a brandcode specific to winstock.
Parameters
brand String like "Citroen" or "Ford" to a brandcode
Returns
String brand identifier, C for peugeot/citroen/psa, F for ford, P for everything else.
Definition at line 61 of file BrandToCode.java.
Referenced by GenerateRoyalMailCSV.formatReferenceFields().
static int convertToWinstockInt (String brand) static
converts converts a string like "citroen" or "fOrd" to a brandcode integer specific to winstock.
Parameters
brand brand String like "Citroen" or "Ford" to a brandcode
Returns
int brand identifier, 3 for peugeot/citroen/psa, 0 for ford, 8 for everything else.
Definition at line 79 of file BrandToCode.java.
Referenced by ItemStockLevel.checkStockLevelOfItems(), PrintInvoices.execute(), OnRunning.execute(), WinstockFormat.format(), Part.getCost(), Part.getDescription(), GenerateRoyalMailCSV.getInvoiceWeight(), and ReScanErrorsWinstockActions.partNoHasError().
Member Data Documentation
final String PSA = "C" static private
definition of the Citroes brandCode
Definition at line 32 of file BrandToCode.java.
final String FORD = "F" static private
definition of the Ford brandCode
Definition at line 34 of file BrandToCode.java.
final String PRESTIGE = "P" static private
definition of the prestige brandCode
Definition at line 36 of file BrandToCode.java.
final Map<String, Integer> intMap_M static private
Initial value:
= new THashMap<String, Integer>()
    {{
        put("C", 3);
        put("F", 0);
        put("P", 8);
    }}
mapping of string brandcode to integer brandcode
Definition at line 41 of file BrandToCode.java.
The documentation for this class was generated from the following file:
src/tomoBay/helpers/BrandToCode.java