TomoBay: VAT Class Reference
VAT Class Reference
This class provides methods that allow the manipulation of values to do with VAT.
Public Member Functions
VAT ()
default ctor
Static Public Member Functions
static final double add (double value)
add vat to the value provided as argument
static final int add (int value)
add vat to the value provided as argument
static final double subtract (double value)
subtract vat to the value provided as argument
static final int subtract (int value)
subtract vat to the value provided as argument
static final double due (double value)
provides the value for VAT due on a particular value
static final int due (int value)
provides the value for VAT due on a particular value
Static Private Member Functions
static final int doubleToInt (double value)
Detailed Description
This class provides methods that allow the manipulation of values to do with VAT.
This class does not care about sign and all methods will use the absolute value of the value provided.
Author
Jan P.C. Hanson
Definition at line 26 of file VAT.java.
Constructor & Destructor Documentation
VAT ()
default ctor
Definition at line 32 of file VAT.java.
Member Function Documentation
static final double add (double value) static
add vat to the value provided as argument
Parameters
value double value for VAT to be added to.
Returns
double representing the original value with VAT added.
Definition at line 40 of file VAT.java.
Referenced by PriceAdjustment.fitness().
static final int add (int value) static
add vat to the value provided as argument
Parameters
value int value for vat to be added to.
Returns
int representing the original value with VAT added.
Definition at line 48 of file VAT.java.
static final double subtract (double value) static
subtract vat to the value provided as argument
Parameters
value double representing the value to have VAT removed from.
Returns
double representing the initial value with the VAT removed
Definition at line 56 of file VAT.java.
Referenced by OrderInfo.summaryInfo(), AbstractSalesDayBookLine.totalExVat(), OrderInfo.transactionInfo(), GSPInvoiceLine.unitPrice(), StandardInvoiceLine.unitPrice(), and StandardInvoiceShippingLine.unitPrice().
static final int subtract (int value) static
subtract vat to the value provided as argument
Parameters
value int representing the value to have VAT removed from
Returns
int representing the initial value with the VAT removed
Definition at line 64 of file VAT.java.
static final double due (double value) static
provides the value for VAT due on a particular value
Parameters
value double value for which VAT should be calculated
Returns
the VAT that should be applied to the given value
Definition at line 72 of file VAT.java.
Referenced by OrderInfo.summaryInfo().
static final int due (int value) static
provides the value for VAT due on a particular value
Parameters
value int value for which VAT should be calculated
Returns
the VAT that should be applied to the given value.
Definition at line 80 of file VAT.java.
static final int doubleToInt (double value) static private
Parameters
value
Returns
Definition at line 88 of file VAT.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/financial/VAT.java