My Project: openDMS.model.sql.queries.concreteQueries.InsertEbayOrders Class Reference
openDMS.model.sql.queries.concreteQueries.InsertEbayOrders Class Reference
Public Member Functions
InsertEbayOrders ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
Timestamp makeTimestamp (String dateTime) throws ParseException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
Author
Jan P.C. Hanson
Definition at line 35 of file InsertEbayOrders.java.
Constructor & Destructor Documentation
openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.InsertEbayOrders ()
default constructor
Definition at line 48 of file InsertEbayOrders.java.
Member Function Documentation
void openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 118 of file InsertEbayOrders.java.
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.execute().
List<String[]> openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. The Ebay Orders Table only has 5 columns so any element above the 4th element will be ignored. col1 =orderID:int(30), col2=buyerID:varchar(40), col3=salesRecNo:int(10), col4=shippingType:varchar(200), col5=createdTime:datetime
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements openDMS.model.sql.queries.AbstractDBQuery.
Definition at line 62 of file InsertEbayOrders.java.
References openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.cleanup(), openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.initQuery(), and openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.makeTimestamp().
void openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 107 of file InsertEbayOrders.java.
References openDMS.model.sql.ConnectionManager.getConnection(), and openDMS.model.sql.ConnectionManager.instance().
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.execute().
Timestamp openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.makeTimestamp (String dateTime) throws ParseException private
turns the string passed in in yyyy-MM-dd HH:mm:ss.S format into a timestamp
Parameters
dateTime string in yyyy-MM-dd HH:mm:ss.S format
Returns
Timestamp
Exceptions
ParseException
Definition at line 96 of file InsertEbayOrders.java.
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.execute().
Member Data Documentation
Connection openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.connection_M = null private
reference to the JDBC Database connection
Definition at line 40 of file InsertEbayOrders.java.
String openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.query private
Initial value:
="INSERT IGNORE INTO ebay.ebay_orders (orderID, buyerID, salesRecNo, shippingType, createdTime)"
            + "VALUES (?,?,?,?,?);"
SQL query string
Definition at line 42 of file InsertEbayOrders.java.
PreparedStatement openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.statement_M = null private
reference to the JDBC Statement
Definition at line 38 of file InsertEbayOrders.java.
The documentation for this class was generated from the following file:
src/openDMS/model/sql/queries/concreteQueries/InsertEbayOrders.java