TomoBay: OutOfHoursTable Class Reference
OutOfHoursTable Class Reference
This class represents the out_of_hours table in the database implementation.
Static Public Attributes
static final AbstractField SALES_REC_NO = OrdersTable.SALES_REC_NO
the salesRecNo field in the out_of_hours table of the database, this is part of a composite primary key for the out_of_hours table and a foreign key for the ebay_orders table.
static final Date DATE = new Date()
the date field in the out_of_hours table of the database.
Private Member Functions
OutOfHoursTable ()
private ctor ensures this class is NEVER INSTANTIATED
Detailed Description
This class represents the out_of_hours table in the database implementation.
Author
Jan P.C. Hanson
Definition at line 26 of file OutOfHoursTable.java.
Constructor & Destructor Documentation
OutOfHoursTable () private
private ctor ensures this class is NEVER INSTANTIATED
Definition at line 53 of file OutOfHoursTable.java.
Member Data Documentation
final AbstractField SALES_REC_NO = OrdersTable.SALES_REC_NO static
the salesRecNo field in the out_of_hours table of the database, this is part of a composite primary key for the out_of_hours table and a foreign key for the ebay_orders table.
INTEGER(10)
Primary Key
Foreign Key ebay_orders table
See also
tomoBay.model.sql.schema.ordersTable.SalesRecNo
tomoBay.model.sql.schema.ordersTable.OrdersTable
Definition at line 38 of file OutOfHoursTable.java.
Referenced by OnRunning.execute(), and InsertOutOfHoursOrders.setParameters().
final Date DATE = new Date() static
the date field in the out_of_hours table of the database.
This is the second part of the composite primary key for this table.
DATE()
Primary Key
See also
tomoBay.model.sql.schema.outOfHoursTable.Date
Definition at line 48 of file OutOfHoursTable.java.
Referenced by OnRunning.execute(), OutOfHoursView.format(), SelectOutOfHoursOrders.format(), OutOfHoursPresenter.present(), InsertOutOfHoursOrders.setParameters(), and SelectOutOfHoursOrders.setParameters().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/schema/outOfHoursTable/OutOfHoursTable.java