TomoBay: MailServerSend Class Reference
MailServerSend Class Reference
This class represents a MailServer send connection, it allows the sending of email from a specific address and going through the MailServer specified by the builder used.
Public Member Functions
void send (Email email, String userID, String pwd) throws MessagingException
this method sends the given email using the userID and password provided in the arguments
Protected Member Functions
MailServerSend ()
default ctor
Protected Attributes
Properties mailServerProperties
the properties of the mail server
String transportProtocol
transport protocol used to send the mail
String serverIP_M
the gmail smtp server ip
Private Member Functions
MimeMessage generateMimeMessage (Email email) throws AddressException, MessagingException
generates a MimeMessage from the Email object
Session createMailServerSession ()
creates a mail server session.
Detailed Description
This class represents a MailServer send connection, it allows the sending of email from a specific address and going through the MailServer specified by the builder used.
This class is NOT to be directly instantiated but should be created using the EmailDirector.
Author
Jan P.C. Hanson
Definition at line 34 of file MailServerSend.java.
Constructor & Destructor Documentation
MailServerSend () protected
default ctor
Definition at line 46 of file MailServerSend.java.
Member Function Documentation
void send (Email email, String userID, String pwd) throws MessagingException
this method sends the given email using the userID and password provided in the arguments
Parameters
email The email object to send
userID the userId to send as
pwd the password associated with this userIS
Exceptions
MessagingException
Definition at line 59 of file MailServerSend.java.
References MailServerSend.createMailServerSession(), and MailServerSend.generateMimeMessage().
Referenced by EmailTest.main(), MailClient.send(), and EmailErrorsMailActions.send().
MimeMessage generateMimeMessage (Email email) throws AddressException, MessagingException private
generates a MimeMessage from the Email object
Parameters
email the Email to convert to a MimeMessage
Returns
MimeMessage that can be sent.
Exceptions
AddressException
MessagingException
Definition at line 79 of file MailServerSend.java.
References MailServerSend.createMailServerSession().
Referenced by MailServerSend.send().
Session createMailServerSession () private
creates a mail server session.
Definition at line 95 of file MailServerSend.java.
Referenced by MailServerSend.generateMimeMessage(), and MailServerSend.send().
Member Data Documentation
Properties mailServerProperties protected
the properties of the mail server
Definition at line 37 of file MailServerSend.java.
String transportProtocol protected
transport protocol used to send the mail
Definition at line 39 of file MailServerSend.java.
String serverIP_M protected
the gmail smtp server ip
Definition at line 41 of file MailServerSend.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/net/email/MailServerSend.java