TomoBay: ReScanErrorsDBActions Class Reference
ReScanErrorsDBActions Class Reference
This class encapsulates all the interactions that this class has with the database.
Public Member Functions
ReScanErrorsDBActions ()
default ctor
List< HeteroFieldContainer > retrieveAllErrorItems ()
returns a list of items from the database that contain errors in the 'notes' field of the ebay_items table.
void updateDBwithCorrectedInfo (ItemSpecifics item)
updates the database with corrected information, as provided in the ItemSpecifics passed in as an argument.
Detailed Description
This class encapsulates all the interactions that this class has with the database.
Author
Jan P.C. Hanson
Definition at line 30 of file ReScanErrorsDBActions.java.
Constructor & Destructor Documentation
ReScanErrorsDBActions ()
default ctor
Definition at line 35 of file ReScanErrorsDBActions.java.
Member Function Documentation
List<HeteroFieldContainer> retrieveAllErrorItems ()
returns a list of items from the database that contain errors in the 'notes' field of the ebay_items table.
Returns
List<String[]> where each
Definition at line 43 of file ReScanErrorsDBActions.java.
References SelectQueryInvoker.execute(), and SelectQueryInvoker.SelectQueryTypeNoParams.SELECT_EBAY_ITEMS_ERROR.
Referenced by OnRunning.execute().
void updateDBwithCorrectedInfo (ItemSpecifics item)
updates the database with corrected information, as provided in the ItemSpecifics passed in as an argument.
Parameters
item the ItemSpecifics containing the corrected information
Definition at line 51 of file ReScanErrorsDBActions.java.
References HeteroFieldContainer.add(), ItemsTable.BRAND, ModifyQueryInvoker.execute(), ItemSpecifics.get(), ItemSpecifics.getID(), ItemsTable.ITEM_ID, ItemsTable.NOTES, ItemsTable.PART_NO, and ModifyQueryInvoker.ModifyQueryTypeParams.UPDATE_ITEM_ERROR.
Referenced by OnRunning.execute().
The documentation for this class was generated from the following file:
src/tomoBay/model/services/reScanErrorsService/ReScanErrorsDBActions.java