My Project: openDMS.ebay.query.recievers.OrdersCall Class Reference
openDMS.ebay.query.recievers.OrdersCall Class Reference
Public Member Functions
OrdersCall (String usrToken, String server)
ApiOrderData call (ApiOrderData data, int numOfDays)
Additional Inherited Members
Protected Member Functions inherited from openDMS.ebay.query.recievers.AbstractAPIcall
AbstractAPIcall (String usrToken, String server)
Protected Attributes inherited from openDMS.ebay.query.recievers.AbstractAPIcall
String usrToken_M
String server_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 30 of file OrdersCall.java.
Constructor & Destructor Documentation
openDMS.ebay.query.recievers.OrdersCall.OrdersCall (String usrToken, String server)
constructor, calls superconstructor
Parameters
usrToken
server
Definition at line 42 of file OrdersCall.java.
References openDMS.ebay.query.data.APIcontext.apiContext(), and openDMS.ebay.query.data.APIcontext.instance().
Member Function Documentation
ApiOrderData openDMS.ebay.query.recievers.OrdersCall.call (ApiOrderData data, int numOfDays)
This method performs a call to the API grabbing a list of orders for the specified number of days.
Parameters
data an ApiOrderData object to populate with the orders
numOfDays
Returns
ApiOrderData, populated with the orders retrieved from the API call.
Definition at line 57 of file OrdersCall.java.
References openDMS.ebay.query.data.ApiOrderData.addData().
Referenced by openDMS.ebay.query.commands.GetOrderListCommand.execute().
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/recievers/OrdersCall.java