TomoBay: AbstractService Class Reference
AbstractService Class Reference abstract
Allows the system to only accept runnable's that implement this interface rather than all runnables.
Public Member Functions
String call () throws ServiceException
The individual services equivalent of main.
abstract< E > void setConfig (AbstractConfiguration< E > config)
sets the configuration for this service.
Protected Member Functions
abstract String onRunning () throws ServiceException
abstract String onPaused () throws ServiceException
abstract String onStopped () throws ServiceException
abstract String onError () throws ServiceException
Detailed Description
Allows the system to only accept runnable's that implement this interface rather than all runnables.
As well as providing an interface that all abstract service should conform to.
There are two varieties of AbstractService Derived Type: an unconfigured Service and a configured service. for an unconfigured service ignore the setConfig method as the service will ignore it anyway.
for a configured service it is necessary to provide an AbstractConfiguration object in order for it to work properly
Author
Jan P.C. Hanson
Definition at line 20 of file AbstractService.java.
Member Function Documentation
String call () throws ServiceException
The individual services equivalent of main.
Definition at line 25 of file AbstractService.java.
References ServerStatus.getStatus(), AbstractService.onError(), AbstractService.onPaused(), AbstractService.onRunning(), AbstractService.onStopped(), ServerStatus.RunLevel.PAUSED, ServerStatus.RunLevel.RUNNING, AbstractService.setConfig(), and ServerStatus.RunLevel.STOPPED.
abstract <E> void setConfig (AbstractConfiguration< E > config) abstract
sets the configuration for this service.
Not all services require configuration, see the documentation for individual services.
Parameters
config the AbstractConfiguration concrete object applicable to the concrete service.
Referenced by AbstractService.call(), and ServiceFactory.make().
abstract String onRunning () throws ServiceException abstract protected
Referenced by AbstractService.call().
abstract String onPaused () throws ServiceException abstract protected
Referenced by AbstractService.call().
abstract String onStopped () throws ServiceException abstract protected
Referenced by AbstractService.call().
abstract String onError () throws ServiceException abstract protected
Referenced by AbstractService.call().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/services/AbstractService.java