My Project: openDMS.model.sql.ConnectionManager Class Reference
openDMS.model.sql.ConnectionManager Class Reference
Public Member Functions
Connection getConnection () throws SQLException
Static Public Member Functions
static ConnectionManager instance ()
Private Member Functions
ConnectionManager ()
Private Attributes
ComboPooledDataSource cpds
Static Private Attributes
static ConnectionManager test = new ConnectionManager()
Detailed Description
This class provides access to a pool of database connections. It is a threadsafe singleton so always use the instance method to get an instance of this class, NEVER STORE THE INSTANCE.
Author
Jan P.C. Hanson
Definition at line 30 of file ConnectionManager.java.
Constructor & Destructor Documentation
openDMS.model.sql.ConnectionManager.ConnectionManager () private
singleton contstructor, initialises the connection pool
Definition at line 40 of file ConnectionManager.java.
References openDMS.helpers.ConfigReader.read().
Member Function Documentation
Connection openDMS.model.sql.ConnectionManager.getConnection () throws SQLException
retrieves a database connection from the pool of available connections. When Connection.close is called the connection is returned to the pool.
Returns
Exceptions
SQLException
Definition at line 71 of file ConnectionManager.java.
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.initQuery(), openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.initQuery(), openDMS.model.sql.queries.concreteQueries.InsertEbayItems.initQuery(), openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery(), openDMS.model.sql.queries.concreteQueries.SelectEbayItems.initQuery(), and openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.initQuery().
static ConnectionManager openDMS.model.sql.ConnectionManager.instance () static
instance method returns an instance of the ConnectionManager class
Returns
ConnectionManager instance
Definition at line 62 of file ConnectionManager.java.
References openDMS.model.sql.ConnectionManager.test.
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.initQuery(), openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.initQuery(), openDMS.model.sql.queries.concreteQueries.InsertEbayItems.initQuery(), openDMS.model.sql.queries.concreteQueries.SelectEbayOrders.initQuery(), openDMS.model.sql.queries.concreteQueries.SelectEbayItems.initQuery(), and openDMS.model.sql.queries.concreteQueries.InsertEbayOrders.initQuery().
Member Data Documentation
ComboPooledDataSource openDMS.model.sql.ConnectionManager.cpds private
C3P0 Data pool
Definition at line 35 of file ConnectionManager.java.
ConnectionManager openDMS.model.sql.ConnectionManager.test = new ConnectionManager() static private
Singleton instance with eager instanciation
Definition at line 33 of file ConnectionManager.java.
Referenced by openDMS.model.sql.ConnectionManager.instance().
The documentation for this class was generated from the following file:
src/openDMS/model/sql/ConnectionManager.java