TomoBay: TriggerService Class Reference
TriggerService Class Reference
This object defines a way of triggering services upon request, it contains a threadpool which is not user customiseable.
Public Member Functions
TriggerService ()
constructor, default
Static Public Member Functions
static Future< String > start (AbstractService service)
tries to start a particular service, if there arn't enough threads available it will be placed in a BlockingQueue until there is a free thread.
static boolean shutdown (int firstInterval, int secondInterval) throws InterruptedException
tries to gracefully shutdown until the number of seconds in the first timeout has elapsed.
Static Private Attributes
static final int INITIALTHREADS = 2
the number of core threads
static final int MAXTHREADS = 10
the maximum number of threads
static final BlockingQueue< Runnable > THREADPOOL = new ArrayBlockingQueue<Runnable>(MAXTHREADS)
thread pool thread queue
static final ThreadPoolExecutor THREADPOOLEXECUTOR
the thread pool executor
Detailed Description
This object defines a way of triggering services upon request, it contains a threadpool which is not user customiseable.
The default number of threads in the threadpool is 10, should this value need altering it will have to be done within the code.
Author
Jan P.C. Hanson
Definition at line 44 of file TriggerService.java.
Constructor & Destructor Documentation
TriggerService ()
constructor, default
Definition at line 60 of file TriggerService.java.
Member Function Documentation
static Future<String> start (AbstractService service) static
tries to start a particular service, if there arn't enough threads available it will be placed in a BlockingQueue until there is a free thread.
Parameters
service the service to be started.
Definition at line 70 of file TriggerService.java.
References TriggerService.THREADPOOLEXECUTOR.
Referenced by ReScanListing.execute(), ReScanBuyer.execute(), IndividualItemRefreshServiceTest.main(), CheckErrorsServiceTest.main(), BasicEbayServiceTest.main(), ReScanErrorsServiceTest.main(), and EmailErrorsServiceTest.main().
static boolean shutdown (int firstInterval, int secondInterval) throws InterruptedException static
tries to gracefully shutdown until the number of seconds in the first timeout has elapsed.
if this fails it then waits until the second timeout has elapsed and tries an immediate shutdown. if both of these fail this method will return false
Parameters
firstInterval the number of seconds to allow the threadpool to shutdown gracefully
secondInterval the number of seconds after the first timeout to allow before shutting down aggressively.
Returns
false if fails to shutdown, true if threadpool shuts down.
Exceptions
InterruptedException
Definition at line 87 of file TriggerService.java.
References TriggerService.THREADPOOL, and TriggerService.THREADPOOLEXECUTOR.
Member Data Documentation
final int INITIALTHREADS = 2 static private
the number of core threads
Definition at line 47 of file TriggerService.java.
final int MAXTHREADS = 10 static private
the maximum number of threads
Definition at line 49 of file TriggerService.java.
final BlockingQueue<Runnable> THREADPOOL = new ArrayBlockingQueue<Runnable>(MAXTHREADS) static private
thread pool thread queue
Definition at line 52 of file TriggerService.java.
Referenced by TriggerService.shutdown().
final ThreadPoolExecutor THREADPOOLEXECUTOR static private
Initial value:
= new ThreadPoolExecutor
    (INITIALTHREADS,MAXTHREADS,0l,TimeUnit.MILLISECONDS,THREADPOOL)
the thread pool executor
Definition at line 54 of file TriggerService.java.
Referenced by TriggerService.shutdown(), and TriggerService.start().
The documentation for this class was generated from the following file:
src/tomoBay/model/services/TriggerService.java