TomoBay: ComponentPrice Class Reference
ComponentPrice Class Reference
This class provices functionality to provide pricing information on a compound item, i.e.
Public Member Functions
ComponentPrice ()
default ctor
Static Public Member Functions
static final int[] prices (int[] childQuantities, int[] childCosts, int parentPrice)
This method returns an array of integers representing the prices of the individual child items.
static final double[] prices (int[] childQuantities, double[] childCosts, double parentPrice)
This method returns an array of doubles representing the prices of the individual child items.
Static Private Member Functions
static final boolean isValid (int[] childQuantities, int[] childCosts)
this method checks to make sure that the input arrays match up as if they do not then the calculations will not make sense
static final boolean isValid (int[] childQuantities, double[] childCosts)
this method checks to make sure that the input arrays match up as if they do not then the calculations will not make sense
Detailed Description
This class provices functionality to provide pricing information on a compound item, i.e.
a parent item that is made of smaller composite items.
Author
Jan P.C. Hanson
Definition at line 25 of file ComponentPrice.java.
Constructor & Destructor Documentation
ComponentPrice ()
default ctor
Definition at line 31 of file ComponentPrice.java.
Member Function Documentation
static final int [] prices (int[] childQuantities, int[] childCosts, int parentPrice) static
This method returns an array of integers representing the prices of the individual child items.
VAT is not taken into account. the array returned will be the same size as the costs array as it assumes that you want the 1st element of the returned array to represent the individual price of the item represented by the first element of the costs array.
Parameters
childQuantities the quantities of the items (in units)
childCosts the cost values of the child items (in pennies)
parentPrice the cost of the parent item
Returns
int[] an integer array representing the prices of the items based on the cost array.
Definition at line 44 of file ComponentPrice.java.
References ComponentPrice.isValid().
Referenced by ComponentPrice.prices().
static final double [] prices (int[] childQuantities, double[] childCosts, double parentPrice) static
This method returns an array of doubles representing the prices of the individual child items.
VAT is not taken into account. the array returned will be the same size as the costs array as it assumes that you want the 1st element of the returned array to represent the individual price of the item represented by the first element of the costs array.
Parameters
childQuantities the quantities of the items (in units)
childCosts the cost values of the child items (in pounds)
parentPrice the cost of the parent item
Returns
int[] an integer array representing the prices of the items based on the cost array.
Definition at line 75 of file ComponentPrice.java.
References ComponentPrice.isValid(), and ComponentPrice.prices().
static final boolean isValid (int[] childQuantities, int[] childCosts) static private
this method checks to make sure that the input arrays match up as if they do not then the calculations will not make sense
Parameters
childQuantities
childCosts
Returns
true if valid, false otherwise
Definition at line 100 of file ComponentPrice.java.
Referenced by ComponentPrice.prices().
static final boolean isValid (int[] childQuantities, double[] childCosts) static private
this method checks to make sure that the input arrays match up as if they do not then the calculations will not make sense
Parameters
childQuantities
childCosts
Returns
true if valid, false otherwise
Definition at line 110 of file ComponentPrice.java.
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/dataTypes/financial/ComponentPrice.java