My Project: openDMS.helpers.viewPresenterFactory.ViewPresenterFactory Class Reference
openDMS.helpers.viewPresenterFactory.ViewPresenterFactory Class Reference
Classes
enum Select
Public Member Functions
AbstractViewPresenterFactory getFactory (String factory)
boolean hasFactory (String factory)
Static Public Member Functions
static ViewPresenterFactory instance ()
Private Member Functions
ViewPresenterFactory ()
void populateMap ()
Static Private Attributes
static final ViewPresenterFactory instance_M = new ViewPresenterFactory()
Detailed Description
Author
Jan P.C. Hanson
Definition at line 24 of file ViewPresenterFactory.java.
Constructor & Destructor Documentation
openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.ViewPresenterFactory () private
default constructor
Definition at line 36 of file ViewPresenterFactory.java.
References openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.populateMap().
Member Function Documentation
AbstractViewPresenterFactory openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.getFactory (String factory)
creates a specific factory based on the string provided.
Parameters
factory string that is compared to enum values.
Returns
AbstractViewPresenterFactory a concrete viewPresenterFactory
Definition at line 55 of file ViewPresenterFactory.java.
Referenced by openDMS.view.UIServlet.doGet().
boolean openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.hasFactory (String factory)
check to see if a factory type exists by comparing the string provided to the internal enum 'Select'
Parameters
factory the string to compare to the internal enum
Returns
boolean true if the factory is a valid type, false otherwise.
Definition at line 64 of file ViewPresenterFactory.java.
Referenced by openDMS.view.UIServlet.doGet().
static ViewPresenterFactory openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.instance () static
singleton instance method, returns an instance of this object.
Returns
ViewPresenterFactory the singleton instance.
Definition at line 47 of file ViewPresenterFactory.java.
References openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.instance_M.
Referenced by openDMS.view.UIServlet.doGet().
void openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.populateMap () private
populate the internal map with viewPresenterFactories.
Definition at line 74 of file ViewPresenterFactory.java.
References openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.Select.EBAY, and openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.Select.ROOT.
Referenced by openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.ViewPresenterFactory().
Member Data Documentation
final ViewPresenterFactory openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.instance_M = new ViewPresenterFactory() static private
Singleton instance variable
Definition at line 27 of file ViewPresenterFactory.java.
Referenced by openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.instance().
The documentation for this class was generated from the following file:
src/openDMS/helpers/viewPresenterFactory/ViewPresenterFactory.java