TomoBay: PrintInvoiceResponse Class Reference
PrintInvoiceResponse Class Reference
Public Member Functions
PrintInvoiceResponse ()
default ctor
ResultCodes isSuccess () throws NotAValidResultCodeException
method of descerning whether the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse has been successful.
void setSentBytes (byte[] sentBytes)
used by the AbstractWinswtock command associated with this response to insert the raw byte values that were sent by the associated command to winstock.
void setResponseBytes (byte[] responseBytes)
used by the AbstractWinstockCommand associated with this response to insert the raw byte values into this object for processing.
String[] getRecieved ()
method used to retrieve the results of the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse.
String getSent ()
method used to retrieve the data sent to the socket.
Private Attributes
byte[] responseBytes_M
internal storage for the raw byte[] that comes back as a response from the socket
byte[] sentBytes_M
internal storage for the raw byte[] that gets sent to the winstock socket.
Detailed Description
Author
Jan P.C. Hanson
Definition at line 23 of file PrintInvoiceResponse.java.
Constructor & Destructor Documentation
PrintInvoiceResponse ()
default ctor
Definition at line 34 of file PrintInvoiceResponse.java.
Member Function Documentation
ResultCodes isSuccess () throws NotAValidResultCodeException
method of descerning whether the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse has been successful.
Returns
boolean true if successful false otherwise.
Implements AbstractWinstockCommandResponse.
Definition at line 41 of file PrintInvoiceResponse.java.
References ResultCodes.forValue().
void setSentBytes (byte[] sentBytes)
used by the AbstractWinswtock command associated with this response to insert the raw byte values that were sent by the associated command to winstock.
Parameters
sentBytes the bytes sent to the winstock socket.
Implements AbstractWinstockCommandResponse.
Definition at line 49 of file PrintInvoiceResponse.java.
Referenced by PrintInvoiceCommand.execute().
void setResponseBytes (byte[] responseBytes)
used by the AbstractWinstockCommand associated with this response to insert the raw byte values into this object for processing.
Not really of any use to the user.
Parameters
responseBytes
Implements AbstractWinstockCommandResponse.
Definition at line 56 of file PrintInvoiceResponse.java.
Referenced by PrintInvoiceCommand.execute().
String [] getRecieved ()
method used to retrieve the results of the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse.
Returns
String the data of the query
Implements AbstractWinstockCommandResponse.
Definition at line 64 of file PrintInvoiceResponse.java.
String getSent ()
method used to retrieve the data sent to the socket.
Returns
String representing the data sent to the socket
Implements AbstractWinstockCommandResponse.
Definition at line 77 of file PrintInvoiceResponse.java.
Member Data Documentation
byte [] responseBytes_M private
internal storage for the raw byte[] that comes back as a response from the socket
Definition at line 26 of file PrintInvoiceResponse.java.
byte [] sentBytes_M private
internal storage for the raw byte[] that gets sent to the winstock socket.
Definition at line 29 of file PrintInvoiceResponse.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/response/PrintInvoiceResponse.java