TomoBay: AbstractSelectParamsQuery Class Reference
AbstractSelectParamsQuery Class Reference abstract
This class defines the abstract base for all Select queries that take parameters.
Public Member Functions
AbstractSelectParamsQuery ()
default ctor
List< HeteroFieldContainer > execute (HeteroFieldContainer parameters) throws SQLException
executes the query using the parameters passed in to populate the query with the relevant information
Public Member Functions inherited from AbstractSelectQuery
AbstractSelectQuery ()
default ctor
Public Member Functions inherited from AbstractDBQuery
PreparedStatement statement ()
get the statement object associated with this query
Protected Member Functions
abstract void setParameters (HeteroFieldContainer parameter) throws ClassCastException, SQLException
Used by derived classes to set the parameters for this particular query.
Protected Member Functions inherited from AbstractSelectQuery
abstract List< HeteroFieldContainer > format (ResultSet resultSet) throws SQLException
the results from a select query come in the form of a ResultSet object, this needs to be closed before the connection can be closed, however once the Resultset is closed it is impossible to get any data from it, so before it is closed the data needs transferring to a DBFieldContainer object.
Protected Member Functions inherited from AbstractDBQuery
abstract String queryString ()
Used by derived classes to define the Query string to be used in the query.
void cleanup () throws SQLException
commits the transaction and does cleanup after the query has been executed
Private Member Functions
void initQuery (String query) throws SQLException
initialise the connection and statement and set transaction variables.
Additional Inherited Members
Protected Attributes inherited from AbstractDBQuery
PreparedStatement statement_M = null
reference to the JDBC Statement
Connection connection_M = null
reference to the JDBC Database connection
Detailed Description
This class defines the abstract base for all Select queries that take parameters.
Author
Jan P.C. Hanson
Definition at line 27 of file AbstractSelectParamsQuery.java.
Constructor & Destructor Documentation
AbstractSelectParamsQuery ()
default ctor
Definition at line 33 of file AbstractSelectParamsQuery.java.
Member Function Documentation
List<HeteroFieldContainer> execute (HeteroFieldContainer parameters) throws SQLException
executes the query using the parameters passed in to populate the query with the relevant information
Parameters
parameters the parameters required by the specific derived query class.
Returns
List<HeteroFieldContainer> containing a list of records from the database where each record is encapsulated as a HeteroFieldContainer with the fields specific to the derived query.
Definition at line 43 of file AbstractSelectParamsQuery.java.
References AbstractDBQuery.cleanup(), AbstractSelectQuery.format(), AbstractSelectParamsQuery.initQuery(), AbstractDBQuery.queryString(), AbstractSelectParamsQuery.setParameters(), and AbstractDBQuery.statement_M.
abstract void setParameters (HeteroFieldContainer parameter) throws ClassCastException, SQLException abstract protected
Used by derived classes to set the parameters for this particular query.
Exceptions
SQLException
ClassCastException
Referenced by AbstractSelectParamsQuery.execute().
void initQuery (String query) throws SQLException private
initialise the connection and statement and set transaction variables.
Parameters
query String containing the sql query
Exceptions
SQLException
Definition at line 67 of file AbstractSelectParamsQuery.java.
References AbstractDBQuery.connection_M, ConnectionManager.getConnection(), ConnectionManager.instance(), and AbstractDBQuery.statement_M.
Referenced by AbstractSelectParamsQuery.execute().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/sql/framework/queryTypes/select/AbstractSelectParamsQuery.java