TomoBay: ServiceFactory Class Reference
ServiceFactory Class Reference
This factory is responsible for creating services which can be passed to the TriggerService or ServicesScheduler objects.
Classes
enum ConfiguredServiceType
enum ServiceType
defensive enum to limit the inputs to the make method
Static Public Member Functions
static AbstractService make (ServiceType service)
make the service requested using an ServiceType enum value
static AbstractService make (ConfiguredServiceType service, AbstractConfiguration<?> config)
make a configured service using the AbstractConfiguration provided
Static Private Attributes
static final Map< ServiceType, AbstractServiceFactory > serviceFactoryMap
internal map holds service factories
static final Map< ConfiguredServiceType, AbstractServiceFactory > configuredServiceFactoryMap
Detailed Description
This factory is responsible for creating services which can be passed to the TriggerService or ServicesScheduler objects.
The types of object that can be created are defined by the internal enum.
Author
Jan P.C. Hanson
Definition at line 38 of file ServiceFactory.java.
Member Function Documentation
static AbstractService make (ServiceType service) static
make the service requested using an ServiceType enum value
Parameters
service the service requested
Returns
AbstractService as requested.
Definition at line 75 of file ServiceFactory.java.
References ServiceFactory.serviceFactoryMap.
Referenced by ReScanListing.execute(), ReScanBuyer.execute(), IndividualItemRefreshServiceTest.main(), MAIN.main(), CheckErrorsServiceTest.main(), BasicEbayServiceTest.main(), ReScanErrorsServiceTest.main(), and EmailErrorsServiceTest.main().
static AbstractService make (ConfiguredServiceType service, AbstractConfiguration<?> config) static
make a configured service using the AbstractConfiguration provided
Parameters
service the service to make only ServiceType enum constants are valid
config the AbstractConfiguration appropriate to the Service being made
Returns
AbstractService, configured as requested.
Definition at line 84 of file ServiceFactory.java.
References ServiceFactory.configuredServiceFactoryMap, and AbstractService.setConfig().
Member Data Documentation
final Map<ServiceType, AbstractServiceFactory> serviceFactoryMap static private
Initial value:
= new THashMap<ServiceType, AbstractServiceFactory>()
    {{
        put(ServiceType.EBAY_SERVICE, new BasicEbayServiceFactory());
        put(ServiceType.TEST_SERVICE, new TestServiceFactory());
        put(ServiceType.CHECK_ERRORS, new CheckErrorsFactory());
        put(ServiceType.RESCAN_ERRORS_SERVICE, new ReScanErrorsServiceFactory());
        put(ServiceType.OUT_OF_HOURS_SERVICE, new OutOfHoursServiceFactory());
    }}
internal map holds service factories
Definition at line 52 of file ServiceFactory.java.
Referenced by ServiceFactory.make().
final Map<ConfiguredServiceType, AbstractServiceFactory> configuredServiceFactoryMap static private
Initial value:
= new THashMap<ConfiguredServiceType, AbstractServiceFactory>()
    {{
        put(ConfiguredServiceType.INDVIDUAL_ITEM_REFRESH_SERVICE, new IndividualItemRefreshServiceFactory());
        put(ConfiguredServiceType.EMAIL_ERRORS_SERVICE, new EmailErrorsServiceFactory());
        put(ConfiguredServiceType.RE_SCAN_BUYER_SERVICE, new ReScanBuyerServiceFactory());
    }}
Definition at line 63 of file ServiceFactory.java.
Referenced by ServiceFactory.make().
The documentation for this class was generated from the following file:
src/tomoBay/model/services/ServiceFactory.java