TomoBay: AbstractLineItem Class Reference
AbstractLineItem Class Reference abstract
Copyright(C) 2015 Jan P.C.
Public Member Functions
AbstractLineItem (AbstractSalesDayBookLine line, int transactionNo, int partIndex)
create an AbstractLineItem using the parameters provided
void adjustPrice (AbstractSalesDayBookLine invoice, int pennyAdjustment)
add or subtract the given amount of pennies from this line item
int quantity (AbstractSalesDayBookLine invoice)
retrieve the invoiced quantity of the part to be invoiced in this line item
String description (AbstractSalesDayBookLine invoice)
retrieve the description of the invoiced part
String partNo (AbstractSalesDayBookLine invoice)
retrieve the part number associated with the part that has been invoiced
int price ()
retrieve the price of the quantity of parts invoiced (EX VAT)
Protected Member Functions
abstract int unitPrice (AbstractSalesDayBookLine line)
implementation specific code used to work out the unit price for a specific line item
Protected Attributes
final int partIndex
the index of the part(within a transaction) that this lineItem corresponds to
final int transactionIndex_M
this index represents the transaction number that this lineItem corresponds to
Private Attributes
int price_M
the sale price (EX VAT) of this line item
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jan P.C. Hanson
Definition at line 23 of file AbstractLineItem.java.
Constructor & Destructor Documentation
AbstractLineItem (AbstractSalesDayBookLine line, int transactionNo, int partIndex)
create an AbstractLineItem using the parameters provided
Parameters
line The AbstractSalesDayBookLine that this lineItem belongs to.
transactionNo the transactionNo associated with this lineItem.
partIndex the index of the part (within the order listing) that is associated with this line item.
Definition at line 39 of file AbstractLineItem.java.
References AbstractLineItem.partIndex, and AbstractLineItem.unitPrice().
Member Function Documentation
void adjustPrice (AbstractSalesDayBookLine invoice, int pennyAdjustment)
add or subtract the given amount of pennies from this line item
Parameters
invoice the AbstractSalesDayBookLine that this AbstractLineItem is contained in.
pennyAdjustment (+ve) values for positive adjustment (-ve) values for negative adjustment.
Definition at line 52 of file AbstractLineItem.java.
Referenced by PriceAdjustment.performAdjustement().
int quantity (AbstractSalesDayBookLine invoice)
retrieve the invoiced quantity of the part to be invoiced in this line item
Returns
int representing the quantity
Definition at line 59 of file AbstractLineItem.java.
References Transaction.listing(), AbstractSalesDayBookLine.orderInfo(), Listing.qty(), Transaction.qtyPurchased(), and Order.transaction().
Referenced by PriceAdjustment.calculateTotal(), and OrderInfo.transactionInfo().
String description (AbstractSalesDayBookLine invoice)
retrieve the description of the invoiced part
Returns
String containing a description of the line item
Definition at line 71 of file AbstractLineItem.java.
References Part.description(), Transaction.listing(), AbstractSalesDayBookLine.orderInfo(), Listing.part(), and Order.transaction().
Referenced by OrderInfo.transactionInfo().
String partNo (AbstractSalesDayBookLine invoice)
retrieve the part number associated with the part that has been invoiced
Returns
String containing the part number for this line item
Definition at line 78 of file AbstractLineItem.java.
References Transaction.listing(), AbstractSalesDayBookLine.orderInfo(), Listing.part(), Part.partNo(), and Order.transaction().
Referenced by PriceAdjustment.calculateTotal(), and OrderInfo.transactionInfo().
int price ()
retrieve the price of the quantity of parts invoiced (EX VAT)
Returns
String containing the price of the line item
Definition at line 85 of file AbstractLineItem.java.
References AbstractLineItem.price_M, and AbstractLineItem.unitPrice().
Referenced by PriceAdjustment.calculateTotal(), PriceAdjustment.convertListToArray(), PriceAdjustment.performAdjustement(), and OrderInfo.transactionInfo().
abstract int unitPrice (AbstractSalesDayBookLine line) abstract protected
implementation specific code used to work out the unit price for a specific line item
Returns
int representing the unit price(in pennies) of this line item.
Referenced by AbstractLineItem.AbstractLineItem(), and AbstractLineItem.price().
Member Data Documentation
final int partIndex protected
the index of the part(within a transaction) that this lineItem corresponds to
Definition at line 26 of file AbstractLineItem.java.
Referenced by AbstractLineItem.AbstractLineItem().
final int transactionIndex_M protected
this index represents the transaction number that this lineItem corresponds to
Definition at line 28 of file AbstractLineItem.java.
int price_M private
the sale price (EX VAT) of this line item
Definition at line 30 of file AbstractLineItem.java.
Referenced by AbstractLineItem.price().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/financial/SalesOrderDayBook/AbstractLineItem.java