TomoBay: SalesOrderView Class Reference
SalesOrderView Class Reference
This class is responsible for formatting the data passed to it by the SalesOrderPresenter and providing a string that can be displayed by the AJAX requestor.
Public Member Functions
SalesOrderView ()
default ctor.
String format (List< HeteroFieldContainer > input)
this method is responsible for formatting the data as required for the specific derived view
Private Member Functions
String pickeability (int invoiced)
defines a set of set of String values that equate to the 'invoiced' values grabbed from the database.
String replaceLast (String string, String target, String replacement)
replace the last instance of a particular character in a string with another.
Detailed Description
This class is responsible for formatting the data passed to it by the SalesOrderPresenter and providing a string that can be displayed by the AJAX requestor.
The data is formatted as a 6 column html table with the column headings: type=checkbox class=chckbl, 'Name' class=name, 'Date' class=date, 'shippingType' class=shippingType, 'Details' class=details contains button, 'Status' class=status.
Author
Jan P.C. Hanson
Definition at line 34 of file SalesOrderView.java.
Constructor & Destructor Documentation
SalesOrderView ()
default ctor.
Definition at line 39 of file SalesOrderView.java.
Member Function Documentation
String format (List< HeteroFieldContainer > input)
this method is responsible for formatting the data as required for the specific derived view
Parameters
input a List<String[]> containing the data to be formatted.
Returns
String that can be output to the AJAX requester.
Implements AbstractView.
Definition at line 46 of file SalesOrderView.java.
References OrdersTable.ACCOUNT, OrdersTable.BUYERID, OrdersTable.CREATED_TIME, ClassRef.INTEGER, OrdersTable.INVOICED, EbayAccounts.name(), OrdersTable.ORDER_ID, SalesOrderView.pickeability(), SalesOrderView.replaceLast(), OrdersTable.SALES_REC_NO, OrdersTable.SHIPPING_TYPE, ClassRef.STRING, and ClassRef.TIMESTAMP.
String pickeability (int invoiced) private
defines a set of set of String values that equate to the 'invoiced' values grabbed from the database.
Parameters
invoiced int between 0 and 3 grabbed from the database: 0='Pickeable', 1='Partially pickable', 2='Unpickeable', 3='ERROR'.
Returns
one of the above string values Pickeable/Partial/Unpickeable/ERROR.
Definition at line 79 of file SalesOrderView.java.
References OrderStatusContext.get(), ServerStatus.getStatus(), and ServerStatus.RunLevel.RUNNING.
Referenced by SalesOrderView.format().
String replaceLast (String string, String target, String replacement) private
replace the last instance of a particular character in a string with another.
Parameters
string the string to analyse
target the String whose last instance is replaced by target
replacement the String to replace the last instance of target with.
Returns
String with the last instance of target replaced by replacement.
Definition at line 95 of file SalesOrderView.java.
Referenced by SalesOrderView.format().
The documentation for this class was generated from the following file:
src/tomoBay/view/views/salesOrderView/SalesOrderView.java