TomoBay: OrderInfo Class Reference
OrderInfo Class Reference
This presenter action takes an orderID string in its execute(String data) method, and returns nicely formatted JSON that can then be passed back to the requestor.
Public Member Functions
OrderInfo ()
Default CTOR.
String execute (String data)
performs the action specified
Private Member Functions
String formatResults (AbstractSalesDayBookLine input)
assembles the various parts of the order and outputs it as a fully formed JSON string.
String summaryInfo (AbstractSalesDayBookLine input)
formats the summary information for this Order
String buyerInfo (Buyer buyer)
formats the buyer information associated with this order
String transactionInfo (AbstractSalesDayBookLine invoice)
formats the transaction information associated with this order
String shippingInfo (AbstractSalesDayBookLine invoice)
formats the shipping information associated with this order
Detailed Description
This presenter action takes an orderID string in its execute(String data) method, and returns nicely formatted JSON that can then be passed back to the requestor.
Author
Jan P.C. Hanson
Definition at line 37 of file OrderInfo.java.
Constructor & Destructor Documentation
OrderInfo ()
Default CTOR.
Definition at line 43 of file OrderInfo.java.
Member Function Documentation
String execute (String data)
performs the action specified
Returns
String representing the results of the performed action.
Implements AbstractPresenterAction.
Definition at line 50 of file OrderInfo.java.
References JSONentity.addPreFormatted(), OrderInfo.formatResults(), SalesDayBookLineFactory.SalesDayBookLineType.INVOICE, SalesDayBookLineFactory.make(), and JSONentity.toString().
String formatResults (AbstractSalesDayBookLine input) private
assembles the various parts of the order and outputs it as a fully formed JSON string.
Parameters
input the AbstractSalesDayBookLine to format as JSON.
Returns
JSON formatted String.
Definition at line 65 of file OrderInfo.java.
References JSONentity.addPreFormatted(), Order.buyer(), OrderInfo.buyerInfo(), AbstractSalesDayBookLine.orderInfo(), OrderInfo.shippingInfo(), OrderInfo.summaryInfo(), JSONentity.toString(), and OrderInfo.transactionInfo().
Referenced by OrderInfo.execute().
String summaryInfo (AbstractSalesDayBookLine input) private
formats the summary information for this Order
Parameters
input the AbstractSalesDayBookLine that summary info needs to be extracted from.
Returns
JSON formatted string representing the summary information
Definition at line 80 of file OrderInfo.java.
References Order.account(), JSONentity.addLeaf(), Order.createdTime(), VAT.due(), AbstractSalesDayBookLine.invoiceNumber(), Order.orderID(), AbstractSalesDayBookLine.orderInfo(), Order.salesRecNo(), Order.shippingType(), VAT.subtract(), GBP.toPennies(), GBP.toString(), and Order.totalPrice().
Referenced by OrderInfo.formatResults().
String buyerInfo (Buyer buyer) private
formats the buyer information associated with this order
Parameters
buyer Buyer object associated with this order
Returns
JSON formatted string containing the buyer information
Definition at line 99 of file OrderInfo.java.
References JSONentity.addLeaf(), Buyer.buyerID(), Buyer.city(), Buyer.county(), Buyer.email(), Buyer.name(), Buyer.phoneNo(), Buyer.postcode(), Buyer.street1(), and Buyer.street2().
Referenced by OrderInfo.formatResults().
String transactionInfo (AbstractSalesDayBookLine invoice) private
formats the transaction information associated with this order
Parameters
invoice The AbstractSalesDayBookLine that transaction info needs to be extracted from
Returns
JSON formatted String containing the transaction information
Definition at line 118 of file OrderInfo.java.
References JSONentity.addBranch(), JSONentity.addLeaf(), Part.brand(), Part.cost(), AbstractLineItem.description(), GBP.fromPennies(), AbstractSalesDayBookLine.getLineItem(), SaneInput.json(), Transaction.listing(), Listing.listingID(), Listing.noOfParts(), Order.noOfTransactions(), AbstractSalesDayBookLine.orderInfo(), Listing.part(), AbstractLineItem.partNo(), Listing.partNos(), AbstractLineItem.price(), Transaction.qtyPurchased(), AbstractLineItem.quantity(), Transaction.shippingCost(), VAT.subtract(), Listing.title(), GBP.toString(), JSONentity.toString(), Order.transaction(), and Transaction.transactionPrice().
Referenced by OrderInfo.formatResults().
String shippingInfo (AbstractSalesDayBookLine invoice) private
formats the shipping information associated with this order
Parameters
invoice the AbstractSalesDayBookLine containing the shipping information to be extracted
Returns
JSON formatted String containing the shipping information.
Definition at line 178 of file OrderInfo.java.
References JSONentity.addLeaf(), Order.buyer(), GBP.fromPennies(), AbstractSalesDayBookLine.getLineItem(), AbstractSalesDayBookLine.orderInfo(), Order.shippingCost(), AbstractSalesDayBookLine.size(), Buyer.street2(), and JSONentity.toString().
Referenced by OrderInfo.formatResults().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/presenters/presenterActions/concreteActions/OrderInfo.java