My Project: openDMS.model.sql.queries.QueryInvoker Class Reference
openDMS.model.sql.queries.QueryInvoker Class Reference
Classes
enum QueryType
Static Public Member Functions
static AbstractDBQuery make (QueryType query)
static List< String[]> execute (QueryType query, String[] parameters) throws SQLException
Static Private Attributes
static final Map< QueryType, AbstractQueryFactory > factoryMap_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 36 of file QueryInvoker.java.
Member Function Documentation
static List<String[]> openDMS.model.sql.queries.QueryInvoker.execute (QueryType query, String[] parameters) throws SQLException static
execute a requested query
Parameters
query one of the enum values provided by QueryType enum.
parameters String[] of parameters specific to the query you are using, see individual query docs.
Returns
List<String[]>
Exceptions
SQLException
Definition at line 76 of file QueryInvoker.java.
References openDMS.model.sql.queries.AbstractDBQuery.execute(), and openDMS.model.sql.queries.QueryInvoker.make().
Referenced by openDMS.presenters.ebay.EbayPresenter.doStuff(), openDMS.model.services.basicEbayUpdate.TransactionsTable.populate(), openDMS.model.services.basicEbayUpdate.OrdersTable.populate(), openDMS.model.services.basicEbayUpdate.BuyersTable.populate(), and openDMS.model.services.basicEbayUpdate.ItemsTable.populate().
static AbstractDBQuery openDMS.model.sql.queries.QueryInvoker.make (QueryType query) static
make the requested data base query.
Parameters
query
Returns
Definition at line 65 of file QueryInvoker.java.
References openDMS.model.sql.queries.QueryInvoker.factoryMap_M.
Referenced by openDMS.model.sql.queries.QueryInvoker.execute().
Member Data Documentation
final Map<QueryType, AbstractQueryFactory> openDMS.model.sql.queries.QueryInvoker.factoryMap_M static private
Initial value:
= new HashMap<QueryType, AbstractQueryFactory>()
        {{
            put(QueryType.INSERT_EBAY_BUYERS, new InsertEbayBuyersFactory());
            put(QueryType.INSERT_EBAY_ITEMS, new InsertEbayItemsFactory());
            put(QueryType.INSERT_EBAY_ORDERS, new InsertEbayOrdersFactory());
            put(QueryType.INSERT_EBAY_TRANSACTIONS, new InsertEbayTransactionsFactory());
            put(QueryType.SELECT_EBAY_ITEMS, new SelectEbayItemsFactory());
            put(QueryType.SELECT_EBAY_ORDERS, new SelectEbayOrdersFactory());
            put(QueryType.SELECT_ITEMS_WITH_BLANK_FIELDS, new SelectItemsWithBlankFieldsFactory());
            put(QueryType.UPDATE_ITEM_BRAND_AND_PARTNO, new UpdateItemBrandAndPartNoFactory());
        }}
internal map holds factory objects created static final to make threadsafe
Definition at line 48 of file QueryInvoker.java.
Referenced by openDMS.model.sql.queries.QueryInvoker.make().
The documentation for this class was generated from the following file:
src/openDMS/model/sql/queries/QueryInvoker.java