TomoBay: HeteroFieldContainer Class Reference
HeteroFieldContainer Class Reference
This class represents a container of AbstractField types and a value associated with this field.
Public Member Functions
HeteroFieldContainer ()
default ctor, initialises the HeteroFieldContainer
void clear ()
clear this heterogenous field type
int size ()
retrieves the size of this HeteroFieldContainer
void finalize () throws Throwable
dtor
Package Functions
public< T > void add (AbstractField field, T value) throws ClassCastException
add an arbitrary value to this Field container with the stipulation that this value is of the same type as the AbstractField passed in as an argument.
public< T > T get (AbstractField field, Class< T > classRef) throws ClassCastException
retrieve the the value of an AbstractField from this HeteroFieldContainer, the field should be of the same type as the type field.
Static Private Member Functions
static< T > boolean isSameType (AbstractField field, Class< T > classDef) throws ClassCastException
performs a type check, assuming that field and type are of the same type then this method returns true, otherwise it will throw an exception.
Private Attributes
Map< String, Map< AbstractField, Object > > fieldMap_M
internal storage representation for a DBFieldContainer
Detailed Description
This class represents a container of AbstractField types and a value associated with this field.
If you REALLY need to store heterogenous types in a container then this class may be useful, but CONSIDER ALL OTHER OPTIONS FIRST.
See also
tomoBay.model.dataTypes.heteroTypeContainer
Author
Jan P.C. Hanson
Definition at line 30 of file HeteroFieldContainer.java.
Constructor & Destructor Documentation
HeteroFieldContainer ()
default ctor, initialises the HeteroFieldContainer
Definition at line 38 of file HeteroFieldContainer.java.
Member Function Documentation
public<T> void add (AbstractField field, T value) throws ClassCastException package
add an arbitrary value to this Field container with the stipulation that this value is of the same type as the AbstractField passed in as an argument.
If the field already exists within the HeteroFieldContainer then the new value will replace the existing one.
Parameters
field AbstractField to add
value the value of the AbstractField to add
Exceptions
ClassCastException due to mismatched types
Definition at line 49 of file HeteroFieldContainer.java.
References HeteroFieldContainer.isSameType().
Referenced by Buyer.Buyer(), ItemStockLevel.check(), AbstractModifyQueryNoParams.execute(), MarkAsInvoiced.execute(), MarkAsUninvoiced.execute(), OnRunning.execute(), SelectEbayBuyers.format(), SelectEbayItemsError.format(), SelectUncalculatedOrders.format(), SelectEbayItems.format(), SelectEbayOrders.format(), SelectAccounts.format(), SelectInvoicedOrders.format(), SelectUninvoicedOrders.format(), SelectEbayItemsNotInTransactions.format(), SelectUninvoicedOrdersNoErrors.format(), SelectEbayOrderByBuyer.format(), SelectUncalculatedInvoices.format(), SelectTransactionByOrder.format(), SelectEbayTransactionByID.format(), SelectBrandByInv.format(), SelectBrandAndPartNoByOrderID.format(), SelectEbayOrderByID.format(), SelectEbayItemSpecific.format(), SelectOutOfHoursOrders.format(), SelectEbayBuyer.format(), SelectEbayOrderHistoryLastNDays.format(), SelectBuyerByAccAndSRN.format(), SelectFullOrderLine.format(), Buyers_Table.getAddress(), OnRunning.getAddress(), Buyers_Table.getGSPaddress(), OnRunning.getGSPaddress(), DBActions.getLatestOrderID(), Listing.getListingInfo(), Order.getOrderInfo(), BuyerDetails.getRawData(), Transaction.getTransactionInfo(), Order.getTransactionList(), GenerateRoyalMailCSV.grabAndProcessDBData(), StockReOrderAnalysis.grabDBdata(), RePopulateEbayItem.populate(), Transactions_Table.populate(), ItemsAndPartsTable.populate(), Orders_Table.populate(), Orders_Table.populateGSP(), OutOfHoursPresenter.present(), InvoiceOrders.updateDB(), ReScanErrorsDBActions.updateDBwithCorrectedInfo(), and OnRunning.updateItemNote().
public<T> T get (AbstractField field, Class< T > classRef) throws ClassCastException package
retrieve the the value of an AbstractField from this HeteroFieldContainer, the field should be of the same type as the type field.
Parameters
field AbstractField to retrieve the value of
classRef the type of the field you wish to retrieve
Returns
T the value of the AbstractDBField of Type type.
Exceptions
ClassCastException due to mismatched types
Definition at line 71 of file HeteroFieldContainer.java.
References HeteroFieldContainer.isSameType().
Referenced by Order.account(), Listing.brand(), Buyer.buyerID(), Buyer.city(), Buyer.county(), Order.createdTime(), Buyer.email(), MarkAsUninvoiced.execute(), MarkAsInvoiced.execute(), OnRunning.execute(), Order.invoiceNo(), Listing.Listing(), Listing.listingID(), Buyer.name(), Order.Order(), Order.orderID(), Listing.partNos(), Buyer.phoneNo(), Buyer.postcode(), Transaction.qtyPurchased(), Order.salesRecNo(), QueryUtility.setBIGINTParam(), QueryUtility.setBYTEParam(), QueryUtility.setDATEParam(), QueryUtility.setDOUBLEParam(), QueryUtility.setFLOATParam(), QueryUtility.setINTEGERParam(), QueryUtility.setTIMESTAMPParam(), QueryUtility.setTINYINTParam(), QueryUtility.setVARCHARParam(), Transaction.shippingCost(), Order.shippingType(), Buyer.street1(), Buyer.street2(), Listing.title(), Order.totalPrice(), Transaction.Transaction(), Transaction.transactionPrice(), and OnRunning.updateItemNote().
void clear ()
clear this heterogenous field type
Definition at line 84 of file HeteroFieldContainer.java.
References HeteroFieldContainer.fieldMap_M.
Referenced by HeteroFieldContainer.finalize(), and GenerateRoyalMailCSV.grabAndProcessDBData().
int size ()
retrieves the size of this HeteroFieldContainer
Returns
int representing the number of fields contained within.
Definition at line 90 of file HeteroFieldContainer.java.
References HeteroFieldContainer.fieldMap_M.
Referenced by Buyer.Buyer().
void finalize () throws Throwable
dtor
Exceptions
Throwable
Definition at line 102 of file HeteroFieldContainer.java.
References HeteroFieldContainer.clear(), and HeteroFieldContainer.fieldMap_M.
static <T> boolean isSameType (AbstractField field, Class< T > classDef) throws ClassCastException static private
performs a type check, assuming that field and type are of the same type then this method returns true, otherwise it will throw an exception.
Parameters
field the AbstractField that you wish to check
classDef the type that this AbstractField should reference
Returns
true if both field and type represent the same type otherwise throws Exception
Exceptions
ClassCastException due to mismatched types
Definition at line 112 of file HeteroFieldContainer.java.
Referenced by HeteroFieldContainer.add(), and HeteroFieldContainer.get().
Member Data Documentation
Map<String, Map<AbstractField, Object> > fieldMap_M private
internal storage representation for a DBFieldContainer
Definition at line 33 of file HeteroFieldContainer.java.
Referenced by HeteroFieldContainer.clear(), HeteroFieldContainer.finalize(), and HeteroFieldContainer.size().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/heteroTypeContainer/HeteroFieldContainer.java