TomoBay: TypeDef Class Reference
TypeDef Class Reference
This class contains only definitions for database types, to be used in conjunction with a derived AbstractDBField type.
Static Public Attributes
static final String STRING = TypeDef.nameOf(ClassRef.STRING)
a String
static final String INTEGER = TypeDef.nameOf(ClassRef.INTEGER)
an Integer
static final String DOUBLE = TypeDef.nameOf(ClassRef.INTEGER)
a Double
static final String FLOAT = TypeDef.nameOf(ClassRef.FLOAT)
a Float
static final String LONG = TypeDef.nameOf(ClassRef.LONG)
a Long
static final String TIMESTAMP = TypeDef.nameOf(ClassRef.TIMESTAMP)
a java.sql.Timestamp
static final String BYTE = TypeDef.nameOf(ClassRef.BYTE)
a Byte
static final String DATE = TypeDef.nameOf(ClassRef.DATE)
a java.util.Date
static final String BOOLEAN = TypeDef.nameOf(ClassRef.BOOLEAN)
a Boolean
Static Private Member Functions
static final String nameOf (Class<?> clazz)
helper method, converts a class object to its name
Detailed Description
This class contains only definitions for database types, to be used in conjunction with a derived AbstractDBField type.
Author
Jan P.C. Hanson
Definition at line 26 of file TypeDef.java.
Member Function Documentation
static final String nameOf (Class<?> clazz) static private
helper method, converts a class object to its name
Parameters
clazz the class to find the name of
Returns
String representing the name of the class
Definition at line 52 of file TypeDef.java.
Member Data Documentation
final String STRING = TypeDef.nameOf(ClassRef.STRING) static
a String
Definition at line 29 of file TypeDef.java.
Referenced by Name.type(), ServerAddr.type(), Street.type(), County.type(), City.type(), ApiKey.type(), Condition.type(), Email.type(), Phone.type(), Postcode.type(), AccountName.type(), ShippingType.type(), Title.type(), OrderID.type(), BuyerID.type(), Brand.type(), Notes.type(), and PartNo.type().
final String INTEGER = TypeDef.nameOf(ClassRef.INTEGER) static
an Integer
Definition at line 31 of file TypeDef.java.
Referenced by Quantity.type(), SalesRecNo.type(), ResultCode.type(), CustomIntegerField.type(), LookbackDays.type(), Invoiced.type(), and Id.type().
final String DOUBLE = TypeDef.nameOf(ClassRef.INTEGER) static
a Double
Definition at line 33 of file TypeDef.java.
final String FLOAT = TypeDef.nameOf(ClassRef.FLOAT) static
a Float
Definition at line 35 of file TypeDef.java.
Referenced by OrderTotal.type(), ShippingCost.type(), and Price.type().
final String LONG = TypeDef.nameOf(ClassRef.LONG) static
a Long
Definition at line 37 of file TypeDef.java.
Referenced by TransactionID.type(), and ItemID.type().
final String TIMESTAMP = TypeDef.nameOf(ClassRef.TIMESTAMP) static
a java.sql.Timestamp
Definition at line 39 of file TypeDef.java.
Referenced by CreatedTime.type().
final String BYTE = TypeDef.nameOf(ClassRef.BYTE) static
a Byte
Definition at line 41 of file TypeDef.java.
final String DATE = TypeDef.nameOf(ClassRef.DATE) static
a java.util.Date
Definition at line 43 of file TypeDef.java.
Referenced by Date.type().
final String BOOLEAN = TypeDef.nameOf(ClassRef.BOOLEAN) static
a Boolean
Definition at line 45 of file TypeDef.java.
Referenced by Packing.type(), Shipping.type(), and Picking.type().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/heteroTypeContainer/TypeDef.java