My Project: openDMS.ebay.query.data.ApiCallData Class Reference
openDMS.ebay.query.data.ApiCallData Class Reference
Classes
enum Data_Type
Public Member Functions
ApiCallData (String usrToken, String server)
void addOrderData (ApiOrderData orders)
void addItemData (ApiItemData item)
void addTransactionData (ApiTransactionData transaction)
ApiOrderData accessOrderData ()
ApiItemData accessItemData ()
ApiTransactionData accessTransactionData ()
String getUserToken ()
String getServerString ()
Private Attributes
ApiOrderData orderData_M
ApiItemData itemData_M
ApiTransactionData transactionData_M
String userToken_M
String server_M
Detailed Description
Copyright(C) 2015 Jan P.C. Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jan P.C. Hanson
Definition at line 23 of file ApiCallData.java.
Constructor & Destructor Documentation
openDMS.ebay.query.data.ApiCallData.ApiCallData (String usrToken, String server)
Definition at line 38 of file ApiCallData.java.
Member Function Documentation
ApiItemData openDMS.ebay.query.data.ApiCallData.accessItemData ()
get the item data object stored in this object
Returns
ApiItemData
Definition at line 79 of file ApiCallData.java.
References openDMS.ebay.query.data.ApiCallData.itemData_M.
Referenced by openDMS.ebay.query.commands.GetItemCommand.execute().
ApiOrderData openDMS.ebay.query.data.ApiCallData.accessOrderData ()
get the order data object stored in this object
Returns
ApiOrderData
Definition at line 72 of file ApiCallData.java.
References openDMS.ebay.query.data.ApiCallData.orderData_M.
Referenced by openDMS.ebay.query.commands.GetOrderListCommand.execute().
ApiTransactionData openDMS.ebay.query.data.ApiCallData.accessTransactionData ()
get the transaction data object stored in this object
Returns
ApiTransactionData
Definition at line 86 of file ApiCallData.java.
References openDMS.ebay.query.data.ApiCallData.transactionData_M.
Referenced by openDMS.ebay.query.commands.GetTransactionListCommand.execute(), and openDMS.ebay.query.commands.GetTransactionListCommand.printResults().
void openDMS.ebay.query.data.ApiCallData.addItemData (ApiItemData item)
set the item data object to be stored in the ApiCallData
Parameters
item the data object to add
Definition at line 58 of file ApiCallData.java.
void openDMS.ebay.query.data.ApiCallData.addOrderData (ApiOrderData orders)
set the order data object to be stored in the ApiCallData
Parameters
orders the data object to add
Definition at line 51 of file ApiCallData.java.
void openDMS.ebay.query.data.ApiCallData.addTransactionData (ApiTransactionData transaction)
set the transaction data object to be stored in the ApiCallData
Parameters
transaction
Definition at line 65 of file ApiCallData.java.
String openDMS.ebay.query.data.ApiCallData.getServerString ()
retrieve the value of the server string
Returns
String representing the server to call to.
Definition at line 100 of file ApiCallData.java.
References openDMS.ebay.query.data.ApiCallData.server_M.
String openDMS.ebay.query.data.ApiCallData.getUserToken ()
retrieve the value for the user token.
Returns
String representing user token.
Definition at line 93 of file ApiCallData.java.
References openDMS.ebay.query.data.ApiCallData.userToken_M.
Member Data Documentation
ApiItemData openDMS.ebay.query.data.ApiCallData.itemData_M private
holder for item data
Definition at line 30 of file ApiCallData.java.
Referenced by openDMS.ebay.query.data.ApiCallData.accessItemData().
ApiOrderData openDMS.ebay.query.data.ApiCallData.orderData_M private
holder for order data
Definition at line 28 of file ApiCallData.java.
Referenced by openDMS.ebay.query.data.ApiCallData.accessOrderData().
String openDMS.ebay.query.data.ApiCallData.server_M private
holder for server string
Definition at line 36 of file ApiCallData.java.
Referenced by openDMS.ebay.query.data.ApiCallData.getServerString().
ApiTransactionData openDMS.ebay.query.data.ApiCallData.transactionData_M private
holder for transaction data
Definition at line 32 of file ApiCallData.java.
Referenced by openDMS.ebay.query.data.ApiCallData.accessTransactionData().
String openDMS.ebay.query.data.ApiCallData.userToken_M private
holder for User token
Definition at line 34 of file ApiCallData.java.
Referenced by openDMS.ebay.query.data.ApiCallData.getUserToken().
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/data/ApiCallData.java