TomoBay: Orders_Table Class Reference
Orders_Table Class Reference
updates the database orders table with information taken from the ebay api orders call.
Public Member Functions
Orders_Table ()
default ctor
Static Public Member Functions
static void populate (OrderType[] orders, int accountID) throws SQLException
populates the Orders Table in the database with data grabbed from the ebay API
static void populateGSP (OrderType order, int accountID, HeteroFieldContainer insertVals)
Detailed Description
updates the database orders table with information taken from the ebay api orders call.
Author
Jan P.C. Hanson
Definition at line 49 of file Orders_Table.java.
Constructor & Destructor Documentation
Orders_Table ()
default ctor
Definition at line 54 of file Orders_Table.java.
Member Function Documentation
static void populate (OrderType[] orders, int accountID) throws SQLException static
populates the Orders Table in the database with data grabbed from the ebay API
Parameters
accountID The accountId representing the account whose orders to search for.
orders list of orders.
Exceptions
SQLException
Definition at line 63 of file Orders_Table.java.
References OrdersTable.ACCOUNT, HeteroFieldContainer.add(), OrdersTable.BUYERID, OrdersTable.CREATED_TIME, ModifyQueryInvoker.execute(), ModifyQueryInvoker.ModifyQueryTypeParams.INSERT_EBAY_ORDERS, EbayOrderCancellationStatus.isCancelled(), OrdersTable.ORDER_ID, OrdersTable.ORDER_TOTAL, Orders_Table.populateGSP(), OrdersTable.SALES_REC_NO, and OrdersTable.SHIPPING_TYPE.
Referenced by OnRunning.execute().
static void populateGSP (OrderType order, int accountID, HeteroFieldContainer insertVals) static
Parameters
order
accountID
insertVals
Definition at line 95 of file Orders_Table.java.
References OrdersTable.ACCOUNT, HeteroFieldContainer.add(), OrdersTable.BUYERID, OrdersTable.CREATED_TIME, OrdersTable.ORDER_ID, OrdersTable.ORDER_TOTAL, OrdersTable.SALES_REC_NO, and OrdersTable.SHIPPING_TYPE.
Referenced by Orders_Table.populate().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/services/basicEbayUpdateService/Orders_Table.java