TomoBay: AbstractSalesDayBookLine Class Reference
AbstractSalesDayBookLine Class Reference abstract
This class represents an Abstract sales day book entry, i.e.
Public Member Functions
AbstractSalesDayBookLine (Order order)
CONSTRUCTOR, creates a SalesDayBookLine based on the Order passed in as a parameter.
AbstractLineItem getLineItem (int index)
retrieve a particular AbstractLineItem from the list of items that make up this AbstractSalesDayBookLine
int size ()
retrieve the number of line items that make up this SalesDayBookLine.
Order orderInfo ()
retrieve the order that this AbstractSalesDayBookLine refers to.
String createdDate ()
Retrieve the timestamp at which this object was created.
int totalIncVat ()
retrieve the total (including VAT) price of this order
int totalExVat ()
retrieve the total (excluding VAT) price for this order
int invoiceNumber ()
returns the invoice number of this invoice, if it exists.
DualList< String, PayloadType > format (AbstractFormat format)
converts this invoice into the format requested
Iterator< AbstractLineItem > iterator ()
iterator method makes this class iterable i.e.
Protected Member Functions
abstract List< AbstractLineItem > generateLineItems ()
Implementation specific code for the generation of AbstractLineItems from the data found in the Order that this object refers to.
Private Member Functions
void adjustPrices ()
Private Attributes
final Order order_M
the order that this SalesDayBookLine applies to
final List< AbstractLineItem > lineItems_M
the list of lineItems that make up this SalesDayBookLine
final String createdTime_M = CheckTime.currentTimeStamp()
the date and time this object was instantiated
Detailed Description
This class represents an Abstract sales day book entry, i.e.
either a credit note or an invoice and provides functionality to create these entries.
Author
Jan P.C. Hanson
Definition at line 33 of file AbstractSalesDayBookLine.java.
Constructor & Destructor Documentation
AbstractSalesDayBookLine (Order order)
CONSTRUCTOR, creates a SalesDayBookLine based on the Order passed in as a parameter.
Parameters
order
Definition at line 46 of file AbstractSalesDayBookLine.java.
References AbstractSalesDayBookLine.adjustPrices(), and AbstractSalesDayBookLine.generateLineItems().
Member Function Documentation
AbstractLineItem getLineItem (int index)
retrieve a particular AbstractLineItem from the list of items that make up this AbstractSalesDayBookLine
Parameters
index the index pointing to the LineItem to retrieve
Returns
AbstractLineItem containing the data that it represents.
Definition at line 60 of file AbstractSalesDayBookLine.java.
Referenced by PriceAdjustment.calculateTotal(), PriceAdjustment.convertListToArray(), PriceAdjustment.noOfItems(), PriceAdjustment.performAdjustement(), OrderInfo.shippingInfo(), and OrderInfo.transactionInfo().
int size ()
retrieve the number of line items that make up this SalesDayBookLine.
Returns
int representing the number of AbstractLineItems.
Definition at line 67 of file AbstractSalesDayBookLine.java.
Referenced by PriceAdjustment.calculateTotal(), WinstockFormat.format(), PriceAdjustment.noOfItems(), and OrderInfo.shippingInfo().
Order orderInfo ()
retrieve the order that this AbstractSalesDayBookLine refers to.
Returns
Order containing all information on the order this object refers to.
Definition at line 73 of file AbstractSalesDayBookLine.java.
References AbstractSalesDayBookLine.order_M.
Referenced by AbstractLineItem.description(), PrintInvoices.execute(), InvoiceOrders.execute(), WinstockFormat.format(), InvoiceOrders.formatMailResult(), OrderInfo.formatResults(), AbstractSalesDayBookLine.invoiceNumber(), AbstractLineItem.partNo(), AbstractLineItem.quantity(), OrderInfo.shippingInfo(), OrderInfo.summaryInfo(), OrderInfo.transactionInfo(), GSPInvoiceLine.unitPrice(), StandardInvoiceLine.unitPrice(), and StandardInvoiceShippingLine.unitPrice().
String createdDate ()
Retrieve the timestamp at which this object was created.
Returns
String representing the timestamp in yyyy-mm-dd hh:mm:ss format
Definition at line 79 of file AbstractSalesDayBookLine.java.
References AbstractSalesDayBookLine.createdTime_M.
int totalIncVat ()
retrieve the total (including VAT) price of this order
Returns
int representing the price (including VAT)
Definition at line 85 of file AbstractSalesDayBookLine.java.
References GBP.toPennies(), and Order.totalPrice().
Referenced by PriceAdjustment.fitness(), and AbstractSalesDayBookLine.totalExVat().
int totalExVat ()
retrieve the total (excluding VAT) price for this order
Returns
int representing the price (excluding vat)
Definition at line 91 of file AbstractSalesDayBookLine.java.
References VAT.subtract(), and AbstractSalesDayBookLine.totalIncVat().
int invoiceNumber ()
returns the invoice number of this invoice, if it exists.
Returns
int representing the invoice number. If this invoice has not yet been processed then this method will return 0 as no invoice number has yet been generated.
Definition at line 98 of file AbstractSalesDayBookLine.java.
References Order.invoiceNo(), and AbstractSalesDayBookLine.orderInfo().
Referenced by PrintInvoices.execute(), InvoiceOrders.execute(), PrintInvoices.print(), and OrderInfo.summaryInfo().
DualList<String,PayloadType> format (AbstractFormat format)
converts this invoice into the format requested
Parameters
format the format to convert this invoice to
Returns
DualList<String
Definition at line 106 of file AbstractSalesDayBookLine.java.
References AbstractFormat.format().
Referenced by InvoiceOrders.formatAsDualList().
Iterator<AbstractLineItem> iterator ()
iterator method makes this class iterable i.e.
it is possible to loop over all AbstractLineItems contained within this AbstractSalesDayBookLine
Returns
Iterator to a list of AbstractLineItem(s)
Definition at line 114 of file AbstractSalesDayBookLine.java.
References AbstractSalesDayBookLine.generateLineItems().
abstract List<AbstractLineItem> generateLineItems () abstract protected
Implementation specific code for the generation of AbstractLineItems from the data found in the Order that this object refers to.
Returns
List<AbstractLineItems> the list of line items that make up this SalesDayBookLine.
Referenced by AbstractSalesDayBookLine.AbstractSalesDayBookLine(), and AbstractSalesDayBookLine.iterator().
void adjustPrices () private
Definition at line 127 of file AbstractSalesDayBookLine.java.
References PriceAdjustment.adjust().
Referenced by AbstractSalesDayBookLine.AbstractSalesDayBookLine().
Member Data Documentation
final Order order_M private
the order that this SalesDayBookLine applies to
Definition at line 36 of file AbstractSalesDayBookLine.java.
Referenced by AbstractSalesDayBookLine.orderInfo().
final List<AbstractLineItem> lineItems_M private
the list of lineItems that make up this SalesDayBookLine
Definition at line 38 of file AbstractSalesDayBookLine.java.
final String createdTime_M = CheckTime.currentTimeStamp() private
the date and time this object was instantiated
Definition at line 40 of file AbstractSalesDayBookLine.java.
Referenced by AbstractSalesDayBookLine.createdDate().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/financial/SalesOrderDayBook/AbstractSalesDayBookLine.java