TomoBay: MarkAsUninvoiced Class Reference
MarkAsUninvoiced Class Reference
Public Member Functions
MarkAsUninvoiced ()
default ctor
String execute (String data)
performs the action specified
Detailed Description
Author
Jan P.C. Hanson
Definition at line 32 of file MarkAsUninvoiced.java.
Constructor & Destructor Documentation
MarkAsUninvoiced ()
default ctor
Definition at line 37 of file MarkAsUninvoiced.java.
Member Function Documentation
String execute (String data)
performs the action specified
Returns
String representing the results of the performed action.
Implements AbstractPresenterAction.
Definition at line 44 of file MarkAsUninvoiced.java.
References OrdersTable.ACCOUNT, HeteroFieldContainer.add(), ModifyQueryInvoker.execute(), HeteroFieldContainer.get(), EbayAccounts.id(), ClassRef.INTEGER, OrdersTable.INVOICED, NonDBFields.RESULT_CODE, OrdersTable.SALES_REC_NO, and ModifyQueryInvoker.ModifyQueryTypeParams.UPDATE_INVOICE_STATUS_SRN.
The documentation for this class was generated from the following file:
src/tomoBay/presenters/presenterActions/concreteActions/MarkAsUninvoiced.java