TomoBay: JSONentity Class Reference
JSONentity Class Reference abstract
This class acts as the abstract base for all derived JSON classes.
Public Member Functions
JSONentity ()
default ctor
JSONentity addPreFormatted (String key, String value)
add pre-formatted text to this derived JSON entity
JSONentity addLeaf (String key, String value)
A leaf node is simply a key value pair.
JSONentity addBranch (String key, JSONentity value)
JSONentity clear ()
void finalize () throws Throwable
abstract String toString ()
Protected Attributes
DualList< String, String > children_M
Detailed Description
This class acts as the abstract base for all derived JSON classes.
Author
Jan P.C. Hanson
Definition at line 24 of file JSONentity.java.
Constructor & Destructor Documentation
JSONentity ()
default ctor
Definition at line 31 of file JSONentity.java.
Member Function Documentation
JSONentity addPreFormatted (String key, String value)
add pre-formatted text to this derived JSON entity
Parameters
key String representing the key for a key value pair containing the preformatted text. If this parameter is null or empty then the pre-formatted text will be added without a key.
value The pre-formatted text to add.
Returns
JSONentity allowing the user to chain these class methods to create larger JSON formatted strings.
Definition at line 45 of file JSONentity.java.
References DualList< V1, V2 >.put().
Referenced by OrderInfo.execute(), and OrderInfo.formatResults().
JSONentity addLeaf (String key, String value)
A leaf node is simply a key value pair.
Parameters
key the string key
value the string value
Returns
Definition at line 58 of file JSONentity.java.
References DualList< V1, V2 >.put().
Referenced by OrderInfo.buyerInfo(), BuyerDetails.execute(), BuyerList.formatResults(), OrderInfo.shippingInfo(), OrderInfo.summaryInfo(), and OrderInfo.transactionInfo().
JSONentity addBranch (String key, JSONentity value)
Parameters
key
value
Definition at line 70 of file JSONentity.java.
References DualList< V1, V2 >.put(), and JSONentity.toString().
Referenced by BuyerList.execute(), and OrderInfo.transactionInfo().
JSONentity clear ()
Returns
Definition at line 81 of file JSONentity.java.
References DualList< V1, V2 >.clear().
void finalize () throws Throwable
Definition at line 84 of file JSONentity.java.
References DualList< V1, V2 >.clear(), and JSONentity.toString().
abstract String toString () abstract
Referenced by JSONentity.addBranch(), BuyerDetails.execute(), BuyerList.execute(), OrderInfo.execute(), JSONentity.finalize(), OrderInfo.formatResults(), BuyerList.formatResults(), OrderInfo.shippingInfo(), and OrderInfo.transactionInfo().
Member Data Documentation
DualList<String, String> children_M protected
Definition at line 26 of file JSONentity.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/json/JSONentity.java