TomoBay: SalesDayBookLineFactory Class Reference
SalesDayBookLineFactory Class Reference
Classes
enum SalesDayBookLineType
enum SalesDayBookLineType_M
Public Member Functions
SalesDayBookLineFactory ()
default ctor
Static Public Member Functions
static AbstractSalesDayBookLine make (SalesDayBookLineType type, Order order)
create the requested AbstractSalesDayBookLine.
Static Private Attributes
static final Map< SalesDayBookLineType_M, AbstractSalesDayBookLineFactory > lineMap_M
maps the type string to an action
Detailed Description
Author
Jan P.C. Hanson
Definition at line 30 of file SalesDayBookLineFactory.java.
Constructor & Destructor Documentation
SalesDayBookLineFactory ()
default ctor
Definition at line 49 of file SalesDayBookLineFactory.java.
Member Function Documentation
static AbstractSalesDayBookLine make (SalesDayBookLineType type, Order order) static
create the requested AbstractSalesDayBookLine.
Parameters
type the type of AbstractSalesDayBookLine that you wish to create
order The order that this AbstractSalesDayBookLine should be associated with.
Returns
Definition at line 58 of file SalesDayBookLineFactory.java.
References Order.buyer(), SalesDayBookLineFactory.SalesDayBookLineType_M.GSP_INVOICE, SalesDayBookLineFactory.lineMap_M, AbstractSalesDayBookLineFactory.make(), Order.shippingCost(), SalesDayBookLineFactory.SalesDayBookLineType_M.STANDARD_INVOICE, SalesDayBookLineFactory.SalesDayBookLineType_M.STANDARD_INVOICE_WITH_SHIPPING, and Buyer.street2().
Referenced by OrderInfo.execute(), PrintInvoices.execute(), and InvoiceOrders.execute().
Member Data Documentation
final Map<SalesDayBookLineType_M, AbstractSalesDayBookLineFactory> lineMap_M static private
Initial value:
= new HashMap<SalesDayBookLineType_M, AbstractSalesDayBookLineFactory>()
        {{
            put(SalesDayBookLineType_M.STANDARD_INVOICE, new StandardInvoiceFactory());
            put(SalesDayBookLineType_M.STANDARD_INVOICE_WITH_SHIPPING, new StandardInvoiceWithShippingFactory());
            put(SalesDayBookLineType_M.GSP_INVOICE, new GSPInvoiceFactory());
        }}
maps the type string to an action
Definition at line 39 of file SalesDayBookLineFactory.java.
Referenced by SalesDayBookLineFactory.make().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/financial/SalesOrderDayBook/SalesDayBookLineFactory.java