TomoBay: ItemsAndPartsTable Class Reference
ItemsAndPartsTable Class Reference
updates the items table with the information gleaned from a specific ebay item call.
Public Member Functions
ItemsAndPartsTable ()
default ctor
Static Public Member Functions
static void populate (String apiKey, String server, int accID, OrderType[] orders) throws ApiException, SdkException, Exception
populates the Orders Table in the database with data grabbed from the ebay API
Static Private Member Functions
static Map< String, String > getSpecifics (ItemType item)
static void populatePartsTable (ItemType itemType, Map< String, String > specifics)
Detailed Description
updates the items table with the information gleaned from a specific ebay item call.
Author
Jan P.C. Hanson
Definition at line 40 of file ItemsAndPartsTable.java.
Constructor & Destructor Documentation
ItemsAndPartsTable ()
default ctor
Definition at line 45 of file ItemsAndPartsTable.java.
Member Function Documentation
static void populate (String apiKey, String server, int accID, OrderType[] orders) throws ApiException, SdkException, Exception static
populates the Orders Table in the database with data grabbed from the ebay API
Parameters
apiKey the apiKey to use when performing eBay API calls
server the eBay server to make API calls to
accID the accountID referencing the account that is to be queried
orders the OrderType[] to find items for
Exceptions
ApiException
SdkException
Exception
Definition at line 58 of file ItemsAndPartsTable.java.
References ItemsTable.ACCOUNT, HeteroFieldContainer.add(), ItemsTable.BRAND, ItemCall.call(), ItemsTable.CONDITION, ModifyQueryInvoker.execute(), SelectQueryInvoker.execute(), ItemsAndPartsTable.getSpecifics(), ModifyQueryInvoker.ModifyQueryTypeParams.INSERT_EBAY_ITEMS, ItemsTable.ITEM_ID, ClassRef.LONG, ItemsTable.PART_NO, ItemsAndPartsTable.populatePartsTable(), SelectQueryInvoker.SelectQueryTypeNoParams.SELECT_EBAY_ITEMS_NOT_IN_TRANSACTIONS, and ItemsTable.TITLE.
Referenced by OnRunning.execute().
static Map<String, String> getSpecifics (ItemType item) static private
Parameters
item
Returns
Definition at line 87 of file ItemsAndPartsTable.java.
Referenced by ItemsAndPartsTable.populate().
static void populatePartsTable (ItemType itemType, Map< String, String > specifics) static private
Definition at line 111 of file ItemsAndPartsTable.java.
Referenced by ItemsAndPartsTable.populate().
The documentation for this class was generated from the following file:
src/tomoBay/model/services/basicEbayUpdateService/ItemsAndPartsTable.java