TomoBay: SelectQueryInvoker Class Reference
SelectQueryInvoker Class Reference
This object is responsible for providing the user with SelectQuery objects as specified by the internal enum, which defines all possible Select queries that can be executed on the database.
Classes
enum SelectQueryTypeNoParams
Defensive enum defines the acceptable inputs to the factory.
enum SelectQueryTypeParams
Defensive enum defines the acceptable inputs to the factory.
Static Public Member Functions
static List< HeteroFieldContainer > execute (SelectQueryTypeNoParams query)
execute a requested query
static List< HeteroFieldContainer > execute (SelectQueryTypeParams query, HeteroFieldContainer parameters)
executes the requested query (one that requires parameters)
Static Private Attributes
static final Map< SelectQueryTypeNoParams, AbstractSelectNoParamsQueryFactory > noParamsMap_M
internal map holds factory objects created static final to make threadsafe
static final Map< SelectQueryTypeParams, AbstractSelectParamsQueryFactory > paramsMap_M
Detailed Description
This object is responsible for providing the user with SelectQuery objects as specified by the internal enum, which defines all possible Select queries that can be executed on the database.
These Select query objects can either be created using the make() method or directly executed using the execute() method.
acceptable input values for those methods is defined in QueryType.
Author
Jan P.C. Hanson
Definition at line 59 of file SelectQueryInvoker.java.
Member Function Documentation
static List<HeteroFieldContainer> execute (SelectQueryTypeNoParams query) static
execute a requested query
Parameters
query one of the enum values provided by noParamsMap_M enum.
Returns
List<HeteroFieldContainer> where each element in the list corresponds to a database record, and each record (HeteroFieldContainer) contains the fields specific to the query that was called (see individual query documentation)
Definition at line 153 of file SelectQueryInvoker.java.
References SelectQueryInvoker.noParamsMap_M.
Referenced by Buyer.Buyer(), ItemStockLevel.check(), OnRunning.execute(), ErrorsList.generateErrorList(), DBActions.getLatestOrderID(), Listing.getListingInfo(), Order.getOrderInfo(), BuyerList.getRawData(), BuyerDetails.getRawData(), Transaction.getTransactionInfo(), Order.getTransactionList(), GenerateRoyalMailCSV.grabAndProcessDBData(), ItemsAndPartsTable.populate(), SalesHistoryPresenter.present(), OutOfHoursPresenter.present(), SalesOrderPresenter.present(), EbayAccounts.refresh(), and ReScanErrorsDBActions.retrieveAllErrorItems().
static List<HeteroFieldContainer> execute (SelectQueryTypeParams query, HeteroFieldContainer parameters) static
executes the requested query (one that requires parameters)
Parameters
query one of the enum constants contained in the paramsMap_M Enum
parameters HeteroFiledContainer containing the fields and values that are required for the individual query (see individual query documentation)
Returns
List<HeteroFieldContainer> where each element in the list corresponds to a database record, and each record (HeteroFieldContainer) contains the fields specific to the query that was called (see individual query documentation)
Definition at line 175 of file SelectQueryInvoker.java.
References SelectQueryInvoker.paramsMap_M.
Member Data Documentation
final Map<SelectQueryTypeNoParams, AbstractSelectNoParamsQueryFactory> noParamsMap_M static private
Initial value:
= new THashMap<SelectQueryTypeNoParams, AbstractSelectNoParamsQueryFactory>()
        {{
            put(SelectQueryTypeNoParams.SELECT_EBAY_ITEMS_NOT_IN_TRANSACTIONS, new SelectEbayItemsNotInTransactionsFactory());
            put(SelectQueryTypeNoParams.SELECT_EBAY_ORDERS, new SelectEbayOrdersFactory());
            put(SelectQueryTypeNoParams.SELECT_EBAY_ITEMS, new SelectEbayItemsFactory());
            put(SelectQueryTypeNoParams.SELECT_UNINVOICED_ORDERS, new SelectUninvoicedOrdersFactory());
            put(SelectQueryTypeNoParams.SELECT_UNINVOICED_ORDERS_NO_ERRORS, new SelectUninvoicedOrdersNoErrorsFactory());
            put(SelectQueryTypeNoParams.SELECT_EBAY_ITEMS_ERROR, new SelectEbayItemsErrorFactory());
            put(SelectQueryTypeNoParams.SELECT_INVOICED_ORDERS, new SelectInvoicedOrdersFactory());
            put(SelectQueryTypeNoParams.SELECT_UNCALCULATED_INVOICES, new SelectUncalculatedInvoicesFactory());
            put(SelectQueryTypeNoParams.SELECT_UNCALCULATED_ORDERS, new SelectUncalculatedOrdersFactory());
            put(SelectQueryTypeNoParams.SELECT_EBAY_BUYERS, new SelectEbayBuyersFactory());
            put(SelectQueryTypeNoParams.SELECT_ACCOUNTS, new SelectAccountsFactory());
        }}
internal map holds factory objects created static final to make threadsafe
Definition at line 115 of file SelectQueryInvoker.java.
Referenced by SelectQueryInvoker.execute().
final Map<SelectQueryTypeParams, AbstractSelectParamsQueryFactory> paramsMap_M static private
Initial value:
= new THashMap<SelectQueryTypeParams, AbstractSelectParamsQueryFactory>()
        {{
            put(SelectQueryTypeParams.SELECT_EBAY_ITEM_SPECIFIC, new SelectEbayItemSpecificFactory());
            put(SelectQueryTypeParams.SELECT_TRANSACTION_BY_ORDERID, new SelectTransactionByOrderIDFactory());
            put(SelectQueryTypeParams.SELECT_FULL_ORDER_LINE, new SelectFullOrderLineFactory());
            put(SelectQueryTypeParams.SELECT_OUT_OF_HOURS_ORDERS, new SelectOutOfHoursOrdersFactory());
            put(SelectQueryTypeParams.SELECT_EBAY_BUYER, new SelectEbayBuyerFactory());
            put(SelectQueryTypeParams.SELECT_EBAY_TRANSACTION_BY_ID, new SelectEbayTransactionByIDFactory());
            put(SelectQueryTypeParams.SELECT_EBAY_ORDER_BY_ID, new SelectEbayOrderByIDFactory());
            put(SelectQueryTypeParams.SELECT_EBAY_ORDER_BY_BUYER, new SelectEbayOrderByBuyerFactory());
            put(SelectQueryTypeParams.SELECT_BRAND_BY_INV_NO, new SelectBrandByInvNoFactory());
            put(SelectQueryTypeParams.SELECT_BRAND_AND_PARTNO_BY_ORDERID, new SelectBrandAndPartNoByOrderIDFactory());
            put(SelectQueryTypeParams.SELECT_EBAY_BUYER_BY_ACCOUNT_AND_SRN, new SelectBuyerByAccAndSRNFactory());
        }}
Definition at line 131 of file SelectQueryInvoker.java.
Referenced by SelectQueryInvoker.execute().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/framework/SelectQueryInvoker.java