TomoBay: PutInvoiceCommand Class Reference
PutInvoiceCommand Class Reference
this class instructs winstock to create an invoice given the data that is passed in.
Public Member Functions
PutInvoiceCommand () throws UnknownHostException, IOException
default ctor
PutInvoiceResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException
Public Member Functions inherited from AbstractWinstockCommand
abstract AbstractWinstockCommandResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException
this method executes the AbstractWinstockCommand specific to the derived type.
Private Attributes
PutInvoiceResponse response_M
the response object
PutInvoicePayload payload_M
the payload object
Static Private Attributes
static final int RESPONSE_LENGTH = 15
constant holding the the length of the response in bytes
Additional Inherited Members
Protected Member Functions inherited from AbstractWinstockCommand
AbstractWinstockCommand () throws UnknownHostException, IOException
default ctor, does preliminary initailisation of the config object and socket connection to Winstock.
Protected Attributes inherited from AbstractWinstockCommand
WinstockConfig config_M
client socket connection
ClientSocket winstockConnection_M
the configuration details
Detailed Description
this class instructs winstock to create an invoice given the data that is passed in.
The format of the message to create (as defined by winstock spec) is as follows:
PutInvoiceMessage
DataType Label Notes
byte Type 34
byte Company 0=ford, 3=citroen, 8=fiat
char AccountCode[9] account identifier
char ship1[51] name
char ship2[51] address line 1
char ship3[51] address line 2
char ship4[51] city
char ship5[51] county
char Postcode[10] postcode
char Order[21] order data
short Lines the # of invlines to follow
InvLine Il[1] see below table
InvLine
DataType Label Notes
char part[17] the part number
char Description[31] the description of the part
int Quantity
int Price
int InStock
nb//the numbers within square brackets are the maximum length that this field can length
this class is a concrete command in a Gof style command pattern
Author
Jan P.C. Hanson
See also
https://dzone.com/articles/design-patterns-command
Definition at line 64 of file PutInvoiceCommand.java.
Constructor & Destructor Documentation
PutInvoiceCommand () throws UnknownHostException, IOException
default ctor
Exceptions
UnknownHostException
IOException
Definition at line 77 of file PutInvoiceCommand.java.
Member Function Documentation
PutInvoiceResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException
Definition at line 88 of file PutInvoiceCommand.java.
References AbstractPayload.getPayload(), PutInvoiceCommand.response_M, PutInvoiceResponse.setResponseBytes(), and PutInvoiceResponse.setSentBytes().
Member Data Documentation
final int RESPONSE_LENGTH = 15 static private
constant holding the the length of the response in bytes
Definition at line 67 of file PutInvoiceCommand.java.
PutInvoiceResponse response_M private
the response object
Definition at line 69 of file PutInvoiceCommand.java.
Referenced by PutInvoiceCommand.execute().
PutInvoicePayload payload_M private
the payload object
Definition at line 71 of file PutInvoiceCommand.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/commands/PutInvoiceCommand.java