TomoBay: WinstockFormat Class Reference
WinstockFormat Class Reference
Public Member Functions
WinstockFormat ()
DualList< String, PayloadType > format (AbstractSalesDayBookLine line)
Public Member Functions inherited from AbstractFormat
AbstractFormat ()
default ctor
abstract DualList< String,PayloadType > format (AbstractSalesDayBookLine line)
Private Member Functions
String shorten (String input)
Detailed Description
Author
Jan P.C. Hanson
Definition at line 30 of file WinstockFormat.java.
Constructor & Destructor Documentation
WinstockFormat ()
Definition at line 36 of file WinstockFormat.java.
Member Function Documentation
DualList<String,PayloadType> format (AbstractSalesDayBookLine line)
Definition at line 43 of file WinstockFormat.java.
References PayloadType.ADDRESS1, PayloadType.ADDRESS2, Part.brand(), Order.buyer(), PayloadType.CITY, Buyer.city(), PayloadType.COMPANY, BrandToCode.convertToWinstockInt(), PayloadType.COUNTY, Buyer.county(), PayloadType.DESCRIPTION, PayloadType.INSTOCK, PayloadType.INV_LINES, PayloadType.INVOICE_ACCOUNT, Transaction.listing(), PayloadType.NAME, Buyer.name(), PayloadType.ORDER_NO, AbstractSalesDayBookLine.orderInfo(), Listing.part(), PayloadType.PART_NO, PayloadType.POSTCODE, Buyer.postcode(), PayloadType.PRICE, DualList< V1, V2 >.put(), PayloadType.QUANTITY, Order.salesRecNo(), WinstockFormat.shorten(), AbstractSalesDayBookLine.size(), Buyer.street1(), Buyer.street2(), Order.transaction(), and PayloadType.TYPE.
String shorten (String input) private
Definition at line 70 of file WinstockFormat.java.
Referenced by WinstockFormat.format().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/financial/SalesOrderDayBook/formats/WinstockFormat.java