TomoBay: OnRunning Class Reference
OnRunning Class Reference
Public Member Functions
OnRunning ()
default ctor
String execute ()
this method defines what to do in the given derived state
Static Package Attributes
static Logger log = Logger.getLogger(ReScanErrorsService.class.getName())
Detailed Description
Author
Jan P.C. Hanson
Definition at line 32 of file OnRunning.java.
Constructor & Destructor Documentation
OnRunning ()
default ctor
Definition at line 38 of file OnRunning.java.
Member Function Documentation
String execute ()
this method defines what to do in the given derived state
Returns
String representing the end product of the state.
Implements AbstractServiceState.
Definition at line 45 of file OnRunning.java.
References ItemsTable.ACCOUNT, ClassRef.INTEGER, ItemsTable.ITEM_ID, ClassRef.LONG, ReScanErrorsWinstockActions.partNoHasError(), ReScanErrorsDBActions.retrieveAllErrorItems(), and ReScanErrorsDBActions.updateDBwithCorrectedInfo().
Referenced by ReScanErrorsService.onRunning().
Member Data Documentation
Logger log = Logger.getLogger(ReScanErrorsService.class.getName()) static package
Definition at line 34 of file OnRunning.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/services/reScanErrorsService/OnRunning.java