TomoBay: PartList Class Reference
PartList Class Reference
Public Member Functions
PartList ()
creates an empty PartList
PartList (String compositePartNo)
creates a part list with the partNoString provided.
void add (String partNo, int quantity)
add a part number to the PartList with a given quantity
void remove (int index)
String getPartNumber (int i)
get the part number at position i in the list
String[] getPartNumbers ()
get the part numbers as a whole
int getPartQty (int i)
get the quantity of the part number at position i in the list
int[] getPartQtys ()
get the par quantities as a whole.
int size ()
the size of the part list.
void finalize () throws Throwable
de- allocate internal data.
Private Member Functions
void convert (String compositePartNo)
Private Attributes
String[] partNos_M
internal holder for part numbers
int[] partQty_M
internal holder for part quantities
Static Private Attributes
static final String singlequant = "(?<=\\w)\\s+(?=[^()]\\w)|(?<=\\w)\\s*+$"
Detailed Description
Author
Jan P.C. Hanson
Definition at line 24 of file PartList.java.
Constructor & Destructor Documentation
PartList ()
creates an empty PartList
Definition at line 37 of file PartList.java.
PartList (String compositePartNo)
creates a part list with the partNoString provided.
Parameters
compositePartNo a list of part numbers and quantities. acceptable formats are: 1234 or 1234(1)567(2)8910(3) or 1234(1)567(2)8910 [if 8910 has qty 1] or 1234 567 [if both 1234 AND 567 have qty 1
Definition at line 50 of file PartList.java.
References PartList.convert().
Member Function Documentation
void add (String partNo, int quantity)
add a part number to the PartList with a given quantity
Parameters
partNo the partNumber
quantity the quantity of the part.
Definition at line 63 of file PartList.java.
Referenced by PartList.convert().
void remove (int index)
Parameters
index
Definition at line 75 of file PartList.java.
References PartList.size().
String getPartNumber (int i)
get the part number at position i in the list
Parameters
i the index of the partNumber you wish to get
Returns
String part number stored at index i
Definition at line 92 of file PartList.java.
Referenced by ItemStockLevel.checkStockLevelOfItems(), Listing.Listing(), SAAJTest.main(), and StockReOrderAnalysis.processDBdata().
String [] getPartNumbers ()
get the part numbers as a whole
Returns
String[] where the elements correspond to the part numbers as ordered in the argument passed to the constructor.
Definition at line 100 of file PartList.java.
References PartList.partNos_M.
Referenced by OnRunning.execute(), and ReScanErrorsWinstockActions.partNoHasError().
int getPartQty (int i)
get the quantity of the part number at position i in the list
Parameters
i the index of the part number you wish to query the quantity of.
Returns
int the quantity of the part number at index i
Definition at line 107 of file PartList.java.
Referenced by ItemStockLevel.checkStockLevelOfItems(), Listing.Listing(), SAAJTest.main(), and StockReOrderAnalysis.processDBdata().
int [] getPartQtys ()
get the par quantities as a whole.
Returns
int[] with each element containing the quantity of the part associated with the same index.
Definition at line 115 of file PartList.java.
References PartList.partQty_M.
int size ()
the size of the part list.
Returns
the size of the part list.
Definition at line 122 of file PartList.java.
Referenced by ItemStockLevel.checkStockLevelOfItems(), Listing.Listing(), SAAJTest.main(), StockReOrderAnalysis.processDBdata(), and PartList.remove().
void finalize () throws Throwable
de- allocate internal data.
Exceptions
Throwable
Definition at line 129 of file PartList.java.
void convert (String compositePartNo) private
Parameters
compositePartNo
Definition at line 139 of file PartList.java.
References PartList.add().
Referenced by PartList.PartList().
Member Data Documentation
String [] partNos_M private
internal holder for part numbers
Definition at line 27 of file PartList.java.
Referenced by PartList.getPartNumbers().
int [] partQty_M private
internal holder for part quantities
Definition at line 29 of file PartList.java.
Referenced by PartList.getPartQtys().
final String singlequant = "(?<=\\w)\\s+(?=[^()]\\w)|(?<=\\w)\\s*+$" static private
Definition at line 33 of file PartList.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/PartList.java