TomoBay: Shipping_Priority Class Reference
Shipping_Priority Class Reference
This class encapsulates the functionality for querying the shipping priority of a particular shipping type.
Static Public Member Functions
static Shipping_Priority instance ()
singleton instance method
static int getPriority (String shippingType)
gets the priority of a particular shipping type.
static int size ()
get the number of shipping types in the hierarchy of shipping types
static void refresh ()
refreshes the internal representation of the shipping type hierarchy with any changes made to the config file.
Private Member Functions
Shipping_Priority ()
singleton ctor, ensures that this class is never instantiated
Static Private Member Functions
static void populatePriorityMap ()
populates the internal map containing the shipping priorities
Static Private Attributes
static Map< String, Integer > priorityMap_M
static Shipping_Priority instance_M = new Shipping_Priority()
Detailed Description
This class encapsulates the functionality for querying the shipping priority of a particular shipping type.
The actual hierarchy of shipping types is taken from the config file.
Author
Jan P.C. Hanson
Definition at line 25 of file Shipping_Priority.java.
Constructor & Destructor Documentation
Shipping_Priority () private
singleton ctor, ensures that this class is never instantiated
Definition at line 33 of file Shipping_Priority.java.
References Shipping_Priority.populatePriorityMap(), and Shipping_Priority.priorityMap_M.
Member Function Documentation
static Shipping_Priority instance () static
singleton instance method
Returns
Shipping_Priority instance of this object
Definition at line 44 of file Shipping_Priority.java.
References Shipping_Priority.instance_M.
static int getPriority (String shippingType) static
gets the priority of a particular shipping type.
Parameters
shippingType String representing the shipping type you wish to find the priority of.
Returns
integer representing the priority 0 being the highest priority and priority decreasing as the value increases.
Definition at line 53 of file Shipping_Priority.java.
References Shipping_Priority.priorityMap_M.
static int size () static
get the number of shipping types in the hierarchy of shipping types
Returns
int representing the size of the shipping type hierarchy
Definition at line 60 of file Shipping_Priority.java.
References Shipping_Priority.priorityMap_M.
static void refresh () static
refreshes the internal representation of the shipping type hierarchy with any changes made to the config file.
Definition at line 67 of file Shipping_Priority.java.
References Shipping_Priority.populatePriorityMap(), and Shipping_Priority.priorityMap_M.
static void populatePriorityMap () static private
populates the internal map containing the shipping priorities
Definition at line 77 of file Shipping_Priority.java.
References ConfigReader.getConfs(), Shipping_Priority.priorityMap_M, and Config.Ship_Type.
Referenced by Shipping_Priority.refresh(), and Shipping_Priority.Shipping_Priority().
Member Data Documentation
Map<String, Integer> priorityMap_M static private
Definition at line 27 of file Shipping_Priority.java.
Referenced by Shipping_Priority.getPriority(), Shipping_Priority.populatePriorityMap(), Shipping_Priority.refresh(), Shipping_Priority.Shipping_Priority(), and Shipping_Priority.size().
Shipping_Priority instance_M = new Shipping_Priority() static private
Definition at line 28 of file Shipping_Priority.java.
Referenced by Shipping_Priority.instance().
The documentation for this class was generated from the following file:
src/tomoBay/helpers/Shipping_Priority.java