TomoBay: WinstockConfig Class Reference
WinstockConfig Class Reference
This class is responsible for grabbing and storing the contents of the winstock configuration file, and providing that information to objects in need of this information.
Public Member Functions
WinstockConfig ()
default constructor
String getMachineName ()
method used to get the string representing the name of the machine on which winstock is running, this could be a domain name or an IP address.
int getPort ()
method used to retrieve the port on which winstock is running.
Detailed Description
This class is responsible for grabbing and storing the contents of the winstock configuration file, and providing that information to objects in need of this information.
Author
Jan P.C. Hanson
Definition at line 25 of file WinstockConfig.java.
Constructor & Destructor Documentation
WinstockConfig ()
default constructor
Definition at line 30 of file WinstockConfig.java.
Member Function Documentation
String getMachineName ()
method used to get the string representing the name of the machine on which winstock is running, this could be a domain name or an IP address.
Returns
String representing the name of the machine on which winstock is running.
Definition at line 38 of file WinstockConfig.java.
References ConfigReader.getConf(), and Config.WIN_LOC.
Referenced by AbstractWinstockCommand.AbstractWinstockCommand().
int getPort ()
method used to retrieve the port on which winstock is running.
Returns
int representing the port number on which winstock is running.
Definition at line 45 of file WinstockConfig.java.
References ConfigReader.getConf(), and Config.WIN_PORT.
Referenced by AbstractWinstockCommand.AbstractWinstockCommand().
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/WinstockConfig.java