TomoBay: ModifyQueryInvoker Class Reference
ModifyQueryInvoker Class Reference
This object is responsible for providing the user with Insert or Update Query objects as specified by the internal enum, which defines all possible Insert or Update queries that can be executed on the database.
Classes
enum ModifyQueryTypeNoParams
enum ModifyQueryTypeParams
Defensive enum defines the acceptable inputs to the factory.
Static Public Member Functions
static HeteroFieldContainer execute (ModifyQueryTypeParams query)
static HeteroFieldContainer execute (ModifyQueryTypeParams query, HeteroFieldContainer parameters)
execute a requested query
Static Private Attributes
static final Map< ModifyQueryTypeParams, AbstractModifyQueryParamsFactory > factoryMap_M
internal map holds factory objects created static final to make threadsafe
static final Map< ModifyQueryTypeNoParams, AbstractModifyQueryNoParamsFactory > noParamsFactoryMap_M
Detailed Description
This object is responsible for providing the user with Insert or Update Query objects as specified by the internal enum, which defines all possible Insert or Update queries that can be executed on the database.
These Insert or Update query objects can either be created using the make() method or directly executed using the execute() method.
acceptable input values for those methods is defined in QueryType.
Author
Jan P.C. Hanson
Definition at line 50 of file ModifyQueryInvoker.java.
Member Function Documentation
static HeteroFieldContainer execute (ModifyQueryTypeParams query) static
Parameters
query one of the enum values provided by ModifyQueryTypeNoParams enum.
Returns
Definition at line 119 of file ModifyQueryInvoker.java.
References ModifyQueryInvoker.noParamsFactoryMap_M.
Referenced by MarkAsInvoiced.execute(), MarkAsUninvoiced.execute(), OnRunning.execute(), RePopulateEbayItem.populate(), Buyers_Table.populate(), Transactions_Table.populate(), ItemsAndPartsTable.populate(), Orders_Table.populate(), DBActions.updateBuyerTable(), InvoiceOrders.updateDB(), ReScanErrorsDBActions.updateDBwithCorrectedInfo(), and OnRunning.updateItemNote().
static HeteroFieldContainer execute (ModifyQueryTypeParams query, HeteroFieldContainer parameters) static
execute a requested query
Parameters
query one of the enum values provided by ModifyQueryTypeParams enum.
parameters String[] of parameters specific to the query you are using, see individual query docs.
Returns
List<String[]>
Exceptions
SQLException
Definition at line 138 of file ModifyQueryInvoker.java.
References ModifyQueryInvoker.factoryMap_M.
Member Data Documentation
final Map<ModifyQueryTypeParams, AbstractModifyQueryParamsFactory> factoryMap_M static private
Initial value:
= new THashMap<ModifyQueryTypeParams, AbstractModifyQueryParamsFactory>()
        {{
            put(ModifyQueryTypeParams.INSERT_EBAY_BUYERS, new InsertEbayBuyersFactory());
            put(ModifyQueryTypeParams.INSERT_EBAY_ITEMS, new InsertEbayItemsFactory());
            put(ModifyQueryTypeParams.INSERT_EBAY_ORDERS, new InsertEbayOrdersFactory());
            put(ModifyQueryTypeParams.INSERT_EBAY_TRANSACTIONS, new InsertEbayTransactionsFactory());
            put(ModifyQueryTypeParams.INSERT_OUT_OF_HOURS, new InsertOutOfHoursFactory());
            put(ModifyQueryTypeParams.INSERT_ORDER_IN_ORDER_STATUS, new InsertOrderInOrderStatusFactory());
            put(ModifyQueryTypeParams.UPDATE_ITEM_BRAND_AND_PARTNO, new UpdateItemBrandAndPartNoFactory());
            put(ModifyQueryTypeParams.UPDATE_INVOICE_STATUS, new UpdateInvoiceStatusFactory());
            put(ModifyQueryTypeParams.UPDATE_ITEM_ERROR, new UpdateItemErrorFactory());
            put(ModifyQueryTypeParams.UPDATE_ITEM_NOTE, new UpdateItemNoteFactory());
            put(ModifyQueryTypeParams.UPDATE_INVOICE_STATUS_SRN, new UpdateInvoiceStatusSRNFactory());
            put(ModifyQueryTypeParams.UPDATE_EBAY_BUYER, new UpdateEbayBuyerFactory());
            put(ModifyQueryTypeParams.DELETE_ORDER_FROM_ORDER_STATUS, new DeleteOrderFromOrderStatusFactory());
        }}
internal map holds factory objects created static final to make threadsafe
Definition at line 91 of file ModifyQueryInvoker.java.
Referenced by ModifyQueryInvoker.execute().
final Map<ModifyQueryTypeNoParams, AbstractModifyQueryNoParamsFactory> noParamsFactoryMap_M static private
Initial value:
= new THashMap<ModifyQueryTypeNoParams, AbstractModifyQueryNoParamsFactory>()
        {{
        }}
Definition at line 111 of file ModifyQueryInvoker.java.
Referenced by ModifyQueryInvoker.execute().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/framework/ModifyQueryInvoker.java