My Project: openDMS.ebay.query.commands.GetTransactionListCommand Class Reference
openDMS.ebay.query.commands.GetTransactionListCommand Class Reference
Public Member Functions
GetTransactionListCommand ()
String execute (ApiCallData callData, int index, String NOTUSED)
ApiCallData getCallData ()
Public Member Functions inherited from openDMS.ebay.query.commands.AbstractEbayQuery
abstract String execute (ApiCallData callData, int index, String string)
abstract ApiCallData getCallData ()
Private Member Functions
String printResults (ApiCallData callData, int a)
Additional Inherited Members
Protected Attributes inherited from openDMS.ebay.query.commands.AbstractEbayQuery
ApiCallData callData_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 29 of file GetTransactionListCommand.java.
Constructor & Destructor Documentation
openDMS.ebay.query.commands.GetTransactionListCommand.GetTransactionListCommand ()
default constructor
Definition at line 36 of file GetTransactionListCommand.java.
Member Function Documentation
String openDMS.ebay.query.commands.GetTransactionListCommand.execute (ApiCallData callData, int index, String NOTUSED)
Definition at line 44 of file GetTransactionListCommand.java.
References openDMS.ebay.query.data.ApiCallData.accessTransactionData(), openDMS.ebay.query.data.ApiTransactionData.clearData(), and openDMS.ebay.query.commands.GetTransactionListCommand.printResults().
ApiCallData openDMS.ebay.query.commands.GetTransactionListCommand.getCallData ()
Definition at line 62 of file GetTransactionListCommand.java.
String openDMS.ebay.query.commands.GetTransactionListCommand.printResults (ApiCallData callData, int a) private
Parameters
callData
a
Returns
String containing formatted results
Definition at line 71 of file GetTransactionListCommand.java.
References openDMS.ebay.query.data.ApiCallData.accessTransactionData(), and openDMS.ebay.query.data.ApiTransactionData.size().
Referenced by openDMS.ebay.query.commands.GetTransactionListCommand.execute().
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/commands/GetTransactionListCommand.java