TomoBay: AbstractModifyQueryNoParams Class Reference
AbstractModifyQueryNoParams Class Reference abstract
This is the Abstract Base Class for all queries that modify the database in some way (INSERT/UPDATE/DELETE) but do not require any parameters in order to run.
Public Member Functions
AbstractModifyQueryNoParams ()
default ctor
HeteroFieldContainer execute () throws SQLException
Executes the query and returns a HeteroFieldContainer containing the result fields.
Public Member Functions inherited from AbstractModifyQuery
AbstractModifyQuery ()
default ctor
Public Member Functions inherited from AbstractDBQuery
PreparedStatement statement ()
get the statement object associated with this query
Protected Member Functions
abstract String queryString ()
Used by derived classes to define the Query string to be used in the query.
Protected Member Functions inherited from AbstractDBQuery
abstract String queryString ()
Used by derived classes to define the Query string to be used in the query.
void cleanup () throws SQLException
commits the transaction and does cleanup after the query has been executed
Private Member Functions
int initQuery (String query) throws SQLException
initialise the connection and statement and set transaction variables.
Additional Inherited Members
Protected Attributes inherited from AbstractDBQuery
PreparedStatement statement_M = null
reference to the JDBC Statement
Connection connection_M = null
reference to the JDBC Database connection
Detailed Description
This is the Abstract Base Class for all queries that modify the database in some way (INSERT/UPDATE/DELETE) but do not require any parameters in order to run.
Author
Jan P.C. Hanson
Definition at line 28 of file AbstractModifyQueryNoParams.java.
Constructor & Destructor Documentation
AbstractModifyQueryNoParams ()
default ctor
Definition at line 33 of file AbstractModifyQueryNoParams.java.
Member Function Documentation
HeteroFieldContainer execute () throws SQLException
Executes the query and returns a HeteroFieldContainer containing the result fields.
Returns
HeteroFieldContainer containing a NonDBFields.RESULT_CODE field only.
Exceptions
SQLException
Definition at line 41 of file AbstractModifyQueryNoParams.java.
References HeteroFieldContainer.add(), AbstractModifyQueryNoParams.initQuery(), AbstractModifyQueryNoParams.queryString(), and NonDBFields.RESULT_CODE.
abstract String queryString () abstract protected
Used by derived classes to define the Query string to be used in the query.
Returns
String containing the JDBC query string
Referenced by AbstractModifyQueryNoParams.execute().
int initQuery (String query) throws SQLException private
initialise the connection and statement and set transaction variables.
Parameters
query String containing the sql query
Exceptions
SQLException
Definition at line 61 of file AbstractModifyQueryNoParams.java.
References AbstractDBQuery.connection_M, ConnectionManager.getConnection(), ConnectionManager.instance(), and AbstractDBQuery.statement_M.
Referenced by AbstractModifyQueryNoParams.execute().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/framework/queryTypes/modify/AbstractModifyQueryNoParams.java