TomoBay: ItemsTable Class Reference
ItemsTable Class Reference
This represents the structure of the ebay_items table of the database.
Static Public Attributes
static final ItemID ITEM_ID = new ItemID()
the itemID field of the ebay_items table, this is the primary key
static final Title TITLE = new Title()
the title field of the ebay_items table, this is the title of the ebay listing.
static final Condition CONDITION = new Condition()
the condition field of the ebay_items table.
static final Brand BRAND = new Brand()
the brand field of the ebay_items table, this is what the ebay SDK calls an 'item specific'.
static final PartNo PART_NO = new PartNo()
the partNo field of the ebay_items table.
static final Notes NOTES = new Notes()
the notes field of the ebay_items table, this is a field that reflects whether there is some kind of error associated with this item i.e.
static final AbstractField ACCOUNT = AccountsTable.ID
the account field of the ebay_items table.
Private Member Functions
ItemsTable ()
private ctor ensures this class is never instantiated
Detailed Description
This represents the structure of the ebay_items table of the database.
This table is a representation of ebay listings grabbed using the eBayAPI
See also
tomoBay.model.eBayAPI
Author
Jan P.C. Hanson
Definition at line 27 of file ItemsTable.java.
Constructor & Destructor Documentation
ItemsTable () private
private ctor ensures this class is never instantiated
Definition at line 94 of file ItemsTable.java.
Member Data Documentation
final ItemID ITEM_ID = new ItemID() static
the itemID field of the ebay_items table, this is the primary key
BIGINT(13)
Primary key
See also
tomoBay.model.sql.schema.itemsTable.ItemID
Definition at line 36 of file ItemsTable.java.
Referenced by EmailErrorsDataFormat.asHTML(), OnRunning.execute(), SelectEbayItemsError.format(), SelectEbayItems.format(), SelectEbayItemsNotInTransactions.format(), SelectEbayItemSpecific.format(), SelectFullOrderLine.format(), Listing.getListingInfo(), Listing.listingID(), RePopulateEbayItem.populate(), ItemsAndPartsTable.populate(), UpdateItemNote.setParameters(), UpdateItemBrandAndPartNo.setParameters(), InsertEbayItems.setParameters(), UpdateItemError.setParameters(), SelectEbayItemSpecific.setParameters(), ReScanErrorsDBActions.updateDBwithCorrectedInfo(), and OnRunning.updateItemNote().
final Title TITLE = new Title() static
the title field of the ebay_items table, this is the title of the ebay listing.
VARCHAR(83)
See also
tomoBay.model.sql.schema.itemsTable.Title
Definition at line 43 of file ItemsTable.java.
Referenced by EmailErrorsDataFormat.asHTML(), SelectEbayItemsError.format(), SelectEbayItems.format(), SelectUncalculatedInvoices.format(), SelectEbayItemSpecific.format(), SelectFullOrderLine.format(), ItemsAndPartsTable.populate(), InsertEbayItems.setParameters(), and Listing.title().
final Condition CONDITION = new Condition() static
the condition field of the ebay_items table.
this field represents the selling condition of a particular item.
VARCHAR(15)
See also
tomoBay.model.sql.schema.itemsTable.Condition
Definition at line 51 of file ItemsTable.java.
Referenced by SelectEbayItemsError.format(), SelectEbayItems.format(), SelectEbayItemSpecific.format(), ItemsAndPartsTable.populate(), and InsertEbayItems.setParameters().
final Brand BRAND = new Brand() static
the brand field of the ebay_items table, this is what the ebay SDK calls an 'item specific'.
In order for the system to pick up brand properly the ebay seller must put the brand in the 'Brand' field on the listing
VARCHAR(50)
See also
tomoBay.model.sql.schema.itemsTable.Brand
Definition at line 60 of file ItemsTable.java.
Referenced by EmailErrorsDataFormat.asHTML(), Listing.brand(), ItemStockLevel.checkStockLevelOfItems(), OnRunning.execute(), SelectEbayItemsError.format(), SelectEbayItems.format(), SelectUncalculatedInvoices.format(), SelectBrandAndPartNoByOrderID.format(), SelectBrandByInv.format(), SelectEbayItemSpecific.format(), SelectFullOrderLine.format(), RePopulateEbayItem.populate(), ItemsAndPartsTable.populate(), UpdateItemBrandAndPartNo.setParameters(), UpdateItemError.setParameters(), InsertEbayItems.setParameters(), and ReScanErrorsDBActions.updateDBwithCorrectedInfo().
final PartNo PART_NO = new PartNo() static
the partNo field of the ebay_items table.
this is what the eba SDK calls an 'item specific'. In order for the system to pick up part numbers properly they must be placed in the 'Manufacturer Part Number' field of the item specifics on the eBay listing.
VARCHAR(55)
See also
tomoBay.model.sql.schema.itemsTable.PartNo
Definition at line 69 of file ItemsTable.java.
Referenced by EmailErrorsDataFormat.asHTML(), ItemStockLevel.checkStockLevelOfItems(), OnRunning.execute(), SelectEbayItemsError.format(), SelectEbayItems.format(), SelectUncalculatedInvoices.format(), SelectBrandAndPartNoByOrderID.format(), SelectEbayItemSpecific.format(), SelectFullOrderLine.format(), Listing.Listing(), Listing.partNos(), RePopulateEbayItem.populate(), ItemsAndPartsTable.populate(), UpdateItemBrandAndPartNo.setParameters(), UpdateItemError.setParameters(), InsertEbayItems.setParameters(), and ReScanErrorsDBActions.updateDBwithCorrectedInfo().
final Notes NOTES = new Notes() static
the notes field of the ebay_items table, this is a field that reflects whether there is some kind of error associated with this item i.e.
part number in the wrong format, brand missing etc. Notes are of the form 'ERROR(18234823482348)check Brand or PartNo' where the long number is the ebay listing id
VARCHAR(60)
See also
tomoBay.model.sql.schema.itemsTable.ItemsTable::ITEM_ID
tomoBay.model.sql.schema.itemsTable.Notes
Definition at line 80 of file ItemsTable.java.
Referenced by EmailErrorsDataFormat.asHTML(), SelectEbayItemsError.format(), SelectEbayItems.format(), SelectEbayItemSpecific.format(), SelectFullOrderLine.format(), UpdateItemNote.setParameters(), UpdateItemError.setParameters(), ReScanErrorsDBActions.updateDBwithCorrectedInfo(), and OnRunning.updateItemNote().
final AbstractField ACCOUNT = AccountsTable.ID static
the account field of the ebay_items table.
this field is a foreign key to the ebay_accounts(tomoBay.model.sql.schema.accountsTable.AccountsTable) table and represents the account that a particular item is associated with.
INT(11)
See also
tomoBay.model.sql.schema.accountsTable.Id
Definition at line 89 of file ItemsTable.java.
Referenced by OnRunning.execute(), SelectEbayItemsError.format(), SelectEbayItems.format(), SelectEbayItemSpecific.format(), ItemsAndPartsTable.populate(), and InsertEbayItems.setParameters().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/schema/itemsTable/ItemsTable.java