My Project: openDMS.ebay.query.QueryInvoker Class Reference
openDMS.ebay.query.QueryInvoker Class Reference
Public Member Functions
QueryInvoker (String userToken, String serverString)
String execute (String command, int index, String stringParam)
Private Member Functions
void populateCommandMap ()
Private Attributes
Map< String, AbstractEbayQuery > commandMap_M
ApiCallData callData_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 30 of file QueryInvoker.java.
Constructor & Destructor Documentation
openDMS.ebay.query.QueryInvoker.QueryInvoker (String userToken, String serverString)
constructor, initialises the QueryInvoker object.
Definition at line 41 of file QueryInvoker.java.
References openDMS.ebay.query.QueryInvoker.populateCommandMap().
Member Function Documentation
String openDMS.ebay.query.QueryInvoker.execute (String command, int index, String stringParam)
executes the command selected from the invoker. It is worth noting that not all commands use the same parameters, some dont use any some just the index, some the stringParam and some use both.
Returns
String representative of the result of the query.
Definition at line 54 of file QueryInvoker.java.
References openDMS.ebay.query.commands.AbstractEbayQuery.execute(), and openDMS.ebay.query.commands.AbstractEbayQuery.getCallData().
void openDMS.ebay.query.QueryInvoker.populateCommandMap () private
fills the commandMap_M with command objects.
Definition at line 67 of file QueryInvoker.java.
Referenced by openDMS.ebay.query.QueryInvoker.QueryInvoker().
Member Data Documentation
ApiCallData openDMS.ebay.query.QueryInvoker.callData_M private
holder for initial callData object
Definition at line 35 of file QueryInvoker.java.
Map<String, AbstractEbayQuery> openDMS.ebay.query.QueryInvoker.commandMap_M private
holder for all the command objects available to the client
Definition at line 33 of file QueryInvoker.java.
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/QueryInvoker.java