TomoBay: EbayAccounts Class Reference
EbayAccounts Class Reference
This class provides static access to information on the ebay accounts that have been registered with the system.
Static Public Member Functions
static String[] accounts ()
static String name (int id)
convert an account ID to a textual name value.
static int id (String accountName)
retrieve the id for the account name specified
static String apiKey (String accountName)
retrieve the ebay api key for the account name specified
static String serverAddress (String accountName)
retrieve the ebay server address for the account name specified
static int lookbackDays (String accountName)
retrieve the number of days previous to the current day that the system should retrieve orders from the ebay API for.
static boolean registerAccount (String accountName, String apiKey, String server, int lookback)
register a new account on the system
static void refresh ()
refresh the account information.
Private Member Functions
EbayAccounts ()
private ctor so that this class can never be instantiated
Static Private Attributes
static List< HeteroFieldContainer > accountInfo_M = SelectQueryInvoker.execute(SelectQueryTypeNoParams.SELECT_ACCOUNTS)
heterofieldcontainer holding the account information
Detailed Description
This class provides static access to information on the ebay accounts that have been registered with the system.
Author
Jan P.C. Hanson
Definition at line 31 of file EbayAccounts.java.
Constructor & Destructor Documentation
EbayAccounts () private
private ctor so that this class can never be instantiated
Definition at line 40 of file EbayAccounts.java.
Member Function Documentation
static String [] accounts () static
Returns
String[] containing the names of all the accounts that are currently registered on the system.
Definition at line 47 of file EbayAccounts.java.
References AccountsTable.ACCOUNT_NAME, EbayAccounts.accountInfo_M, and ClassRef.STRING.
Referenced by OnRunning.execute().
static String name (int id) static
convert an account ID to a textual name value.
Parameters
id the id of the account as it is on the database
Returns
String containg a textual name for this account
Definition at line 60 of file EbayAccounts.java.
References AccountsTable.ACCOUNT_NAME, EbayAccounts.accountInfo_M, AccountsTable.ID, EbayAccounts.id(), ClassRef.INTEGER, and ClassRef.STRING.
Referenced by Order.account(), OnRunning.execute(), SalesOrderView.format(), OnRunning.getItemData(), and ItemSpecifics.ItemSpecifics().
static int id (String accountName) static
retrieve the id for the account name specified
Parameters
accountName the account name to find the id of
Returns
int the id of the account specified
Definition at line 75 of file EbayAccounts.java.
References AccountsTable.ACCOUNT_NAME, EbayAccounts.accountInfo_M, AccountsTable.ID, ClassRef.INTEGER, and ClassRef.STRING.
Referenced by MarkAsInvoiced.execute(), MarkAsUninvoiced.execute(), OnRunning.execute(), and EbayAccounts.name().
static String apiKey (String accountName) static
retrieve the ebay api key for the account name specified
Parameters
accountName the account name to find the api key of
Returns
String containing the ebay api key for the account specified
Definition at line 90 of file EbayAccounts.java.
References AccountsTable.ACCOUNT_NAME, EbayAccounts.accountInfo_M, AccountsTable.API_KEY, and ClassRef.STRING.
Referenced by OnRunning.execute(), OnRunning.getItemData(), and ItemSpecifics.ItemSpecifics().
static String serverAddress (String accountName) static
retrieve the ebay server address for the account name specified
Parameters
accountName the account name to find the ebay server address of
Returns
String containing the ebay server address for the account specified
Definition at line 111 of file EbayAccounts.java.
References AccountsTable.ACCOUNT_NAME, EbayAccounts.accountInfo_M, AccountsTable.SERVER_ADDR, and ClassRef.STRING.
Referenced by OnRunning.execute(), OnRunning.getItemData(), and ItemSpecifics.ItemSpecifics().
static int lookbackDays (String accountName) static
retrieve the number of days previous to the current day that the system should retrieve orders from the ebay API for.
Parameters
accountName the account name to find this value for
Returns
int representing the number of lookback days
Definition at line 133 of file EbayAccounts.java.
References AccountsTable.ACCOUNT_NAME, EbayAccounts.accountInfo_M, ClassRef.INTEGER, AccountsTable.LOOKBACK_DAYS, and ClassRef.STRING.
Referenced by OnRunning.execute().
static boolean registerAccount (String accountName, String apiKey, String server, int lookback) static
register a new account on the system
Parameters
accountName the name of the new account, must be distinct from any other account name
apiKey the api key associated with this account
server the server address that this account should use when performing api calls
lookback the number of days prior to the current day that the system should use when looking for new orders.
Returns
Todo:
use query to add account to database
Definition at line 158 of file EbayAccounts.java.
References EbayAccounts.refresh().
static void refresh () static
refresh the account information.
Definition at line 168 of file EbayAccounts.java.
References EbayAccounts.accountInfo_M, SelectQueryInvoker.execute(), and SelectQueryInvoker.SelectQueryTypeNoParams.SELECT_ACCOUNTS.
Referenced by EbayAccounts.registerAccount().
Member Data Documentation
List<HeteroFieldContainer> accountInfo_M = SelectQueryInvoker.execute(SelectQueryTypeNoParams.SELECT_ACCOUNTS) static private
heterofieldcontainer holding the account information
Definition at line 35 of file EbayAccounts.java.
Referenced by EbayAccounts.accounts(), EbayAccounts.apiKey(), EbayAccounts.id(), EbayAccounts.lookbackDays(), EbayAccounts.name(), EbayAccounts.refresh(), and EbayAccounts.serverAddress().
The documentation for this class was generated from the following file:
src/tomoBay/model/eBayAPI/EbayAccounts.java