TomoBay: ViewFactory Class Reference
ViewFactory Class Reference
This class is the visitor in a visitor/double dispatch type setup where the AbstractPresenter concrete classes are the visitables and contain the corresponding accept() methods.
Public Member Functions
AbstractView visit (ErrorPresenter presenter)
factory method for ErrorView
AbstractView visit (RootPresenter presenter)
factory method for the RootView
AbstractView visit (SalesHistoryPresenter presenter)
factory method for the SalesHistoryView
AbstractView visit (SalesOrderPresenter presenter)
factory method for the SalesOrderView
AbstractView visit (WarehouseOrderPresenter presenter)
factory method for the SalesOrderView
AbstractView visit (OrderDetailsPresenter orderDetailsPresenter)
AbstractView visit (AdminPresenter adminPresenter)
AbstractView visit (OutOfHoursPresenter outOfHoursPresenter)
AbstractView visit (CRMOverviewPresenter crmOverviewPresenter)
AbstractView visit (CRMDetailPresenter crmDetailPresenter)
Detailed Description
This class is the visitor in a visitor/double dispatch type setup where the AbstractPresenter concrete classes are the visitables and contain the corresponding accept() methods.
This visitor acts as a view factory allowing the presenters to be responsible for the creation of their own views.
Author
Jan P.C. Hanson
Definition at line 46 of file ViewFactory.java.
Member Function Documentation
AbstractView visit (ErrorPresenter presenter)
factory method for ErrorView
Parameters
presenter a valid ErrorPresenter
Returns
ErrorView
Definition at line 53 of file ViewFactory.java.
Referenced by WarehouseOrderPresenter.accept(), OrderDetailsPresenter.accept(), AdminPresenter.accept(), RootPresenter.accept(), ErrorPresenter.accept(), CRMDetailPresenter.accept(), CRMOverviewPresenter.accept(), SalesHistoryPresenter.accept(), OutOfHoursPresenter.accept(), SalesOrderPresenter.accept(), ViewFactoryTest.testVisitErrorPresenter(), ViewFactoryTest.testVisitRootPresenter(), ViewFactoryTest.testVisitSalesHistoryPresenter(), ViewFactoryTest.testVisitSalesOrderPresenter(), and ViewFactoryTest.testVisitWarehouseOrderPresenter().
AbstractView visit (RootPresenter presenter)
factory method for the RootView
Parameters
presenter a valid RootPresenter
Returns
RootView
Definition at line 61 of file ViewFactory.java.
AbstractView visit (SalesHistoryPresenter presenter)
factory method for the SalesHistoryView
Parameters
presenter a valid SalesHistoryPresenter
Returns
SalesHistoryView
Definition at line 69 of file ViewFactory.java.
AbstractView visit (SalesOrderPresenter presenter)
factory method for the SalesOrderView
Parameters
presenter a valid SalesOrderPresenter
Returns
SalesOrderView
Definition at line 77 of file ViewFactory.java.
AbstractView visit (WarehouseOrderPresenter presenter)
factory method for the SalesOrderView
Parameters
presenter a valid WarehouseOrderPresenter
Returns
WarehouseOrderView
Definition at line 85 of file ViewFactory.java.
AbstractView visit (OrderDetailsPresenter orderDetailsPresenter)
Parameters
orderDetailsPresenter
Returns
Definition at line 92 of file ViewFactory.java.
AbstractView visit (AdminPresenter adminPresenter)
Parameters
adminPresenter
Returns
Definition at line 100 of file ViewFactory.java.
AbstractView visit (OutOfHoursPresenter outOfHoursPresenter)
Parameters
outOfHoursPresenter
Returns
Definition at line 108 of file ViewFactory.java.
AbstractView visit (CRMOverviewPresenter crmOverviewPresenter)
Parameters
crmOverviewPresenter
Returns
Definition at line 115 of file ViewFactory.java.
AbstractView visit (CRMDetailPresenter crmDetailPresenter)
Parameters
crmDetailPresenter
Returns
Definition at line 122 of file ViewFactory.java.
The documentation for this class was generated from the following file:
src/tomoBay/view/ViewFactory.java