TomoBay: Email Class Reference
Email Class Reference
This class represents an email, it contains recipients a subject and a message body.
Public Member Functions
void setRecipient (Message.RecipientType recipientType, String address) throws AddressException, MessagingException
set a recipient of the email, valid RecipientType listed in Message.RecipientType : TO/CC/BCC.
void setSubject (String subject) throws MessagingException
set the subject line of the email.
void setMessage (String message) throws MessagingException
sets the email body
Protected Member Functions
Email ()
default ctor
Protected Attributes
Map< String, Message.RecipientType > recipients_M
map containing the recipients
String subject_M
String containing the subject line.
String messageBody_M
String containing the message body.
Detailed Description
This class represents an email, it contains recipients a subject and a message body.
This class is NOT to be directly instantiated, but should be created using the EmailDirector.
Author
Jan P.C. Hanson
Definition at line 30 of file Email.java.
Constructor & Destructor Documentation
Email () protected
default ctor
Definition at line 42 of file Email.java.
References Email.recipients_M.
Member Function Documentation
void setRecipient (Message.RecipientType recipientType, String address) throws AddressException, MessagingException
set a recipient of the email, valid RecipientType listed in Message.RecipientType : TO/CC/BCC.
Parameters
recipientType TO/CC/BCC
address a string containing the email address of the recipient
Exceptions
MessagingException
AddressException
Definition at line 56 of file Email.java.
References Email.recipients_M.
Referenced by EmailErrorsMailActions.addRecipient(), EmailTest.main(), and MailClient.setUpEmail().
void setSubject (String subject) throws MessagingException
set the subject line of the email.
Parameters
subject String containing the subject line of the email
Exceptions
MessagingException
Definition at line 65 of file Email.java.
Referenced by EmailErrorsMailActions.addSubject(), EmailTest.main(), and MailClient.setUpEmail().
void setMessage (String message) throws MessagingException
sets the email body
Parameters
message String containing the message body for the email
Exceptions
MessagingException
Definition at line 73 of file Email.java.
Referenced by EmailErrorsMailActions.addMessage(), EmailTest.main(), and MailClient.setUpEmail().
Member Data Documentation
Map<String, Message.RecipientType> recipients_M protected
map containing the recipients
Definition at line 33 of file Email.java.
Referenced by Email.Email(), and Email.setRecipient().
String subject_M protected
String containing the subject line.
Definition at line 35 of file Email.java.
String messageBody_M protected
String containing the message body.
Definition at line 37 of file Email.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/net/email/Email.java