My Project: openDMS.view.UIViews Class Reference
openDMS.view.UIViews Class Reference
Public Member Functions
UIViews ()
Map< String, String > createViews ()
Private Member Functions
void populateRootView ()
void populateEbayView ()
Private Attributes
Map< String, String > views_M
Detailed Description
This represents the Views for the system. it provides functionality to create the views as a mapping of String keys to html strings.
Author
Jan P.C. Hanson
Definition at line 28 of file UIViews.java.
Constructor & Destructor Documentation
openDMS.view.UIViews.UIViews ()
default constructor
Definition at line 36 of file UIViews.java.
Member Function Documentation
Map<String, String> openDMS.view.UIViews.createViews ()
creates the views
Returns
Map<String, String> the html contained in the files stored in the 'res' folder mapped to string identifiers.
Definition at line 47 of file UIViews.java.
References openDMS.view.UIViews.populateEbayView(), openDMS.view.UIViews.populateRootView(), and openDMS.view.UIViews.views_M.
void openDMS.view.UIViews.populateEbayView () private
populat5e the internal map with the html for the ebay view
Definition at line 65 of file UIViews.java.
References openDMS.helpers.FileToString.convert().
Referenced by openDMS.view.UIViews.createViews().
void openDMS.view.UIViews.populateRootView () private
populate the internal map with the html for the root view
Definition at line 57 of file UIViews.java.
References openDMS.helpers.FileToString.convert().
Referenced by openDMS.view.UIViews.createViews().
Member Data Documentation
Map<String, String> openDMS.view.UIViews.views_M private
mapping of String identifiers to html strings
Definition at line 31 of file UIViews.java.
Referenced by openDMS.view.UIViews.createViews().
The documentation for this class was generated from the following file:
src/openDMS/view/UIViews.java