TomoBay: OrdersCall Class Reference
OrdersCall Class Reference
This represents an eBay API call that requests information about an order.
Public Member Functions
OrdersCall (String usrToken, String server)
constructor, initialises the OrdersCall using the credentials passed in.
OrderType[] call (int numOfDays) throws ApiException, SdkException, Exception
This method performs a call to the API grabbing a list of orders for the specified number of days.
OrderType[] call (String orderID) throws ApiException, SdkException, Exception
this method performs a call to the API grabbing the order associated with the ID passed in.
Static Package Attributes
static Logger log = Logger.getLogger(OrdersCall.class.getName())
Private Member Functions
void setUpCall (int numOfDays)
this method does some setup for the API call
PaginationType setUpPagination ()
do setup for the pagination.
OrderType[] reformResults (List< OrderType[]> results)
convert the List<OrderType[]> passed in as an argument to a single OrderType[] containing all of the elements in the same order.
Private Attributes
GetOrdersCall order_M
holder for the call object
GetOrdersRequestType ordreq_M
holder for request object
Static Private Attributes
static final int PAGE_NO_MIN = 1
Additional Inherited Members
Protected Member Functions inherited from AbstractAPIcall
AbstractAPIcall (String usrToken, String server)
this constructor initialises the Abstract query with a usr token and server string, these are needed so that it can properly assign an ApiContext to the call.
Protected Attributes inherited from AbstractAPIcall
String usrToken_M
holder for the user token string provided in the construction of this object
String server_M
holder for the server string provided in the construction of this object
Detailed Description
This represents an eBay API call that requests information about an order.
Author
Jan P.C. Hanson
Definition at line 36 of file OrdersCall.java.
Constructor & Destructor Documentation
OrdersCall (String usrToken, String server)
constructor, initialises the OrdersCall using the credentials passed in.
Parameters
usrToken
server
Definition at line 51 of file OrdersCall.java.
References APIcontext.apiContext(), and APIcontext.instance().
Member Function Documentation
OrderType [] call (int numOfDays) throws ApiException, SdkException, Exception
This method performs a call to the API grabbing a list of orders for the specified number of days.
Parameters
numOfDays the number of days to get data for
Returns
OrderType[] and array where each element contains order specific data type
Exceptions
Exception
SdkException
ApiException
Definition at line 68 of file OrdersCall.java.
References OrdersCall.PAGE_NO_MIN, OrdersCall.reformResults(), OrdersCall.setUpCall(), and OrdersCall.setUpPagination().
Referenced by OnRunning.execute().
OrderType [] call (String orderID) throws ApiException, SdkException, Exception
this method performs a call to the API grabbing the order associated with the ID passed in.
Parameters
orderID
Returns
Exceptions
ApiException
SdkException
Exception
Definition at line 95 of file OrdersCall.java.
void setUpCall (int numOfDays) private
this method does some setup for the API call
Parameters
numOfDays the number of days to look back for results
Definition at line 107 of file OrdersCall.java.
Referenced by OrdersCall.call().
PaginationType setUpPagination () private
do setup for the pagination.
Returns
PaginationType containing this setup.
Definition at line 124 of file OrdersCall.java.
References OrdersCall.PAGE_NO_MIN.
Referenced by OrdersCall.call().
OrderType [] reformResults (List< OrderType[]> results) private
convert the List<OrderType[]> passed in as an argument to a single OrderType[] containing all of the elements in the same order.
Parameters
results the List<OrderType[]> to convert
Returns
OrderType[] containing all the elements of the arrays in the List<OrderType[]>
Definition at line 139 of file OrdersCall.java.
Referenced by OrdersCall.call().
Member Data Documentation
Logger log = Logger.getLogger(OrdersCall.class.getName()) static package
Definition at line 38 of file OrdersCall.java.
GetOrdersCall order_M private
holder for the call object
Definition at line 40 of file OrdersCall.java.
GetOrdersRequestType ordreq_M private
holder for request object
Definition at line 42 of file OrdersCall.java.
final int PAGE_NO_MIN = 1 static private
Definition at line 44 of file OrdersCall.java.
Referenced by OrdersCall.call(), and OrdersCall.setUpPagination().
The documentation for this class was generated from the following file:
src/tomoBay/model/eBayAPI/OrdersCall.java