My Project: openDMS.model.eBayAPI.ItemCall Class Reference
openDMS.model.eBayAPI.ItemCall Class Reference
Public Member Functions
ItemCall (String usrToken, String server)
ItemType call (String itemId) throws ApiException, SdkException, Exception
Additional Inherited Members
Protected Member Functions inherited from openDMS.model.eBayAPI.AbstractAPIcall
AbstractAPIcall (String usrToken, String server)
Protected Attributes inherited from openDMS.model.eBayAPI.AbstractAPIcall
String usrToken_M
String server_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 28 of file ItemCall.java.
Constructor & Destructor Documentation
openDMS.model.eBayAPI.ItemCall.ItemCall (String usrToken, String server)
constructor, calls superconstructor and
Parameters
usrToken
server
Definition at line 40 of file ItemCall.java.
References openDMS.model.eBayAPI.APIcontext.apiContext(), and openDMS.model.eBayAPI.APIcontext.instance().
Member Function Documentation
ItemType openDMS.model.eBayAPI.ItemCall.call (String itemId) throws ApiException, SdkException, Exception
This method performs a call to the API grabbing a item data for the specified itemID.
Parameters
data an ApiOrderData object to populate with the orders
itemID the itemID found from the order data
Returns
ItemType containing all item specific data
Exceptions
Exception
SdkException
ApiException
Definition at line 58 of file ItemCall.java.
Referenced by openDMS.model.services.basicEbayUpdate.ItemsTable.populate().
The documentation for this class was generated from the following file:
src/openDMS/model/eBayAPI/ItemCall.java