TomoBay: PrintInvoices Class Reference
PrintInvoices Class Reference
Public Member Functions
PrintInvoices ()
default ctor
String execute (String data)
performs the action specified
Static Package Attributes
static final Logger log = Logger.getLogger(PrintInvoices.class.getName())
Private Member Functions
String[] splitOrderNoString (String orderNos)
splits the 'data' string into a string array
DualList< String, PayloadType > formatAsDualList (String invoiceNo, String brand, String packingList)
formats the AbstractSalesDayBookLine into a format that can be passed to the WinstockCommandInvoker.
String print (DualList< String, PayloadType > printThis, AbstractSalesDayBookLine line)
actually send the data to the winstock server to print the invoice
Detailed Description
Author
Jan P.C. Hanson
Definition at line 37 of file PrintInvoices.java.
Constructor & Destructor Documentation
PrintInvoices ()
default ctor
Definition at line 43 of file PrintInvoices.java.
Member Function Documentation
String execute (String data)
performs the action specified
Returns
String representing the results of the performed action.
Implements AbstractPresenterAction.
Definition at line 50 of file PrintInvoices.java.
References Part.brand(), BrandToCode.convertToWinstockInt(), PrintInvoices.formatAsDualList(), SalesDayBookLineFactory.SalesDayBookLineType.INVOICE, AbstractSalesDayBookLine.invoiceNumber(), Transaction.listing(), SalesDayBookLineFactory.make(), AbstractSalesDayBookLine.orderInfo(), Listing.part(), PrintInvoices.print(), PrintInvoices.splitOrderNoString(), and Order.transaction().
String [] splitOrderNoString (String orderNos) private
splits the 'data' string into a string array
Parameters
orderNos the 'data' string
Returns
String[] containing all the orderNos in the original 'data' string
Definition at line 82 of file PrintInvoices.java.
Referenced by PrintInvoices.execute().
DualList<String, PayloadType> formatAsDualList (String invoiceNo, String brand, String packingList) private
formats the AbstractSalesDayBookLine into a format that can be passed to the WinstockCommandInvoker.
Parameters
invoiceNo the invoice to be formatted
brand the brand code associated with the invoice to be printed
packingList the number of packing lists you wish printed (as a string)
Returns
DualList<String, PayloadType> accepted by the WinstockCommandInvoker
Definition at line 92 of file PrintInvoices.java.
References PayloadType.COMPANY, PayloadType.INVOICE_NO, PayloadType.PACKING_LISTS, PayloadType.PRINT_COPIES, DualList< V1, V2 >.put(), and PayloadType.TYPE.
Referenced by PrintInvoices.execute().
String print (DualList< String, PayloadType > printThis, AbstractSalesDayBookLine line) private
actually send the data to the winstock server to print the invoice
Parameters
printThis the data to print
line the AbstractSalesDayBookLine containing the line info
Returns
String containing an appropriate response.
Definition at line 109 of file PrintInvoices.java.
References WinstockCommandInvoker.execute(), AbstractSalesDayBookLine.invoiceNumber(), AbstractWinstockCommandResponse.isSuccess(), WinstockCommandInvoker.WinstockCommandTypes.PrintInvoice, ResultCodes.SUCCESS, and StackTraceToString.toString().
Referenced by PrintInvoices.execute().
Member Data Documentation
final Logger log = Logger.getLogger(PrintInvoices.class.getName()) static package
Definition at line 39 of file PrintInvoices.java.
The documentation for this class was generated from the following file:
src/tomoBay/presenters/presenterActions/concreteActions/PrintInvoices.java