TomoBay: WinstockCommandInvoker Class Reference
WinstockCommandInvoker Class Reference
This class acts as the Invoker in a GoF style command pattern, it is responsible for the execution of AbstractWinstockCommands.
Classes
enum WinstockCommandTypes
defensive enum used to limit the amount of acceptable inputs to this invoker
Static Public Member Functions
static AbstractWinstockCommandResponse execute (WinstockCommandInvoker.WinstockCommandTypes commandType, DualList< String, PayloadType > commandInfo) throws UnknownHostException, IOException, PayloadException
This method executes the AbstractWinstockCommand that the user has requested.
Static Private Attributes
static final Map< WinstockCommandTypes, AbstractWinstockCommandFactory > factoryMap_M
internal Map responsible for associating a WinstockCommandTypes with its corresponding AbstractWinstockCommandFactory object.
Detailed Description
This class acts as the Invoker in a GoF style command pattern, it is responsible for the execution of AbstractWinstockCommands.
In this case it is also a factory and as such is responsible for the creation of these concrete command objects. The internal Enum defines the acceptable range of commands that can be created.
Author
Jan P.C. Hanson
See also
https://dzone.com/articles/design-patterns-command
https://dzone.com/articles/design-patterns-factory
Definition at line 42 of file WinstockCommandInvoker.java.
Member Function Documentation
static AbstractWinstockCommandResponse execute (WinstockCommandInvoker.WinstockCommandTypes commandType, DualList< String, PayloadType > commandInfo) throws UnknownHostException, IOException, PayloadException static
This method executes the AbstractWinstockCommand that the user has requested.
Parameters
commandType contains the type of winstock command that is being called
commandInfo contains the information to perform the command
See also
tomoBay.model.winstock.WinstockCommandInvoker.WinstockCommandTypes
Returns
AbstractWinstockCommandResponse containing the servers response to this command.
Exceptions
IOException
UnknownHostException
PayloadException
Definition at line 75 of file WinstockCommandInvoker.java.
References WinstockCommandInvoker.factoryMap_M.
Referenced by InvoiceOrders.execute(), PrintInvoices.print(), and ClientSocketTest.test().
Member Data Documentation
final Map<WinstockCommandTypes, AbstractWinstockCommandFactory> factoryMap_M static private
Initial value:
= new THashMap<WinstockCommandTypes, AbstractWinstockCommandFactory>()
        {{
            put(WinstockCommandInvoker.WinstockCommandTypes.PutInvoice, new PutInvoiceCommandFactory());
            put(WinstockCommandInvoker.WinstockCommandTypes.PrintInvoice, new PrintInvoiceCommandFactory());
        }}
internal Map responsible for associating a WinstockCommandTypes with its corresponding AbstractWinstockCommandFactory object.
Definition at line 58 of file WinstockCommandInvoker.java.
Referenced by WinstockCommandInvoker.execute().
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/WinstockCommandInvoker.java