TomoBay: ConfigReader Class Reference
ConfigReader Class Reference
naive config file reader.
Public Member Functions
ConfigReader ()
Default ctor.
Static Public Member Functions
static String getConf (Config configVar)
find the value of the config variable specified in the arguments.
static String getConf (Config configVar, int index)
find the value of the config variable specified in the arguments.
static String[] getConfs (Config configVar)
Find all values of the specified config variable, if multiple instances exist then the array will be the same size as the number of instances.
static int size (Config configVar)
find out how many instances of a particular config variable exist within the config file.
Static Private Member Functions
static String getConfig (String filePath, String fileName, String charSet)
reads the whole config file into a string
Detailed Description
naive config file reader.
takes individual lines of a file and converts it to an array of strings.
Author
Jan P.C. Hanson
Definition at line 31 of file ConfigReader.java.
Constructor & Destructor Documentation
ConfigReader ()
Default ctor.
Definition at line 36 of file ConfigReader.java.
Member Function Documentation
static String getConfig (String filePath, String fileName, String charSet) static private
reads the whole config file into a string
Parameters
filePath the path to the config file (without the file name on the end)
fileName the name of the file as it is on the file system
charSet the character set to use to encode the result.
Returns
String containing the contents of the config file.
Definition at line 47 of file ConfigReader.java.
Referenced by ConfigReader.getConf(), ConfigReader.getConfs(), and ConfigReader.size().
static String getConf (Config configVar) static
find the value of the config variable specified in the arguments.
If multiple instances of this variable exist then it will return the first instance. To find all values for a config variable with multiple instances use getConfs().
Parameters
configVar the config variable to find the value of
Returns
String containing the value of the config variable.
Definition at line 72 of file ConfigReader.java.
References ConfigReader.getConfig(), Config.getVar(), and XMLParser.parse().
Referenced by ConnectionManager.ConnectionManager(), Friday.endTime(), Monday.endTime(), Sunday.endTime(), Thursday.endTime(), Saturday.endTime(), Tuesday.endTime(), Wednesday.endTime(), WinstockConfig.getMachineName(), WinstockConfig.getPort(), Stock.requestInvoiceWeight(), MailClient.send(), EmailErrorsMailActions.send(), Monday.startTime(), Sunday.startTime(), Friday.startTime(), Wednesday.startTime(), Tuesday.startTime(), Thursday.startTime(), and Saturday.startTime().
static String getConf (Config configVar, int index) static
find the value of the config variable specified in the arguments.
If multiple instances of this variable exist then it will return the first instance. To find all values for a config variable with multiple instances use getConfs().
Parameters
configVar the config variable to find the value of
index the index of the config variable instance you wish to find.
Returns
String containing the value of the config variable.
Definition at line 86 of file ConfigReader.java.
References ConfigReader.getConfig(), Config.getVar(), and XMLParser.parseAll().
static String [] getConfs (Config configVar) static
Find all values of the specified config variable, if multiple instances exist then the array will be the same size as the number of instances.
for single instance variables the size with be 1.
Parameters
configVar the config variable to find values of.
Returns
String[] containing all the values of the given config variable.
Definition at line 101 of file ConfigReader.java.
References ConfigReader.getConfig(), Config.getVar(), and XMLParser.parseAll().
Referenced by Shipping_Priority.populatePriorityMap(), and RoyalMailCSVGenerator.RoyalMailCSVGenerator().
static int size (Config configVar) static
find out how many instances of a particular config variable exist within the config file.
Remember indices should go from 0 to size-1
Parameters
configVar the config variable to count
Returns
int the number instances of the config variable provided
Definition at line 118 of file ConfigReader.java.
References ConfigReader.getConfig(), Config.getVar(), and XMLParser.parseAll().
Referenced by RoyalMailCSVGeneratorTest.testSize().
The documentation for this class was generated from the following file:
src/tomoBay/helpers/ConfigReader.java