TomoBay: APIcontext Class Reference
APIcontext Class Reference
This class contains functionality to provide an APIContext object which is used by API calls in order to authorise an API call.
Public Member Functions
ApiContext apiContext (String usrToken, String server)
used for getting an ApiContext object that can then be passed to individual API calls.
Static Public Member Functions
static APIcontext instance ()
Used instead of constructor for getting an APIcontext instance.
Private Member Functions
APIcontext ()
private constructor, Singleton
Static Private Attributes
static final APIcontext instance_M = new APIcontext()
instance variable holds singleton instance
Detailed Description
This class contains functionality to provide an APIContext object which is used by API calls in order to authorise an API call.
It is a Singleton
Author
Jan P.C. Hanson
Definition at line 26 of file APIcontext.java.
Constructor & Destructor Documentation
APIcontext () private
private constructor, Singleton
Definition at line 34 of file APIcontext.java.
Member Function Documentation
static APIcontext instance () static
Used instead of constructor for getting an APIcontext instance.
Returns
the singleton instance
Definition at line 41 of file APIcontext.java.
References APIcontext.instance_M.
Referenced by ItemCall.ItemCall(), ListingsCall.ListingsCall(), OrdersCall.OrdersCall(), and OrderTransactionsCall.OrderTransactionsCall().
ApiContext apiContext (String usrToken, String server)
used for getting an ApiContext object that can then be passed to individual API calls.
Parameters
usrToken an eBay API user token
server the server to use for api calls (https://api.sandbox.ebay.com/wsapi for testing and XXXXXXXXXXXXX for production)
Returns
ApiContext object.
Definition at line 52 of file APIcontext.java.
Referenced by ItemCall.ItemCall(), ListingsCall.ListingsCall(), OrdersCall.OrdersCall(), and OrderTransactionsCall.OrderTransactionsCall().
Member Data Documentation
final APIcontext instance_M = new APIcontext() static private
instance variable holds singleton instance
Definition at line 29 of file APIcontext.java.
Referenced by APIcontext.instance().
The documentation for this class was generated from the following file:
src/tomoBay/model/eBayAPI/APIcontext.java