My Project: openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers Class Reference
openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers Class Reference
Public Member Functions
InsertEbayBuyers ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
Author
Jan P.C. Hanson
Definition at line 30 of file InsertEbayBuyers.java.
Constructor & Destructor Documentation
openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.InsertEbayBuyers ()
default constructor
Definition at line 44 of file InsertEbayBuyers.java.
Member Function Documentation
void openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 89 of file InsertEbayBuyers.java.
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.execute().
List<String[]> openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. The Ebay Orders Table only has 3 columns so any element above the 2nd element will be ignored. col1 =buyerID:varchar(40), col2=name:varchar(45), col3=address:varchar(150),
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements openDMS.model.sql.queries.AbstractDBQuery.
Definition at line 57 of file InsertEbayBuyers.java.
References openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.cleanup(), and openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.initQuery().
void openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 78 of file InsertEbayBuyers.java.
References openDMS.model.sql.ConnectionManager.getConnection(), and openDMS.model.sql.ConnectionManager.instance().
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.execute().
Member Data Documentation
Connection openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.connection_M = null private
reference to the JDBC Database connection
Definition at line 35 of file InsertEbayBuyers.java.
String openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.query private
Initial value:
="INSERT IGNORE INTO ebay.ebay_buyers "
            + "(buyerID, name, shippingAddress)"
            + "VALUES (?,?,?);"
SQL query string
Definition at line 37 of file InsertEbayBuyers.java.
PreparedStatement openDMS.model.sql.queries.concreteQueries.InsertEbayBuyers.statement_M = null private
reference to the JDBC Statement
Definition at line 33 of file InsertEbayBuyers.java.
The documentation for this class was generated from the following file:
src/openDMS/model/sql/queries/concreteQueries/InsertEbayBuyers.java