My Project: openDMS.helpers.ConfigReader Class Reference
openDMS.helpers.ConfigReader Class Reference
Static Public Member Functions
static String[] read (String pathToFile, String fileName)
Static Private Member Functions
static String convert (String filePath, String fileName, String charSet)
Detailed Description
Author
Jan P.C. Hanson
Definition at line 29 of file ConfigReader.java.
Member Function Documentation
static String openDMS.helpers.ConfigReader.convert (String filePath, String fileName, String charSet) static private
Definition at line 50 of file ConfigReader.java.
Referenced by openDMS.helpers.ConfigReader.read().
static String [] openDMS.helpers.ConfigReader.read (String pathToFile, String fileName) static
reads a config file and passes back an list of strings representing different lines in the config file specified. It is important when constructing config files to put the correct setting on the correct line. line 1 = sandbox server string, line 2 = sandbox user token, line 3 = production server string, line 4 = production user token.
Parameters
pathToFile the path to the file including the trailing slash
fileName the actual filename
Returns
List<String> containing the various lines of the config file. String[0] = blank, String[1] = sandbox server string, String[2] = sandbox user token String[3] = production server string, String[4] = production user token.
Definition at line 43 of file ConfigReader.java.
References openDMS.helpers.ConfigReader.convert().
Referenced by openDMS.model.sql.ConnectionManager.ConnectionManager(), and openDMS.model.services.basicEbayUpdate.BasicEbayUpdateService.run().
The documentation for this class was generated from the following file:
src/openDMS/helpers/ConfigReader.java