My Project: openDMS.view.views.EbayView Class Reference
openDMS.view.views.EbayView Class Reference
Classes
enum Part
Public Member Functions
EbayView ()
String make (AbstractViewPart part)
Protected Member Functions
void populateMap ()
Private Attributes
Map< Part, String > viewPart_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 26 of file EbayView.java.
Constructor & Destructor Documentation
openDMS.view.views.EbayView.EbayView ()
default constructor
Definition at line 36 of file EbayView.java.
References openDMS.view.views.EbayView.populateMap().
Member Function Documentation
String openDMS.view.views.EbayView.make (AbstractViewPart part)
This method constructs the part of the view that is requested in the parameters.
Parameters
part should be taken from the internal Enum defined within this class. Each enum constant refers to a specific part of the view.
Returns
String containing the HTML for the part of the view that has been requested.
Implements openDMS.view.views.AbstractView.
Definition at line 47 of file EbayView.java.
void openDMS.view.views.EbayView.populateMap () protected
populates the map with the
Definition at line 53 of file EbayView.java.
References openDMS.helpers.FileToString.convert(), openDMS.view.views.EbayView.Part.FOOTER, and openDMS.view.views.EbayView.Part.HEADER.
Referenced by openDMS.view.views.EbayView.EbayView().
Member Data Documentation
Map<Part, String> openDMS.view.views.EbayView.viewPart_M private
mapping of enum constant keys to html strings
Definition at line 29 of file EbayView.java.
The documentation for this class was generated from the following file:
src/openDMS/view/views/EbayView.java