TomoBay: AbstractEmailBuilder Class Reference
AbstractEmailBuilder Class Reference abstract
Copyright(C) 2015 Jan P.C.
Protected Member Functions
AbstractEmailBuilder ()
default constructor
abstract void buildMailServerSendConnection ()
populates the MailServerSend object with a specific configuration
void buildEmail ()
builds the Email object
Protected Attributes
MailServerSend mailServer_M
holder for Sending Mail server
Email email_M
Holder for email object.
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/. This is the abstract base class for all the concrete email builders. Each derived class represents a different mail server.
Author
Jan P.C. Hanson
Definition at line 24 of file AbstractEmailBuilder.java.
Constructor & Destructor Documentation
AbstractEmailBuilder () protected
default constructor
Definition at line 34 of file AbstractEmailBuilder.java.
References AbstractEmailBuilder.buildMailServerSendConnection().
Member Function Documentation
abstract void buildMailServerSendConnection () abstract protected
populates the MailServerSend object with a specific configuration
Referenced by AbstractEmailBuilder.AbstractEmailBuilder(), and EmailDirector.constructEmailAndServer().
void buildEmail () protected
builds the Email object
Definition at line 48 of file AbstractEmailBuilder.java.
Referenced by EmailDirector.constructEmailAndServer().
Member Data Documentation
MailServerSend mailServer_M protected
holder for Sending Mail server
Definition at line 27 of file AbstractEmailBuilder.java.
Referenced by EmailDirector.getMailSendServer().
Email email_M protected
Holder for email object.
Definition at line 29 of file AbstractEmailBuilder.java.
Referenced by EmailDirector.getEmail().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/net/email/AbstractEmailBuilder.java