My Project: openDMS.model.sql.queries.concreteQueries.SelectEbayItems Class Reference
openDMS.model.sql.queries.concreteQueries.SelectEbayItems Class Reference
Public Member Functions
SelectEbayItems ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
List< String[]> formatResults (ResultSet results) throws SQLException
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement selectStatement_M = null
Connection connection_M = null
String query
Detailed Description
Author
Jan P.C. Hanson
Definition at line 31 of file SelectEbayItems.java.
Constructor & Destructor Documentation
openDMS.model.sql.queries.concreteQueries.SelectEbayItems.SelectEbayItems ()
default constructor
Definition at line 47 of file SelectEbayItems.java.
Member Function Documentation
void openDMS.model.sql.queries.concreteQueries.SelectEbayItems.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 105 of file SelectEbayItems.java.
Referenced by openDMS.model.sql.queries.concreteQueries.SelectEbayItems.execute().
List<String[]> openDMS.model.sql.queries.concreteQueries.SelectEbayItems.execute (String[] parameter) throws SQLException
execute the query
Parameters
NOT USED
Returns
List<String[]> representing the results of the query. The list contains only 1 column the itemID, so each list element contains a String[1] which contains
Exceptions
SQLException
Implements openDMS.model.sql.queries.AbstractDBQuery.
Definition at line 57 of file SelectEbayItems.java.
References openDMS.model.sql.queries.concreteQueries.SelectEbayItems.cleanup(), openDMS.model.sql.queries.concreteQueries.SelectEbayItems.formatResults(), and openDMS.model.sql.queries.concreteQueries.SelectEbayItems.initQuery().
List<String[]> openDMS.model.sql.queries.concreteQueries.SelectEbayItems.formatResults (ResultSet results) throws SQLException private
formats the ResultSet (returned from the executed query) as a string
Parameters
results the ResultSet (post query execution)
Returns
String containing the formatted results.
Exceptions
SQLException
Definition at line 78 of file SelectEbayItems.java.
Referenced by openDMS.model.sql.queries.concreteQueries.SelectEbayItems.execute().
void openDMS.model.sql.queries.concreteQueries.SelectEbayItems.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 94 of file SelectEbayItems.java.
References openDMS.model.sql.ConnectionManager.getConnection(), and openDMS.model.sql.ConnectionManager.instance().
Referenced by openDMS.model.sql.queries.concreteQueries.SelectEbayItems.execute().
Member Data Documentation
Connection openDMS.model.sql.queries.concreteQueries.SelectEbayItems.connection_M = null private
reference to the JDBC Database connection
Definition at line 36 of file SelectEbayItems.java.
String openDMS.model.sql.queries.concreteQueries.SelectEbayItems.query private
Initial value:
="SELECT DISTINCT ebay_transactions.itemID "
            + "FROM ebay_transactions "
            + "WHERE ebay_transactions.itemID "
            + "NOT IN (SELECT DISTINCT ebay_items.itemID FROM ebay_items);"
SQL query string
Definition at line 38 of file SelectEbayItems.java.
PreparedStatement openDMS.model.sql.queries.concreteQueries.SelectEbayItems.selectStatement_M = null private
reference to the JDBC Statement
Definition at line 34 of file SelectEbayItems.java.
The documentation for this class was generated from the following file:
src/openDMS/model/sql/queries/concreteQueries/SelectEbayItems.java