My Project: openDMS.ebay.query.data.ApiItemData Class Reference
openDMS.ebay.query.data.ApiItemData Class Reference
Public Member Functions
ApiItemData ()
void addData (ItemType item)
ItemType accessData (int index)
void removeData (int index)
void clearData ()
Private Attributes
List< ItemType > items_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 27 of file ApiItemData.java.
Constructor & Destructor Documentation
openDMS.ebay.query.data.ApiItemData.ApiItemData ()
Definition at line 32 of file ApiItemData.java.
Member Function Documentation
ItemType openDMS.ebay.query.data.ApiItemData.accessData (int index)
access ItemType data of the ApiCallData
Parameters
index the index of the data you wish to access
Returns
ItemType
Definition at line 49 of file ApiItemData.java.
Referenced by openDMS.ebay.query.commands.GetItemCommand.execute().
void openDMS.ebay.query.data.ApiItemData.addData (ItemType item)
add ItemType data to the ApiCallData
Parameters
transaction the TransactionType to add
Definition at line 41 of file ApiItemData.java.
Referenced by openDMS.ebay.query.recievers.ItemCall.call().
void openDMS.ebay.query.data.ApiItemData.clearData ()
clears all data from this object
Definition at line 62 of file ApiItemData.java.
Referenced by openDMS.ebay.query.commands.GetItemCommand.execute().
void openDMS.ebay.query.data.ApiItemData.removeData (int index)
removes data at a specific index
Parameters
index
Definition at line 56 of file ApiItemData.java.
Member Data Documentation
List<ItemType> openDMS.ebay.query.data.ApiItemData.items_M private
holder for ItemTypes
Definition at line 30 of file ApiItemData.java.
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/data/ApiItemData.java