My Project: openDMS.model.sql.queries.concreteQueries.InsertEbayItems Class Reference
openDMS.model.sql.queries.concreteQueries.InsertEbayItems Class Reference
Public Member Functions
InsertEbayItems ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
Author
Jan P.C. Hanson
Definition at line 32 of file InsertEbayItems.java.
Constructor & Destructor Documentation
openDMS.model.sql.queries.concreteQueries.InsertEbayItems.InsertEbayItems ()
default constructor
Definition at line 46 of file InsertEbayItems.java.
Member Function Documentation
void openDMS.model.sql.queries.concreteQueries.InsertEbayItems.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 93 of file InsertEbayItems.java.
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayItems.execute().
List<String[]> openDMS.model.sql.queries.concreteQueries.InsertEbayItems.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. The Ebay Orders Table only has 5 columns so any element above the 4th element will be ignored. col1 =itemID:varchar(11), col2=title:varchar(83), col3=sellCondition:varchar(15), col4=brand:varchar(45), col5=varchar(100)
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements openDMS.model.sql.queries.AbstractDBQuery.
Definition at line 60 of file InsertEbayItems.java.
References openDMS.model.sql.queries.concreteQueries.InsertEbayItems.cleanup(), and openDMS.model.sql.queries.concreteQueries.InsertEbayItems.initQuery().
void openDMS.model.sql.queries.concreteQueries.InsertEbayItems.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 82 of file InsertEbayItems.java.
References openDMS.model.sql.ConnectionManager.getConnection(), and openDMS.model.sql.ConnectionManager.instance().
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayItems.execute().
Member Data Documentation
Connection openDMS.model.sql.queries.concreteQueries.InsertEbayItems.connection_M = null private
reference to the JDBC Database connection
Definition at line 37 of file InsertEbayItems.java.
String openDMS.model.sql.queries.concreteQueries.InsertEbayItems.query private
Initial value:
="INSERT IGNORE INTO ebay.ebay_items "
            + "(itemID, title, sellCondition, brand, partNo)"
            + "VALUES (?,?,?,?,?);"
SQL query string
Definition at line 39 of file InsertEbayItems.java.
PreparedStatement openDMS.model.sql.queries.concreteQueries.InsertEbayItems.statement_M = null private
reference to the JDBC Statement
Definition at line 35 of file InsertEbayItems.java.
The documentation for this class was generated from the following file:
src/openDMS/model/sql/queries/concreteQueries/InsertEbayItems.java