TomoBay: AbstractSelectQuery Class Reference
AbstractSelectQuery Class Reference abstract
Public Member Functions
AbstractSelectQuery ()
default ctor
Public Member Functions inherited from AbstractDBQuery
PreparedStatement statement ()
get the statement object associated with this query
Protected Member Functions
abstract List< HeteroFieldContainer > format (ResultSet resultSet) throws SQLException
the results from a select query come in the form of a ResultSet object, this needs to be closed before the connection can be closed, however once the Resultset is closed it is impossible to get any data from it, so before it is closed the data needs transferring to a DBFieldContainer object.
Protected Member Functions inherited from AbstractDBQuery
abstract String queryString ()
Used by derived classes to define the Query string to be used in the query.
void cleanup () throws SQLException
commits the transaction and does cleanup after the query has been executed
Additional Inherited Members
Protected Attributes inherited from AbstractDBQuery
PreparedStatement statement_M = null
reference to the JDBC Statement
Connection connection_M = null
reference to the JDBC Database connection
Detailed Description
Author
Jan P.C. Hanson
Definition at line 30 of file AbstractSelectQuery.java.
Constructor & Destructor Documentation
AbstractSelectQuery ()
default ctor
Definition at line 36 of file AbstractSelectQuery.java.
References AbstractSelectQuery.format().
Member Function Documentation
abstract List<HeteroFieldContainer> format (ResultSet resultSet) throws SQLException abstract protected
the results from a select query come in the form of a ResultSet object, this needs to be closed before the connection can be closed, however once the Resultset is closed it is impossible to get any data from it, so before it is closed the data needs transferring to a DBFieldContainer object.
Parameters
resultSet the ResultSet to format
Returns
DBFieldContainer containing the relevant data
Referenced by AbstractSelectQuery.AbstractSelectQuery(), AbstractSelectNoParamsQuery.execute(), and AbstractSelectParamsQuery.execute().
The documentation for this class was generated from the following file:
/home/orpheus/projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/sql/framework/queryTypes/select/AbstractSelectQuery.java