TomoBay: AbstractWinstockCommand Class Reference
AbstractWinstockCommand Class Reference abstract
This is the abstract base class for all Winstock commands, and acts as the abstract command in a GoF style command pattern.
Public Member Functions
abstract AbstractWinstockCommandResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException
this method executes the AbstractWinstockCommand specific to the derived type.
Protected Member Functions
AbstractWinstockCommand () throws UnknownHostException, IOException
default ctor, does preliminary initailisation of the config object and socket connection to Winstock.
Protected Attributes
WinstockConfig config_M
client socket connection
ClientSocket winstockConnection_M
the configuration details
Detailed Description
This is the abstract base class for all Winstock commands, and acts as the abstract command in a GoF style command pattern.
Author
Jan P.C. Hanson
See also
https://dzone.com/articles/design-patterns-command
Definition at line 34 of file AbstractWinstockCommand.java.
Constructor & Destructor Documentation
AbstractWinstockCommand () throws UnknownHostException, IOException protected
default ctor, does preliminary initailisation of the config object and socket connection to Winstock.
Exceptions
UnknownHostException
IOException
Definition at line 47 of file AbstractWinstockCommand.java.
References AbstractWinstockCommand.execute(), WinstockConfig.getMachineName(), and WinstockConfig.getPort().
Member Function Documentation
abstract AbstractWinstockCommandResponse execute (DualList< String, PayloadType > commandInfo) throws IOException, PayloadException abstract
this method executes the AbstractWinstockCommand specific to the derived type.
Returns
AbstractWinstockCommandRepsonse containing the results of the command.
Referenced by AbstractWinstockCommand.AbstractWinstockCommand().
Member Data Documentation
WinstockConfig config_M protected
client socket connection
Definition at line 37 of file AbstractWinstockCommand.java.
ClientSocket winstockConnection_M protected
the configuration details
Definition at line 39 of file AbstractWinstockCommand.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/winstock/commands/AbstractWinstockCommand.java