My Project: openDMS.ebay.query.data.ApiOrderData Class Reference
openDMS.ebay.query.data.ApiOrderData Class Reference
Public Member Functions
ApiOrderData ()
void addData (OrderType order)
OrderType accessData (int index)
void removeData (int index)
void clearData ()
int size ()
Private Attributes
List< OrderType > orders_M
Detailed Description
Author
Jan P.C. Hanson
Definition at line 26 of file ApiOrderData.java.
Constructor & Destructor Documentation
openDMS.ebay.query.data.ApiOrderData.ApiOrderData ()
constructor
Definition at line 34 of file ApiOrderData.java.
Member Function Documentation
OrderType openDMS.ebay.query.data.ApiOrderData.accessData (int index)
access NameValueListType data of the ApiCallData
Parameters
index the index of the data you wish to access
Returns
OrderType
Definition at line 49 of file ApiOrderData.java.
Referenced by openDMS.ebay.query.commands.GetOrderListCommand.execute().
void openDMS.ebay.query.data.ApiOrderData.addData (OrderType order)
add OrderType data to the ApiCallData
Parameters
order the OrderType to add
Definition at line 41 of file ApiOrderData.java.
Referenced by openDMS.ebay.query.recievers.OrdersCall.call().
void openDMS.ebay.query.data.ApiOrderData.clearData ()
clears all data from this object
Definition at line 62 of file ApiOrderData.java.
Referenced by openDMS.ebay.query.commands.GetOrderListCommand.execute().
void openDMS.ebay.query.data.ApiOrderData.removeData (int index)
removes data at a specific index
Parameters
index
Definition at line 56 of file ApiOrderData.java.
int openDMS.ebay.query.data.ApiOrderData.size ()
return the number of entries in the ApiOrderData
Returns
int representing the number of entries.
Definition at line 69 of file ApiOrderData.java.
Member Data Documentation
List<OrderType> openDMS.ebay.query.data.ApiOrderData.orders_M private
holder for OrderTypes
Definition at line 29 of file ApiOrderData.java.
The documentation for this class was generated from the following file:
src/openDMS/ebay/query/data/ApiOrderData.java