TomoBay: OutOfHoursPresenter Class Reference
OutOfHoursPresenter Class Reference
Public Member Functions
String present (AbstractView view, String type, String data)
this method is called when you actually want to present the information to be displayed to the appropriate view for formatting returning a string that can be displayed by the servlet.
AbstractView accept (ViewFactory viewFactory)
double dispatch method that allows the presenter to be responsible for creation of its associated view, through the use of the ViewFactory object passed in the arguments.
Private Member Functions
List< HeteroFieldContainer > removeOldOrders (List< HeteroFieldContainer > orderList)
remove orders older than the
Date ToDate (String stringDate)
Static Private Attributes
static final int OLD_ORDER_LIMIT = 30
Detailed Description
Author
Jan P.C. Hanson
Definition at line 35 of file OutOfHoursPresenter.java.
Member Function Documentation
String present (AbstractView view, String type, String data)
this method is called when you actually want to present the information to be displayed to the appropriate view for formatting returning a string that can be displayed by the servlet.
Returns
String representing the html formatted information presented to the view by this presenter.
Implements AbstractPresenter.
Definition at line 44 of file OutOfHoursPresenter.java.
References HeteroFieldContainer.add(), OutOfHoursTable.DATE, NonDBFields.DATE_COMPARISON, SelectQueryInvoker.execute(), AbstractView.format(), OutOfHoursPresenter.removeOldOrders(), and SelectQueryInvoker.SelectQueryTypeParams.SELECT_OUT_OF_HOURS_ORDERS.
AbstractView accept (ViewFactory viewFactory)
double dispatch method that allows the presenter to be responsible for creation of its associated view, through the use of the ViewFactory object passed in the arguments.
Parameters
viewFactory a ViewFactory object.
Returns
AbstractView the view associated with this particular presenter.
Implements AbstractPresenter.
Definition at line 62 of file OutOfHoursPresenter.java.
References ViewFactory.visit().
List<HeteroFieldContainer> removeOldOrders (List< HeteroFieldContainer > orderList) private
remove orders older than the
Parameters
orderList
Returns
Definition at line 70 of file OutOfHoursPresenter.java.
References ClassRef.DATE, NonDBFields.DATE_COMPARISON, and TimeStampFunctions.olderThan().
Referenced by OutOfHoursPresenter.present().
Date ToDate (String stringDate) private
Parameters
stringDate
Returns
Definition at line 86 of file OutOfHoursPresenter.java.
Member Data Documentation
final int OLD_ORDER_LIMIT = 30 static private
Definition at line 38 of file OutOfHoursPresenter.java.
The documentation for this class was generated from the following file:
src/tomoBay/presenters/sales/OutOfHoursPresenter.java