TomoBay: RoyalMailPasswordDigest Class Reference
RoyalMailPasswordDigest Class Reference
This class creates a password digest of the form seen below:
Public Member Functions
RoyalMailPasswordDigest (int nonce, Date createdDate, String password)
constructor initialises the RoyalMailPasswordDigest using the parameters: nonce, createdDate and password.
String digest ()
retrieve the digest of the password and other parameters passed into the constructor.
Private Member Functions
final byte[] sha1HashFn (String message) throws NoSuchAlgorithmException
This method creates an SHA-1 hash of the message provided.
Private Attributes
final int nonce_M
number used once
final Date createdDate_M
the date/time the api call was created, of the form: 2016-04-27T14:12:04.852Z
final String password_M
the API password
Detailed Description
This class creates a password digest of the form seen below:
digest = base64_encode(SHA-11(nonce + creationdate + SHA-1(password))
Author
Jan P.C. Hanson
Definition at line 31 of file RoyalMailPasswordDigest.java.
Constructor & Destructor Documentation
RoyalMailPasswordDigest (int nonce, Date createdDate, String password)
constructor initialises the RoyalMailPasswordDigest using the parameters: nonce, createdDate and password.
Parameters
nonce an integer value that MAY NOT repeat during at minimum a 5 minute window.
createdDate the date/time that the API call was created, of the form:
2016-04-27T14:12:04.852Z
password the API password
Definition at line 48 of file RoyalMailPasswordDigest.java.
Member Function Documentation
String digest ()
retrieve the digest of the password and other parameters passed into the constructor.
Returns
T the password digest.
Implements AbstractDigest< T >.
Definition at line 60 of file RoyalMailPasswordDigest.java.
References RoyalMailPasswordDigest.sha1HashFn().
Referenced by RoyalMailPasswordDigestTest.testDigest().
final byte [] sha1HashFn (String message) throws NoSuchAlgorithmException private
This method creates an SHA-1 hash of the message provided.
Parameters
message the message to find the SHA-1 hash of
Returns
byte[] containing the hashed message
Exceptions
NoSuchAlgorithmException
Definition at line 84 of file RoyalMailPasswordDigest.java.
Referenced by RoyalMailPasswordDigest.digest().
Member Data Documentation
final int nonce_M private
number used once
Definition at line 34 of file RoyalMailPasswordDigest.java.
final Date createdDate_M private
the date/time the api call was created, of the form: 2016-04-27T14:12:04.852Z
Definition at line 36 of file RoyalMailPasswordDigest.java.
final String password_M private
the API password
Definition at line 38 of file RoyalMailPasswordDigest.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/royalMail/RoyalMailPasswordDigest.java