My Project: openDMS.helpers.FileToString Class Reference
openDMS.helpers.FileToString Class Reference
Static Public Member Functions
static String convert (String filePath, String fileName, String charSet)
Private Member Functions
FileToString ()
Detailed Description
This is a helper class that provides functionality to convert a text based file to a string.
Author
Jan P.C. Hanson
Definition at line 28 of file FileToString.java.
Constructor & Destructor Documentation
openDMS.helpers.FileToString.FileToString () private
this class should not be instanciated
Definition at line 33 of file FileToString.java.
Member Function Documentation
static String openDMS.helpers.FileToString.convert (String filePath, String fileName, String charSet) static
uses a buffered reader to read each line from a file into a string.
Parameters
filePath the path to a particular file
fileName the name of the file to be read
charSet the Character set to use for the conversion
Returns
String containing the contents of the file.
Definition at line 43 of file FileToString.java.
Referenced by openDMS.view.UIViews.populateEbayView(), openDMS.view.views.RootView.populateMap(), openDMS.view.views.EbayView.populateMap(), and openDMS.view.UIViews.populateRootView().
The documentation for this class was generated from the following file:
src/openDMS/helpers/FileToString.java