My Project: openDMS.model.services.basicEbayUpdate.BasicEbayUpdateService Class Reference
openDMS.model.services.basicEbayUpdate.BasicEbayUpdateService Class Reference
Public Member Functions
void run ()
Detailed Description
This class represents the start of the execution flow for the eBay Service, The service quereies the eBay API for Order and Item information and
Author
Jan P.C. Hanson
Definition at line 28 of file BasicEbayUpdateService.java.
Member Function Documentation
void openDMS.model.services.basicEbayUpdate.BasicEbayUpdateService.run ()
Implements openDMS.model.services.AbstractService.
Definition at line 35 of file BasicEbayUpdateService.java.
References openDMS.model.eBayAPI.OrdersCall.call(), openDMS.model.services.basicEbayUpdate.TransactionsTable.populate(), openDMS.model.services.basicEbayUpdate.OrdersTable.populate(), openDMS.model.services.basicEbayUpdate.BuyersTable.populate(), openDMS.model.services.basicEbayUpdate.ItemsTable.populate(), and openDMS.helpers.ConfigReader.read().
The documentation for this class was generated from the following file:
src/openDMS/model/services/basicEbayUpdate/BasicEbayUpdateService.java