My Project: openDMS.view.UIServlet Class Reference
openDMS.view.UIServlet Class Reference
Public Member Functions
UIServlet (Map< String, String > views)
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Static Private Attributes
static final String userToken = "AgAAAA**AQAAAA**aAAAAA**s6cKVg**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4GhDpGFoAidj6x9nY+seQ**MpQDAA**AAMAAA**4Aqt9SemYN6DehoPdEsoWuFqCELKvJyBaHL5q1gdWL40la/sjo+abdJSSvNmW8aGcgrgiEXsXJdO+C8RV4lVLvjLnZM0Sadri0BUqP1EK4OTdZWMh8DqaqAqiCi/RhzB+OvHmUd7g5aztZn+wTAIDdglX1cBsJNWnDo4Y9CmK0Et0tbiEiMabvPyO8zwR/Touug6qWkQK488NxJtdo+ZrNZKQ33XXOIoC+nwj8py85vXzxq029DvF31Wmk6ZZcnAuBnpWu8l6h1V+nEPy5V4f1lCIiJdSs++wKP0Dw8FkIXsiTOO4c4LF67gU35LNlaiE/GunY/yJuDeXQ6AJB0RLoFQck+LaEJ2OGH6ZPyzITTWTkf8qY6PBTRE7tCe8okI/Qnbcc6Y6Rol80uJtDQ27Jf7H1XoHoVOgQtTWcZa0BYP7Vbqo54lGyOsVnAHGZ4so+T9WvhZ/MJOacbou9YUptwPYfZwQsTnl0BvVgd6bt5XPsao54A+9ujPhZM5gk0/l9CnG4g47P+jiUtVyw4Gp4cD4fUzRMGK5hQ2jwm+/zK+kokExZbhpIiJBozA7n+5UPRwlmxh8fg1YBW0J0S7/BXBk4zNmpkYOwVQR4kj56/t5fcI9cYfzonRpnn7VUonD21KE6/1lZVsF0/OKoi8OU+xEJZlc8f1E3gv5MYN/qkcjDIn0lq6Fp+1fx6Yod2x1cUfIIXLsdQhqhcZ82LhdfWY/5QdoYGNN2M30yq+6tp4krIx5xBZvBzE8I1sqaRM"
static final String server = "https://api.sandbox.ebay.com/wsapi"
static final String productionToken = "AgAAAA**AQAAAA**aAAAAA**4tcTVg**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFkoujC5mDqAqdj6x9nY+seQ**kQQDAA**AAMAAA**ilVcADfxf7JwysgfZrD35zyh0fs4LpTwAGFfiOIv7Bka9ztFrnmfhHaYVHJmNvmf63bF1fkz1gjdTE3Uq6cGnyQiLJw/v6850sx/O61iOiC6jzDR2Z+a6euBFkoepDu76cFdyYsNSftTuaEe901/EJFsD1zLszVwgJRtGmC1fw4TqmqOH8rncBjWpq16DWNJpzdISwgiEEPy9FZ7zErE8Ss84tu7RGO/uQtOiSglq6pXaGtnjOY7McNE8gtxIavzL6veZbC+7GjdaF3jp1ib5U1bUYrW4vfF+uXDRRmJzU4qP8/GGSy5ZpwUGt1E/5Od1rvgQXp/baEuwFtzUXI/A0jmMlA6weVGaTD+KS2eH8GsVSSJtl8nVTqRV4HBI57d1ASV5DVgok0uvSAaGaMn4Mmka5ps8EgyhbECl0S29CpdOeXL/O+bcEL0dp1ETUerkq7wWyoMC1bvhw2cMjBEBDyTf59IioXxYzNsxu6vk7ZaZLVkzlhxh3dCL7mOm1ptDjXeqtqEQrJ4zGclHEP0DGPnnu8Ch0JUc40V78Ee6qDo9aB8V5/3nqY2JjXjbIaeVwiSaJZb93H/SNxeZnVMU4gIt6yd9l3VA3sv8ZthnJ5EclNHBV4oqZ+LHD3uSDgt8a+/j4018l21Jbf8d0cDA9TBqBkgQNcKSSI3RUfIZtK3P/gQ0tAxSREU5Y7rWgsH24LdVYb/1v27c8nR7BmIc5TfGMY4if5R/lhtJtM9HBMuWp+bbtj5OQCW32mH7myz"
static final String productionServer = "https://api.ebay.com/wsapi"
static final long serialVersionUID = -417534770555839323L
Detailed Description
Author
Jan P.C. Hanson
Definition at line 37 of file UIServlet.java.
Constructor & Destructor Documentation
openDMS.view.UIServlet.UIServlet (Map< String, String > views)
instantiates a servlet using the views provided.
Parameters
views
Definition at line 51 of file UIServlet.java.
Member Function Documentation
void openDMS.view.UIServlet.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
service method, this controls how the servlet responds to particular URL query strings
Parameters
request the http request to the servlet
response the http response to the servlet
Definition at line 59 of file UIServlet.java.
References openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.getFactory(), openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.hasFactory(), openDMS.helpers.viewPresenterFactory.ViewPresenterFactory.instance(), openDMS.helpers.viewPresenterFactory.AbstractViewPresenterFactory.makePresenter(), openDMS.helpers.viewPresenterFactory.AbstractViewPresenterFactory.makeView(), and openDMS.presenters.AbstractPresenter.present().
Member Data Documentation
final String openDMS.view.UIServlet.productionServer = "https://api.ebay.com/wsapi" static private
Definition at line 42 of file UIServlet.java.
final String openDMS.view.UIServlet.productionToken = "AgAAAA**AQAAAA**aAAAAA**4tcTVg**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFkoujC5mDqAqdj6x9nY+seQ**kQQDAA**AAMAAA**ilVcADfxf7JwysgfZrD35zyh0fs4LpTwAGFfiOIv7Bka9ztFrnmfhHaYVHJmNvmf63bF1fkz1gjdTE3Uq6cGnyQiLJw/v6850sx/O61iOiC6jzDR2Z+a6euBFkoepDu76cFdyYsNSftTuaEe901/EJFsD1zLszVwgJRtGmC1fw4TqmqOH8rncBjWpq16DWNJpzdISwgiEEPy9FZ7zErE8Ss84tu7RGO/uQtOiSglq6pXaGtnjOY7McNE8gtxIavzL6veZbC+7GjdaF3jp1ib5U1bUYrW4vfF+uXDRRmJzU4qP8/GGSy5ZpwUGt1E/5Od1rvgQXp/baEuwFtzUXI/A0jmMlA6weVGaTD+KS2eH8GsVSSJtl8nVTqRV4HBI57d1ASV5DVgok0uvSAaGaMn4Mmka5ps8EgyhbECl0S29CpdOeXL/O+bcEL0dp1ETUerkq7wWyoMC1bvhw2cMjBEBDyTf59IioXxYzNsxu6vk7ZaZLVkzlhxh3dCL7mOm1ptDjXeqtqEQrJ4zGclHEP0DGPnnu8Ch0JUc40V78Ee6qDo9aB8V5/3nqY2JjXjbIaeVwiSaJZb93H/SNxeZnVMU4gIt6yd9l3VA3sv8ZthnJ5EclNHBV4oqZ+LHD3uSDgt8a+/j4018l21Jbf8d0cDA9TBqBkgQNcKSSI3RUfIZtK3P/gQ0tAxSREU5Y7rWgsH24LdVYb/1v27c8nR7BmIc5TfGMY4if5R/lhtJtM9HBMuWp+bbtj5OQCW32mH7myz" static private
Definition at line 41 of file UIServlet.java.
final long openDMS.view.UIServlet.serialVersionUID = -417534770555839323L static private
needed to avoid warnings
Definition at line 45 of file UIServlet.java.
final String openDMS.view.UIServlet.server = "https://api.sandbox.ebay.com/wsapi" static private
Definition at line 40 of file UIServlet.java.
final String openDMS.view.UIServlet.userToken = "AgAAAA**AQAAAA**aAAAAA**s6cKVg**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4GhDpGFoAidj6x9nY+seQ**MpQDAA**AAMAAA**4Aqt9SemYN6DehoPdEsoWuFqCELKvJyBaHL5q1gdWL40la/sjo+abdJSSvNmW8aGcgrgiEXsXJdO+C8RV4lVLvjLnZM0Sadri0BUqP1EK4OTdZWMh8DqaqAqiCi/RhzB+OvHmUd7g5aztZn+wTAIDdglX1cBsJNWnDo4Y9CmK0Et0tbiEiMabvPyO8zwR/Touug6qWkQK488NxJtdo+ZrNZKQ33XXOIoC+nwj8py85vXzxq029DvF31Wmk6ZZcnAuBnpWu8l6h1V+nEPy5V4f1lCIiJdSs++wKP0Dw8FkIXsiTOO4c4LF67gU35LNlaiE/GunY/yJuDeXQ6AJB0RLoFQck+LaEJ2OGH6ZPyzITTWTkf8qY6PBTRE7tCe8okI/Qnbcc6Y6Rol80uJtDQ27Jf7H1XoHoVOgQtTWcZa0BYP7Vbqo54lGyOsVnAHGZ4so+T9WvhZ/MJOacbou9YUptwPYfZwQsTnl0BvVgd6bt5XPsao54A+9ujPhZM5gk0/l9CnG4g47P+jiUtVyw4Gp4cD4fUzRMGK5hQ2jwm+/zK+kokExZbhpIiJBozA7n+5UPRwlmxh8fg1YBW0J0S7/BXBk4zNmpkYOwVQR4kj56/t5fcI9cYfzonRpnn7VUonD21KE6/1lZVsF0/OKoi8OU+xEJZlc8f1E3gv5MYN/qkcjDIn0lq6Fp+1fx6Yod2x1cUfIIXLsdQhqhcZ82LhdfWY/5QdoYGNN2M30yq+6tp4krIx5xBZvBzE8I1sqaRM" static private
Definition at line 39 of file UIServlet.java.
The documentation for this class was generated from the following file:
src/openDMS/view/UIServlet.java