TomoBay: Conditional< T > Class Template Reference
Conditional< T > Class Template Reference abstract
This class attempts to represent conditional statements in an object oriented manner.
Public Member Functions
Conditional ()
default ctor
T evaluate ()
Evaluate the start condition inherent to this conditional (if it exists).
T evaluate (Condition condition, Result< T > result)
evaluate this conditional based on the Condition and Result objects passed as parameters to this method
abstract Condition startCondition ()
This method can be used by derived classes to define a start condition in the event that a 'chain of responsibility' style conditional is needed (analogous to a nested if-then-else)
abstract Result< T > startResult ()
This method can be used by derived classes to define the behaviour that the start condition should invoke.
Detailed Description
This class attempts to represent conditional statements in an object oriented manner.
A Condition object is evaluated and depending on whether the Condition evaluates to true or false the appropriate code in the Result object is invoked (using double dispatch).
Two evaluate methods are defined here: evaluate() and evaluate(Condition condition, Result<T> result); which is to be used depends on how you wish to use these constructs. The parameterless evaluate() method is provided in the case where you need to define a particular start condition and chain conditional statements, much like a nested if-then-else statement. The evaluate(Condition condition, Result<T> result) is provided in the case where a simple if-else statement is needed.
See also
tomoBay.model.dataTypes.conditionalStatement
Author
Jan P.C. Hanson
Definition at line 35 of file Conditional.java.
Constructor & Destructor Documentation
Conditional ()
default ctor
Definition at line 40 of file Conditional.java.
Member Function Documentation
T evaluate ()
Evaluate the start condition inherent to this conditional (if it exists).
Returns
Definition at line 47 of file Conditional.java.
Referenced by SalesOrderPresenter.checkPickability(), AllPickeableResult.result(), UnPickeableResult.result(), and ErrorResult.result().
T evaluate (Condition condition, Result< T > result)
evaluate this conditional based on the Condition and Result objects passed as parameters to this method
Parameters
condition the Condition object that should be evaluated.
result the Result object that contains the behaviour to invoke for this conditional.
Returns
T as defined when instantiating this Conditional object.
Definition at line 57 of file Conditional.java.
abstract Condition startCondition () abstract
This method can be used by derived classes to define a start condition in the event that a 'chain of responsibility' style conditional is needed (analogous to a nested if-then-else)
Returns
Condition object representing the start condition (first handler)
abstract Result<T> startResult () abstract
This method can be used by derived classes to define the behaviour that the start condition should invoke.
Returns
Result object representing the startCondition behaviours (dependant on the evaluation of the Condition object).
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/conditionalStatement/Conditional.java