TomoBay: ServiceScheduler Class Reference
ServiceScheduler Class Reference
This class defines a service scheduler, it runs services intervalicaly, with the interval being defined from the previous termination of that service thread.
Public Member Functions
ServiceScheduler (int noOfThreads)
constructor creates a thread pool with the number of threads specified in the arguments.
void add (AbstractService service)
add a service to the list of services to run at the periods specified in the method parameters.
void clear ()
void start (long rateInMins)
starts the periodic services.
void stop ()
stops the periodic services
Static Package Attributes
static Logger log = Logger.getLogger(ServiceScheduler.class.getName())
Private Attributes
ScheduledThreadPoolExecutor serviceScheduler_M
Scheduled thread pool.
List< AbstractService > services_M
List of scheduled services.
List< Future< String > > servicesResults_M
List of Scheduled futures representing service threads return values.
Detailed Description
This class defines a service scheduler, it runs services intervalicaly, with the interval being defined from the previous termination of that service thread.
Contains a threadpool which should be changed to reflect the number of services stored in the queue, for small numbers of services; and set to a sensible value for larger numbers of services.
Author
Jan P.C. Hanson
Definition at line 34 of file ServiceScheduler.java.
Constructor & Destructor Documentation
ServiceScheduler (int noOfThreads)
constructor creates a thread pool with the number of threads specified in the arguments.
Parameters
noOfThreads the number of threads to populate the pool with.
Definition at line 49 of file ServiceScheduler.java.
Member Function Documentation
void add (AbstractService service)
add a service to the list of services to run at the periods specified in the method parameters.
Definition at line 61 of file ServiceScheduler.java.
Referenced by MAIN.main().
void clear ()
Definition at line 64 of file ServiceScheduler.java.
Referenced by ServiceScheduler.stop().
void start (long rateInMins)
starts the periodic services.
Parameters
rateInMins
Definition at line 70 of file ServiceScheduler.java.
References StackTraceToString.toString().
Referenced by MAIN.main().
void stop ()
stops the periodic services
Definition at line 93 of file ServiceScheduler.java.
References ServiceScheduler.clear().
Member Data Documentation
Logger log = Logger.getLogger(ServiceScheduler.class.getName()) static package
Definition at line 36 of file ServiceScheduler.java.
ScheduledThreadPoolExecutor serviceScheduler_M private
Scheduled thread pool.
Definition at line 38 of file ServiceScheduler.java.
List<AbstractService> services_M private
List of scheduled services.
Definition at line 40 of file ServiceScheduler.java.
List<Future<String> > servicesResults_M private
List of Scheduled futures representing service threads return values.
Definition at line 43 of file ServiceScheduler.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/services/ServiceScheduler.java