TomoBay: ServerStatus Class Reference
ServerStatus Class Reference
Copyright(C) 2015 Jan P.C.
Classes
enum RunLevel
enum providing allowed ServerStatus values
Public Member Functions
synchronized void setStatus (ServerStatus.RunLevel status)
Static Public Member Functions
static ServerStatus instance ()
retrieve an instance of this object
static synchronized ServerStatus.RunLevel getStatus ()
static String os ()
returns the name of the os that the server is being run on.
Private Member Functions
ServerStatus ()
private constructor ensures singleton is never instantiated
Static Private Attributes
static final ServerStatus instance_M = new ServerStatus()
singleton instance variable
static RunLevel status_M
status variable
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Author
Jan P.C. Hanson
Definition at line 23 of file ServerStatus.java.
Constructor & Destructor Documentation
ServerStatus () private
private constructor ensures singleton is never instantiated
Definition at line 34 of file ServerStatus.java.
Member Function Documentation
static ServerStatus instance () static
retrieve an instance of this object
Returns
ServerStatus
Definition at line 41 of file ServerStatus.java.
References ServerStatus.instance_M.
Referenced by PeriodicServicesController.executeStatic(), and MAIN.main().
synchronized void setStatus (ServerStatus.RunLevel status)
Parameters
status
Definition at line 48 of file ServerStatus.java.
References ServerStatus.status_M.
Referenced by PeriodicServicesController.executeStatic(), and MAIN.main().
static synchronized ServerStatus.RunLevel getStatus () static
Returns
Definition at line 55 of file ServerStatus.java.
References ServerStatus.status_M.
Referenced by AbstractService.call(), SalesOrderView.pickeability(), and SalesOrderPresenter.present().
static String os () static
returns the name of the os that the server is being run on.
Returns
String containing the os name.
Definition at line 62 of file ServerStatus.java.
Referenced by Part.badChar().
Member Data Documentation
final ServerStatus instance_M = new ServerStatus() static private
singleton instance variable
Definition at line 26 of file ServerStatus.java.
Referenced by ServerStatus.instance().
RunLevel status_M static private
status variable
Definition at line 28 of file ServerStatus.java.
Referenced by ServerStatus.getStatus(), and ServerStatus.setStatus().
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/ServerStatus.java