My Project: openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions Class Reference
openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions Class Reference
Public Member Functions
InsertEbayTransactions ()
List< String[]> execute (String[] parameter) throws SQLException
Private Member Functions
void initQuery () throws SQLException
void cleanup () throws SQLException
Private Attributes
PreparedStatement statement_M = null
Connection connection_M = null
String query
Detailed Description
Author
Jan P.C. Hanson
Definition at line 30 of file InsertEbayTransactions.java.
Constructor & Destructor Documentation
openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.InsertEbayTransactions ()
default constructor
Definition at line 44 of file InsertEbayTransactions.java.
Member Function Documentation
void openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.cleanup () throws SQLException private
do cleanup after the query has been executed
Exceptions
SQLException
Definition at line 91 of file InsertEbayTransactions.java.
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.execute().
List<String[]> openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.execute (String[] parameter) throws SQLException
execute the query
Parameters
parameter an array of strings where the 0th element is the parameter for the first column, the 1st element is the parameter for the 2nd column and so on. The Ebay Orders Table only has 4 columns so any element above the 3rd element will be ignored. col1 =transactionID:bigint(20), col2=orderID:varchar(30), col3=itemID:bigint(20), col4=quantity:int(7)
Returns
List<String[]> representing the results of the query. The list contains only 1 String[] which in turn contains only 1 element, this is the resultcode for the query.
Exceptions
SQLException
Implements openDMS.model.sql.queries.AbstractDBQuery.
Definition at line 58 of file InsertEbayTransactions.java.
References openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.cleanup(), and openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.initQuery().
void openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.initQuery () throws SQLException private
initialise the connection and statement and set transaction variables.
Exceptions
SQLException
Definition at line 80 of file InsertEbayTransactions.java.
References openDMS.model.sql.ConnectionManager.getConnection(), and openDMS.model.sql.ConnectionManager.instance().
Referenced by openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.execute().
Member Data Documentation
Connection openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.connection_M = null private
reference to the JDBC Database connection
Definition at line 35 of file InsertEbayTransactions.java.
String openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.query private
Initial value:
="INSERT IGNORE INTO ebay.ebay_transactions "
            + "(transactionID, orderID, itemID, quantity)"
            + "VALUES (?,?,?, ?);"
SQL query string
Definition at line 37 of file InsertEbayTransactions.java.
PreparedStatement openDMS.model.sql.queries.concreteQueries.InsertEbayTransactions.statement_M = null private
reference to the JDBC Statement
Definition at line 33 of file InsertEbayTransactions.java.
The documentation for this class was generated from the following file:
src/openDMS/model/sql/queries/concreteQueries/InsertEbayTransactions.java