TomoBay: ReScanErrorsWinstockActions Class Reference
ReScanErrorsWinstockActions Class Reference
This class encapsulates all CheckErrorsService interactions with Winstock.
Public Member Functions
ReScanErrorsWinstockActions ()
default ctor
boolean partNoHasError (ItemSpecifics item)
this method checks to see if a particular item (through the ItemSpecifics passed in as an argument) has errors, if none of the part numbers contained in the ItemSpecifics are erroneous then this method returns true, otherwise it will return false as soon as it deiscovers an error i.e.
Detailed Description
This class encapsulates all CheckErrorsService interactions with Winstock.
Author
Jan P.C. Hanson
Definition at line 25 of file ReScanErrorsWinstockActions.java.
Constructor & Destructor Documentation
ReScanErrorsWinstockActions ()
default ctor
Definition at line 30 of file ReScanErrorsWinstockActions.java.
Member Function Documentation
boolean partNoHasError (ItemSpecifics item)
this method checks to see if a particular item (through the ItemSpecifics passed in as an argument) has errors, if none of the part numbers contained in the ItemSpecifics are erroneous then this method returns true, otherwise it will return false as soon as it deiscovers an error i.e.
does not get a valid response from WinStock
Parameters
item the ItemSpecifics for the item that we wish to check for errors
Returns
true if no errors exist, false otherwise.
Definition at line 41 of file ReScanErrorsWinstockActions.java.
References BrandToCode.convertToWinstockInt(), ItemSpecifics.get(), and PartList.getPartNumbers().
Referenced by OnRunning.execute().
The documentation for this class was generated from the following file:
src/tomoBay/model/services/reScanErrorsService/ReScanErrorsWinstockActions.java