TomoBay: BuyerDetails Class Reference
BuyerDetails Class Reference
Public Member Functions
BuyerDetails ()
default ctor
String execute (String data)
performs the action specified
Static Private Member Functions
static final List< HeteroFieldContainer > getRawData (String buyerID)
Detailed Description
Author
Jan P.C. Hanson
Definition at line 34 of file BuyerDetails.java.
Constructor & Destructor Documentation
BuyerDetails ()
default ctor
Definition at line 40 of file BuyerDetails.java.
Member Function Documentation
String execute (String data)
performs the action specified
Returns
String representing the results of the performed action.
Implements AbstractPresenterAction.
Definition at line 47 of file BuyerDetails.java.
References JSONentity.addLeaf(), BuyerTable.BUYERID, BuyerTable.CITY, BuyerTable.COUNTY, BuyerTable.EMAIL, BuyerDetails.getRawData(), SaneInput.json(), BuyerTable.NAME, BuyerTable.PHONE, BuyerTable.POSTCODE, BuyerTable.STREET1, BuyerTable.STREET2, ClassRef.STRING, and JSONentity.toString().
static final List<HeteroFieldContainer> getRawData (String buyerID) static private
Parameters
buyerID
Returns
Definition at line 69 of file BuyerDetails.java.
References HeteroFieldContainer.add(), BuyerTable.BUYERID, SelectQueryInvoker.execute(), and SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_BUYER.
Referenced by BuyerDetails.execute().
The documentation for this class was generated from the following file:
src/tomoBay/presenters/presenterActions/concreteActions/BuyerDetails.java