TomoBay: InvoiceOrders Class Reference
InvoiceOrders Class Reference
This AbstractPresenterAction provides functionality to invoice a number of orders based on the order numbers provided as the data string to the execute method.
Public Member Functions
InvoiceOrders ()
default ctor
String execute (String data)
performs the action specified
Static Package Attributes
static final Logger log = Logger.getLogger(InvoiceOrders.class.getName())
Private Member Functions
String[] splitOrderNoString (String orderNos)
splits the 'data' string into a string array
void updateDB (String invNo, String orderNo)
update the database entry for a particular order to include the invoice number in the invoiced column of the orders table.
DualList< String, PayloadType > formatAsDualList (AbstractSalesDayBookLine invoice)
formats the AbstractSalesDayBookLine into a format that can be passed to the WinstockCommandInvoker.
String formatMailResult (String invNo, String weight, AbstractSalesDayBookLine invoice)
void emailResults (String result)
Static Private Attributes
static final String EMAILHEADER
static final String EMAILFOOTER ="</tbody></table>"
Detailed Description
This AbstractPresenterAction provides functionality to invoice a number of orders based on the order numbers provided as the data string to the execute method.
This string should be a comma separated string of valid order numbers i.e. real order numbers that are less than 90 days old.
Author
Jan P.C. Hanson
Definition at line 47 of file InvoiceOrders.java.
Constructor & Destructor Documentation
InvoiceOrders ()
default ctor
Definition at line 58 of file InvoiceOrders.java.
Member Function Documentation
String execute (String data)
performs the action specified
Returns
String representing the results of the performed action.
Implements AbstractPresenterAction.
Definition at line 65 of file InvoiceOrders.java.
References Order.createdTime(), InvoiceOrders.EMAILFOOTER, InvoiceOrders.EMAILHEADER, InvoiceOrders.emailResults(), WinstockCommandInvoker.execute(), InvoiceOrders.formatAsDualList(), InvoiceOrders.formatMailResult(), AbstractWinstockCommandResponse.getRecieved(), SalesDayBookLineFactory.SalesDayBookLineType.INVOICE, AbstractSalesDayBookLine.invoiceNumber(), SalesDayBookLineFactory.make(), TimeStampFunctions.olderThan(), AbstractSalesDayBookLine.orderInfo(), WinstockCommandInvoker.WinstockCommandTypes.PutInvoice, Order.salesRecNo(), InvoiceOrders.splitOrderNoString(), and InvoiceOrders.updateDB().
String [] splitOrderNoString (String orderNos) private
splits the 'data' string into a string array
Parameters
orderNos the 'data' string
Returns
String[] containing all the orderNos in the original 'data' string
Definition at line 100 of file InvoiceOrders.java.
Referenced by InvoiceOrders.execute().
void updateDB (String invNo, String orderNo) private
update the database entry for a particular order to include the invoice number in the invoiced column of the orders table.
Parameters
invNo the invoice number as a string
orderNo the order number as a string
Definition at line 109 of file InvoiceOrders.java.
References HeteroFieldContainer.add(), ModifyQueryInvoker.execute(), OrdersTable.INVOICED, OrdersTable.ORDER_ID, and ModifyQueryInvoker.ModifyQueryTypeParams.UPDATE_INVOICE_STATUS.
Referenced by InvoiceOrders.execute().
DualList<String, PayloadType> formatAsDualList (AbstractSalesDayBookLine invoice) private
formats the AbstractSalesDayBookLine into a format that can be passed to the WinstockCommandInvoker.
Parameters
invoice the invoice to be formatted
Returns
DualList<String, PayloadType> accepted by the WinstockCommandInvoker
Definition at line 122 of file InvoiceOrders.java.
References AbstractSalesDayBookLine.format().
Referenced by InvoiceOrders.execute().
String formatMailResult (String invNo, String weight, AbstractSalesDayBookLine invoice) private
Definition at line 125 of file InvoiceOrders.java.
References Order.account(), Order.createdTime(), AbstractSalesDayBookLine.orderInfo(), and Order.salesRecNo().
Referenced by InvoiceOrders.execute().
void emailResults (String result) private
Parameters
result
Definition at line 140 of file InvoiceOrders.java.
References InvoiceOrders.EMAILFOOTER, InvoiceOrders.EMAILHEADER, and MailClient.send().
Referenced by InvoiceOrders.execute().
Member Data Documentation
final Logger log = Logger.getLogger(InvoiceOrders.class.getName()) static package
Definition at line 49 of file InvoiceOrders.java.
final String EMAILHEADER static private
Initial value:
="<table border='1' style='width:100%'><thead><th>Account</th>"
                + "<th>SalesRecordNo</th><th>Created time</th><th>Weight</th><th>Invoice Number</th></thead><tbody>"
Definition at line 50 of file InvoiceOrders.java.
Referenced by InvoiceOrders.emailResults(), and InvoiceOrders.execute().
final String EMAILFOOTER ="</tbody></table>" static private
Definition at line 52 of file InvoiceOrders.java.
Referenced by InvoiceOrders.emailResults(), and InvoiceOrders.execute().
The documentation for this class was generated from the following file:
src/tomoBay/presenters/presenterActions/concreteActions/InvoiceOrders.java