TomoBay: Transaction Class Reference
Transaction Class Reference
This class represents an eBay transaction, each transaction contains 1 Listing.
Public Member Functions
Transaction (Long transactionID)
CONSTRUCTOR, initialise object using the transactionID provided to query the database for the rest of the information.
Listing listing ()
retrieve the listing associated with this transaction
int qtyPurchased ()
retrieve the quantity of this listing purchased
double transactionPrice ()
retrieve the price associated with this transaction
float shippingCost ()
retrieve the shipping cost associated with this transaction
Static Private Member Functions
static final HeteroFieldContainer getTransactionInfo (Long transactionID)
retrieve the transaction information for this order from the database based on the order ID passed in as a parameter.
Private Attributes
final Listing listing_M
the listing associated with this transaction
final HeteroFieldContainer transaction_info_M
Container for all the order information retrieved by the query.
Detailed Description
This class represents an eBay transaction, each transaction contains 1 Listing.
This transaction contains more general information about the transaction such as price and shipping cost etc whereas the Listing object contains information more relevant to the actual product being sold.
Author
Jan P.C. Hanson
Definition at line 32 of file Transaction.java.
Constructor & Destructor Documentation
Transaction (Long transactionID)
CONSTRUCTOR, initialise object using the transactionID provided to query the database for the rest of the information.
Parameters
transactionID
Definition at line 44 of file Transaction.java.
References HeteroFieldContainer.get(), Transaction.getTransactionInfo(), TransactionsTable.ITEM_ID, and ClassRef.LONG.
Member Function Documentation
Listing listing ()
retrieve the listing associated with this transaction
Returns
Listing
Definition at line 55 of file Transaction.java.
References Transaction.listing_M.
Referenced by AbstractLineItem.description(), PrintInvoices.execute(), WinstockFormat.format(), AbstractLineItem.partNo(), AbstractLineItem.quantity(), OrderInfo.transactionInfo(), GSPInvoiceLine.unitPrice(), and StandardInvoiceLine.unitPrice().
int qtyPurchased ()
retrieve the quantity of this listing purchased
Returns
int representing how many of this listing are billed to this transaction
Definition at line 61 of file Transaction.java.
References HeteroFieldContainer.get(), ClassRef.INTEGER, and TransactionsTable.QUANTITY.
Referenced by AbstractLineItem.quantity(), OrderInfo.transactionInfo(), and Transaction.transactionPrice().
double transactionPrice ()
retrieve the price associated with this transaction
Returns
double representing the transaction price
Definition at line 68 of file Transaction.java.
References ClassRef.FLOAT, HeteroFieldContainer.get(), TransactionsTable.PRICE, and Transaction.qtyPurchased().
Referenced by OrderInfo.transactionInfo(), GSPInvoiceLine.unitPrice(), and StandardInvoiceLine.unitPrice().
float shippingCost ()
retrieve the shipping cost associated with this transaction
Returns
double representing the shipping cost
Definition at line 75 of file Transaction.java.
References ClassRef.FLOAT, HeteroFieldContainer.get(), and TransactionsTable.SHIPPING_COST.
Referenced by OrderInfo.transactionInfo().
static final HeteroFieldContainer getTransactionInfo (Long transactionID) static private
retrieve the transaction information for this order from the database based on the order ID passed in as a parameter.
Parameters
transactionID Long containing the transactionID for the order that should have info on it found
Returns
HeteroFieldContainer containing the transaction information.
See also
tomoBay.model.sql.queries.concreteQueries.select.params.SelectEbayTransactionByID
Definition at line 87 of file Transaction.java.
References HeteroFieldContainer.add(), SelectQueryInvoker.execute(), SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_TRANSACTION_BY_ID, and TransactionsTable.TRANSACTION_ID.
Referenced by Transaction.Transaction().
Member Data Documentation
final Listing listing_M private
the listing associated with this transaction
Definition at line 35 of file Transaction.java.
Referenced by Transaction.listing().
final HeteroFieldContainer transaction_info_M private
Container for all the order information retrieved by the query.
Definition at line 37 of file Transaction.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/order/Transaction.java