TomoBay: NonDBFields Class Reference
NonDBFields Class Reference
Static Public Attributes
static final ResultCode RESULT_CODE = new ResultCode()
this is a return value from an insert or update query it is an integer value
static final Date DATE_COMPARISON = new Date()
this is a Date field that can be used as a comparison value against the OutOfHoursTable.Date
static final CustomIntegerField Custom_INT_FIELD = new CustomIntegerField()
this is an input or return to/from a custom integer field, i.e.
Private Member Functions
NonDBFields ()
ensures that this class is NEVER INSTANTIATED
Detailed Description
Author
Jan P.C. Hanson
Definition at line 26 of file NonDBFields.java.
Constructor & Destructor Documentation
NonDBFields () private
ensures that this class is NEVER INSTANTIATED
Definition at line 53 of file NonDBFields.java.
Member Data Documentation
final ResultCode RESULT_CODE = new ResultCode() static
this is a return value from an insert or update query it is an integer value
Integer
NON DB FIELD
Definition at line 33 of file NonDBFields.java.
Referenced by AbstractModifyQueryNoParams.execute(), MarkAsUninvoiced.execute(), MarkAsInvoiced.execute(), AbstractModifyQueryParams.execute(), and OnRunning.execute().
final Date DATE_COMPARISON = new Date() static
this is a Date field that can be used as a comparison value against the OutOfHoursTable.Date
Date
NON DB FIELD (indirect)
Definition at line 40 of file NonDBFields.java.
Referenced by OutOfHoursPresenter.present(), OutOfHoursPresenter.removeOldOrders(), and SelectOutOfHoursOrders.setParameters().
final CustomIntegerField Custom_INT_FIELD = new CustomIntegerField() static
this is an input or return to/from a custom integer field, i.e.
one defined in a query but is not directly a database field.
INTEGER
NON DB FIELD
Definition at line 48 of file NonDBFields.java.
Referenced by SelectEbayOrderHistoryLastNDays.format(), StockReOrderAnalysis.grabDBdata(), StockReOrderAnalysis.processDBdata(), and SelectEbayOrderHistoryLastNDays.setParameters().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/schema/nonDBFields/NonDBFields.java