TomoBay: QueryUtility Class Reference
QueryUtility Class Reference
This is a helper class that provides static access to methods useful for creating SQL queries within this framework.
Static Public Member Functions
static void setINTEGERParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setVARCHARParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setBYTEParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setBIGINTParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setTINYINTParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setTIMESTAMPParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setDATEParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setDOUBLEParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
static void setFLOATParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException
set an Integer parameter for the query object specified.
Private Member Functions
QueryUtility ()
private ctor ensures that this class is never instantiated
Detailed Description
This is a helper class that provides static access to methods useful for creating SQL queries within this framework.
Author
Jan P.C. Hanson
Definition at line 29 of file QueryUtility.java.
Constructor & Destructor Documentation
QueryUtility () private
private ctor ensures that this class is never instantiated
Definition at line 35 of file QueryUtility.java.
References QueryUtility.setINTEGERParam().
Member Function Documentation
static void setINTEGERParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 48 of file QueryUtility.java.
References HeteroFieldContainer.get(), ClassRef.INTEGER, QueryUtility.setVARCHARParam(), and AbstractDBQuery.statement().
Referenced by QueryUtility.QueryUtility(), UpdateInvoiceStatusSRN.setParameters(), UpdateInvoiceStatus.setParameters(), InsertOutOfHoursOrders.setParameters(), InsertEbayItems.setParameters(), InsertEbayOrders.setParameters(), InsertEbayTransactions.setParameters(), SelectBuyerByAccAndSRN.setParameters(), and SelectBrandByInv.setParameters().
static void setVARCHARParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 62 of file QueryUtility.java.
References HeteroFieldContainer.get(), QueryUtility.setBYTEParam(), AbstractDBQuery.statement(), and ClassRef.STRING.
Referenced by QueryUtility.setINTEGERParam(), InsertOrderInOrderStatus.setParameters(), UpdateInvoiceStatus.setParameters(), UpdateItemNote.setParameters(), UpdateItemBrandAndPartNo.setParameters(), UpdateItemError.setParameters(), InsertEbayOrders.setParameters(), InsertEbayItems.setParameters(), InsertEbayTransactions.setParameters(), UpdateEbayBuyer.setParameters(), SelectBuyerByAccAndSRN.setParameters(), InsertEbayBuyers.setParameters(), SelectEbayOrderByBuyer.setParameters(), SelectTransactionByOrder.setParameters(), SelectBrandAndPartNoByOrderID.setParameters(), SelectEbayOrderByID.setParameters(), SelectEbayBuyer.setParameters(), and SelectFullOrderLine.setParameters().
static void setBYTEParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 76 of file QueryUtility.java.
References ClassRef.BYTE, HeteroFieldContainer.get(), QueryUtility.setBIGINTParam(), and AbstractDBQuery.statement().
Referenced by QueryUtility.setVARCHARParam().
static void setBIGINTParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 90 of file QueryUtility.java.
References HeteroFieldContainer.get(), ClassRef.LONG, QueryUtility.setTINYINTParam(), and AbstractDBQuery.statement().
Referenced by QueryUtility.setBYTEParam(), UpdateItemNote.setParameters(), UpdateItemBrandAndPartNo.setParameters(), InsertEbayItems.setParameters(), UpdateItemError.setParameters(), InsertEbayTransactions.setParameters(), SelectEbayTransactionByID.setParameters(), and SelectEbayItemSpecific.setParameters().
static void setTINYINTParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 104 of file QueryUtility.java.
References ClassRef.BOOLEAN, HeteroFieldContainer.get(), QueryUtility.setTIMESTAMPParam(), and AbstractDBQuery.statement().
Referenced by QueryUtility.setBIGINTParam().
static void setTIMESTAMPParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 118 of file QueryUtility.java.
References HeteroFieldContainer.get(), QueryUtility.setDATEParam(), AbstractDBQuery.statement(), and ClassRef.TIMESTAMP.
Referenced by InsertEbayOrders.setParameters(), and QueryUtility.setTINYINTParam().
static void setDATEParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 132 of file QueryUtility.java.
References ClassRef.DATE, HeteroFieldContainer.get(), QueryUtility.setDOUBLEParam(), and AbstractDBQuery.statement().
Referenced by InsertOutOfHoursOrders.setParameters(), SelectOutOfHoursOrders.setParameters(), and QueryUtility.setTIMESTAMPParam().
static void setDOUBLEParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 146 of file QueryUtility.java.
References ClassRef.DOUBLE, HeteroFieldContainer.get(), QueryUtility.setFLOATParam(), and AbstractDBQuery.statement().
Referenced by QueryUtility.setDATEParam().
static void setFLOATParam (AbstractDBQuery queryObj, HeteroFieldContainer parameters, AbstractField field, int index) throws ClassCastException, SQLException static
set an Integer parameter for the query object specified.
Parameters
queryObj the query in which to set the Integer parameter (usually just pass in 'this')
parameters the HeteroFieldContainer containing all the parameters.
field the particular AbstractField within the HeteroFieldContainer to use for this parameter.
index the index of this parameter
Exceptions
ClassCastException
SQLException
Definition at line 160 of file QueryUtility.java.
References ClassRef.FLOAT, HeteroFieldContainer.get(), and AbstractDBQuery.statement().
Referenced by QueryUtility.setDOUBLEParam(), InsertEbayOrders.setParameters(), and InsertEbayTransactions.setParameters().
The documentation for this class was generated from the following file:
src/tomoBay/model/sql/framework/QueryUtility.java