TomoBay: Order Class Reference
Order Class Reference
This class represents an eBay order, and the relevant information associated with it.
Public Member Functions
Order (String orderID)
initialise this order using the orderID provided
String orderID ()
The order ID is a string(numerical) that uniquely identifies this order from all others.
Buyer buyer ()
Retrieve the Buyer that placed this order.
Transaction transaction (int index)
An order is made up of transactions, this method retrieves the specified transaction, given the index parameter.
int noOfTransactions ()
use this method to find out how many transactions are associated with this order,
int salesRecNo ()
retrieve the sales record number associated with this order
String account ()
retrieve the account that this order is associated with
String shippingType ()
retrieve the shipping type used for this order as a string
String createdTime ()
retrieve the time at which this order was created
int invoiceNo ()
retrieve the invoice number from this order(if it has one)
float totalPrice ()
retrieve the total price associated with this order, i.e.
double shippingCost ()
Static Package Attributes
static final Logger log = Logger.getLogger(Order.class.getName())
Static Private Member Functions
static final HeteroFieldContainer getOrderInfo (String orderID)
helper method, retrieves the order specific information from the database, in order to be able to populate the properties of this object.
static final Transaction[] getTransactionList (String orderID)
helper method, retrieves the transactions associated with this order by querying the database and using the results to generate Transaction objects.
Private Attributes
final Buyer buyer_M
the buyer of this order
final Transaction[] transactions_M
the transactions associated with this order
final HeteroFieldContainer order_info_M
Container for all the order information retrieved by the query.
Detailed Description
This class represents an eBay order, and the relevant information associated with it.
Once instantiated this object will contain a Buyer object and an array of Transaction objects, and while this Order object will contain general information relevant to this eBay order, in order to gain more in depth details of the order i.e. buyer information or detailed information about the items that have been sold, it is necessary to query these contained objects.
Author
Jan P.C. Hanson
Definition at line 40 of file Order.java.
Constructor & Destructor Documentation
Order (String orderID)
initialise this order using the orderID provided
Parameters
orderID
Definition at line 54 of file Order.java.
References OrdersTable.BUYERID, HeteroFieldContainer.get(), Order.getOrderInfo(), Order.getTransactionList(), ClassRef.STRING, and StackTraceToString.toString().
Member Function Documentation
String orderID ()
The order ID is a string(numerical) that uniquely identifies this order from all others.
Returns
String containing the orderID
Definition at line 75 of file Order.java.
References HeteroFieldContainer.get(), OrdersTable.ORDER_ID, and ClassRef.STRING.
Referenced by OrderInfo.summaryInfo().
Buyer buyer ()
Retrieve the Buyer that placed this order.
Returns
Buyer object containing all the information on the buyer
Definition at line 81 of file Order.java.
References Order.buyer_M.
Referenced by WinstockFormat.format(), OrderInfo.formatResults(), SalesDayBookLineFactory.make(), and OrderInfo.shippingInfo().
Transaction transaction (int index)
An order is made up of transactions, this method retrieves the specified transaction, given the index parameter.
Should you select a transaction that does not exist you'll probably get an IndexOutOfBounds exception
Parameters
index the index of the transaction you wish to return
Returns
Transaction object containing all pertinent information to do with that transaction.
Definition at line 90 of file Order.java.
Referenced by AbstractLineItem.description(), PrintInvoices.execute(), WinstockFormat.format(), AbstractLineItem.partNo(), AbstractLineItem.quantity(), OrderInfo.transactionInfo(), GSPInvoiceLine.unitPrice(), and StandardInvoiceLine.unitPrice().
int noOfTransactions ()
use this method to find out how many transactions are associated with this order,
Returns
int representing the number of transactions available in this order.
Definition at line 96 of file Order.java.
Referenced by OrderInfo.transactionInfo().
int salesRecNo ()
retrieve the sales record number associated with this order
Returns
int representing the salesRecordNumber
Definition at line 102 of file Order.java.
References HeteroFieldContainer.get(), ClassRef.INTEGER, and OrdersTable.SALES_REC_NO.
Referenced by InvoiceOrders.execute(), WinstockFormat.format(), InvoiceOrders.formatMailResult(), and OrderInfo.summaryInfo().
String account ()
retrieve the account that this order is associated with
Returns
String containing the name of the ebay account
Definition at line 109 of file Order.java.
References OrdersTable.ACCOUNT, HeteroFieldContainer.get(), ClassRef.INTEGER, and EbayAccounts.name().
Referenced by InvoiceOrders.formatMailResult(), and OrderInfo.summaryInfo().
String shippingType ()
retrieve the shipping type used for this order as a string
Returns
String representing the shipping type
Definition at line 116 of file Order.java.
References HeteroFieldContainer.get(), OrdersTable.SHIPPING_TYPE, and ClassRef.STRING.
Referenced by OrderInfo.summaryInfo().
String createdTime ()
retrieve the time at which this order was created
Returns
String representing the time at which the order was created.
Definition at line 123 of file Order.java.
References OrdersTable.CREATED_TIME, HeteroFieldContainer.get(), and ClassRef.TIMESTAMP.
Referenced by InvoiceOrders.execute(), InvoiceOrders.formatMailResult(), and OrderInfo.summaryInfo().
int invoiceNo ()
retrieve the invoice number from this order(if it has one)
Returns
0 if the order is uninvoiced, otherwise an actual invoice number. in some cases this method will return 1, this indicates that the order has been manually invoiced or that it was automatically invoiced before this capability was put in place.
Definition at line 132 of file Order.java.
References HeteroFieldContainer.get(), ClassRef.INTEGER, and OrdersTable.INVOICED.
Referenced by AbstractSalesDayBookLine.invoiceNumber().
float totalPrice ()
retrieve the total price associated with this order, i.e.
how much the customer paid.
Returns
double representing the amount the customer paid for this order.
Definition at line 139 of file Order.java.
References ClassRef.FLOAT, HeteroFieldContainer.get(), and OrdersTable.ORDER_TOTAL.
Referenced by OrderInfo.summaryInfo(), and AbstractSalesDayBookLine.totalIncVat().
double shippingCost ()
Returns
Definition at line 146 of file Order.java.
Referenced by SalesDayBookLineFactory.make(), OrderInfo.shippingInfo(), and StandardInvoiceShippingLine.unitPrice().
static final HeteroFieldContainer getOrderInfo (String orderID) static private
helper method, retrieves the order specific information from the database, in order to be able to populate the properties of this object.
Parameters
orderID the orderID associated with this order
Returns
String[] containing the information specific to this order.
Definition at line 163 of file Order.java.
References HeteroFieldContainer.add(), SelectQueryInvoker.execute(), OrdersTable.ORDER_ID, and SelectQueryInvoker.SelectQueryTypeParams.SELECT_EBAY_ORDER_BY_ID.
Referenced by Order.Order().
static final Transaction [] getTransactionList (String orderID) static private
helper method, retrieves the transactions associated with this order by querying the database and using the results to generate Transaction objects.
Parameters
orderID the orderID associated with this order
Returns
Transaction[] that can be used to populate the final Transaction[] member variable.
Definition at line 179 of file Order.java.
References HeteroFieldContainer.add(), SelectQueryInvoker.execute(), ClassRef.LONG, OrdersTable.ORDER_ID, SelectQueryInvoker.SelectQueryTypeParams.SELECT_TRANSACTION_BY_ORDERID, and TransactionsTable.TRANSACTION_ID.
Referenced by Order.Order().
Member Data Documentation
final Logger log = Logger.getLogger(Order.class.getName()) static package
Definition at line 42 of file Order.java.
final Buyer buyer_M private
the buyer of this order
Definition at line 44 of file Order.java.
Referenced by Order.buyer().
final Transaction [] transactions_M private
the transactions associated with this order
Definition at line 46 of file Order.java.
final HeteroFieldContainer order_info_M private
Container for all the order information retrieved by the query.
Definition at line 48 of file Order.java.
The documentation for this class was generated from the following file:
src/tomoBay/model/dataTypes/order/Order.java