TomoBay: MAIN Class Reference
MAIN Class Reference
The entry point into the program, this is a stopgap solution to get invoices ,of orders that are completely fulfillable, printed automatically.
Static Public Member Functions
static final void main (String[] args) throws Exception
Static Private Attributes
static final Logger log = Logger.getLogger(MAIN.class)
Detailed Description
The entry point into the program, this is a stopgap solution to get invoices ,of orders that are completely fulfillable, printed automatically.
Author
Jan P.C. Hanson
Definition at line 17 of file MAIN.java.
Member Function Documentation
static final void main (String[] args) throws Exception static
Definition at line 21 of file MAIN.java.
References ServiceScheduler.add(), ServiceFactory.ServiceType.CHECK_ERRORS, ServiceFactory.ServiceType.EBAY_SERVICE, ServiceFactory.ConfiguredServiceType.EMAIL_ERRORS_SERVICE, ServerStatus.instance(), ServiceFactory.make(), ServiceFactory.ServiceType.OUT_OF_HOURS_SERVICE, ServiceFactory.ServiceType.RESCAN_ERRORS_SERVICE, ServerStatus.RunLevel.RUNNING, ServerStatus.setStatus(), HttpServer.start(), and ServiceScheduler.start().
Member Data Documentation
final Logger log = Logger.getLogger(MAIN.class) static private
Definition at line 19 of file MAIN.java.
The documentation for this class was generated from the following file:
src/tomoBay/MAIN.java