TomoBay: Config Enum Reference
Config Enum Reference
This Enum provides constants which refer to tags in the config file.
Public Member Functions
String getVar ()
return the string associated with the enum const
Public Attributes
MON_ST =("MONDAY_START_TIME")
MON_END =("MONDAY_END_TIME")
TUE_ST =("TUESDAY_START_TIME")
TUE_END =("TUESDAY_END_TIME")
WED_ST =("WEDNESDAY_START_TIME")
WED_END =("WEDNESDAY_END_TIME")
THUR_ST =("THURSDAY_START_TIME")
THUR_END =("THURSDAY_END_TIME")
FRI_ST =("FRIDAY_START_TIME")
FRI_END =("FRIDAY_END_TIME")
SAT_ST =("SATURDAY_START_TIME")
SAT_END =("SATURDAY_END_TIME")
SUN_ST =("SUNDAY_START_TIME")
SUN_END =("SUNDAY_END_TIME")
DB_QSTR =("JDBC_QUERY_STRING")
DB_USR =("DB_USER")
DB_PWD =("DB_PASSWORD")
DB_CON_MIN =("DB_CONNECTION_POOL_MIN_SIZE")
DB_CON_MAX =("DB_CONNECTION_POOL_MAX_SIZE")
DB_AQUIRE_INC =("DB_CONNECTION_POOL_AQUIRE_INCREMENT")
DB_MAX_STMTS =("DB_CONNECTION_POOL_MAX_STATEMENTS")
WIN_LOC =("WINSTOCK_IP")
WIN_PORT =("WINSTOCK_PORT")
WIN_URL1 =("WINSTOCK_URL_PT1")
WIN_URL2 =("WINSTOCK_URL_PT2")
WIN_WEIGHT_CALL1 =("WINSTOCK_WEIGHT_CALL_PT1")
WIN_WEIGHT_CALL2 =("WINSTOCK_WEIGHT_CALL_PT2")
EBAY_SAND_SRV =("EBAY_SANDBOX_SERVER")
EBAY_SAND_KEY =("EBAY_SANDBOX_API_KEY")
EBAY_PROD_SRV =("EBAY_PRODUCTION_SERVER")
EBAY_PROD_KEY =("EBAY_PRODUCTION_API_KEY")
EBAY_LOOKBCK =("EBAY_LOOKBACK_DAYS")
MAIL_ADDR =("SYSTEM_EMAIL_ADDRESS")
MAIL_PWD =("SYSTEM_EMAIL_PASSWORD")
MAIL_USR =("EMAIL_USER")
Ship_Type =("SHIPPING_TYPE")
RM_CSV_DEF =("RM_CSV_DEF")
CSV_FIELD =("CSV_FIELD")
CSV_FIELD_NAME =("CSV_FIELD_NAME")
CSV_FIELD_VALID =("CSV_FIELD_VALIDATION")
Private Member Functions
Config (final String text)
needed to allow values associated with enum constants
Private Attributes
final String text
needed to allow values associated with enum constants
Detailed Description
This Enum provides constants which refer to tags in the config file.
Author
Jan P.C. Hanson
Definition at line 24 of file Config.java.
Constructor & Destructor Documentation
Config (final String text) private
needed to allow values associated with enum constants
Parameters
text
Definition at line 84 of file Config.java.
Member Function Documentation
String getVar ()
return the string associated with the enum const
Returns
String
Definition at line 91 of file Config.java.
Referenced by ConfigReader.getConf(), ConfigReader.getConfs(), and ConfigReader.size().
Member Data Documentation
MON_ST =("MONDAY_START_TIME")
Definition at line 26 of file Config.java.
Referenced by Monday.startTime().
MON_END =("MONDAY_END_TIME")
Definition at line 27 of file Config.java.
Referenced by Monday.endTime().
TUE_ST =("TUESDAY_START_TIME")
Definition at line 28 of file Config.java.
Referenced by Tuesday.startTime().
TUE_END =("TUESDAY_END_TIME")
Definition at line 29 of file Config.java.
Referenced by Tuesday.endTime().
WED_ST =("WEDNESDAY_START_TIME")
Definition at line 30 of file Config.java.
Referenced by Wednesday.startTime().
WED_END =("WEDNESDAY_END_TIME")
Definition at line 31 of file Config.java.
Referenced by Wednesday.endTime().
THUR_ST =("THURSDAY_START_TIME")
Definition at line 32 of file Config.java.
Referenced by Thursday.startTime().
THUR_END =("THURSDAY_END_TIME")
Definition at line 33 of file Config.java.
Referenced by Thursday.endTime().
FRI_ST =("FRIDAY_START_TIME")
Definition at line 34 of file Config.java.
Referenced by Friday.startTime().
FRI_END =("FRIDAY_END_TIME")
Definition at line 35 of file Config.java.
Referenced by Friday.endTime().
SAT_ST =("SATURDAY_START_TIME")
Definition at line 36 of file Config.java.
Referenced by Saturday.startTime().
SAT_END =("SATURDAY_END_TIME")
Definition at line 37 of file Config.java.
Referenced by Saturday.endTime().
SUN_ST =("SUNDAY_START_TIME")
Definition at line 38 of file Config.java.
Referenced by Sunday.startTime().
SUN_END =("SUNDAY_END_TIME")
Definition at line 39 of file Config.java.
Referenced by Sunday.endTime().
DB_QSTR =("JDBC_QUERY_STRING")
Definition at line 41 of file Config.java.
Referenced by ConnectionManager.ConnectionManager().
DB_USR =("DB_USER")
Definition at line 42 of file Config.java.
Referenced by ConnectionManager.ConnectionManager().
DB_PWD =("DB_PASSWORD")
Definition at line 43 of file Config.java.
Referenced by ConnectionManager.ConnectionManager().
DB_CON_MIN =("DB_CONNECTION_POOL_MIN_SIZE")
Definition at line 44 of file Config.java.
Referenced by ConnectionManager.ConnectionManager().
DB_CON_MAX =("DB_CONNECTION_POOL_MAX_SIZE")
Definition at line 45 of file Config.java.
Referenced by ConnectionManager.ConnectionManager().
DB_AQUIRE_INC =("DB_CONNECTION_POOL_AQUIRE_INCREMENT")
Definition at line 46 of file Config.java.
Referenced by ConnectionManager.ConnectionManager().
DB_MAX_STMTS =("DB_CONNECTION_POOL_MAX_STATEMENTS")
Definition at line 47 of file Config.java.
Referenced by ConnectionManager.ConnectionManager().
WIN_LOC =("WINSTOCK_IP")
Definition at line 49 of file Config.java.
Referenced by WinstockConfig.getMachineName().
WIN_PORT =("WINSTOCK_PORT")
Definition at line 50 of file Config.java.
Referenced by WinstockConfig.getPort().
WIN_URL1 =("WINSTOCK_URL_PT1")
Definition at line 51 of file Config.java.
WIN_URL2 =("WINSTOCK_URL_PT2")
Definition at line 52 of file Config.java.
WIN_WEIGHT_CALL1 =("WINSTOCK_WEIGHT_CALL_PT1")
Definition at line 53 of file Config.java.
Referenced by Stock.requestInvoiceWeight().
WIN_WEIGHT_CALL2 =("WINSTOCK_WEIGHT_CALL_PT2")
Definition at line 54 of file Config.java.
Referenced by Stock.requestInvoiceWeight().
EBAY_SAND_SRV =("EBAY_SANDBOX_SERVER")
Definition at line 56 of file Config.java.
EBAY_SAND_KEY =("EBAY_SANDBOX_API_KEY")
Definition at line 57 of file Config.java.
EBAY_PROD_SRV =("EBAY_PRODUCTION_SERVER")
Definition at line 58 of file Config.java.
EBAY_PROD_KEY =("EBAY_PRODUCTION_API_KEY")
Definition at line 59 of file Config.java.
EBAY_LOOKBCK =("EBAY_LOOKBACK_DAYS")
Definition at line 60 of file Config.java.
MAIL_ADDR =("SYSTEM_EMAIL_ADDRESS")
Definition at line 62 of file Config.java.
Referenced by MailClient.send(), and EmailErrorsMailActions.send().
MAIL_PWD =("SYSTEM_EMAIL_PASSWORD")
Definition at line 63 of file Config.java.
Referenced by MailClient.send(), and EmailErrorsMailActions.send().
MAIL_USR =("EMAIL_USER")
Definition at line 64 of file Config.java.
Ship_Type =("SHIPPING_TYPE")
Definition at line 66 of file Config.java.
Referenced by Shipping_Priority.populatePriorityMap().
RM_CSV_DEF =("RM_CSV_DEF")
Definition at line 68 of file Config.java.
CSV_FIELD =("CSV_FIELD")
Definition at line 69 of file Config.java.
CSV_FIELD_NAME =("CSV_FIELD_NAME")
Definition at line 70 of file Config.java.
Referenced by RoyalMailCSVGenerator.RoyalMailCSVGenerator(), and RoyalMailCSVGeneratorTest.testSize().
CSV_FIELD_VALID =("CSV_FIELD_VALIDATION")
Definition at line 71 of file Config.java.
Referenced by RoyalMailCSVGenerator.RoyalMailCSVGenerator().
final String text private
needed to allow values associated with enum constants
Definition at line 78 of file Config.java.
The documentation for this enum was generated from the following file:
src/tomoBay/helpers/Config.java