TomoBay: PayloadType Enum Reference
PayloadType Enum Reference
This Enum contains all the types that can be loaded into an AbstractPayload.
Static Public Member Functions
[static initializer]
static int value (PayloadType type) throws PayloadException
retrieves the integer value associated with the particular enum constant
Public Attributes
PRINT_TYPE =(35)
PUT_INVOICE_TYPE =(34)
TYPE =(-1)
COMPANY =(-1)
INVOICE_NO =(-1)
PACKING_LISTS =(-1)
PRINT_COPIES =(-1)
QUANTITY =(-1)
PRICE =(-1)
INSTOCK =(-1)
INV_LINES =(-1)
INVOICE_ACCOUNT =(9)
NAME =(51)
ADDRESS1 =(51)
ADDRESS2 =(51)
CITY =(51)
COUNTY =(51)
POSTCODE =(10)
ORDER_NO =(21)
PART_NO =(17)
DESCRIPTION =(31)
Private Member Functions
PayloadType (int value)
private ctor to allow integer values to be associated with enum constants
Private Attributes
int value_M
needed to assign values to constants
Static Private Attributes
staticfinal Map< PayloadType, Integer > payloadTypeByValue = new HashMap<PayloadType, Integer>()
map of the constant values to the enum constants
Detailed Description
This Enum contains all the types that can be loaded into an AbstractPayload.
Author
Jan P.C. Hanson
Definition at line 26 of file PayloadType.java.
Constructor & Destructor Documentation
PayloadType (int value) private
private ctor to allow integer values to be associated with enum constants
Parameters
value
Definition at line 68 of file PayloadType.java.
Member Function Documentation
[static initializer] () static
static int value (PayloadType type) throws PayloadException static
retrieves the integer value associated with the particular enum constant
Parameters
type the specific PayloadType to check
Returns
int equal to the value associated with the enum constant
Exceptions
PayloadException
Definition at line 77 of file PayloadType.java.
References PayloadType.payloadTypeByValue.
Member Data Documentation
PRINT_TYPE =(35)
Definition at line 28 of file PayloadType.java.
PUT_INVOICE_TYPE =(34)
Definition at line 29 of file PayloadType.java.
TYPE =(-1)
Definition at line 31 of file PayloadType.java.
Referenced by WinstockFormat.format(), PrintInvoices.formatAsDualList(), ClientSocketTest.main(), PrintInvoicePayload.PrintInvoicePayload(), and PutInvoicePayload.PutInvoicePayload().
COMPANY =(-1)
Definition at line 32 of file PayloadType.java.
Referenced by WinstockFormat.format(), PrintInvoices.formatAsDualList(), ClientSocketTest.main(), PrintInvoicePayload.PrintInvoicePayload(), and PutInvoicePayload.PutInvoicePayload().
INVOICE_NO =(-1)
Definition at line 33 of file PayloadType.java.
Referenced by PrintInvoices.formatAsDualList(), ClientSocketTest.main(), and PrintInvoicePayload.PrintInvoicePayload().
PACKING_LISTS =(-1)
Definition at line 34 of file PayloadType.java.
Referenced by PrintInvoices.formatAsDualList(), ClientSocketTest.main(), and PrintInvoicePayload.PrintInvoicePayload().
PRINT_COPIES =(-1)
Definition at line 35 of file PayloadType.java.
Referenced by PrintInvoices.formatAsDualList(), ClientSocketTest.main(), and PrintInvoicePayload.PrintInvoicePayload().
QUANTITY =(-1)
Definition at line 36 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
PRICE =(-1)
Definition at line 37 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
INSTOCK =(-1)
Definition at line 38 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
INV_LINES =(-1)
Definition at line 39 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
INVOICE_ACCOUNT =(9)
Definition at line 41 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
NAME =(51)
Definition at line 42 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
ADDRESS1 =(51)
Definition at line 43 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
ADDRESS2 =(51)
Definition at line 44 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
CITY =(51)
Definition at line 45 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
COUNTY =(51)
Definition at line 46 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
POSTCODE =(10)
Definition at line 47 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
ORDER_NO =(21)
Definition at line 48 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
PART_NO =(17)
Definition at line 49 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
DESCRIPTION =(31)
Definition at line 50 of file PayloadType.java.
Referenced by WinstockFormat.format(), ClientSocketTest.main(), and PutInvoicePayload.PutInvoicePayload().
int value_M private
needed to assign values to constants
Definition at line 54 of file PayloadType.java.
static final Map<PayloadType, Integer> payloadTypeByValue = new HashMap<PayloadType, Integer>() static private
map of the constant values to the enum constants
Definition at line 57 of file PayloadType.java.
Referenced by PayloadType.value().
The documentation for this enum was generated from the following file:
src/tomoBay/model/winstock/payloads/PayloadType.java