TomoBay: ResultCodes Enum Reference
ResultCodes Enum Reference
Copyright(C) 2015 Jan P.C.
Static Public Member Functions
[static initializer]
initialiser for the codesByValue map
static ResultCodes forValue (int codeNumber) throws NotAValidResultCodeException
this method allows the user to retrieve the enum const based on an integer value.
Public Attributes
SUCCESS =(0)
TERMINATOR_ERROR =(10)
INVOICING_ERROR =(100)
ERROR_SYNTAX =(-1)
SYNTAX_ERROR =(0xff)
PRINTING_ERROR =(101)
Private Member Functions
ResultCodes (int codes)
private constructor to allow the enum constants to be associated with integer values
Private Attributes
int codes_M
holder for the integer values of the enum constants
Static Private Attributes
staticfinal Map< Integer, ResultCodes > codesByValue = new HashMap<Integer, ResultCodes>()
map of the constant values to the enum constants
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/. This enum defines a series of result codes applicable to the winstock responses. as well as allowing the user of this enum to
Author
Jan P.C. Hanson
Definition at line 30 of file ResultCodes.java.
Constructor & Destructor Documentation
ResultCodes (int codes) private
private constructor to allow the enum constants to be associated with integer values
Parameters
codes
Definition at line 55 of file ResultCodes.java.
Member Function Documentation
[static initializer] () static
initialiser for the codesByValue map
static ResultCodes forValue (int codeNumber) throws NotAValidResultCodeException static
this method allows the user to retrieve the enum const based on an integer value.
Parameters
codeNumber the numerical value to equate to an enum constant
Returns
ResultCodes appropriate to the integer passed in.
Exceptions
NotAValidResultCodeException
Definition at line 64 of file ResultCodes.java.
References ResultCodes.codesByValue.
Referenced by PutInvoiceResponse.isSuccess(), and PrintInvoiceResponse.isSuccess().
Member Data Documentation
SUCCESS =(0)
Definition at line 32 of file ResultCodes.java.
Referenced by PrintInvoices.print().
TERMINATOR_ERROR =(10)
Definition at line 33 of file ResultCodes.java.
INVOICING_ERROR =(100)
Definition at line 34 of file ResultCodes.java.
ERROR_SYNTAX =(-1)
Definition at line 35 of file ResultCodes.java.
SYNTAX_ERROR =(0xff)
Definition at line 36 of file ResultCodes.java.
PRINTING_ERROR =(101)
Definition at line 37 of file ResultCodes.java.
static final Map<Integer, ResultCodes> codesByValue = new HashMap<Integer, ResultCodes>() static private
map of the constant values to the enum constants
Definition at line 40 of file ResultCodes.java.
Referenced by ResultCodes.forValue().
int codes_M private
holder for the integer values of the enum constants
Definition at line 49 of file ResultCodes.java.
The documentation for this enum was generated from the following file:
/home/orpheus/projects/TomoMotorParts/StopGap/src/tomoBay/model/winstock/response/ResultCodes.java