TomoBay: PickeableStatus Enum Reference
PickeableStatus Enum Reference
this enum defines the different status's and status codes for the state of an order with respect to invoiceability.
Public Member Functions
int getStatusCode ()
retrieve the status code for a particular constant
Static Public Member Functions
static PickeableStatus fromInt (int statusCode)
static int size ()
gets the number of constants held in this enum
Public Attributes
ERROR =(0)
there has been an error somewhere along the line.....dufus
PICKEABLE =(1)
an invoice is fully invoiceable or already invoiced
PARTIAL =(2)
this order is partially invoiceable, probably due to some parts being out of stock
UNPICKEABLE =(3)
it is not possible to invoice this order at the present time
PICKEABLE_PROCESSING =(-1)
this order is fully pickeable and is currently being processed
PARTIAL_PROCESSING =(-2)
this order is partially pickeable and is currently being processed
UNPICKEABLE_PROCESSING =(-3)
this order is unpickeable and is currently being processed
Private Member Functions
PickeableStatus (int status)
private ctor so enum can hold int values
Private Attributes
int status_M
holder for the status code
Static Private Attributes
staticfinal Map< Integer, PickeableStatus > fromInt_M
map for converting ints back to enum constants
staticfinal int size = PickeableStatus.values().length
size of the enum
Detailed Description
this enum defines the different status's and status codes for the state of an order with respect to invoiceability.
Author
Jan P.C. Hanson
Definition at line 26 of file PickeableStatus.java.
Constructor & Destructor Documentation
PickeableStatus (int status) private
private ctor so enum can hold int values
Definition at line 64 of file PickeableStatus.java.
Member Function Documentation
int getStatusCode ()
retrieve the status code for a particular constant
Returns
integer status code
Definition at line 71 of file PickeableStatus.java.
static PickeableStatus fromInt (int statusCode) static
Parameters
statusCode
Returns
Definition at line 79 of file PickeableStatus.java.
References PickeableStatus.fromInt_M.
static int size () static
gets the number of constants held in this enum
Returns
integer denoting the size of the enum
Definition at line 86 of file PickeableStatus.java.
References PickeableStatus.size.
Member Data Documentation
ERROR =(0)
there has been an error somewhere along the line.....dufus
Definition at line 29 of file PickeableStatus.java.
Referenced by PartialPickeableResult.result(), and ErrorResult.result().
PICKEABLE =(1)
an invoice is fully invoiceable or already invoiced
Definition at line 31 of file PickeableStatus.java.
Referenced by AllPickeableResult.result().
PARTIAL =(2)
this order is partially invoiceable, probably due to some parts being out of stock
Definition at line 33 of file PickeableStatus.java.
Referenced by PartialPickeableResult.result().
UNPICKEABLE =(3)
it is not possible to invoice this order at the present time
Definition at line 35 of file PickeableStatus.java.
Referenced by UnPickeableResult.result().
PICKEABLE_PROCESSING =(-1)
this order is fully pickeable and is currently being processed
Definition at line 37 of file PickeableStatus.java.
PARTIAL_PROCESSING =(-2)
this order is partially pickeable and is currently being processed
Definition at line 39 of file PickeableStatus.java.
UNPICKEABLE_PROCESSING =(-3)
this order is unpickeable and is currently being processed
Definition at line 41 of file PickeableStatus.java.
static final Map<Integer, PickeableStatus> fromInt_M static private
Initial value:
= new THashMap<Integer,PickeableStatus>()
    {{
        put(PickeableStatus.ERROR.getStatusCode(), PickeableStatus.ERROR);
        put(PickeableStatus.UNPICKEABLE.getStatusCode() , PickeableStatus.UNPICKEABLE);
        put(PickeableStatus.PARTIAL.getStatusCode() , PickeableStatus.PARTIAL);
        put(PickeableStatus.PICKEABLE.getStatusCode() , PickeableStatus.PICKEABLE);
        put(PickeableStatus.PICKEABLE_PROCESSING.getStatusCode(), PickeableStatus.PICKEABLE_PROCESSING);
        put(PickeableStatus.PARTIAL_PROCESSING.getStatusCode(), PickeableStatus.PARTIAL_PROCESSING);
        put(PickeableStatus.UNPICKEABLE_PROCESSING.getStatusCode(), PickeableStatus.UNPICKEABLE_PROCESSING);
    }}
map for converting ints back to enum constants
Definition at line 44 of file PickeableStatus.java.
Referenced by PickeableStatus.fromInt().
int status_M private
holder for the status code
Definition at line 56 of file PickeableStatus.java.
static final int size = PickeableStatus.values().length static private
size of the enum
Definition at line 59 of file PickeableStatus.java.
Referenced by PickeableStatus.size(), and SortOrders.sortByPickeability().
The documentation for this enum was generated from the following file:
src/tomoBay/presenters/helpers/pickeability/PickeableStatus.java