TomoBay: AbstractConfiguration< T > Interface Template Reference
AbstractConfiguration< T > Interface Template Reference
This interface defines the form that every configuration object used to provide information to particular services should conform to.
Public Member Functions
AbstractConfiguration< T > configure (T value)
used to set the configuration information for the service.
T configure ()
used by the service to retrieve the information necessary for the service to configure itself.
Detailed Description
This interface defines the form that every configuration object used to provide information to particular services should conform to.
***Using a Configuration Object***
***Writing a Configuration Object***
Author
Jan P.C. Hanson
Definition at line 33 of file AbstractConfiguration.java.
Member Function Documentation
AbstractConfiguration<T> configure (T value)
used to set the configuration information for the service.
Parameters
value
Referenced by IndividualItemRefreshService.setConfig(), ReScanBuyerService.setConfig(), and EmailErrorsService.setConfig().
T configure ()
used by the service to retrieve the information necessary for the service to configure itself.
Returns
Implemented in EmailErrorsConfig, ReScanBuyerServiceConfig, IndividualItemRefreshConfig, and UpdateOrderStatusConfig.
The documentation for this interface was generated from the following file:
src/tomoBay/model/services/AbstractConfiguration.java