TomoBay: AbstractWinstockCommandResponse Interface Reference
AbstractWinstockCommandResponse Interface Reference
This is the interface that all winstock command responses should subscribe to.
Public Member Functions
void setSentBytes (byte[] sentBytes)
used by the AbstractWinswtock command associated with this response to insert the raw byte values that were sent by the associated command to winstock.
void setResponseBytes (byte[] responseBytes)
used by the AbstractWinstockCommand associated with this response to insert the raw byte values into this object for processing.
ResultCodes isSuccess () throws NotAValidResultCodeException
method of descerning whether the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse has been successful.
String[] getRecieved ()
method used to retrieve the results of the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse.
String getSent ()
method used to retrieve the data sent to the socket.
Detailed Description
This is the interface that all winstock command responses should subscribe to.
I defines a set of methods that allow the system to populate an AbstractWinstockResponseObject with data, and allow the user to retrieve human readable data.
Author
Jan P.C. Hanson
Definition at line 27 of file AbstractWinstockCommandResponse.java.
Member Function Documentation
void setSentBytes (byte[] sentBytes)
used by the AbstractWinswtock command associated with this response to insert the raw byte values that were sent by the associated command to winstock.
Parameters
sentBytes the bytes sent to the winstock socket.
Implemented in PutInvoiceResponse, and PrintInvoiceResponse.
void setResponseBytes (byte[] responseBytes)
used by the AbstractWinstockCommand associated with this response to insert the raw byte values into this object for processing.
Not really of any use to the user.
Parameters
responseBytes
Implemented in PrintInvoiceResponse, and PutInvoiceResponse.
ResultCodes isSuccess () throws NotAValidResultCodeException
method of descerning whether the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse has been successful.
Returns
boolean true if successful false otherwise.
Implemented in PrintInvoiceResponse, and PutInvoiceResponse.
Referenced by PrintInvoices.print(), and ClientSocketTest.test().
String [] getRecieved ()
method used to retrieve the results of the AbstractWinstockCommand associated with this AbstractWinstockCommandResponse.
Returns
String the data of the query
Implemented in PutInvoiceResponse, and PrintInvoiceResponse.
Referenced by InvoiceOrders.execute(), and ClientSocketTest.test().
String getSent ()
method used to retrieve the data sent to the socket.
Returns
String representing the data sent to the socket
Implemented in PrintInvoiceResponse, and PutInvoiceResponse.
Referenced by ClientSocketTest.test().
The documentation for this interface was generated from the following file:
src/tomoBay/model/winstock/response/AbstractWinstockCommandResponse.java