TomoBay: ItemSpecifics Class Reference
ItemSpecifics Class Reference
This class represents the item specifics (Brand, ManufacturerPartNumber etc), it takes care of retrieving the information from the eBay API and making it easily accessible.
Public Member Functions
ItemSpecifics (long itemID, int account)
constructor creates an ItemSpecifics object for the itemID passed in as an argument.
long getID ()
provides the itemID associated with this ItemSpecifics object
String get (String key)
returns a particular Item specific
Private Member Functions
ItemType performAPIcall (long itemID)
performs the API call and return an ItemType containing the item information requested, or if for some reason the call fails a null pointer is returned.
void populateMap (ItemType item)
this method takes an ItemType as a parameter and uses it to iterate through the NameValueListType[] contained within it adding the appropriate names and values to the this.itemSpecifics_M map.
Private Attributes
final String apiKey_M
holder containing the credentials to access the eBay API
final String server_M
Map< String, String > itemSpecifics_M
map containing the item Specifics, this is what the user uses indirectly
final long itemID_M
String containing the itemID.
Detailed Description
This class represents the item specifics (Brand, ManufacturerPartNumber etc), it takes care of retrieving the information from the eBay API and making it easily accessible.
Author
Jan P.C. Hanson
Definition at line 32 of file ItemSpecifics.java.
Constructor & Destructor Documentation
ItemSpecifics (long itemID, int account)
constructor creates an ItemSpecifics object for the itemID passed in as an argument.
Parameters
itemID the id of the item that you need the specifics of
account the ebay account to use for the query.
Definition at line 48 of file ItemSpecifics.java.
References EbayAccounts.apiKey(), EbayAccounts.name(), ItemSpecifics.performAPIcall(), ItemSpecifics.populateMap(), and EbayAccounts.serverAddress().
Member Function Documentation
long getID ()
provides the itemID associated with this ItemSpecifics object
Returns
String itemID.
Definition at line 64 of file ItemSpecifics.java.
References ItemSpecifics.itemID_M.
Referenced by ReScanErrorsDBActions.updateDBwithCorrectedInfo().
String get (String key)
returns a particular Item specific
Parameters
key generally 'ManufacturerPartNumber' or 'Brand'
Returns
the data associated with that key.
Definition at line 72 of file ItemSpecifics.java.
Referenced by ReScanErrorsWinstockActions.partNoHasError(), and ReScanErrorsDBActions.updateDBwithCorrectedInfo().
ItemType performAPIcall (long itemID) private
performs the API call and return an ItemType containing the item information requested, or if for some reason the call fails a null pointer is returned.
and the stack trace is printed to the console.
Parameters
itemID the itemID for the item that you wish to find information on.
Definition at line 81 of file ItemSpecifics.java.
References ItemCall.call().
Referenced by ItemSpecifics.ItemSpecifics().
void populateMap (ItemType item) private
this method takes an ItemType as a parameter and uses it to iterate through the NameValueListType[] contained within it adding the appropriate names and values to the this.itemSpecifics_M map.
Before adding the 'name' field to the key of the map it removes the spaces in the name, so to access 'Manufacturer Part Number' you would request 'ManufacturerPartNumber' etc.
Parameters
item the ItemType returned from the API call.
Definition at line 99 of file ItemSpecifics.java.
Referenced by ItemSpecifics.ItemSpecifics().
Member Data Documentation
final String apiKey_M private
holder containing the credentials to access the eBay API
Definition at line 35 of file ItemSpecifics.java.
final String server_M private
Definition at line 37 of file ItemSpecifics.java.
Map<String, String> itemSpecifics_M private
map containing the item Specifics, this is what the user uses indirectly
Definition at line 39 of file ItemSpecifics.java.
final long itemID_M private
String containing the itemID.
Definition at line 41 of file ItemSpecifics.java.
Referenced by ItemSpecifics.getID().
The documentation for this class was generated from the following file:
/home/orpheus/Projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/services/reScanErrorsService/ItemSpecifics.java