TomoBay: SortOrders Class Reference
SortOrders Class Reference
This class contains functionality for performing a category based sorting algorithm first ordering the data passed in by shipping type and the now sorted data by Pickeability.
Public Member Functions
SortOrders ()
default ctor
List< HeteroFieldContainer > sortDefault (List< HeteroFieldContainer > rows)
sort an input list of Strings i.e.
Private Member Functions
List< HeteroFieldContainer > sortByPickeability (List< HeteroFieldContainer > input)
sort the list<String> by Invoice status descending (see InvoiceableStatus enum)
List< HeteroFieldContainer > sortByShipping (List< HeteroFieldContainer > input)
sort the List<String> by shipping type descending (see ShippingPriority enum)
List< HeteroFieldContainer > reAssembleCategories (List< List< HeteroFieldContainer >> input, int size)
reassemble the categories into one list
Detailed Description
This class contains functionality for performing a category based sorting algorithm first ordering the data passed in by shipping type and the now sorted data by Pickeability.
this leads to data that is first displayed by pickeability then within each pickability type it is then sorted by shipping type.
each element of the list passed should be of the form: [orderID, buyerID, salesRecNo, shippingType, createdTime, picked, packed, shipped, invoiced]
See also
tomoBay.helpers.ShippingPriority
Author
Jan P.C. Hanson
Definition at line 37 of file SortOrders.java.
Constructor & Destructor Documentation
SortOrders ()
default ctor
Definition at line 42 of file SortOrders.java.
Member Function Documentation
List<HeteroFieldContainer> sortDefault (List< HeteroFieldContainer > rows)
sort an input list of Strings i.e.
the results of an eBay orders query, by shipping type and then by date.
Parameters
rows
Returns
sorted list of strings.
Definition at line 51 of file SortOrders.java.
References SortOrders.sortByPickeability(), and SortOrders.sortByShipping().
Referenced by SalesOrderPresenter.present().
List<HeteroFieldContainer> sortByPickeability (List< HeteroFieldContainer > input) private
sort the list<String> by Invoice status descending (see InvoiceableStatus enum)
Parameters
input list of strings unordered
Returns
List<String> sorted by date descending
Definition at line 59 of file SortOrders.java.
References ClassRef.INTEGER, OrdersTable.INVOICED, SortOrders.reAssembleCategories(), and PickeableStatus.size.
Referenced by SortOrders.sortDefault().
List<HeteroFieldContainer> sortByShipping (List< HeteroFieldContainer > input) private
sort the List<String> by shipping type descending (see ShippingPriority enum)
Parameters
input list of strings sorted by date descending.
Returns
List<String> sorted by ShippingPriority then date
Definition at line 78 of file SortOrders.java.
References SortOrders.reAssembleCategories(), OrdersTable.SHIPPING_TYPE, ShippingPriority.size, and ClassRef.STRING.
Referenced by SortOrders.sortDefault().
List<HeteroFieldContainer> reAssembleCategories (List< List< HeteroFieldContainer >> input, int size) private
reassemble the categories into one list
Parameters
input List<List<String[]>> the list of catagories
size the size of the shipping priority enum
Returns
category sorted list of strings with previous sort order preserved
Definition at line 98 of file SortOrders.java.
Referenced by SortOrders.sortByPickeability(), and SortOrders.sortByShipping().
The documentation for this class was generated from the following file:
/home/orpheus/Projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/helpers/SortOrders.java