TomoBay: ErrorsList Class Reference
ErrorsList Class Reference
This class represents the list of errors that exist within the ebay_items table in the database, and the functionality to retrieve that list as well as some other bits and bobs like find out if errors exist.
Public Member Functions
ErrorsList ()
default ctor, generates a the list of errors that this object represents
List< HeteroFieldContainer > get ()
generate a list of items from the database that contain error messages.
boolean exist ()
returns true if errors exist in the ebay listings false if not
Private Member Functions
void generateErrorList ()
generate the list of errors.
Private Attributes
List< HeteroFieldContainer > errorList_M
the list of errors
Detailed Description
This class represents the list of errors that exist within the ebay_items table in the database, and the functionality to retrieve that list as well as some other bits and bobs like find out if errors exist.
Author
Jan P.C. Hanson
Definition at line 29 of file ErrorsList.java.
Constructor & Destructor Documentation
ErrorsList ()
default ctor, generates a the list of errors that this object represents
Definition at line 37 of file ErrorsList.java.
References ErrorsList.generateErrorList().
Member Function Documentation
List<HeteroFieldContainer> get ()
generate a list of items from the database that contain error messages.
Returns
List<String[]> containing all items that contain error messages.
Definition at line 47 of file ErrorsList.java.
References ErrorsList.errorList_M.
Referenced by OnRunning.execute().
boolean exist ()
returns true if errors exist in the ebay listings false if not
Returns
true if errors exist in the ebay listings false if not
Definition at line 54 of file ErrorsList.java.
Referenced by OnRunning.execute().
void generateErrorList () private
generate the list of errors.
this method is only called by the constructor
Definition at line 63 of file ErrorsList.java.
References SelectQueryInvoker.execute(), and SelectQueryInvoker.SelectQueryTypeNoParams.SELECT_EBAY_ITEMS_ERROR.
Referenced by ErrorsList.ErrorsList().
Member Data Documentation
List<HeteroFieldContainer> errorList_M private
the list of errors
Definition at line 32 of file ErrorsList.java.
Referenced by ErrorsList.get().
The documentation for this class was generated from the following file:
/home/orpheus/Projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/services/emailErrorsService/ErrorsList.java