TomoBay: OnRunning Class Reference
OnRunning Class Reference
Public Member Functions
OnRunning ()
default ctor
String execute ()
this method defines what to do in the given derived state
Private Member Functions
java.sql.Date getDate ()
Detailed Description
Author
Jan P.C. Hanson
Definition at line 36 of file OnRunning.java.
Constructor & Destructor Documentation
OnRunning ()
default ctor
Definition at line 42 of file OnRunning.java.
Member Function Documentation
String execute ()
this method defines what to do in the given derived state
Returns
String representing the end product of the state.
Implements AbstractServiceState.
Definition at line 49 of file OnRunning.java.
References HeteroFieldContainer.add(), OutOfHoursTable.DATE, ModifyQueryInvoker.execute(), SelectQueryInvoker.execute(), HeteroFieldContainer.get(), ModifyQueryInvoker.ModifyQueryTypeParams.INSERT_OUT_OF_HOURS, ClassRef.INTEGER, OutOfHoursTable.SALES_REC_NO, OrdersTable.SALES_REC_NO, and SelectQueryInvoker.SelectQueryTypeNoParams.SELECT_UNINVOICED_ORDERS.
Referenced by OutOfHoursService.onRunning().
java.sql.Date getDate () private
Returns
Definition at line 68 of file OnRunning.java.
References CheckTime.OutOfHoursDate().
The documentation for this class was generated from the following file:
/home/orpheus/Projects/TomoMotorParts/TomoBay/Development/TomoBay/src/tomoBay/model/services/outOfHoursService/OnRunning.java